#!/usr/bin/env python3
"""Fase 1 — minería de transcripts: tasa de activación SOBRE OPORTUNIDADES.

Recorre las sesiones auditadas, marca eventos-disparador con heurísticas
verificables, y los cruza contra las invocaciones reales de Skill/Agent,
separando las AUTOMÁTICAS de las PEDIDAS por el usuario.

Señal de fallo de comando: `is_error` del bloque tool_result (no regex sobre la
salida — eso contaba ✗ impresos por scripts propios como si fueran fallos).

Todo lo de aquí es aproximado por construcción. Se imprimen conteos crudos y
ejemplos para que cada número se pueda auditar a mano.
"""
import json, os, re, sys, glob
from collections import Counter

PROJECTS = os.path.expanduser("~/.claude/projects")

# Roles/skills renamed across the roster (spec 0026 T17, R43; #869): a session
# mined from BEFORE a rename names the OLD id, one mined AFTER names the NEW
# one, and without folding them together they'd split into two Counter
# buckets that each look inert on their own — exactly the false "0%
# activation" #605/#705 already burned an investigation on for a different
# miscount.
#
# The alias maps used to be hand-copied here, independent from
# `lib/retired-names.ts`'s `RETIRED_AGENTS`/`RETIRED_SKILLS` registries — the
# risk #869 flagged: the next rename could update the registry and silently
# leave this script's dicts stale. They now come from
# `activation-aliases.json`, GENERATED by `pnpm gen:schemas` from
# `packages/cli/src/lib/activation-aliases.ts`, which derives them from those
# same registries. A drift test (`activation-aliases.test.ts`) fails if the
# JSON falls behind the module.
#
# Not every renamed retiree becomes an alias here: `commit-pr-pilot` →
# `publisher` is the only role rename this script's raw `subagent_type`
# strings can observe (nothing in this file counts `orchestrator`/`scout`/
# `auditor` under a fixed key the way `mark("pr → review-diff/pilot", ...)`
# does for `publisher`). That exclusion — and any future one — is a reasoned,
# recorded decision in `activation-aliases.ts`, not a silent omission:
# `excludedRoleAliases`/`excludedSkillAliases` below carry the ids the
# registry marks as renamed but the module deliberately left out, with why.
_ALIASES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "activation-aliases.json")
with open(_ALIASES_FILE, encoding="utf-8") as _fh:
    _ALIASES = json.load(_fh)
ROLE_ALIASES = _ALIASES["roleAliases"]
SKILL_ALIASES = _ALIASES["skillAliases"]


def canon_role(name):
    return ROLE_ALIASES.get(name, name)


def canon_skill(name):
    return SKILL_ALIASES.get(name, name)

VERIFY_CMD = re.compile(
    r"\b(pnpm|npm|yarn|bun)\s+(run\s+)?(test|lint|typecheck|type-check|build|check)"
    r"|\bvitest\b|\bjest\b|\btsc\b|\bpytest\b|\bruff\b|\beslint\b|\bbiome\b"
    r"|test:coverage|gh pr checks|gh run", re.I)
DONE_CLAIM = re.compile(
    r"(^|\s)(listo|hecho|terminado|completado|queda listo|todo (en )?verde|✅)\b", re.I)
ERROR_LINE = re.compile(r"(error TS\d+|^\s*Error:|\bFAIL\b|error\[E\d+\]|Traceback)", re.M)
PR_CMD = re.compile(r"(?:^|&&\s*|;\s*)gh pr create")
COMMIT_CMD = re.compile(r"git commit")
CD_PREFIX = re.compile(r'^\s*cd\s+("[^"]*"|\S+)\s*&&\s*')
# Los dos fallos que NO son un bug: el harness bloqueando y el usuario negando.
# Juntos son el 29.1% de las 281 llamadas fallidas del parque.
HOOK_BLOCK = re.compile(r"PreToolUse:|PostToolUse:|hook error")
DENIED = re.compile(r"requested permissions|user doesn't want|denied|rejected", re.I)

# ─── Qué cuenta como archivo fuente no trivial ──────────────────────────────
#
# UNA definición, y vive en TypeScript: `packages/cli/src/lib/source-classify.ts`.
# Este script no puede importarla, así que lee las reglas materializadas por
# `pnpm gen:schemas`. Un test de deriva (source-classify.test.ts) falla si el
# JSON se queda atrás del módulo.
#
# La versión anterior era una regex de extensiones, y sobre las 506 escrituras
# del parque admitía un 43% que no corresponde: 28.7% tests que acompañan
# (cláusula c), 13.4% archivos fuera del repo —un script de andamiaje bajo /tmp
# no llega a ningún diff— y una escritura en node_modules. El sesgo va en una
# sola dirección: infla el denominador de "oportunidades", que es justo por qué
# la tasa de activación salía baja. Y NO es uniforme entre repos: los tests
# acompañan al trabajo de feature, así que los repos que más delegan son los que
# más se penalizan.
_RULES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "source-classify.rules.json")
with open(_RULES_FILE, encoding="utf-8") as _fh:
    _SPEC = json.load(_fh)
RULES = [(r["kind"], re.compile(r["pattern"])) for r in _SPEC["rules"]]

# También estas dos: tenerlas copiadas a mano aquí es como se quedaron atrás en
# cuanto el módulo ganó una extensión (`.ipynb`) — el defecto exacto que el
# archivo compartido existe para cerrar.
SOURCE_EXT = re.compile(_SPEC["sourceExt"])
HARNESS_PROSE = re.compile(_SPEC["harnessProse"])

AUDITS = os.path.expanduser("~/.navori/audits")


def session_version(sid):
    """La versión de navori RENDERIZADA cuando corrió la sesión.

    Sale del registro `start` que el hook escribe al armar audit-mode, no del
    repo: lo que el repo tenga hoy no es la doctrina que estuvo vigente
    entonces. Sin esto, un cambio de doctrina y su medición no se pueden atar.
    """
    if not os.path.isdir(AUDITS):
        return None
    for repo in os.listdir(AUDITS):
        f = os.path.join(AUDITS, repo, f"session-{sid}.log")
        if not os.path.isfile(f):
            continue
        try:
            with open(f, errors="replace") as fh:
                for line in fh:
                    d = json.loads(line)
                    return d.get("navoriRendered") if d.get("event") == "start" else None
        except Exception:
            return None
    return None


def session_cwd(sid):
    """La raíz del repo de una sesión, desde la cabecera de su log de audit.

    Sin esto no hay forma de decir "fuera del repo", y un script de scratchpad
    bajo /tmp cuenta como si fuera código del producto.
    """
    if not os.path.isdir(AUDITS):
        return ""
    for repo in os.listdir(AUDITS):
        f = os.path.join(AUDITS, repo, f"session-{sid}.log")
        if not os.path.isfile(f):
            continue
        with open(f, errors="replace") as fh:
            for line in fh:
                try:
                    return json.loads(line).get("cwd") or ""
                except json.JSONDecodeError:
                    return ""
    return ""


def to_repo_relative(path, root):
    """Espejo de `toRepoRelative` en el módulo TS."""
    if not path:
        return None
    p = path.replace("\\", "/")
    root = (root or "").replace("\\", "/").rstrip("/")
    if not root:
        return None if p.startswith("/") else p.lstrip("./")
    if p == root:
        return ""
    # Un vecino que solo COMPARTE PREFIJO no está dentro: `/repo-2/x` empieza
    # por `/repo`.
    if p.startswith(root + "/"):
        return p[len(root) + 1:]
    return None if p.startswith("/") else p.lstrip("./")


def classify_path(path, root=""):
    """Cláusula (a), decidida desde la ruta. Espejo de `classifyPath`."""
    rel = to_repo_relative(path, root)
    if rel is None:
        return "outside-repo"
    for kind, rx in RULES:
        if rx.search(rel):
            return kind
    if HARNESS_PROSE.search(rel):
        return "source"
    return "source" if SOURCE_EXT.search(rel) else "docs"


def non_trivial(paths, root=""):
    """Cláusulas (a)+(c) sobre el conjunto de UN turno. Espejo de `countNonTrivial`.

    Un test cuenta solo cuando ES el cambio: con cualquier fuente no-test
    presente, los tests acompañan y no suman. Sin ese brazo la regla sería
    inaplicable en este repo, que pide un test con cada fix.

    Es un TECHO, no un conteo exacto: la cláusula (b) —¿el cambio altera el
    comportamiento, o solo propaga un rename?— necesita el contenido del diff, y
    aquí solo hay rutas.
    """
    src = [p for p in paths if classify_path(p, root) == "source"]
    tests = [p for p in paths if classify_path(p, root) == "test"]
    return src if src else tests


def load(prefix):
    for d in os.listdir(PROJECTS):
        for f in glob.glob(os.path.join(PROJECTS, d, prefix + "*.jsonl")):
            return f
    return None


def subagent_transcripts(main_path, session):
    """Los transcripts de los subagentes de ESTA sesión.

    `load()` devuelve solo el `<session>.jsonl` del hilo principal, y el trabajo
    de los subagentes vive aparte, en `<proyecto>/<session>/subagents/`. Nunca se
    abrían: 652 archivos en el parque, invisibles para toda medición de este
    script. El sesgo va en una sola dirección —penaliza justo a las sesiones que
    delegan, que son las que el harness quiere premiar—, el mismo defecto
    direccional que #674 documentó en el clasificador de archivos.
    """
    if not main_path:
        return []
    return sorted(glob.glob(
        os.path.join(os.path.dirname(main_path), session, "subagents", "agent-*.jsonl")))


def subagent_skills(main_path, session):
    """Uso de skills dentro de los subagentes, por las DOS vías, separadas.

    Separadas porque miden cosas distintas y una de las dos resultó ser casi
    toda la señal. Medido sobre los 652 transcripts de subagente del parque:

      - invocación explícita (`Skill` tool_use) dentro de un subagente: **2**
      - records con `attributionSkill` heredado del padre:          **~1,400**

    Un subagente casi nunca invoca una skill: la HEREDA. Sumar solo los tool_use
    —el remedio que pedía el issue— habría agregado dos llamadas en todo el
    parque y dejado fuera el resto. El campo es el mismo que `lib/audit` consume
    desde #725; aquí se lee con la misma cautela, porque el formato del
    transcript es interno al host y puede cambiar en cualquier release.
    """
    invoked, inherited = Counter(), Counter()
    for f in subagent_transcripts(main_path, session):
        try:
            fh = open(f, errors="replace")
        except OSError:
            continue
        with fh:
            for line in fh:
                # Filtro barato antes de parsear: la inmensa mayoría de los
                # records no dice nada de skills y este bucle corre sobre cientos
                # de archivos.
                if '"Skill"' not in line and "attributionSkill" not in line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                if d.get("type") != "assistant":
                    continue
                a = d.get("attributionSkill")
                if isinstance(a, str) and a:
                    inherited[a] += 1
                c = (d.get("message") or {}).get("content")
                if not isinstance(c, list):
                    continue
                for b in c:
                    if not isinstance(b, dict) or b.get("type") != "tool_use":
                        continue
                    if b.get("name") != "Skill":
                        continue
                    sk = (b.get("input") or {}).get("skill")
                    if isinstance(sk, str) and sk:
                        invoked[sk] += 1
    return invoked, inherited


def text_of(msg):
    c = (msg or {}).get("content")
    if isinstance(c, str):
        return c
    return "\n".join(b.get("text") or "" for b in c
                     if isinstance(b, dict) and b.get("type") == "text") if isinstance(c, list) else ""


def sig(cmd):
    """Firma de comando: sin el `cd ... &&` de cabecera, primeros 4 tokens."""
    return " ".join(CD_PREFIX.sub("", cmd or "").split()[:4])


def is_debuggable(x):
    """¿Este fallo pide diagnóstico, o trae su causa escrita?"""
    if not x["error"]:
        return False
    out = x["out"] or ""
    if HOOK_BLOCK.search(out[:200]) or DENIED.search(out[:300]):
        return False
    return bool(VERIFY_CMD.search(str(x["input"].get("command", "")))) or bool(ERROR_LINE.search(out))


def parse(path):
    """Devuelve turnos del hilo principal. Cada tool_use lleva su is_error."""
    turns, cur, mode = [], None, Counter()
    pending = {}   # tool_use_id -> dict del tool en el turno
    with open(path) as fh:
        for line in fh:
            try:
                d = json.loads(line)
            except Exception:
                continue
            if d.get("permissionMode"):
                mode[d["permissionMode"]] += 1
            if d.get("isSidechain"):
                continue
            t, msg = d.get("type"), d.get("message") or {}
            c = msg.get("content")
            if t == "user":
                blocks = c if isinstance(c, list) else []
                results = [b for b in blocks if isinstance(b, dict) and b.get("type") == "tool_result"]
                if results:
                    for b in results:
                        tu = pending.get(b.get("tool_use_id"))
                        if tu is not None:
                            tu["error"] = bool(b.get("is_error"))
                            body = b.get("content")
                            tu["out"] = body if isinstance(body, str) else json.dumps(body)[:8000]
                    continue
                txt = text_of(msg)
                if txt.strip():
                    cur = {"user": txt, "tools": [], "assistant": []}
                    turns.append(cur)
            elif t == "assistant" and cur is not None and isinstance(c, list):
                for b in c:
                    if not isinstance(b, dict):
                        continue
                    if b.get("type") == "tool_use":
                        rec = {"name": b.get("name"), "input": b.get("input") or {},
                               "error": False, "out": ""}
                        cur["tools"].append(rec)
                        pending[b.get("id")] = rec
                    elif b.get("type") == "text":
                        cur["assistant"].append(b.get("text") or "")
    return turns, mode


def analyze(session, examples):
    path = load(session)
    if not path:
        return None
    turns, mode = parse(path)
    repo = os.path.basename(os.path.dirname(path)).split("-Docs-")[-1]
    # La raíz del repo de ESTA sesión, para poder decir "fuera del repo". Sale
    # de la cabecera de su log de audit, que es donde el hook la registró.
    root = session_cwd(session)

    opp, hit, auto, asked = Counter(), Counter(), Counter(), Counter()
    failed_once = {}

    for ti, t in enumerate(turns):
        u = t["user"].lower()
        cmds = " ; ".join(str(x["input"].get("command", "")) for x in t["tools"]
                          if x["name"] == "Bash")
        used_skill = {canon_skill(str(x["input"].get("skill", ""))) for x in t["tools"]
                      if x["name"] == "Skill"}
        used_agent = {canon_role(str(x["input"].get("subagent_type", ""))) for x in t["tools"]
                      if x["name"] in ("Agent", "Task")}

        for x in t["tools"]:
            if x["name"] == "Skill":
                s = canon_skill(str(x["input"].get("skill", "?")))
                (asked if (s in u) else auto)[s] += 1
            elif x["name"] in ("Agent", "Task"):
                a = canon_role(str(x["input"].get("subagent_type", "?")))
                (asked if a in u else auto)[a] += 1

        def mark(key, cond, agent=None, skill=None, note=""):
            got = (agent in used_agent if agent else False) or (skill in used_skill if skill else False)
            # `got` implica oportunidad: cuando se delega, el trabajo ocurre en el
            # sidechain y `cond` (que mira el hilo principal) es ciego. Sin esto el
            # 0% sería un artefacto del instrumento, no un hallazgo.
            if not cond and not got:
                return
            opp[key] += 1
            if got:
                hit[key] += 1
            elif len(examples[key]) < 3:
                examples[key].append(f"{session} turno {ti+1}: {note[:110]}")

        # O1 — implementer: 2+ archivos fuente NO TRIVIALES tocados en el turno.
        # "No trivial" sale del clasificador compartido, no de una regex de
        # extensiones: descarta generados, efímeros, fuera-del-repo, y los tests
        # que acompañan a un fuente ya contado (cláusula c).
        written = [str(x["input"].get("file_path", "")) for x in t["tools"]
                   if x["name"] in ("Edit", "Write") and x["input"].get("file_path")]
        touched = set(non_trivial(written, root))
        mark("implementer", len(touched) >= 2, agent="implementer",
             note=f"{len(touched)} archivos fuente: {sorted(touched)[:2]}")

        # O2 — verify-before-done: afirma cierre sin comando de verificación en el turno
        final = "\n".join(t["assistant"])[-1500:]
        mark("verify-before-done",
             bool(touched) and bool(DONE_CLAIM.search(final)) and not VERIFY_CMD.search(cmds),
             skill="verify-before-done", note=t["user"][:60])

        # O3 — debug-error: un fallo que hay que DIAGNOSTICAR.
        #
        # La versión anterior pedía >=5 líneas de error ("pared de errores") y
        # daba 0 oportunidades en 58 sesiones. No era una heurística estrecha:
        # la condición no ocurre. Sobre 281 llamadas fallidas, NINGUNA llega a 3
        # líneas de error —ni siquiera las 67 que no llevan truncado explícito,
        # una de ellas con 387 líneas de salida—. El gate corre como hook ANTES
        # del commit, así que una suite roja se manifiesta como UN `git commit`
        # bloqueado, no como cuarenta líneas que triagear; y el 89.2% de los
        # comandos de verificación pasan por `| tail`/`| head`, con mediana de
        # salida de 7 líneas.
        #
        # El disparador de la skill se reapuntó a "falló y no sé por qué", así
        # que esto mide eso: un fallo que pide diagnóstico. Se excluyen los dos
        # que NO lo piden —un bloqueo de hook y un permiso denegado son el
        # harness funcionando, y su causa viene escrita en la propia salida—.
        # Es un PISO, no un techo: un fallo auto-explicativo (ruta inexistente)
        # que traiga una línea de error reconocible entra igual.
        debuggable = any(is_debuggable(x) for x in t["tools"])
        mark("debug-error", debuggable, skill="debug-failure", note=t["user"][:60])

        # O4 — se abre PR
        mark("pr → review-diff/pilot", bool(PR_CMD.search(cmds)),
             agent="publisher", skill="review-diff", note=t["user"][:60])

        # O5 — reviewer: código fuente editado y commiteado en el mismo turno
        mark("reviewer", bool(touched) and bool(COMMIT_CMD.search(cmds)),
             agent="reviewer", note=f"{len(touched)} archivos + git commit")

        # O6 — loop-back-debug: MISMO comando falla dos veces en la sesión
        for x in t["tools"]:
            if x["name"] != "Bash" or not x["error"]:
                continue
            k = sig(str(x["input"].get("command", "")))
            if len(k) < 6:
                continue
            if failed_once.get(k):
                mark("loop-back-debug", True, skill="debug-failure", note=k)
            failed_once[k] = True

    sub_invoked, sub_inherited = subagent_skills(path, session)

    first = turns[0]["user"][:60].replace("\n", " ") if turns else ""
    broad = bool(re.search(r"implementa|construye|crea |feature|migra|refactor|spec", first, re.I))
    return dict(session=session, repo=repo, turns=len(turns), first=first,
                mode="+".join(f"{k}:{v}" for k, v in mode.most_common(2)) or "?",
                scope="amplio" if broad else "incremental",
                opp=opp, hit=hit, auto=auto, asked=asked,
                sub_invoked=sub_invoked, sub_inherited=sub_inherited,
                sub_files=len(subagent_transcripts(path, session)))


def _selftest():
    """Fixture del criterio 2 (spec 0026 T17, R43): una sesión sintética con un
    `Agent`/`Task` de `subagent_type` `architect` debe producir un conteo
    distinto de cero en AUTO o ASKED. El criterio 2 mide delegación explícita
    hacia `architect` (R49) — sin este fixture, un regreso a cero pasaría
    desapercibido porque el script no tiene otra suite que lo ejerza.

    Construye un `~/.claude/projects`/`audits` de usar y tirar en un
    `tempfile.TemporaryDirectory`, apunta los globals del módulo ahí, y corre
    `analyze()` de verdad — no una copia paralela del conteo — para que el
    fixture falle si la lógica real deja de contar `architect`.
    """
    import tempfile

    global PROJECTS, AUDITS
    with tempfile.TemporaryDirectory() as tmp:
        PROJECTS = os.path.join(tmp, "projects")
        AUDITS = os.path.join(tmp, "audits")
        proj_dir = os.path.join(PROJECTS, "-tmp-fixture-repo")
        os.makedirs(proj_dir)
        session = "fixture-architect"
        transcript = [
            {"type": "user", "message": {"content": "usa a architect para proponer el diseño"}},
            {
                "type": "assistant",
                "message": {
                    "content": [
                        {
                            "type": "tool_use",
                            "name": "Agent",
                            "input": {
                                "subagent_type": "architect",
                                "description": "propone el diseño",
                            },
                        }
                    ]
                },
            },
        ]
        with open(os.path.join(proj_dir, f"{session}.jsonl"), "w") as fh:
            for rec in transcript:
                fh.write(json.dumps(rec) + "\n")

        examples = {k: [] for k in ["implementer", "verify-before-done", "debug-error",
                                    "pr → review-diff/pilot", "reviewer", "loop-back-debug"]}
        result = analyze(session, examples)
        assert result is not None, "la sesión fixture debió parsear"
        count = result["auto"].get("architect", 0) + result["asked"].get("architect", 0)
        assert count != 0, f"conteo de 'architect' debió ser distinto de cero, salió {count}"
        print(f"OK selftest: subagent_type=architect conteo={count}")


# ─── Fase 2 — planificación por niveles (spec 0032, R32) ────────────────────
#
# Por repo: total de tareas, conteo por nivel, porcentaje de nivel >= 1,
# clasificaciones erróneas y escalamientos por rechazo. Una "tarea" es UN
# despacho al `implementer`: la línea de apertura del encargo que el gate
# exige (`workplan: <feature>` o `nivel-0: <path>`, R16) es la marca que este
# script reconoce en el `tool_use` de `Agent`/`Task` del hilo principal — el
# mismo contrato que `evaluatePlanGate` valida en vivo
# (`packages/cli/src/lib/plan/gate.ts`).
WORKPLAN_LINE_RX = re.compile(r"^workplan:\s*(\S+)")
NIVEL0_LINE_RX = re.compile(r"^nivel-0:\s*(\S+)")
PROGRESS_DIRNAME = ".claude/progress"


def _read_workplan_level(root, feature):
    """Nivel declarado, leído del JSON del workplan si SIGUE en disco.

    Es un artefacto efímero y gitignored (`workplan_<feature>.json`): una
    tarea posterior lo puede sobrescribir antes de que este script mine la
    sesión. Ausente no es cero — es "no verificable", y se cuenta aparte
    (`unverifiable`) en vez de sesgar el reparto por nivel.
    """
    path = os.path.join(root, PROGRESS_DIRNAME, f"workplan_{feature}.json")
    if not os.path.isfile(path):
        return None
    try:
        with open(path, errors="replace") as fh:
            return json.load(fh).get("level")
    except Exception:
        return None


def _read_gate_log_rejections(root, feature):
    """Rechazos `CHANGES_REQUESTED` distintos que el gate ya grabó para este
    feature (`workplan_<feature>.gate.jsonl`, `recordAndCountRejections` en
    `lib/plan/gate.ts`, R19). Cada línea es una entrada; basta con contarlas."""
    path = os.path.join(root, PROGRESS_DIRNAME, f"workplan_{feature}.gate.jsonl")
    if not os.path.isfile(path):
        return 0
    n = 0
    with open(path, errors="replace") as fh:
        for line in fh:
            if line.strip():
                n += 1
    return n


def run_classify_diff(root, feature, dirname=PROGRESS_DIRNAME):
    """Invoca `navori plan classify <feature> --diff --json` de verdad — R32
    llama a la única definición de nivel (R1) en vez de reimplementar los
    pesos de `signals.ts` en Python. Devuelve el JSON parseado, o `None`
    cuando `navori` no está en PATH, el comando falla, o el workplan ya
    rotó fuera de disco: "no verificable", nunca un valor adivinado.

    Nombre de módulo (no un método de clase) a propósito: los tests lo
    reasignan como global, igual que `_selftest` ya reasigna `PROJECTS`/
    `AUDITS` — no hay `unittest.mock` en este script.
    """
    import subprocess

    try:
        proc = subprocess.run(
            [
                "navori",
                "plan",
                "classify",
                feature,
                "--diff",
                "origin/main",
                "--json",
                "--cwd",
                root,
                "--dir",
                dirname,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    # 0 = no excede el nivel declarado, 1 = lo excede (R21): ambos son un
    # veredicto válido. Cualquier otro código es un fallo del comando.
    if proc.returncode not in (0, 1):
        return None
    try:
        return json.loads(proc.stdout.strip().splitlines()[-1])
    except Exception:
        return None


def mine_dispatches(session):
    """Cada despacho al `implementer` en el hilo principal de la sesión.

    Un despacho sin la línea de apertura del gate (`workplan:`/`nivel-0:`) no
    es una tarea que `plan classify` pueda evaluar — pasa solo cuando el gate
    está apagado o degradado (R17); se excluye en vez de adivinar su nivel.
    """
    path = load(session)
    if not path:
        return []
    root = session_cwd(session)
    dispatches = []
    with open(path, errors="replace") as fh:
        for line in fh:
            try:
                d = json.loads(line)
            except Exception:
                continue
            if d.get("type") != "assistant":
                continue
            content = (d.get("message") or {}).get("content")
            if not isinstance(content, list):
                continue
            for b in content:
                if not isinstance(b, dict) or b.get("type") != "tool_use":
                    continue
                if b.get("name") not in ("Agent", "Task"):
                    continue
                inp = b.get("input") or {}
                if canon_role(str(inp.get("subagent_type", ""))) != "implementer":
                    continue
                first_line = str(inp.get("prompt", "")).split("\n", 1)[0].strip()
                m0 = NIVEL0_LINE_RX.match(first_line)
                mw = WORKPLAN_LINE_RX.match(first_line)
                if m0:
                    dispatches.append(dict(session=session, root=root, feature=None,
                                            declared_level=0))
                elif mw:
                    feature = mw.group(1)
                    dispatches.append(dict(session=session, root=root, feature=feature,
                                            declared_level=_read_workplan_level(root, feature)))
    return dispatches


def mine_plan_tiers(sessions):
    """R32: por repo, total de tareas, conteo por nivel, % de nivel >= 1,
    clasificaciones erróneas y escalamientos por rechazo.

    Cruce de instrumento: una escalación grabada por el gate exige al menos
    dos despachos previos del MISMO feature (R19 — dos `CHANGES_REQUESTED`
    antes de exigir el nivel siguiente). Si el log de escalaciones tiene
    rechazos para un feature del que esta lista de sesiones vio menos de dos
    despachos, la lista está incompleta para ese repo: se reporta
    `doubtful_instrument` en vez del porcentaje (Contracts, design.md).
    """
    by_repo = {}
    for s in sessions:
        path = load(s)
        if not path:
            continue
        repo = os.path.basename(os.path.dirname(path)).split("-Docs-")[-1]
        entry = by_repo.setdefault(repo, dict(tasks=[], dispatch_counts=Counter()))
        for d in mine_dispatches(s):
            entry["tasks"].append(d)
            if d["feature"]:
                entry["dispatch_counts"][d["feature"]] += 1

    report = {}
    for repo, entry in by_repo.items():
        tasks = entry["tasks"]
        total = len(tasks)
        level_counts = Counter(t["declared_level"] for t in tasks
                                if t["declared_level"] is not None)
        unverifiable = sum(1 for t in tasks if t["declared_level"] is None)

        escalations, misclassified, checked, doubtful = 0, 0, 0, False
        seen = set()
        for t in tasks:
            feature, root = t["feature"], t["root"]
            if not feature or feature in seen:
                continue
            seen.add(feature)
            rejections = _read_gate_log_rejections(root, feature)
            if rejections >= 2:
                escalations += 1
                if entry["dispatch_counts"][feature] < 2:
                    doubtful = True
            if t["declared_level"] is not None:
                verdict = run_classify_diff(root, feature)
                if verdict is not None:
                    checked += 1
                    if verdict.get("exceedsDeclared"):
                        misclassified += 1

        classifiable = total - unverifiable
        pct_ge1 = None
        if not doubtful and classifiable:
            n_ge1 = sum(c for lvl, c in level_counts.items() if lvl >= 1)
            pct_ge1 = 100 * n_ge1 / classifiable

        sessions_for_repo = len({t["session"] for t in tasks})
        report[repo] = dict(
            total_tasks=total,
            level_counts=dict(level_counts),
            unverifiable=unverifiable,
            pct_level_ge1=pct_ge1,
            misclassified=misclassified,
            checked=checked,
            escalations=escalations,
            doubtful_instrument=doubtful,
            sessions=sessions_for_repo,
            provisional=sessions_for_repo < 15,
        )
    return report


def print_plan_tiers_report(report, out=sys.stdout):
    out.write("\n" + "=" * 104 + "\n")
    out.write("PLANIFICACIÓN POR NIVELES — por repo (R32)\n")
    out.write("=" * 104 + "\n")
    for repo in sorted(report):
        r = report[repo]
        prov = " (provisional: < 15 sesiones)" if r["provisional"] else ""
        out.write(f"\n{repo}{prov}\n")
        out.write(f"  tareas={r['total_tasks']} (no verificables={r['unverifiable']}) "
                   f"sesiones={r['sessions']}\n")
        out.write(f"  por nivel: {r['level_counts']}\n")
        if r["doubtful_instrument"]:
            out.write("  % nivel >= 1: instrumento en duda (escalaciones grabadas sin los "
                       "despachos que las explican en esta lista de sesiones)\n")
        elif r["pct_level_ge1"] is not None:
            out.write(f"  % nivel >= 1: {r['pct_level_ge1']:.1f}%\n")
        else:
            out.write("  % nivel >= 1: sin tareas verificables\n")
        out.write(f"  clasificaciones erróneas: {r['misclassified']}/{r['checked']} verificadas\n")
        out.write(f"  escalamientos por rechazo: {r['escalations']}\n")


def _selftest_plan_tiers():
    """Un fixture por métrica de R32, cada uno en su propio directorio de
    usar y tirar, ejerciendo `mine_plan_tiers` de verdad — no una copia
    paralela del conteo."""
    import tempfile

    global PROJECTS, AUDITS, run_classify_diff

    def _write_session(proj_dir, session, dispatches):
        """`dispatches`: lista de líneas de apertura del encargo
        (`"workplan: foo"` / `"nivel-0: a.ts"`), una por despacho."""
        recs = []
        for opening in dispatches:
            recs.append({"type": "user", "message": {"content": f"despacha ({opening})"}})
            recs.append({
                "type": "assistant",
                "message": {"content": [{
                    "type": "tool_use", "name": "Agent",
                    "input": {"subagent_type": "implementer", "prompt": f"{opening}\nresto"},
                }]},
            })
        with open(os.path.join(proj_dir, f"{session}.jsonl"), "w") as fh:
            for rec in recs:
                fh.write(json.dumps(rec) + "\n")

    def _fresh_repo(tmp, name):
        proj_dir = os.path.join(PROJECTS, name)
        os.makedirs(proj_dir, exist_ok=True)
        return proj_dir

    with tempfile.TemporaryDirectory() as tmp:
        PROJECTS = os.path.join(tmp, "projects")
        AUDITS = os.path.join(tmp, "audits")
        os.makedirs(PROJECTS)
        real_run_classify_diff = run_classify_diff
        run_classify_diff = lambda root, feature, dirname=PROGRESS_DIRNAME: None  # noqa: E731

        # Métrica 1: total_tasks — dos despachos, uno nivel 0, uno workplan.
        proj = _fresh_repo(tmp, "fixture-total")
        root = os.path.join(tmp, "repo-total")
        os.makedirs(root, exist_ok=True)
        audits_repo = os.path.join(AUDITS, "fixture-total")
        os.makedirs(audits_repo, exist_ok=True)
        with open(os.path.join(audits_repo, "session-s-total.log"), "w") as fh:
            fh.write(json.dumps({"event": "start", "cwd": root}) + "\n")
        _write_session(proj, "s-total", ["nivel-0: a.ts", "workplan: feat-a"])
        report = mine_plan_tiers(["s-total"])
        r = report["fixture-total"]
        assert r["total_tasks"] == 2, f"total_tasks debió ser 2, salió {r['total_tasks']}"
        assert r["unverifiable"] == 1, "feat-a sin workplan.json en disco debe contar no verificable"

        # Métrica 2: conteo por nivel — con los workplans en disco.
        proj = _fresh_repo(tmp, "fixture-levels")
        root = os.path.join(tmp, "repo-levels")
        os.makedirs(os.path.join(root, PROGRESS_DIRNAME), exist_ok=True)
        for feature, level in [("f0", 0), ("f1", 1), ("f2", 2)]:
            with open(os.path.join(root, PROGRESS_DIRNAME, f"workplan_{feature}.json"), "w") as fh:
                json.dump({"level": level}, fh)
        AUDITS_repo = os.path.join(AUDITS, "fixture-levels")
        os.makedirs(AUDITS_repo, exist_ok=True)
        with open(os.path.join(AUDITS_repo, "session-s-levels.log"), "w") as fh:
            fh.write(json.dumps({"event": "start", "cwd": root}) + "\n")
        _write_session(proj, "s-levels", ["workplan: f0", "workplan: f1", "workplan: f2"])
        report = mine_plan_tiers(["s-levels"])
        r = report["fixture-levels"]
        assert r["level_counts"] == {0: 1, 1: 1, 2: 1}, r["level_counts"]

        # Métrica 3: % nivel >= 1 — reusa el fixture de niveles: 2 de 3 son >= 1.
        assert abs(r["pct_level_ge1"] - (200 / 3)) < 0.01, r["pct_level_ge1"]

        # Métrica 4: clasificaciones erróneas — `run_classify_diff` fijo a
        # "excede el nivel declarado" para exactamente un feature.
        run_classify_diff = lambda root, feature, dirname=PROGRESS_DIRNAME: (
            {"exceedsDeclared": True} if feature == "f1" else {"exceedsDeclared": False}
        )
        report = mine_plan_tiers(["s-levels"])
        r = report["fixture-levels"]
        assert r["misclassified"] == 1, f"misclassified debió ser 1, salió {r['misclassified']}"
        assert r["checked"] == 3, r["checked"]
        run_classify_diff = lambda root, feature, dirname=PROGRESS_DIRNAME: None  # noqa: E731

        # Métrica 5: escalamientos por rechazo — dos despachos del mismo
        # feature más dos rechazos grabados en su `.gate.jsonl`.
        proj = _fresh_repo(tmp, "fixture-escalation")
        root = os.path.join(tmp, "repo-escalation")
        os.makedirs(os.path.join(root, PROGRESS_DIRNAME), exist_ok=True)
        with open(os.path.join(root, PROGRESS_DIRNAME, "workplan_feat-b.gate.jsonl"), "w") as fh:
            fh.write(json.dumps({"reviewHash": "h1", "verdict": "CHANGES_REQUESTED"}) + "\n")
            fh.write(json.dumps({"reviewHash": "h2", "verdict": "CHANGES_REQUESTED"}) + "\n")
        AUDITS_repo = os.path.join(AUDITS, "fixture-escalation")
        os.makedirs(AUDITS_repo, exist_ok=True)
        with open(os.path.join(AUDITS_repo, "session-s-escalation.log"), "w") as fh:
            fh.write(json.dumps({"event": "start", "cwd": root}) + "\n")
        _write_session(proj, "s-escalation", ["workplan: feat-b", "workplan: feat-b"])
        report = mine_plan_tiers(["s-escalation"])
        r = report["fixture-escalation"]
        assert r["escalations"] == 1, f"escalations debió ser 1, salió {r['escalations']}"
        assert r["doubtful_instrument"] is False, "dos despachos vistos explican la escalación"

        # Métrica 6: instrumento en duda — misma escalación, pero la lista de
        # sesiones solo trae UN despacho de `feat-b`: falta evidencia.
        with open(os.path.join(AUDITS_repo, "session-s-escalation-solo.log"), "w") as fh:
            fh.write(json.dumps({"event": "start", "cwd": root}) + "\n")
        _write_session(proj, "s-escalation-solo", ["workplan: feat-b"])
        report = mine_plan_tiers(["s-escalation-solo"])
        r = report["fixture-escalation"]
        assert r["doubtful_instrument"] is True, "un despacho no explica dos rechazos grabados"
        assert r["pct_level_ge1"] is None, "en duda no debe reportar un porcentaje"

        # Métrica 7: provisional — menos de 15 sesiones por repo.
        assert r["provisional"] is True, "una sola sesión debe marcarse provisional"

        run_classify_diff = real_run_classify_diff
        print("OK selftest: mine_plan_tiers cubre las 7 métricas de R32")


if len(sys.argv) > 1 and sys.argv[1] == "--selftest":
    _selftest()
    _selftest_plan_tiers()
    sys.exit(0)

if len(sys.argv) > 2 and sys.argv[1] == "--plan-tiers":
    plan_sessions = [s.strip() for s in open(sys.argv[2]) if s.strip()]
    print_plan_tiers_report(mine_plan_tiers(plan_sessions))
    sys.exit(0)

SESSIONS = [s.strip() for s in open(sys.argv[1]) if s.strip()]
examples = {k: [] for k in ["implementer", "verify-before-done", "debug-error",
                            "pr → review-diff/pilot", "reviewer", "loop-back-debug"]}
rows = [r for r in (analyze(s, examples) for s in SESSIONS) if r]

print("=" * 104)
print(f"{'sesión':<10}{'repo':<24}{'turnos':>7}  {'modo':<26}{'scope':<13}{'activadas/oportunidades':>24}")
print("=" * 104)
TO, TH, AUTO, ASKED = Counter(), Counter(), Counter(), Counter()
for r in rows:
    TO += r["opp"]; TH += r["hit"]; AUTO += r["auto"]; ASKED += r["asked"]
    o, h = sum(r["opp"].values()), sum(r["hit"].values())
    print(f"{r['session']:<10}{r['repo'][:23]:<24}{r['turns']:>7}  {r['mode'][:25]:<26}"
          f"{r['scope']:<13}{f'{h}/{o}':>24}")

print("\n" + "=" * 104)
print("POR DISPARADOR")
print("=" * 104)
print(f"{'disparador':<26}{'oportunidades':>15}{'activadas':>12}{'tasa':>8}")
for k in sorted(TO, key=lambda x: -TO[x]):
    o, h = TO[k], TH[k]
    print(f"{k:<26}{o:>15}{h:>12}{(100*h//o if o else 0):>7}%")
to, th = sum(TO.values()), sum(TH.values())
print(f"{'TOTAL':<26}{to:>15}{th:>12}{(100*th//to if to else 0):>7}%")

# ─── La distribución, no solo el agregado ───────────────────────────────────
#
# Una tasa agregada invita a leer una propiedad donde solo hay una media, y esa
# lectura ya costó una investigación entera (#705). El agregado por repo daba
# "cuatro repos donde el harness está inerte"; medida la distribución, dos
# tercios de TODAS las sesiones no delegan nada —en los repos que "sí delegan"
# también—, y que las pocas sesiones de un repo caigan todas de ese lado es lo
# que se espera por azar, no una propiedad suya.
#
# Se exige un mínimo de oportunidades por sesión: una sesión con una sola
# oportunidad es 0% o 100% y solo agrega varianza al histograma.
MIN_OPP = 3
buckets = Counter()
graded = 0
for r in rows:
    o, h = sum(r["opp"].values()), sum(r["hit"].values())
    if o < MIN_OPP:
        continue
    graded += 1
    rate = 100 * h / o
    buckets["0%" if rate == 0 else "1-24%" if rate < 25 else "25-74%" if rate < 75 else "75-100%"] += 1

print("\n" + "=" * 104)
print(f"DISTRIBUCIÓN POR SESIÓN — {graded} sesiones con >= {MIN_OPP} oportunidades")
print("=" * 104)
if graded:
    for k in ["0%", "1-24%", "25-74%", "75-100%"]:
        n = buckets[k]
        print(f"  {k:>8}{n:>5}  ({100*n/graded:4.1f}%)  {'#' * round(40 * n / graded)}")
    base = buckets["0%"] / graded
    # La doctrina vigente DURANTE la medición, que es lo único que este número
    # describe. Sin ella, una tasa base se lee como una propiedad del harness en
    # vez de como una foto de la versión que estaba puesta.
    vers = sorted({v for v in (session_version(r["session"]) for r in rows) if v})
    if vers:
        span = vers[0] if len(vers) == 1 else f"{vers[0]} … {vers[-1]}"
        print(f"\n  Versiones renderizadas durante estas sesiones: {span}")
    print(f"\n  Tasa base de sesiones que NO delegan nada: {100*base:.1f}%.")
    print("  Con esa base, que las N sesiones de un repo salgan todas en cero tiene")
    print(f"  probabilidad {100*base:.0f}%^N — con 3 sesiones, {100*base**3:.0f}%. Antes de")
    print("  leer una propiedad del repo en un agregado, contar cuántas sesiones lo forman.")
else:
    print(f"  (ninguna sesión llegó a {MIN_OPP} oportunidades)")

# ─── El desglose por repo, con su denominador al lado ───────────────────────
#
# El agregado escondía que un repo aporta la mayoría de los fallos y otro está
# cinco veces por encima de la media (#705), así que la tabla se imprime. Pero
# se imprime CON la columna de sesiones y con la nota de abajo: sin ellas, una
# fila en cero se lee como una propiedad del repo, que es exactamente la lectura
# que el bloque de distribución de arriba existe para corregir.
#
# Se detalla aparte el disparador que motivó el issue —`pr → review-diff/pilot`,
# el de mayor volumen— porque el total por repo mezcla seis disparadores con
# tasas muy distintas, y esa media tampoco es una propiedad del repo.
PILOT = "pr → review-diff/pilot"
by_repo = {}
for r in rows:
    a = by_repo.setdefault(r["repo"], dict(sessions=0, opp=0, hit=0, popp=0, phit=0))
    a["sessions"] += 1
    a["opp"] += sum(r["opp"].values())
    a["hit"] += sum(r["hit"].values())
    a["popp"] += r["opp"][PILOT]
    a["phit"] += r["hit"][PILOT]

print("\n" + "=" * 104)
print("POR REPO — omite los repos sin oportunidades; el TOTAL cuadra con POR DISPARADOR")
print("=" * 104)
print(f"{'repo':<34}{'sesiones':>9}{'opp':>7}{'activadas':>11}{'tasa':>7}"
      f"{'pr-opp':>9}{'pr-act':>9}{'tasa':>7}")
for k in sorted((k for k, v in by_repo.items() if v["opp"]),
                key=lambda x: (-by_repo[x]["opp"], x)):
    a = by_repo[k]
    print(f"{k[:33]:<34}{a['sessions']:>9}{a['opp']:>7}{a['hit']:>11}"
          f"{(100*a['hit']//a['opp']):>6}%"
          f"{a['popp']:>9}{a['phit']:>9}{(100*a['phit']//a['popp'] if a['popp'] else 0):>6}%")
po, ph = TO[PILOT], TH[PILOT]
print(f"{'TOTAL':<34}{len(rows):>9}{to:>7}{th:>11}{(100*th//to if to else 0):>6}%"
      f"{po:>9}{ph:>9}{(100*ph//po if po else 0):>6}%")
print("\n  'sesiones' es el denominador real de la fila, y la fila no se puede leer sin él:")
if graded:
    print(f"  con una tasa base de {100*base:.1f}% de sesiones que NO delegan nada, un repo de")
    print("  pocas sesiones saliendo en cero es lo esperable por azar, no una propiedad suya.")
else:
    print("  con la tasa base de sesiones que no delegan nada, un repo de pocas sesiones")
    print("  saliendo en cero es lo esperable por azar, no una propiedad suya.")
print("  Solo una fila con muchas oportunidades sostiene una lectura sobre ESE repo.")
print("  El TOTAL cuenta las sesiones de todos los repos, también los omitidos por no")
print("  tener ninguna oportunidad.")

print("\n" + "=" * 104)
print("INVOCACIONES REALES — automáticas vs pedidas por el usuario")
print("=" * 104)
for k in sorted(set(AUTO) | set(ASKED)):
    print(f"  {k:<24} automática={AUTO[k]:<4} pedida={ASKED[k]}")

# ─── Lo que ocurre DENTRO de los subagentes ─────────────────────────────────
#
# Aparte y no sumado al bloque de arriba, a propósito: ese cuenta invocaciones
# del hilo principal, y mezclarle records de trabajo heredado convertiría una
# tabla de "cuántas veces se pidió" en un híbrido que no responde ninguna de las
# dos preguntas. Es la trampa que este archivo ya pagó dos veces (#673, #674):
# un contador leído como si midiera otra cosa.
SUB_INV, SUB_INH = Counter(), Counter()
sub_files = 0
for r in rows:
    SUB_INV += r["sub_invoked"]; SUB_INH += r["sub_inherited"]; sub_files += r["sub_files"]
print("\n" + "=" * 104)
print(f"DENTRO DE LOS SUBAGENTES — {sub_files} transcripts que este script no abría")
print("=" * 104)
if sub_files == 0:
    print("  (ninguna sesión analizada delegó)")
else:
    print(f"  {'skill':<26}{'invocada':>10}{'heredada':>10}")
    for k in sorted(set(SUB_INV) | set(SUB_INH), key=lambda x: -(SUB_INH[x] + SUB_INV[x])):
        print(f"  {k[:24]:<26}{SUB_INV[k]:>10}{SUB_INH[k]:>10}")
    print(f"  {'TOTAL':<26}{sum(SUB_INV.values()):>10}{sum(SUB_INH.values()):>10}")
    print("\n  'invocada' = tool Skill dentro del subagente. 'heredada' = records que el")
    print("  host marcó con attributionSkill del padre. Un subagente casi nunca invoca")
    print("  una skill: la hereda, y esa columna es la que estaba perdida entera.")

print("\n" + "=" * 104)
print("EJEMPLOS de oportunidad NO activada (para auditar la heurística a mano)")
print("=" * 104)
for k, v in examples.items():
    for e in v:
        print(f"  [{k}] {e}")
