#!/usr/bin/env bash
#
# PreToolUse(Bash) guard: content search goes through the tgrep wrapper.
#
# WHY THIS IS A GUARD AND NOT A SENTENCE IN CLAUDE.md. The doctrine telling the
# model to route content search through the wrapper has shipped since 0.7.8 and
# is measured at 7.4% adoption over 2,761 real searches. The session that
# produced the best analysis of tgrep anyone has written still went through
# shell for 9 of every 10 searches (#668), so comprehension was never the
# bottleneck. In this harness the mechanical layers hold — guard-destructive 14
# blocks out of 14, quality-gate-pre-commit 7 out of 7 — and the advisory ones
# do not. This moves one doctrine across that line.
#
# WHAT IT BLOCKS, and nothing else: a segment that STARTS a command (never one
# after a pipe) and invokes `grep`/`egrep`/`fgrep` recursively, or `rg` with no
# single file target. Measured against the 8,562 real grep/rg invocations of the
# park: it fires on 55% of genuine content searches and on ZERO extractions.
#
# WHAT IT DELIBERATELY LETS THROUGH, because a false block teaches the model to
# route AROUND the guard — which is worse than the search it would have stopped:
#
#   · `… | grep x`        filtering another command's output (46% of all
#                         invocations). Not a repo search; the wrapper cannot
#                         replace it.
#   · `grep -n x file.ts` extracting from an ALREADY KNOWN file (22%). The
#                         harness's own doctrine prefers this to the wrapper.
#   · anything it cannot parse with certainty — a quoted pattern carrying a
#                         newline, an unbalanced quote. Unsure means allow.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add repo-specific exceptions in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# navori:include extract-cmd
cmd=$(extract_cmd)

navori_audit_name="guard-search-routing"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# `source` names the PLUGIN, not core: disabling tgrep changes which hooks run,
# and without this the report cannot explain why a phase thinned out between two
# sessions.
navori_audit_source="plugin:tgrep"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-log
navori_audit_begin

# The verdict is resolved in a trap, not by a call at the end of the file: this
# hook's managed block ends before its user section, so a call placed after it
# would live in the user's territory and never reach the mirror.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

if [ -z "$cmd" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin comando que inspeccionar"
  exit 0
fi

# The wrapper itself is never blocked — it runs `grep -rn` internally on the
# fallback path, and this hook sees the command the agent typed, not the one the
# wrapper spawns. Checked FIRST so no rule below can ever fire on it.
case "$cmd" in
  *tgrep-search.sh*)
    navori_audit_verdict="skip"
    navori_audit_reason="es el wrapper"
    exit 0
    ;;
esac

# INERT CONTENT: a heredoc body is DATA, not a call.
#
# Every rule below reads the command as TEXT, so a script or a test file written
# with `python3 - <<'PY' … PY` that merely QUOTES a search was blocked even
# though nothing ran. That is not hypothetical: it fired on the very session that
# was adding this guard's own regression tests, because one of the test cases IS
# the string `grep -rn "..." src/`.
#
# `guard-destructive` solves this properly, with a ~60-line pass that tells a
# documentation heredoc from a write-then-execute one. This guard does NOT copy
# it, and the asymmetry is the point: that guard defends against data loss and
# must resist an adversary, while this one redirects a search and fails open by
# design. Measured on the park, only 2.9% of its blocks (25 of 852) involve a
# heredoc at all, so giving them up costs almost nothing and removes an entire
# false-positive class in three lines instead of sixty.
#
# Yes, this means `… <<EOF` is an escape hatch. That is acceptable here: this
# guard is a mechanism against habit, not a sandbox.
case "$cmd" in
  *"<<"*)
    navori_audit_verdict="skip"
    navori_audit_reason="heredoc: el cuerpo es dato, no una llamada"
    exit 0
    ;;
esac

# BOUNDED WORK: the guard runs under a wall-clock timeout it does not control,
# and being killed is indistinguishable from approving. Every pass below is one
# linear `sed`/`grep` over the command; a command past the ceiling is ALLOWED
# rather than inspected, because this guard redirects a search — it does not
# protect against data loss, so failing open is the right failure here (and the
# opposite of what guard-destructive does with the same trade-off).
if [ "${#cmd}" -gt 20000 ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="comando demasiado grande para inspeccionar"
  exit 0
fi

# SEGMENTS. A command is split so each rule only ever matches WITHIN one
# segment, and each segment carries whether it starts a command or continues a
# pipe. That distinction is the whole design: `grep -n foo` is extraction from
# stdin after a `|`, and a repo search at the start of a line. The segment alone
# cannot tell them apart.
#
# Order matters: `||` must be rewritten before `|`, or the first `|` of a `||`
# is consumed and the second starts a bogus "piped" segment.
#
# A line continuation is NOT a separator: without joining it first, `\` + newline
# splits a quoted pattern in half and the fragment lands with no target, which
# every heuristic below reads as a recursive search. Measured on the park: that
# alone mislabelled over a thousand extractions.
segments=$(printf '%s' "$cmd" \
  | sed -e ':a' -e '$!N' -e 's/\\\n/ /' -e 'ta' -e 'P' -e 'D' \
  | sed -e 's/||/\
@C@/g' -e 's/&&/\
@C@/g' -e 's/;/\
@C@/g' -e 's/|/\
@P@/g')

# Does this segment name at least ONE concrete file among its TARGET operands?
#
# This is the difference between searching the repo and reading files you have
# already found, and it cannot be read off the flags: `grep -rn "oxlint"
# apps/a/package.json apps/b/package.json` carries `-r` and is pure extraction —
# grep ignores recursion once you hand it files. Blocking that shape cost a real
# session a round-trip for nothing, and it is 9.3% of every recursive grep in the
# park (124 of 1,328), concentrated on reading single files under `node_modules/`.
#
# ONE file is enough to allow, not all of them: this guard fails open by design,
# and a mixed `src/ extra.ts` is more likely a reader being sloppy than a search
# worth a round-trip.
#
# The first non-flag operand is the PATTERN and is skipped — otherwise
# `grep -rn "config.json" src/` would look like it names a file when what it
# names is what it is looking FOR.
names_a_file() {
  printf '%s' "$1" | awk '
    {
      seen_pattern = 0
      for (i = 2; i <= NF; i++) {
        t = $i
        if (substr(t, 1, 1) == "-") continue
        if (!seen_pattern) { seen_pattern = 1; continue }
        gsub(/^["'"'"']+|["'"'"']+$/, "", t)
        if (t ~ /\*/) continue
        if (t ~ /\/$/) continue
        if (t ~ /\.[A-Za-z0-9]+$/) found = 1
      }
    }
    END { exit(found ? 0 : 1) }
  '
}

block() {
  echo "[navori] BLOCKED by guard-search-routing: $1" >&2
  echo "[navori] route content search through the indexed wrapper:" >&2
  echo "[navori]   bash .claude/scripts/tgrep-search.sh <same ripgrep flags>" >&2
  echo "[navori] it carries its own 'allow' rule: no prompt, no classifier round-trip." >&2
  # The path is relative BECAUSE the allow rule is a literal
  # (`Bash(bash .claude/scripts/tgrep-search.sh *)`): any other spelling —
  # absolute, `cd … &&`, `$CLAUDE_PROJECT_DIR` (which is NOT set in the agent's
  # shell, only in a hook's) — stops matching it and buys a prompt. So the cwd
  # is a real constraint of the remedy, and saying so beats an exit 127 the
  # caller has to diagnose after already obeying (#724).
  echo "[navori] run it from the repo root: the path is relative because the" >&2
  echo "[navori] 'allow' rule is literal, and the shell keeps whatever cwd the" >&2
  echo "[navori] last 'cd' left." >&2
  echo "[navori] exit contract: 0 = match, 1 = no match, 2 = NOTHING WAS SEARCHED." >&2
  echo "[navori] this does NOT apply to '| grep' (filtering output) nor to" >&2
  echo "[navori] 'grep -n x known-file' (extracting from a file you already found):" >&2
  echo "[navori] both of those stay correct, and the wrapper cannot replace them." >&2
  # Only assignments here: nothing may come between the decision and `exit 2`.
  # The recording happens in the trap, after the exit is already committed.
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Walk the command-start segments only. `@P@` lines are dropped here, and that
# is what keeps every pipe-filter out of every rule below: the first line of the
# command carries no marker (it starts the command), and each `@C@` line starts
# a new one.
starts=$(printf '%s\n' "$segments" | sed -n -e 's/^@C@//p' -e '1{/^@[CP]@/!p;}')

while IFS= read -r seg; do
  [ -n "$seg" ] || continue

  # Peel `VAR=value` prefixes so the verb anchor below sees the real command
  # (#724 B2). `LC_ALL=C grep -rn foo src/` evaded every rule here by sitting
  # one token to the right of the anchor — verified: exit 0 against exit 2 for
  # the same command without the prefix.
  #
  # Parameter expansion, not a `sed` fork: this runs once per segment next to
  # two `grep -qE` forks that are already there, and a heredoc is many segments.
  # The idiom is the one `gate-trigger.sh` uses (its FIX C) and it is the third
  # place this peel lives — `guard-destructive.sh` does it with a sed loop and
  # `parse.ts`'s `leadingBinary` in TypeScript. A fourth earns a shared partial.
  seg="${seg#"${seg%%[![:space:]]*}"}"
  while [[ "$seg" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do
    case "$seg" in
      *[[:space:]]*)
        seg="${seg#*[[:space:]]}"
        seg="${seg#"${seg%%[![:space:]]*}"}"
        ;;
      *) seg=""; break ;;
    esac
  done
  [ -n "$seg" ] || continue

  # Recursive grep: the flag may sit anywhere among the options, so the verb is
  # anchored at the segment start and the flag matched as its own token.
  # `-[a-zA-Z]*[rR][a-zA-Z]*` matches `-r`, `-R`, `-rn`, `-nr`; it cannot match
  # `--include` or `--color`, because after the leading `-` the class does not
  # accept another `-`.
  if printf '%s' "$seg" | grep -qE '^[[:space:]]*(grep|egrep|fgrep)([[:space:]]|$)' \
    && printf '%s' "$seg" | grep -qE '(^|[[:space:]])(-[a-zA-Z]*[rR][a-zA-Z]*|--recursive)([[:space:]]|=|$)' \
    && ! names_a_file "$seg"; then
    block "busqueda de contenido recursiva por shell"
  fi

  # `rg` is recursive by DEFAULT, so the question inverts: it is extraction only
  # when a single concrete file is named. The test is deliberately loose — any
  # token that looks like a path with an extension — because the cost of the two
  # errors is not symmetric. Missing a search costs one unmeasured call; blocking
  # a legitimate extraction teaches the model to work around the guard.
  if printf '%s' "$seg" | grep -qE '^[[:space:]]*rg([[:space:]]|$)' \
    && ! names_a_file "$seg"; then
    block "busqueda de contenido por shell (rg es recursivo por defecto)"
  fi
done <<EOF
$starts
EOF

# navori:user-section
# user: add repo-specific exceptions or extra redirects here. `$cmd` holds the
# full command and `block "<reason>"` aborts with exit 2.

exit 0
