import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

/**
 * Detection of native git hooks (spec 0045 D3, R5/R6). Read-only: it inspects
 * files and asks git where the hooks live, and never executes a hook.
 */

/** The git events whose native hook can stand in for navori's commit gate. */
export const NATIVE_HOOK_EVENTS = ["pre-commit", "pre-push"] as const;
export type NativeHookEvent = (typeof NATIVE_HOOK_EVENTS)[number];

export type NativeHookManager = "husky" | "lefthook" | "pre-commit" | "plain";

/**
 * Why a hook counts as absent (R6). `unknown-git` covers both "git failed" and
 * "git older than 2.9" (no `core.hooksPath`): an ambiguous detection is absent.
 */
export type NativeHookAbsence =
  | "unknown-git"
  | "missing"
  | "not-executable"
  | "empty"
  | "husky-stub"
  | "no-lefthook-config"
  | "no-pre-commit-config"
  | "pre-commit-stage-missing"
  | "no-user-content";

export interface NativeHookState {
  event: NativeHookEvent;
  active: boolean;
  /** Manager that generated the hook, when the file exists and was recognised. */
  manager: NativeHookManager | null;
  /** Absolute path of the hook file as git resolves it; null when git is unknown. */
  path: string | null;
  /** Set exactly when `active` is false. */
  absence: NativeHookAbsence | null;
}

export interface NativeHooksDetection {
  /** `git rev-parse --show-toplevel` of `cwd`; null outside a work tree. */
  top: string | null;
  hooksDir: string | null;
  /** Output of `git --version`, for the "unknown" message (M6). */
  gitVersion: string | null;
  hooks: Record<NativeHookEvent, NativeHookState>;
}

function git(cwd: string, args: string[]): string | null {
  try {
    return execFileSync("git", ["-C", cwd, ...args], {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

/** `core.hooksPath` exists since git 2.9. */
function supportsHooksPath(version: string | null): boolean {
  const m = version?.match(/(\d+)\.(\d+)/);
  if (!m) return false;
  const major = Number(m[1]);
  return major > 2 || (major === 2 && Number(m[2]) >= 9);
}

const absent = (
  event: NativeHookEvent,
  path: string | null,
  absence: NativeHookAbsence,
  manager: NativeHookManager | null = null,
): NativeHookState => ({ event, active: false, manager, path, absence });

/** A non-shebang, non-comment, non-blank line: something the user wrote. */
function hasUserContent(text: string): boolean {
  return text.split("\n").some((raw) => {
    const line = raw.trim();
    return line !== "" && !line.startsWith("#");
  });
}

function isNonEmptyRegular(path: string): boolean {
  try {
    const st = statSync(path);
    return st.isFile() && st.size > 0;
  } catch {
    return false;
  }
}

function readSafe(path: string): string {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return "";
  }
}

const HUSKY_STUB = /^\s*\.\s+"\$\(dirname "\$0"\)\/h"\s*$/m;
const PRE_COMMIT_HEADER = /File generated by pre-commit/;
const LEFTHOOK_CONFIG = /^\.?lefthook(-local)?\.(ya?ml|json|toml)$/;

function lefthookDeclares(top: string, event: NativeHookEvent): boolean {
  let names: string[];
  try {
    names = readdirSync(top).filter((n) => LEFTHOOK_CONFIG.test(n));
  } catch {
    return false;
  }
  return names.some((name) => {
    const text = readSafe(join(top, name));
    if (name.endsWith(".json")) return new RegExp(`"${event}"\\s*:`).test(text);
    if (name.endsWith(".toml")) return new RegExp(`^\\[${event}[\\].]`, "m").test(text);
    return new RegExp(`^${event}\\s*:`, "m").test(text);
  });
}

function classify(
  event: NativeHookEvent,
  top: string,
  hooksDir: string,
  file: string,
): NativeHookState {
  if (!existsSync(file)) return absent(event, file, "missing");
  let executable = false;
  try {
    const st = statSync(file);
    if (!st.isFile()) return absent(event, file, "missing");
    if (st.size === 0) return absent(event, file, "empty");
    executable = (st.mode & 0o111) !== 0;
  } catch {
    return absent(event, file, "missing");
  }
  if (!executable) return absent(event, file, "not-executable");

  const text = readSafe(file);
  const active = (manager: NativeHookManager): NativeHookState => ({
    event,
    active: true,
    manager,
    path: file,
    absence: null,
  });

  // husky v9: the file git runs is a stub; the user's script lives one level up.
  const huskyDir = basename(hooksDir) === "_" && existsSync(join(hooksDir, "h"));
  if (huskyDir || HUSKY_STUB.test(text)) {
    return isNonEmptyRegular(join(dirname(hooksDir), event))
      ? active("husky")
      : absent(event, file, "husky-stub", "husky");
  }
  if (/lefthook/.test(text)) {
    return lefthookDeclares(top, event)
      ? active("lefthook")
      : absent(event, file, "no-lefthook-config", "lefthook");
  }
  if (PRE_COMMIT_HEADER.test(text)) {
    const config = join(top, ".pre-commit-config.yaml");
    if (!existsSync(config)) return absent(event, file, "no-pre-commit-config", "pre-commit");
    if (event === "pre-push" && !/pre-push/.test(readSafe(config)))
      return absent(event, file, "pre-commit-stage-missing", "pre-commit");
    return active("pre-commit");
  }
  return hasUserContent(text) ? active("plain") : absent(event, file, "no-user-content", "plain");
}

/**
 * Evaluates `pre-commit` and `pre-push` in the clone or worktree holding `cwd`.
 * The hooks directory comes from `git rev-parse --git-path hooks` run in the
 * toplevel, so a relative `core.hooksPath` resolves per worktree.
 */
export function detectNativeHooks(cwd: string): NativeHooksDetection {
  const gitVersion = git(cwd, ["--version"]);
  const top = git(cwd, ["rev-parse", "--show-toplevel"]);
  const rel = top === null ? null : git(top, ["rev-parse", "--git-path", "hooks"]);
  if (top === null || rel === null || rel === "" || !supportsHooksPath(gitVersion)) {
    const unknown = (event: NativeHookEvent): NativeHookState => absent(event, null, "unknown-git");
    return {
      top,
      hooksDir: null,
      gitVersion,
      hooks: { "pre-commit": unknown("pre-commit"), "pre-push": unknown("pre-push") },
    };
  }
  const hooksDir = resolve(top, rel);
  return {
    top,
    hooksDir,
    gitVersion,
    hooks: {
      "pre-commit": classify("pre-commit", top, hooksDir, join(hooksDir, "pre-commit")),
      "pre-push": classify("pre-push", top, hooksDir, join(hooksDir, "pre-push")),
    },
  };
}

/** Paths from `git worktree list --porcelain`; empty outside git. */
export function listWorktreePaths(cwd: string): string[] {
  const out = git(cwd, ["worktree", "list", "--porcelain"]);
  if (out === null) return [];
  return out
    .split("\n")
    .filter((l) => l.startsWith("worktree "))
    .map((l) => l.slice("worktree ".length));
}
