#!/usr/bin/env bash
# Generated by @navori/plugin-cognitive. Runs eslint-plugin-sonarjs's
# cognitive-complexity rule over TS/TSX files changed vs `{{branchBase}}`,
# mirroring the threshold SonarCloud applies on PR.
#
# The rule runs from an isolated toolchain under
# `.claude/scripts/cognitive-tool/` (its own eslint + sonarjs, deliberately
# kept out of the host project's package.json and eslint config). Bootstrap
# it once:
#   (cd .claude/scripts/cognitive-tool && bun install)
#
# Triggered as a PreToolUse(Bash) hook, gated inline to fire only on
# `git commit` / `git push`. Skips silently when the toolchain is not
# bootstrapped — the gate is optional.

set -euo pipefail

cmd=$(jq -r '.tool_input.command // empty' 2>/dev/null || true)
case "$cmd" in
  'git commit'*|'git push'*) ;;
  *) exit 0 ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_DIR="$SCRIPT_DIR/cognitive-tool"
ESLINT_BIN="$TOOL_DIR/node_modules/.bin/eslint"

if [ ! -x "$ESLINT_BIN" ]; then
  echo "⊘ cognitive-tool no instalado — corre: (cd $TOOL_DIR && bun install)" >&2
  exit 0
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

if ! git rev-parse --verify {{branchBase}} >/dev/null 2>&1; then
  echo "⊘ branch '{{branchBase}}' no existe localmente — skip cognitive" >&2
  exit 0
fi

# Run from the repo root so changed paths stay relative — robust to spaces in
# the repo's absolute path. NUL-delimited read handles spaces inside filenames
# too. The `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
# --diff-filter=ACMRT excludes deletions so eslint never sees a missing path.
cd "$(git rev-parse --show-toplevel)"

files=()
while IFS= read -r -d '' f; do
  files+=("$f")
done < <(git diff --name-only -z --diff-filter=ACMRT {{branchBase}} -- '*.ts' '*.tsx' 2>/dev/null)

if [ ${#files[@]} -eq 0 ]; then
  echo "✓ cognitive: sin cambios vs {{branchBase}}" >&2
  exit 0
fi

echo "▶ cognitive-complexity scan en ${#files[@]} archivo(s) modificados vs {{branchBase}}" >&2

# --no-config-lookup: ignore any eslintrc walking up from the target files.
# --config: use only the local cognitive rule config.
"$ESLINT_BIN" \
  --no-config-lookup \
  --config "$TOOL_DIR/eslint.config.mjs" \
  "${files[@]}"
