#!/usr/bin/env bash
# Generated by @navori/plugin-cognitive. Runs eslint-plugin-sonarjs's
# cognitive-complexity rule over TS/TSX files changed vs `{{branchBase}}`,
# mirroring the threshold SonarCloud applies on PR.
#
# The rule runs from an isolated toolchain under
# `.claude/scripts/cognitive-tool/` (its own eslint + sonarjs, deliberately
# kept out of the host project's package.json and eslint config). Bootstrap
# it once:
#   (cd .claude/scripts/cognitive-tool && bun install)
#
# Triggered as a PreToolUse(Bash) hook (gated to git commit/push) and as a
# Stop hook (runs unconditionally at session close). Skips silently when the
# toolchain is not bootstrapped — the gate is optional.

set -euo pipefail

# PreToolUse(Bash) passes the command — gate to commit/push. The Stop hook
# passes no command — run unconditionally at session close. Extract without
# hard-depending on jq (not preinstalled on macOS): try jq, then node (Claude
# Code's own runtime), then a best-effort sed unwrap. No command extracted →
# empty $cmd → runs unconditionally.
payload=$(cat)
extract_cmd() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r '.tool_input.command // empty' 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";process.stdin.on("data",c=>s+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(s)?.tool_input?.command??""))}catch{}})' 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p'
}
cmd=$(extract_cmd)

# --- shared gate detection (keep IN SYNC across sibling hooks) --------------
# Detect a `git commit` / `git push` invocation anywhere in a (possibly
# compound) command. Splits $1 on the shell separators && || ; | and newlines,
# strips leading whitespace plus simple `VAR=value` env prefixes from each
# segment, and returns 0 if ANY segment STARTS with `git commit`/`git push` on
# a word boundary. Replaces literal-prefix `case` matching, which silently
# skipped the gate for `cd x && git commit`, `echo y; git push`, or a leading
# space. Because it matches a segment START, a quoted `echo "git commit"` does
# NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`, or
# obfuscation — a seatbelt, not a sandbox. The IDENTICAL function body lives in
# the sibling gate scripts (they render standalone, so there is no shared lib):
#   core-assets/hooks/quality-gate-pre-commit.sh
#   plugins/jscpd/scripts/check-jscpd.sh
#   plugins/semgrep/scripts/check-semgrep.sh
is_git_commit_or_push() {
  local input="$1" segment
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$'\n'}"
  input="${input//||/$'\n'}"
  input="${input//;/$'\n'}"
  input="${input//|/$'\n'}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). Trailing boundary keeps
    # `git commitgraph` / `git config …` from matching as commit/push.
    if printf '%s' "$segment" | grep -qE '^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+(commit|push)([[:space:]]|$)'; then
      return 0
    fi
  done <<< "$input"
  return 1
}

# No command extracted (empty $cmd) → run unconditionally (Stop hook path). A
# real command that is NOT a git commit/push → skip. Anything else → scan.
if [ -n "$cmd" ] && ! is_git_commit_or_push "$cmd"; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_DIR="$SCRIPT_DIR/cognitive-tool"
ESLINT_BIN="$TOOL_DIR/node_modules/.bin/eslint"

if [ ! -x "$ESLINT_BIN" ]; then
  echo "⊘ cognitive-tool no instalado — corre: (cd $TOOL_DIR && bun install)" >&2
  exit 0
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

if ! git rev-parse --verify {{branchBase}} >/dev/null 2>&1; then
  echo "⊘ branch '{{branchBase}}' no existe localmente — skip cognitive" >&2
  exit 0
fi

# Run from the repo root so changed paths stay relative — robust to spaces in
# the repo's absolute path. NUL-delimited read handles spaces inside filenames
# too. The `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
# --diff-filter=ACMRT excludes deletions so eslint never sees a missing path.
cd "$(git rev-parse --show-toplevel)"

files=()
while IFS= read -r -d '' f; do
  files+=("$f")
done < <(git diff --name-only -z --diff-filter=ACMRT {{branchBase}} -- '*.ts' '*.tsx' 2>/dev/null)

if [ ${#files[@]} -eq 0 ]; then
  echo "✓ cognitive: sin cambios vs {{branchBase}}" >&2
  exit 0
fi

echo "▶ cognitive-complexity scan en ${#files[@]} archivo(s) modificados vs {{branchBase}}" >&2

# --no-config-lookup: ignore any eslintrc walking up from the target files.
# --config: use only the local cognitive rule config.
"$ESLINT_BIN" \
  --no-config-lookup \
  --config "$TOOL_DIR/eslint.config.mjs" \
  "${files[@]}"
