# navori:managed start id="guard-destructive-base" hash="fe407323" version="0.6.3" source="@navori/core"
#!/usr/bin/env bash
#
# Defensive PreToolUse(Bash) guard.
# Reads the full command (compound commands included) from Claude Code's tool
# input and HARD-BLOCKS (exit 2) the destructive patterns that static deny
# rules in settings.json can't reliably catch: variable-indirected `rm -rf`,
# force-push to the base branch, hook-skipping, fork bombs, and writes to block
# devices. Exit 2 in a PreToolUse hook is evaluated BEFORE permission rules, so
# this is the strongest line of defense — it overrides even an `allow` match.
#
# KNOWN, ACCEPTED LIMITATION: matching is regex-based over the command string —
# over the part of it the shell will actually INTERPRET, since #462 (see "INERT
# CONTENT" below: a heredoc body or a `-m`/`--body` value is data, not a call).
# A compound command is split into one segment per line first, so each rule only
# ever matches WITHIN a segment (see "SEGMENTS" below) — that is what keeps a
# `git commit` in one segment from being paired with a flag in another.
# Multi-line continuations, git global options (`git -C … commit`), and simple
# wrappers (`command`/`\git`/parens) ARE normalized before matching now, and a
# quoted skip-flag (`git commit "--no-verify"`) is still caught. Still unhandled:
# `sh -c`, `eval`, base64/printf obfuscation, and escaped-quote edge cases inside
# quoted spans. This guard is a SEATBELT against accidental
# destructive commands, NOT a sandbox against a deliberate adversary.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific guards in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# A missing JSON parser used to make this guard wave every command through; the
# shared extractor falls back to sed so it still inspects the command.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
cmd=$(extract_cmd)
[ -z "$cmd" ] && exit 0

# branchBase is shell-quoted at render time via the shq: marker (#197): a
# hostile branchBase in navori.config.json lands here as an inert literal,
# never executable.
base='main'

block() {
  echo "[navori] BLOCKED by guard-destructive: $1" >&2
  # Truncated: the ceiling below blocks commands far larger than any transcript
  # should carry, and the reason line already says which rule fired.
  echo "[navori] command: ${cmd:0:2000}" >&2
  echo "[navori] if intentional, run the command yourself outside the agent." >&2
  exit 2
}

# BOUNDED WORK (#511) — the guard runs under a wall-clock timeout it does NOT
# control (10s in Claude Code's default wiring), and being KILLED is
# indistinguishable from approving: the hook says nothing and the tool call
# proceeds. So a guard cannot defend itself by handling the timeout; it has to
# never get near it. Two halves, both load-bearing:
#
#   1. every pass below is LINEAR in what it reads — `sed`/`grep`, never a bash
#      `${var//pat/repl}` and never a bash string builder inside a loop. Both
#      are QUADRATIC in bash 3.2.57 (the /bin/bash macOS actually ships) and
#      both were here: one `${_split//&&/…}` over a 2000-segment command
#      measured 83s on its own, and the inert-content pass's per-line
#      `skeleton="${skeleton}${_line}"` measured 3.4s at 16k lines, 13.2s at
#      32k and 53.2s at 64k — 96-99% of the guard's whole runtime, and past the
#      timeout with not a single rule evaluated. The builder is an array append
#      plus one `printf` join now; the substitutions are `sed`.
#   2. what is still too big to inspect is DENIED, never waved through. A guard
#      that cannot evaluate a command must say no: the discarded input gets a
#      verdict, and that verdict is `block`. Nothing a human types reaches these
#      ceilings; what does is either generated or an attempt to drown the guard.
#
# The ceilings price the dimensions that actually cost, and they are SEPARATE
# because those dimensions cost differently. Conflating them is what the first
# cut of #511 got wrong: `CMD_MAX` bounded BYTES while the cost driver was LINES,
# so 16k one-char lines (3.4s, inside the ceiling) were admitted and a 40k-char
# prose heredoc (70ms, one pass) was denied — expensive work through, cheap work
# blocked, and the ~3x margin against the timeout there by accident.
# Every figure below is bash 3.2.57 on an M-series Mac, measured AT the ceiling:
#   · CMD_MAX  — total bytes. This prices the `sed`/`grep` passes, each of which
#     reads the whole command once, and they are cheap: one 131k-char line is
#     187ms, and the adversarial shape for the `rm` operand run (a single `rm`
#     segment filling the ceiling with operands) is 211ms — linear, no
#     backtracking blow-up.
#   · LINE_MAX — lines walked by the inert-content pass below, the only per-LINE
#     loop in this file, and one that runs at all ONLY when the command contains
#     `<<` (without one the skeleton IS the command). At the line ceiling with
#     every line KEPT (the expensive arm) and padded to the byte ceiling: 300ms.
#   · HEREDOC_PROBE_MAX — heredoc-opener candidates, each paying two `sed` and a
#     `grep` of its own on top of the per-line cost.
# All three at once — 64 openers, 4096 lines, 130k bytes — is 501ms, the worst
# case measured anywhere in this file. The audit's 2000-segment repro went from
# 46.9s (killed) to 65ms.
#
# The ceiling does NOT make the accumulator's shape a non-issue, which is why
# both halves ship: the quadratic builder at these very ceilings measures 3.5s
# against the array's 300ms — inside the 10s timeout on this machine, and past
# it on the 2-4x slower box the audit is actually worried about.
#
# NOT COVERED by a ceiling, deliberately: the line count of a command with NO
# `<<` in it. The per-line loop is skipped there, so what is left is linear in
# bytes and `CMD_MAX` prices it directly — the densest such input that fits,
# 64k one-char lines in 128k bytes, measures 442ms. It is named because the
# LINE_MAX row above would otherwise read as "lines are bounded", and they are
# only bounded on the path where they cost per line.
CMD_MAX=131072
LINE_MAX=4096
HEREDOC_PROBE_MAX=64
if [ "${#cmd}" -gt "$CMD_MAX" ]; then
  block "command too large to inspect (${#cmd} chars > ${CMD_MAX}) — nothing in it was evaluated"
fi

# Pre-expanded newline, shared by the inert-content pass and the segment split.
# It stays a variable for the reason it became one in #391: an inline $'\n' is
# NOT expanded by zsh in every position bash expands it, and a divergence here
# leaves compound commands unsplit — the rules then fail open. A plain variable
# expands identically in both, in a string concatenation and inside the `sed`
# replacement the split below builds.
_nl=$'\n'

# INERT CONTENT (#462) — what the shell EXECUTES vs what it merely WRITES.
#
# Every rule below reads the command as TEXT, so a PR body or a commit message
# that QUOTES a destructive command was blocked even though nothing ran. That
# fires on every security change, because documenting a fix means quoting the
# attack it defends against: #403 could not write its own PR body, and a commit
# message naming a recursive delete of HOME needed the `git commit -F <file>`
# detour.
#
# `live` is `$cmd` minus its INERT spans — the text the shell hands to a program
# as DATA and never interprets as a command. `$cmd` stays intact for the
# messages; the rules read `live` (directly, or through `scan`).
#
# INERT (dropped before matching):
#   · a heredoc BODY — `cat > body.md <<'EOF' … EOF` is file content.
#   · the quoted VALUE of a message/body flag (`-m`, `--body`, …) — it lands in
#     a commit object or in a PR, the shell never runs it.
#
# NOT inert. This is the line the decision draws — stated as the FRONTIER it
# actually is, denylist included, because an unstated denylist reads as coverage:
#   · a heredoc whose opener names a SCRIPT path (`cat > run.sh <<'EOF'`) — that
#     is step 1 of write-then-execute, not documentation. The extension list is
#     matched case-INSENSITIVELY; an unlisted or absent extension (`Makefile`,
#     `.mk`, `.lua`, `.awk`, `cat > /tmp/payload`) reads as documentation, and
#     only the execution tell below can still catch it.
#   · ANY command that also EXECUTES something. Precisely: a KNOWN interpreter
#     (`_hd_run`) in COMMAND POSITION — optionally behind `VAR=v` and the simple
#     prefixes of `_hd_pre` WITH their arguments (`sudo -u me`, `env FOO=1`,
#     `timeout 5`), and behind the wrappers the tell normalizes away (`(…)`,
#     `{ …; }`, `\bash`, `"bash"`, `command bash`) —, or a path in command
#     position (`./x`, `/x`, `~/x`), or a `$(…)`/backtick substitution the shell
#     would expand (`git commit -m "$(rm -rf ~)"` really does run it). Such a
#     command is scanned WHOLE, exactly as before #462.
#     ANY OTHER RUNNER ESCAPES, and that is the accepted trade, not an oversight:
#     `npx tsx f`, `lua f`, `make -f f`, `find … -exec bash {} \;`, a runner
#     reached through a shell function or an alias, and one named by a BRACED
#     variable (`${SH} f` — the wrapper normalization collapses `{` to a space,
#     so it reaches the tell as `$ SH`; the plain `$SHELL f` IS caught). A word
#     split by escapes (`b\ash f`) escapes too, as it already does the rules in
#     the pre-#462 guard. A denylist is never complete;
#     widening it is cheap per entry, but each entry ALSO drags a legitimate
#     `… && make build` sitting next to a prose heredoc back into a full scan —
#     back into the exact false positive #462 exists to kill. Same class as the
#     `sh -c` / `eval` limitation the header states: a seatbelt, not a sandbox.
#   · a `<<` that merely sits inside a string (`echo "a << b"`) — it opens no
#     heredoc, so it can never be used to swallow the next real command. A line
#     whose quotes do not pair up (`echo "a \" << EOF"`) counts as a NON-opener
#     for the same reason: inventing a heredoc there would elide the real
#     commands that follow, the one way this pass could scan LESS than before.
# Unchanged scope: a deliberate adversary (`sh -c`, `eval`, base64) already had
# simpler doors and is still out of reach. This is a seatbelt, not a sandbox.
#
# COST (#511, second pass). This is the ONE per-line loop in the file, so it is
# the one place where the number of lines — not the number of bytes — prices the
# guard. Two things keep it bounded:
#   · it runs only when the command contains `<<`. There is nothing to elide
#     without a heredoc, so every other command takes the `*)` arm and the
#     skeleton IS the command, at zero per-line cost.
#   · the kept lines land in an ARRAY, joined once at the end. The
#     `skeleton="${skeleton}${_line}${_nl}"` this replaces was quadratic (bash
#     copies the whole accumulator on every iteration), and it was 96-99% of the
#     guard's runtime: 3.5s at 16k lines, 13.2s at 32k, 53.2s at 64k — killed by
#     the timeout, which reads exactly like an approval. Same inputs through the
#     array: 445ms, 833ms, 1.6s. Linear, and 32x cheaper at the top end.
#     Inside LINE_MAX the gap is 3.5s vs 300ms, so the ceiling alone would not
#     have been enough on a slower box; the two halves are not redundant.
_hd_q='@navoriQ@'   # marks a QUOTED heredoc delimiter (`<<'EOF'`: no expansion)
skeleton=""
_sk=()
_hd_delim=""
_hd_inert=0
_hd_expand=0
_hd_probes=0
_hd_lines=0
case "$cmd" in
  *'<<'*) _hd_scan=1 ;;
  *) _hd_scan=0 ;;
esac
while [ "$_hd_scan" = 1 ] && IFS= read -r _line; do
  # BOUNDED WORK (#511): the ceiling is checked HERE, per line, instead of by
  # counting first — the loop is the only thing the count would protect, so
  # stopping inside it costs at most LINE_MAX cheap iterations and saves a
  # whole extra pass over the command on the way in.
  _hd_lines=$((_hd_lines + 1))
  if [ "$_hd_lines" -gt "$LINE_MAX" ]; then
    block "too many lines to inspect (> ${LINE_MAX}) — nothing in it was evaluated"
  fi
  if [ -n "$_hd_delim" ]; then
    # Inside a heredoc body. The terminator is compared whitespace-trimmed (a
    # `<<-` terminator may be indented); trimming can only end the body EARLIER
    # than the shell would, i.e. scan more, never less.
    _t="${_line#"${_line%%[![:space:]]*}"}"
    _t="${_t%"${_t##*[![:space:]]}"}"
    if [ "$_t" = "$_hd_delim" ]; then
      _hd_delim=""
      continue
    fi
    if [ "$_hd_inert" = 0 ]; then
      _sk+=("$_line")
      continue
    fi
    # An UNQUOTED delimiter (`<<EOF`) still runs `$(…)`/backticks inside the
    # body — plain prose there is inert, a substitution is a real invocation.
    # Keeping exactly those lines feeds the whole-command fallback below.
    if [ "$_hd_expand" = 1 ]; then
      case "$_line" in
        *'$('* | *'`'*) _sk+=("$_line") ;;
      esac
    fi
    continue
  fi
  _sk+=("$_line")
  # Fast path: no `<<`, no heredoc — a PreToolUse hook runs on EVERY Bash call,
  # so the sed probes below are worth paying only on the lines that can open one.
  case "$_line" in
    *'<<'*) ;;
    *) continue ;;
  esac
  # BOUNDED WORK (#511): every candidate line below pays two `sed` processes and
  # a `grep`, so a command made of thousands of `<<`-bearing lines is a way to
  # run the guard out of its timeout — the one failure mode that reads as
  # approval. A real command opens one to three heredocs; past the ceiling the
  # verdict is `block`, not silence.
  _hd_probes=$((_hd_probes + 1))
  if [ "$_hd_probes" -gt "$HEREDOC_PROBE_MAX" ]; then
    block "too many heredoc openers to inspect (> ${HEREDOC_PROBE_MAX}) — nothing in it was evaluated"
  fi
  # Heredoc opener? The probe marks the DELIMITER's own quotes first, then drops
  # every other quoted span, so `cat <<'EOF'` is told apart from a `<<` inside a
  # string; `<<<` (here-string) is neutralized so it can't pose as `<<`.
  _probe=$(printf '%s' "$_line" | sed -E \
    -e "s/<<(-?)[[:space:]]*'([A-Za-z_][A-Za-z0-9_]*)'/<<\1${_hd_q}\2/g" \
    -e "s/<<(-?)[[:space:]]*\"([A-Za-z_][A-Za-z0-9_]*)\"/<<\1${_hd_q}\2/g" \
    -e "s/<<(-?)[[:space:]]*\\\\([A-Za-z_][A-Za-z0-9_]*)/<<\1${_hd_q}\2/g" \
    -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g" -e "s/<<</ /g")
  # A quote left over in the probe means those two `sed` passes paired the quotes
  # somewhere the shell would not (an escaped `\"`, an odd count): the `<<` may
  # well sit inside a string, and INVENTING a heredoc here is the one failure
  # mode of this whole pass that scans LESS — it would elide every following line,
  # real commands included (`echo "a \" << EOF"` + a real `rm -rf ~/`). Treat the
  # line as a NON-opener; worst case the body is scanned, which is what the guard
  # did before #462.
  case "$_probe" in
    *'"'* | *"'"*) continue ;;
  esac
  # `^[^<]*` anchors on the FIRST `<` of the line: no match (a `<` redirect
  # before the heredoc) simply leaves the body under the rules.
  _open=$(printf '%s' "$_probe" \
    | sed -nE "s/^[^<]*(<<-?[[:space:]]*(${_hd_q})?[A-Za-z_][A-Za-z0-9_]*).*/\1/p")
  if [ -z "$_open" ]; then continue; fi
  _hd_delim=$(printf '%s' "$_open" | sed -E "s/^<<-?[[:space:]]*(${_hd_q})?//")
  _hd_inert=1
  _hd_expand=0
  case "$_open" in
    *"${_hd_q}"*) ;;
    *) _hd_expand=1 ;;
  esac
  # Writing a SCRIPT is not documenting: keep `cat > run.sh <<'EOF'` visible.
  # Case-INSENSITIVE (`-i`): macOS ships a case-insensitive filesystem, so
  # `cat > /tmp/p.SH` writes and runs the same file as `p.sh`.
  if printf '%s' "$_line" \
    | grep -qiE "\.(sh|bash|zsh|ksh|fish|py|rb|pl|js|jsx|mjs|cjs|ts|tsx|command|bat|ps1|scpt)([[:space:]]|[\"'\`]|\$)"; then
    _hd_inert=0
  fi
done <<< "$cmd"
# Join ONCE. `$(…)` strips trailing newlines, so the terminator is re-added: a
# trailing EMPTY line is the only thing that can be lost, and an empty line
# carries no command. The `${#_sk[@]}` guard is not cosmetic — under `set -u`,
# bash 3.2 treats `"${_sk[@]}"` on an EMPTY array as an unbound variable and
# aborts the guard, which the caller cannot tell apart from an approval.
if [ "$_hd_scan" = 1 ]; then
  if [ "${#_sk[@]}" -gt 0 ]; then
    skeleton=$(printf '%s\n' "${_sk[@]}")
    skeleton="${skeleton}${_nl}"
  fi
else
  skeleton="${cmd}${_nl}"
fi

# A `$(…)`/backtick substitution outside single quotes RUNS: `git commit -m
# "$(rm -rf ~)"` is an invocation wearing a message's clothes. This check must
# read the skeleton BEFORE the flag values are elided below — eliding first
# swallowed the `$(` and let exactly that command through.
#
# TWO probes, OR'd, because neither alone is enough:
#   · single-quoted spans dropped — catches a `$(` sitting outside every quote.
#   · the double-quoted spans ALONE — inside them an apostrophe is LITERAL, so
#     the first probe pairs `it's … it's` as if it were a quoted span and deletes
#     the `$(` between them. That is ordinary punctuation in the very messages
#     #462 exists to allow (`-m "it's fine $(rm -rf / ) it's"`), and it disarmed
#     the only check that catches an invocation disguised as a message.
# Over-reading here only falls back to scanning the whole command, i.e. to the
# pre-#462 behaviour: the safe side.
_hd_whole=0
if printf '%s' "$skeleton" | sed -E "s/'[^']*'//g" | grep -qE '\$\(|`'; then
  _hd_whole=1
else
  # Fast path, same idea as the `<<` one above: probe 2 costs two processes on
  # EVERY Bash call, and it can only ever fire when a substitution is present
  # somewhere in the first place.
  case "$skeleton" in
    *'$('* | *'`'*)
      if printf '%s' "$skeleton" | grep -oE '"[^"]*"' | grep -qE '\$\(|`'; then
        _hd_whole=1
      fi
      ;;
  esac
fi

# Message/body flag VALUES. The flag itself stays so rule 1 still sees the shape
# of the invocation (`git commit -m "" --no-verify` is still a skip-flag), and
# `--body-file` is untouched: `([[:space:]]+|=)` can't match its `-`.
_hd_flags='-m|--message|--body|--title|--description|--notes'
skeleton=$(printf '%s' "$skeleton" | sed -E \
  -e "s/(^|[[:space:]])(${_hd_flags})([[:space:]]+|=)'[^']*'/\1\2 ''/g" \
  -e "s/(^|[[:space:]])(${_hd_flags})([[:space:]]+|=)\"[^\"]*\"/\1\2 \"\"/g")

# The elision holds ONLY while nothing in the command can run what was written.
# A segment that STARTS with an interpreter or with a path is an execution, and
# reverts to the whole command — which is why `cat > x <<'EOF' … EOF; bash x` is
# still blocked. Anything else keeps only what the shell will interpret.
#
# `_hd_pre` — the runner may sit behind simple prefixes, WITH their own arguments:
# `sudo -u me bash x`, `env FOO=1 bash x`, `timeout 5 bash x`. Matching only a
# prefix glued to the interpreter turned every one of those into a free pass.
_hd_pre='(sudo|doas|env|command|nohup|timeout|time|nice|ionice|stdbuf|setsid)'
_hd_pre="${_hd_pre}([[:space:]]+(-[^[:space:]]+([[:space:]]+[^-[:space:]][^[:space:]]*)?"
_hd_pre="${_hd_pre}|[A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*|[0-9][^[:space:]]*))*[[:space:]]+"
_hd_run='bash|sh|zsh|ksh|dash|ash|fish|tcsh|csh|source|eval|exec|xargs'
_hd_run="${_hd_run}|python[0-9.]*|node|deno|bun|perl|ruby|osascript"
_hd_exec='(^|[;&|])[[:space:]]*([A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*[[:space:]]+)*'
_hd_exec="${_hd_exec}(${_hd_pre})*"
# `\$[A-Za-z_]` covers a runner named by a plain VARIABLE (`$SHELL x`). The
# BRACED form (`${SH} x`) is NOT covered and is one of the declared escapes: the
# same wrapper normalization that puts `{ bash x; }` back in command position
# collapses `{` to a space, so `${SH}` reaches the tell as `$ SH`. Catching it
# would mean teaching that normalization about `$`-prefixed braces — a change to
# a security-sensitive transform, worth its own unit.
# Why catching the plain form is safe: a variable in command position is never a
# legitimate WRITER, so the false-positive cost is ~0 and the declared frontier
# stays complete — which is what the denylist trade-off rests on (#462).
_hd_exec="${_hd_exec}((${_hd_run})([[:space:]]|\$)|\.[[:space:]]|[.~]?/|\\\$[A-Za-z_])"
# The tell reads a NORMALIZED copy, never the raw skeleton: `_hd_exec` anchors on
# `^`/`;&|`, so any wrapper between the boundary and the interpreter used to hide
# it. The transforms are FIX C's (below) plus quote REMOVAL, which is what puts
# `(bash x)`, `{ bash x; }`, `\bash x`, `"bash" x` and `command bash x` back in
# command position. Unquoting is safe HERE and not below: its only effect is
# deciding whether to fall back to the whole command, i.e. to the pre-#462
# behaviour — it never reaches the rules, so a quoted skip-flag is untouched.
if [ "$_hd_whole" = 1 ] || printf '%s' "$skeleton" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/[(){}]/ /g" \
  -e "s/'([^']*)'/\1/g" \
  -e 's/"([^"]*)"/\1/g' | grep -qE "$_hd_exec"; then
  live="$cmd"
else
  live="$skeleton"
fi

# Normalized copy used ONLY by the rules below. `$cmd` stays intact for the
# messages. The transforms only add boundaries / drop noise, so they always push
# toward MORE blocking:
#   FIX B — join `\<newline>` continuations into a space and flatten any other
#           newline to `;` (a boundary the rules already handle) so a multi-line
#           `git commit \<NL> --no-verify` is matched as one logical command.
#   FIX C — neutralize wrappers into boundaries: a leading `command ` word, a
#           leading backslash (`\git`), and `(` runs, so `command git …`,
#           `\git …` and `(git …)` read as a plain `git …`.
# `scan` keeps quoted spans intact, so a quoted skip-flag (`git commit
# "--no-verify"`) is still caught — stripping the quotes there was a real bypass.
#
# LINEAR ONLY (#511): what used to be three bash `${var//pat/repl}` passes is
# now `sed`. Those substitutions are quadratic in bash 3.2.57 and `&&` alone
# cost 83s on a 2000-segment command — past the hook's timeout, so the guard was
# killed before evaluating a single rule and the command went through unopposed.
# The newline→`;` pass is simply gone: the split below turns separators BACK
# into newlines, so a newline that stays a newline lands in the same place.
scan=$(printf '%s' "$live" | sed \
  -e :a -e '/\\$/N' -e 's/\\\n/ /' -e ta)   # FIX B: join line continuations
scan=$(printf '%s' "$scan" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/\(/ /g")

# SEGMENTS — one segment per LINE, shared by rules 1, 2 and 3.
#
# This is the backbone of the whole file: `grep` and `sed` match LINE BY LINE, so
# once a compound command is split one-segment-per-line, every rule below is
# scoped to a single segment for free — a pattern can no longer pair a `git
# commit` in one segment with a flag in another, and `$` means "end of this
# segment", not "end of the whole command line".
# #307 first did this for the force-push rule with a private copy of the split;
# rules 1 (#A2) and 3 (#A1) had the cross-segment bug it cured, so the split now
# happens ONCE, here, and all three rules read `$segments`.
#
# Each segment is peeled so it STARTS with its command word: leading whitespace
# and `VAR=value` env prefixes go away (`FOO=1 git push …` → `git push …`); the
# `(`, `\` and `command ` wrappers were already neutralized by FIX C above.
#
# Both halves are one `sed` pass each, for the reason stated above the `scan`
# block: the four `${_split//…}` substitutions AND the per-segment string
# builder that replaced them were the guard's whole time budget (37s just
# appending 20k segments). `sed` is linear in both.
# The peel loop is the `:a … ta` branch: it strips ONE `VAR=value` prefix per
# turn, exactly like the `while` it replaces, and `([[:space:]]+|$)` reproduces
# its two endings — more words follow, or the segment was nothing but the
# assignment and collapses to empty.
_split=$(printf '%s' "$scan" | sed \
  -e "s/&&/\\$_nl/g" -e "s/||/\\$_nl/g" -e "s/;/\\$_nl/g" -e "s/|/\\$_nl/g")
segments=$(printf '%s' "$_split" | sed -E \
  -e 's/^[[:space:]]+//' \
  -e :a -e 's/^[A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*([[:space:]]+|$)//' -e ta)

# Same list with quoted spans dropped, used ONLY by the combined-short-flag
# check, so a hyphen-word inside a commit message (`-m "add -notify option"`)
# can't trip it.
segments_unquoted=$(printf '%s' "$segments" | sed -E -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g")

# Git commit/push detector shared by rule 1. The leading boundary accepts ; & |
# so `true;git commit …` (no space after the separator) is caught; the
# `git(… -opt …)*` middle allows git global options between `git` and the
# subcommand (`git -c k=v commit …`).
git_cp='(^|[[:space:]]|[;&|])git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+(commit|push)'

# 1. Skipping quality gates / hooks — defeats the whole point of the harness.
#    Two checks: the literal `--no-verify` over `segments` (quotes kept, so a
#    quoted flag is still caught), and `-[a-zA-Z]*n[a-zA-Z]*` over
#    `segments_unquoted` to catch `-n` folded into a combined short-flag token
#    (`git commit -qn`/`-nq`) without a hyphen-word in a message tripping it.
#    Both run over the SEGMENT list, so the `.*` between the git invocation and
#    the flag can never leave the segment that holds the commit/push. Matching
#    the whole command string instead is what made `git commit -m x && git log
#    -n 3` (or `&& grep -rn TODO src/`) block as a bogus "--no-verify": any short
#    flag carrying an `n` ANYWHERE later in the line was read as the commit's.
if printf '%s' "$segments"            | grep -qE "${git_cp}.*--no-verify" \
  || printf '%s' "$segments_unquoted" | grep -qE "${git_cp}.*[[:space:]]-[a-zA-Z]*n[a-zA-Z]*([[:space:]]|\$)"; then
  block "git commit/push with --no-verify (skipping hooks/gates)"
fi

# 2. Force-push to the base branch. force-with-lease is allowed (safe rebase
#    flow on feature branches); bare --force/-f against the base branch is not.
#    #307: every sub-check is scoped to the ACTUAL `git push` invocation(s),
#    never the whole command string. Keeping only the segments that START a
#    `git … push` means a `+`
#    in a commit message (`-m "format:check + test"`), a base-branch name in a
#    sibling command (`gh pr create --base main`), or a heredoc/`--body` can no
#    longer be misread as a force-push refspec or as the pushed ref — that
#    false positive blocked legit compound commit+push+PR commands. The refspec
#    `+` is matched only when glued to a ref (`+main`, never `+ test`), the way
#    git actually spells a force-push refspec.
push_seg=$(printf '%s' "$segments" \
  | grep -E '^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+push([[:space:]]|$)' \
  || true)

if [ -n "$push_seg" ] \
  && printf '%s' "$push_seg" | grep -qE '(--force([[:space:]]|$)|[[:space:]]-f([[:space:]]|$)|[[:space:]]\+[^[:space:]])' \
  && ! printf '%s' "$push_seg" | grep -qE 'force-with-lease' \
  && printf '%s' "$push_seg" | grep -qE "(^|[[:space:]+/])${base}([[:space:]]|\$)"; then
  block "force-push to the base branch '${base}'"
fi

# 3. rm -rf with variable indirection or absolute home/system roots that static
#    deny globs miss. The deny rules in settings.json (`Bash(rm -rf ~/*)`,
#    `Bash(rm -rf /*)`) only match a command that STARTS that way, so anything
#    compound (`cd /tmp && rm -rf ~/`) walks past them — exactly the class this
#    guard exists to cover. Matching per SEGMENT is what makes that work: `$`
#    below means "end of this segment", so the target no longer has to sit at
#    the end of the whole command line.
#
#    COVERED (blocked). The FLAGS axis is normalized (see below), so every
#    spelling of "recursive/force" counts: `-rf`, `-fr`, `-r`, `-R`, `-fR`,
#    `--recursive`, `--force`, and any mix of them, with other option tokens
#    (`--no-preserve-root`, `--one-file-system`, a `--` separator) interleaved.
#    The OPERAND axis is scanned whole (see below): `rm` takes a LIST of paths,
#    so a sensitive one blocks wherever it sits in that list.
#    The QUOTING axis counts too: a quote AROUND the target — opening, closing,
#    single or double — is stripped by the shell before `rm` ever sees the path,
#    so `rm -rf "/"` deletes exactly what `rm -rf /` deletes and the two must get
#    the same verdict. They did not: the rule accepted an opening quote and had
#    no ending for the closing one, so `"/"`, `'/'`, `"/usr"`, `"~"` and
#    `rm -rf build "/etc"` all returned 0. Worse than the hole was its SHAPE —
#    `rm -rf "~/"` did block, by accident (the home pattern's path-component
#    class swallowed the closing quote as if it were part of the path), so a
#    spot-check on the obvious spelling reported the axis as covered.
#    The rows below name one spelling each; the TARGET is what they vary:
#      rm -rf $VAR / "$VAR"        variable indirection (`PATH=/; rm -rf $PATH`)
#      rm -rf /   ·  rm -rf /*     the filesystem root
#      rm -rf ~   ·  ~/  ·  ~/Documents        HOME and its immediate children
#      rm -rf /Users/me  ·  /Users/me/Desktop  the same, spelled absolutely
#      rm -rf /usr  ·  /etc  ·  /var/folders   a system root or an immediate child
#      rm -rf /tmp  ·  /private/tmp            the scratch root itself, bare
#      rm -rf "/" · '/' · "/usr" · "~" · build "/etc"   any of the above QUOTED
#    NOT COVERED (deliberate, so everyday cleanup keeps working):
#      relative paths — `rm -rf node_modules`, `rm -rf ./dist`
#      anything INSIDE the scratch root — `rm -rf /tmp/navori-test-123`: a temp
#        dir is scratch by definition and agents create and delete them all day;
#        only wiping `/tmp` wholesale is the accident worth catching.
#      DEEP absolute paths — `rm -rf /Users/me/dev/app/node_modules`, `/tmp/x/y`:
#        past the first level under a root, a path is assumed to be project or
#        scratch data. Wiping HOME or a system dir is the accident worth
#        catching; a deep path is a targeted delete, and blocking every one of
#        them would fire daily (agents are told to use absolute paths) and only
#        teach the operator to route around the guard.
#      quoting SPLICED INTO the path, and backslash escapes — `rm -rf /"u"sr`,
#        `rm -rf "/us"r`, `rm -rf \~`, `rm -rf \/`. The shell removes those
#        before `rm` runs, so they name the same paths the rows above cover; the
#        guard reads TEXT and the pattern needs the path spelled contiguously.
#        This is the residue of the quoting axis, and it is named because the
#        row above claims that axis: quotes AROUND the target are covered,
#        quotes INSIDE it are not. Same class as the escaped-word limitation the
#        header already states (`b\ash f`), and it needs a deliberate hand —
#        nobody types `/"u"sr` by accident.
#      `sh -c`, `eval`, base64/printf obfuscation — seatbelt, not a sandbox.
#
#    FLAG NORMALIZATION (#509). The rule used to describe the danger by the
#    TEXT it usually wears (`-[a-zA-Z]*[rf]…`, lowercase) instead of by what
#    `rm` MEANS, so three everyday spellings of the same command walked past it:
#    `rm -R ~/` (POSIX/GNU/BSD all treat `-R` as `-r`), `rm --recursive --force
#    ~/`, and `rm -rf --no-preserve-root /` — the one command that erases the
#    system root, and the only one of the three that also evades the static
#    `deny` globs. So the flags are NORMALIZED before they are matched:
#      · long → short: `--recursive`→`-r`, `--force`→`-f`, `--dir`→`-d`.
#        Rewritten (not just alternated into the pattern) because a long flag
#        sits between `rm` and its target and otherwise breaks the run.
#      · `-R` ≡ `-r` lives in the character class instead: BSD `sed` has no
#        portable case-folding (`\l`/`\U` are GNU-only), and folding the whole
#        segment would corrupt the TARGET, which is case-sensitive.
#      · any other option token is allowed to sit anywhere in the run, so
#        `--no-preserve-root`, `--one-file-system` or a `--` separator no longer
#        detach the recursive flag from its target.
#    `segments_rm` is read by THIS rule only — rewriting `--force` globally
#    would otherwise reach the force-push rule.
#
#    EVERY OPERAND, NOT JUST THE FIRST. The same defect one axis over: the rule
#    matched `rm`, then the flags, then ONE target, so a harmless path in first
#    position detached the rule from everything after it — `rm -rf build /` and
#    `rm -rf node_modules ~/` both erased the root/HOME with exit 0. But `rm`
#    takes a LIST of operands and deletes every one of them, so sensitivity is a
#    property of the TARGET's shape (root / home / variable), never of its
#    position. `rm_arg` is therefore a run of ANY argument tokens — further
#    options and harmless operands alike — between the recursive flag and the
#    target, and the same run is allowed BEFORE the flag so that GNU's option
#    permutation (`rm build -rf /`, which really does erase `/` on Linux) is
#    covered too. False positives stay bounded because the verdict still hangs
#    on the target: `rm -rf build coverage` has no sensitive operand and keeps
#    passing, exactly as the verdict table demands.
#    `rm_arg` excludes `<`, `>` and `&` on purpose — what follows a redirection
#    or a `&` is not something `rm` deletes, so `rm -rf dist > /dev/null` (or
#    `rm dist & ls -R /usr`) must not be read as `rm -rf /dev/null`.
#
#    THE FALSE POSITIVE THIS BUYS, named rather than left to be discovered.
#    "Any token" also means tokens that are not operands of that `rm` at all, so
#    an UNQUOTED mention of `rm` anywhere in a segment now reaches forward to any
#    sensitive absolute path later in the SAME segment. Measured, all exit 2:
#      echo rm -rf build /usr
#      python3 -c "print(1)" # rm -rf a /bin/zsh      ← inside a comment
#      rm -rf "release /usr notes"                     ← one quoted operand
#    It is a deliberate trade, and a bounded one: the mention has to be
#    unquoted (a `-m "…rm -rf ~/…"` message or a heredoc body was already elided
#    into `live`, and `(^|[[:space:]])rm` does not match after a `"`), it has to
#    share a segment with the path (`;`, `&&`, `||`, `|` all end the reach), and
#    the path still has to be root/home/system — `echo rm -rf build dist` passes.
#    The everyday shapes that LOOK like this stay clean, and the verdict tables
#    pin them: `find … -exec rm -rf {} +`, `xargs rm -rf`, `rm -rf dist >
#    /dev/null`, `docker run --rm -v /var/run/docker.sock:…`, `tar -rf a.tar
#    /etc/hosts`, `cp -R /usr/share/x .`. Narrowing `rm_arg` to "options only"
#    is what reopens `rm -rf build /`, and an erased root costs more than a
#    blocked `echo`; the header's seatbelt framing is the standing answer, and
#    the way past a firing here is to quote the mention or split the segment.
segments_rm=$(printf '%s' "$segments" | sed -E \
  -e 's/(^|[[:space:]])--recursive([[:space:]]|$)/\1-r\2/g' \
  -e 's/(^|[[:space:]])--force([[:space:]]|$)/\1-f\2/g' \
  -e 's/(^|[[:space:]])--dir([[:space:]]|$)/\1-d\2/g')
rm_arg='[^<>&[:space:]]+[[:space:]]+'           # any option OR operand token
rm_kill='-[a-zA-Z]*[rRf][a-zA-Z]*[[:space:]]+'  # a short option carrying r/R/f
rm_run="(^|[[:space:]])rm[[:space:]]+(${rm_arg})*${rm_kill}(${rm_arg})*"
rm_quote="[\"']?"                     # ONE optional quote, either flavour
rm_var='\$'                           # `$VAR`, `${VAR}` — any variable
rm_home='~(/[^[:space:]/]*)?|/(Users|home)(/[^[:space:]/]+(/[^[:space:]/]*)?)?'
rm_root='/\*?|/(Applications|Library|System|Volumes|bin|boot|dev|etc|lib|lib64|mnt|opt|root|sbin|srv|sys|usr|var)(/[^[:space:]/]*)?'
rm_tmp='/private(/tmp)?|/tmp'         # scratch root: the root itself, never a child
# The CLOSING quote is part of the ending, not an afterthought: without it the
# rule read `rm -rf "/"` as "root, then a character that is not the end of the
# segment" and returned 0. `rm_quote` appears on BOTH sides of the target below.
rm_end="/?${rm_quote}([[:space:]]|\$)"  # optional trailing `/`, closing quote, end
if printf '%s' "$segments_rm" \
  | grep -qE "${rm_run}${rm_quote}(${rm_var}|(${rm_home}|${rm_root}|${rm_tmp})${rm_end})"; then
  block "recursive rm over a variable / root / home"
fi

# 3b. `--no-preserve-root` is an aggravating factor on its own (#509): it exists
#     for the single purpose of disarming the last safety net `rm` has, and no
#     legitimate use of it exists inside an agent. Target, flag order and
#     quoting are therefore irrelevant — its presence in an `rm` SEGMENT blocks.
#     "Quoting is irrelevant" is now true rather than asserted: the flag carries
#     the same `rm_quote` on both sides that rule 3's target does, so
#     `rm "--no-preserve-root" -rf ./build` blocks like the bare spelling. It
#     read as covered before and was not — the same shape as the target-side
#     hole, one rule over.
#     Scoped to the segment (grep is line-based) so an `rm` in one command and
#     the flag in another are never paired; a commit message or a heredoc body
#     that merely quotes it was already elided into `live` and never gets here.
if printf '%s' "$segments" \
  | grep -qE "(^|[[:space:]])rm[[:space:]](.*[[:space:]])?${rm_quote}--no-preserve-root${rm_quote}([[:space:]]|\$)"; then
  block "rm --no-preserve-root (disarms rm's own root protection)"
fi

# 4. Fork bomb. Reads `live`, not `scan`: FIX C turns `(` into a space, which
#    would defuse the very pattern this rule looks for.
if printf '%s' "$live" | grep -qE ':\(\)[[:space:]]*\{[[:space:]]*:\|:'; then
  block "fork bomb"
fi

# 5. Writing to a raw block device (wipes a disk/partition).
if printf '%s' "$live" | grep -qE '(of=/dev/(sd|nvme|disk|hd)|>[[:space:]]*/dev/(sd|nvme|disk|hd))'; then
  block "direct write to a block device"
fi

# 6. Shell rewrites of a file navori MAINTAINS (#530). In auto mode every edit
#    arrives as a shell command — `sed -i`, a heredoc, a `>` redirect — instead
#    of the `Edit` tool, and the two fail very differently: `Edit` aborts when
#    the old text doesn't match (a check that the agent understood the file),
#    while `sed -i` with a pattern that matches nothing exits 0 and a `>` with
#    the wrong path truncates the file. On a managed file the damage is the #523
#    shape: the body changes, its `hash=` no longer matches, navori marks the
#    block `user-modified` and STOPS UPDATING IT. Nothing announces that.
#
#    These files are a MIRROR, and the harness already says so in prose ("los
#    conflictos en `.claude/` y CLAUDE.md no se resuelven a mano: son espejo").
#    This rule is that policy made executable. The way to change them is to edit
#    the source asset and run `navori render --apply`, or `navori sync` to
#    reconcile — neither of which matches here, because neither redirects.
#
#    COVERED (blocked), by FORM of the write:
#      > path  ·  >| path        truncating redirect (`>>` append is NOT: it adds
#                                after the blocks and invalidates no hash)
#      sed -i … path             in-place rewrite
#      tee path                  overwrite (`tee -a` is an append, so it is not)
#    …and by TARGET, the marker-carrying outputs of `ENGINE_OUTPUTS`
#    (lib/health.ts), which is what "managed" means anywhere else in navori:
#      CLAUDE.md · AGENTS.md · .claude/settings.json
#      .claude/agents · .claude/skills · .claude/hooks
#      .agents/skills · .codex/config.toml · .codex/agents · .codex/hooks
#      .cursor/rules
#
#    NOT COVERED, and each exclusion is load-bearing:
#      .claude/progress/… and .codex/progress/…   the agent handoff files, for
#        BOTH engines. Every subagent ends by writing one, usually with a
#        heredoc; blocking that breaks the harness's own protocol with the
#        harness's own guard. They carry no markers, so nothing there can be
#        invalidated. Naming `.codex/` wholesale was exactly that bug: it
#        swallowed `.codex/progress/` and would have silenced every Codex
#        subagent's handoff (#389's rule caught it).
#      .claude/settings.local.json · .claude/worktrees/   machine-local, never
#        rendered, never marker-managed.
#      cp/mv INTO a managed path, `python -c` writes, `awk > file`, `perl -i`.
#        Enumerating write verbs is the losing half of this fight — the same
#        "describe the danger by its textual form" pattern the blind audit found
#        eight times. The PostToolUse watcher is the half that doesn't care about
#        form: it re-checks the hashes AFTER the fact, so anything that gets past
#        this rule still surfaces. This rule is the seatbelt; that one is the net.
managed_dir='\.claude/(agents|skills|hooks)|\.agents/skills|\.codex/(agents|hooks)|\.cursor/rules'
managed_path="(CLAUDE\.md|AGENTS\.md|\.claude/settings\.json|\.codex/config\.toml|(${managed_dir})/[^[:space:];&|]+)"
# The redirect check reads `scan`, NOT `segments`: the split rewrites every `|`
# into a newline, so `>| CLAUDE.md` (forced clobber) would be torn in half and
# the target would land in a segment of its own. Reading the unsplit copy is
# safe HERE and nowhere else in this file, because the pattern is local — only
# whitespace may sit between the `>` and its target, so it cannot reach across a
# `&&` into another command the way rules 1-3 could.
# `-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*` accepts the backup-suffix spellings that
# are the everyday form on both platforms: GNU `sed -i.bak`, BSD `sed -i ''`.
# Missing them would have left the rule covering the tutorial spelling only.
if printf '%s' "$scan" | grep -qE "(^|[^>])>\|?[[:space:]]*(\./)?${managed_path}([[:space:]]|\$)" \
  || printf '%s' "$segments" | grep -qE "(^|[[:space:]])sed[[:space:]]+(-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*|--in-place)([[:space:]]|=).*${managed_path}" \
  || printf '%s' "$segments" | grep -qE "(^|[[:space:]])tee[[:space:]]+([^-][^[:space:]]*[[:space:]]+)*(\./)?${managed_path}([[:space:]]|\$)"; then
  block "shell rewrite of a navori-managed file — edit the source asset and run 'navori render --apply' (or 'navori sync'); a direct write invalidates the block hash and freezes it"
fi
# navori:managed end id="guard-destructive-base"

# user: add extra guards here. `$cmd` already holds the full command (compound
# commands included) and `block "<reason>"` aborts with exit 2.
# Example:
#
#   if printf '%s' "$cmd" | grep -qE 'drop[[:space:]]+(table|database)'; then
#     block "DROP TABLE/DATABASE"
#   fi

exit 0
