# navori:managed start id="guard-destructive-base" hash="531dc6ef" version="0.6.0" source="@navori/core"
#!/usr/bin/env bash
#
# Defensive PreToolUse(Bash) guard.
# Reads the full command (compound commands included) from Claude Code's tool
# input and HARD-BLOCKS (exit 2) the destructive patterns that static deny
# rules in settings.json can't reliably catch: variable-indirected `rm -rf`,
# force-push to the base branch, hook-skipping, fork bombs, and writes to block
# devices. Exit 2 in a PreToolUse hook is evaluated BEFORE permission rules, so
# this is the strongest line of defense — it overrides even an `allow` match.
#
# KNOWN, ACCEPTED LIMITATION: matching is regex-based over the command string.
# A compound command is split into one segment per line first, so each rule only
# ever matches WITHIN a segment (see "SEGMENTS" below) — that is what keeps a
# `git commit` in one segment from being paired with a flag in another.
# Multi-line continuations, git global options (`git -C … commit`), and simple
# wrappers (`command`/`\git`/parens) ARE normalized before matching now, and a
# quoted skip-flag (`git commit "--no-verify"`) is still caught. Still unhandled:
# `sh -c`, `eval`, base64/printf obfuscation, and escaped-quote edge cases inside
# quoted spans. This guard is a SEATBELT against accidental
# destructive commands, NOT a sandbox against a deliberate adversary.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific guards in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# A missing JSON parser used to make this guard wave every command through; the
# shared extractor falls back to sed so it still inspects the command.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
cmd=$(extract_cmd)
[ -z "$cmd" ] && exit 0

# branchBase is shell-quoted at render time via the shq: marker (#197): a
# hostile branchBase in navori.config.json lands here as an inert literal,
# never executable.
base='main'

block() {
  echo "[navori] BLOCKED by guard-destructive: $1" >&2
  echo "[navori] command: $cmd" >&2
  echo "[navori] if intentional, run the command yourself outside the agent." >&2
  exit 2
}

# Normalized copy used ONLY by the rules below. `$cmd` stays intact for the
# messages. The transforms only add boundaries / drop noise, so they always push
# toward MORE blocking:
#   FIX B — join `\<newline>` continuations into a space and flatten any other
#           newline to `;` (a boundary the rules already handle) so a multi-line
#           `git commit \<NL> --no-verify` is matched as one logical command.
#   FIX C — neutralize wrappers into boundaries: a leading `command ` word, a
#           leading backslash (`\git`), and `(` runs, so `command git …`,
#           `\git …` and `(git …)` read as a plain `git …`.
# `scan` keeps quoted spans intact, so a quoted skip-flag (`git commit
# "--no-verify"`) is still caught — stripping the quotes there was a real bypass.
scan="$cmd"
scan="${scan//\\$'\n'/ }"     # FIX B: join line continuations
scan="${scan//$'\n'/;}"       # FIX B: flatten remaining newlines to a boundary
scan=$(printf '%s' "$scan" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/\(/ /g")

# SEGMENTS — one segment per LINE, shared by rules 1, 2 and 3.
#
# This is the backbone of the whole file: `grep` and `sed` match LINE BY LINE, so
# once a compound command is split one-segment-per-line, every rule below is
# scoped to a single segment for free — a pattern can no longer pair a `git
# commit` in one segment with a flag in another, and `$` means "end of this
# segment", not "end of the whole command line".
# #307 first did this for the force-push rule with a private copy of the split;
# rules 1 (#A2) and 3 (#A1) had the cross-segment bug it cured, so the split now
# happens ONCE, here, and all three rules read `$segments`.
#
# Each segment is peeled so it STARTS with its command word: leading whitespace
# and `VAR=value` env prefixes go away (`FOO=1 git push …` → `git push …`); the
# `(`, `\` and `command ` wrappers were already neutralized by FIX C above.
segments=""
# Pre-expanded newline: zsh does NOT expand $'\n' in the REPLACEMENT of
# ${var//pat/repl} (it inserts the literal characters), so an inline $'\n'
# left compound commands unsplit there and the rules below fail-open (#391).
# A plain variable expands identically in bash and zsh.
_nl=$'\n'
_split="$scan"
_split="${_split//&&/$_nl}"
_split="${_split//||/$_nl}"
_split="${_split//;/$_nl}"
_split="${_split//|/$_nl}"
while IFS= read -r _seg; do
  _seg="${_seg#"${_seg%%[![:space:]]*}"}"                 # strip leading ws
  while [[ "$_seg" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do     # strip VAR=val prefixes
    case "$_seg" in
      *[[:space:]]*)
        _seg="${_seg#*[[:space:]]}"
        _seg="${_seg#"${_seg%%[![:space:]]*}"}"
        ;;
      *) _seg=""; break ;;
    esac
  done
  segments="${segments}${_seg}"$'\n'
done <<< "$_split"

# Same list with quoted spans dropped, used ONLY by the combined-short-flag
# check, so a hyphen-word inside a commit message (`-m "add -notify option"`)
# can't trip it.
segments_unquoted=$(printf '%s' "$segments" | sed -E -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g")

# Git commit/push detector shared by rule 1. The leading boundary accepts ; & |
# so `true;git commit …` (no space after the separator) is caught; the
# `git(… -opt …)*` middle allows git global options between `git` and the
# subcommand (`git -c k=v commit …`).
git_cp='(^|[[:space:]]|[;&|])git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+(commit|push)'

# 1. Skipping quality gates / hooks — defeats the whole point of the harness.
#    Two checks: the literal `--no-verify` over `segments` (quotes kept, so a
#    quoted flag is still caught), and `-[a-zA-Z]*n[a-zA-Z]*` over
#    `segments_unquoted` to catch `-n` folded into a combined short-flag token
#    (`git commit -qn`/`-nq`) without a hyphen-word in a message tripping it.
#    Both run over the SEGMENT list, so the `.*` between the git invocation and
#    the flag can never leave the segment that holds the commit/push. Matching
#    the whole command string instead is what made `git commit -m x && git log
#    -n 3` (or `&& grep -rn TODO src/`) block as a bogus "--no-verify": any short
#    flag carrying an `n` ANYWHERE later in the line was read as the commit's.
if printf '%s' "$segments"            | grep -qE "${git_cp}.*--no-verify" \
  || printf '%s' "$segments_unquoted" | grep -qE "${git_cp}.*[[:space:]]-[a-zA-Z]*n[a-zA-Z]*([[:space:]]|\$)"; then
  block "git commit/push with --no-verify (skipping hooks/gates)"
fi

# 2. Force-push to the base branch. force-with-lease is allowed (safe rebase
#    flow on feature branches); bare --force/-f against the base branch is not.
#    #307: every sub-check is scoped to the ACTUAL `git push` invocation(s),
#    never the whole command string. Keeping only the segments that START a
#    `git … push` means a `+`
#    in a commit message (`-m "format:check + test"`), a base-branch name in a
#    sibling command (`gh pr create --base main`), or a heredoc/`--body` can no
#    longer be misread as a force-push refspec or as the pushed ref — that
#    false positive blocked legit compound commit+push+PR commands. The refspec
#    `+` is matched only when glued to a ref (`+main`, never `+ test`), the way
#    git actually spells a force-push refspec.
push_seg=$(printf '%s' "$segments" \
  | grep -E '^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+push([[:space:]]|$)' \
  || true)

if [ -n "$push_seg" ] \
  && printf '%s' "$push_seg" | grep -qE '(--force([[:space:]]|$)|[[:space:]]-f([[:space:]]|$)|[[:space:]]\+[^[:space:]])' \
  && ! printf '%s' "$push_seg" | grep -qE 'force-with-lease' \
  && printf '%s' "$push_seg" | grep -qE "(^|[[:space:]+/])${base}([[:space:]]|\$)"; then
  block "force-push to the base branch '${base}'"
fi

# 3. rm -rf with variable indirection or absolute home/system roots that static
#    deny globs miss. The deny rules in settings.json (`Bash(rm -rf ~/*)`,
#    `Bash(rm -rf /*)`) only match a command that STARTS that way, so anything
#    compound (`cd /tmp && rm -rf ~/`) walks past them — exactly the class this
#    guard exists to cover. Matching per SEGMENT is what makes that work: `$`
#    below means "end of this segment", so the target no longer has to sit at
#    the end of the whole command line.
#
#    COVERED (blocked):
#      rm -rf $VAR / "$VAR"        variable indirection (`PATH=/; rm -rf $PATH`)
#      rm -rf /   ·  rm -rf /*     the filesystem root
#      rm -rf ~   ·  ~/  ·  ~/Documents        HOME and its immediate children
#      rm -rf /Users/me  ·  /Users/me/Desktop  the same, spelled absolutely
#      rm -rf /usr  ·  /etc  ·  /var/folders   a system root or an immediate child
#      rm -rf /tmp  ·  /private/tmp            the scratch root itself, bare
#    NOT COVERED (deliberate, so everyday cleanup keeps working):
#      relative paths — `rm -rf node_modules`, `rm -rf ./dist`
#      anything INSIDE the scratch root — `rm -rf /tmp/navori-test-123`: a temp
#        dir is scratch by definition and agents create and delete them all day;
#        only wiping `/tmp` wholesale is the accident worth catching.
#      DEEP absolute paths — `rm -rf /Users/me/dev/app/node_modules`, `/tmp/x/y`:
#        past the first level under a root, a path is assumed to be project or
#        scratch data. Wiping HOME or a system dir is the accident worth
#        catching; a deep path is a targeted delete, and blocking every one of
#        them would fire daily (agents are told to use absolute paths) and only
#        teach the operator to route around the guard.
#      `sh -c`, `eval`, base64/printf obfuscation — seatbelt, not a sandbox.
rm_run='(^|[[:space:]])rm[[:space:]]+(-[a-zA-Z]*r[a-zA-Z]*[[:space:]]+|-[a-zA-Z]*f[a-zA-Z]*[[:space:]]+)*-?[a-zA-Z]*[rf][a-zA-Z]*[[:space:]]+'
rm_quote="[\"']?"                     # optional opening quote around the target
rm_var='\$'                           # `$VAR`, `${VAR}` — any variable
rm_home='~(/[^[:space:]/]*)?|/(Users|home)(/[^[:space:]/]+(/[^[:space:]/]*)?)?'
rm_root='/\*?|/(Applications|Library|System|Volumes|bin|boot|dev|etc|lib|lib64|mnt|opt|root|sbin|srv|sys|usr|var)(/[^[:space:]/]*)?'
rm_tmp='/private(/tmp)?|/tmp'         # scratch root: the root itself, never a child
rm_end='/?([[:space:]]|$)'            # optional trailing slash, then end of segment
if printf '%s' "$segments" \
  | grep -qE "${rm_run}${rm_quote}(${rm_var}|(${rm_home}|${rm_root}|${rm_tmp})${rm_end})"; then
  block "recursive rm over a variable / root / home"
fi

# 4. Fork bomb.
if printf '%s' "$cmd" | grep -qE ':\(\)[[:space:]]*\{[[:space:]]*:\|:'; then
  block "fork bomb"
fi

# 5. Writing to a raw block device (wipes a disk/partition).
if printf '%s' "$cmd" | grep -qE '(of=/dev/(sd|nvme|disk|hd)|>[[:space:]]*/dev/(sd|nvme|disk|hd))'; then
  block "direct write to a block device"
fi
# navori:managed end id="guard-destructive-base"

# user: add extra guards here. `$cmd` already holds the full command (compound
# commands included) and `block "<reason>"` aborts with exit 2.
# Example:
#
#   if printf '%s' "$cmd" | grep -qE 'drop[[:space:]]+(table|database)'; then
#     block "DROP TABLE/DATABASE"
#   fi

exit 0
