# navori:managed start id="guard-destructive-base" hash="8a86155d" version="0.6.0" source="@navori/core"
#!/usr/bin/env bash
#
# Defensive PreToolUse(Bash) guard.
# Reads the full command (compound commands included) from Claude Code's tool
# input and HARD-BLOCKS (exit 2) the destructive patterns that static deny
# rules in settings.json can't reliably catch: variable-indirected `rm -rf`,
# force-push to the base branch, hook-skipping, fork bombs, and writes to block
# devices. Exit 2 in a PreToolUse hook is evaluated BEFORE permission rules, so
# this is the strongest line of defense — it overrides even an `allow` match.
#
# KNOWN, ACCEPTED LIMITATION: matching is regex-based over the command string —
# over the part of it the shell will actually INTERPRET, since #462 (see "INERT
# CONTENT" below: a heredoc body or a `-m`/`--body` value is data, not a call).
# A compound command is split into one segment per line first, so each rule only
# ever matches WITHIN a segment (see "SEGMENTS" below) — that is what keeps a
# `git commit` in one segment from being paired with a flag in another.
# Multi-line continuations, git global options (`git -C … commit`), and simple
# wrappers (`command`/`\git`/parens) ARE normalized before matching now, and a
# quoted skip-flag (`git commit "--no-verify"`) is still caught. Still unhandled:
# `sh -c`, `eval`, base64/printf obfuscation, and escaped-quote edge cases inside
# quoted spans. This guard is a SEATBELT against accidental
# destructive commands, NOT a sandbox against a deliberate adversary.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific guards in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# A missing JSON parser used to make this guard wave every command through; the
# shared extractor falls back to sed so it still inspects the command.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
cmd=$(extract_cmd)
[ -z "$cmd" ] && exit 0

# branchBase is shell-quoted at render time via the shq: marker (#197): a
# hostile branchBase in navori.config.json lands here as an inert literal,
# never executable.
base='main'

block() {
  echo "[navori] BLOCKED by guard-destructive: $1" >&2
  echo "[navori] command: $cmd" >&2
  echo "[navori] if intentional, run the command yourself outside the agent." >&2
  exit 2
}

# Pre-expanded newline, shared by the inert-content pass and the segment split.
# zsh does NOT expand $'\n' in the REPLACEMENT of ${var//pat/repl} (it inserts
# the literal characters), so an inline $'\n' left compound commands unsplit
# there and the rules below fail-open (#391). A plain variable expands
# identically in bash and zsh.
_nl=$'\n'

# INERT CONTENT (#462) — what the shell EXECUTES vs what it merely WRITES.
#
# Every rule below reads the command as TEXT, so a PR body or a commit message
# that QUOTES a destructive command was blocked even though nothing ran. That
# fires on every security change, because documenting a fix means quoting the
# attack it defends against: #403 could not write its own PR body, and a commit
# message naming a recursive delete of HOME needed the `git commit -F <file>`
# detour.
#
# `live` is `$cmd` minus its INERT spans — the text the shell hands to a program
# as DATA and never interprets as a command. `$cmd` stays intact for the
# messages; the rules read `live` (directly, or through `scan`).
#
# INERT (dropped before matching):
#   · a heredoc BODY — `cat > body.md <<'EOF' … EOF` is file content.
#   · the quoted VALUE of a message/body flag (`-m`, `--body`, …) — it lands in
#     a commit object or in a PR, the shell never runs it.
#
# NOT inert. This is the line the decision draws — stated as the FRONTIER it
# actually is, denylist included, because an unstated denylist reads as coverage:
#   · a heredoc whose opener names a SCRIPT path (`cat > run.sh <<'EOF'`) — that
#     is step 1 of write-then-execute, not documentation. The extension list is
#     matched case-INSENSITIVELY; an unlisted or absent extension (`Makefile`,
#     `.mk`, `.lua`, `.awk`, `cat > /tmp/payload`) reads as documentation, and
#     only the execution tell below can still catch it.
#   · ANY command that also EXECUTES something. Precisely: a KNOWN interpreter
#     (`_hd_run`) in COMMAND POSITION — optionally behind `VAR=v` and the simple
#     prefixes of `_hd_pre` WITH their arguments (`sudo -u me`, `env FOO=1`,
#     `timeout 5`), and behind the wrappers the tell normalizes away (`(…)`,
#     `{ …; }`, `\bash`, `"bash"`, `command bash`) —, or a path in command
#     position (`./x`, `/x`, `~/x`), or a `$(…)`/backtick substitution the shell
#     would expand (`git commit -m "$(rm -rf ~)"` really does run it). Such a
#     command is scanned WHOLE, exactly as before #462.
#     ANY OTHER RUNNER ESCAPES, and that is the accepted trade, not an oversight:
#     `npx tsx f`, `lua f`, `make -f f`, `find … -exec bash {} \;`, a runner
#     reached through a shell function or an alias, and one named by a BRACED
#     variable (`${SH} f` — the wrapper normalization collapses `{` to a space,
#     so it reaches the tell as `$ SH`; the plain `$SHELL f` IS caught). A word
#     split by escapes (`b\ash f`) escapes too, as it already does the rules in
#     the pre-#462 guard. A denylist is never complete;
#     widening it is cheap per entry, but each entry ALSO drags a legitimate
#     `… && make build` sitting next to a prose heredoc back into a full scan —
#     back into the exact false positive #462 exists to kill. Same class as the
#     `sh -c` / `eval` limitation the header states: a seatbelt, not a sandbox.
#   · a `<<` that merely sits inside a string (`echo "a << b"`) — it opens no
#     heredoc, so it can never be used to swallow the next real command. A line
#     whose quotes do not pair up (`echo "a \" << EOF"`) counts as a NON-opener
#     for the same reason: inventing a heredoc there would elide the real
#     commands that follow, the one way this pass could scan LESS than before.
# Unchanged scope: a deliberate adversary (`sh -c`, `eval`, base64) already had
# simpler doors and is still out of reach. This is a seatbelt, not a sandbox.
_hd_q='@navoriQ@'   # marks a QUOTED heredoc delimiter (`<<'EOF'`: no expansion)
skeleton=""
_hd_delim=""
_hd_inert=0
_hd_expand=0
while IFS= read -r _line; do
  if [ -n "$_hd_delim" ]; then
    # Inside a heredoc body. The terminator is compared whitespace-trimmed (a
    # `<<-` terminator may be indented); trimming can only end the body EARLIER
    # than the shell would, i.e. scan more, never less.
    _t="${_line#"${_line%%[![:space:]]*}"}"
    _t="${_t%"${_t##*[![:space:]]}"}"
    if [ "$_t" = "$_hd_delim" ]; then
      _hd_delim=""
      continue
    fi
    if [ "$_hd_inert" = 0 ]; then
      skeleton="${skeleton}${_line}${_nl}"
      continue
    fi
    # An UNQUOTED delimiter (`<<EOF`) still runs `$(…)`/backticks inside the
    # body — plain prose there is inert, a substitution is a real invocation.
    # Keeping exactly those lines feeds the whole-command fallback below.
    if [ "$_hd_expand" = 1 ]; then
      case "$_line" in
        *'$('* | *'`'*) skeleton="${skeleton}${_line}${_nl}" ;;
      esac
    fi
    continue
  fi
  skeleton="${skeleton}${_line}${_nl}"
  # Fast path: no `<<`, no heredoc — a PreToolUse hook runs on EVERY Bash call,
  # so the sed probes below are worth paying only on the lines that can open one.
  case "$_line" in
    *'<<'*) ;;
    *) continue ;;
  esac
  # Heredoc opener? The probe marks the DELIMITER's own quotes first, then drops
  # every other quoted span, so `cat <<'EOF'` is told apart from a `<<` inside a
  # string; `<<<` (here-string) is neutralized so it can't pose as `<<`.
  _probe=$(printf '%s' "$_line" | sed -E \
    -e "s/<<(-?)[[:space:]]*'([A-Za-z_][A-Za-z0-9_]*)'/<<\1${_hd_q}\2/g" \
    -e "s/<<(-?)[[:space:]]*\"([A-Za-z_][A-Za-z0-9_]*)\"/<<\1${_hd_q}\2/g" \
    -e "s/<<(-?)[[:space:]]*\\\\([A-Za-z_][A-Za-z0-9_]*)/<<\1${_hd_q}\2/g" \
    -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g" -e "s/<<</ /g")
  # A quote left over in the probe means those two `sed` passes paired the quotes
  # somewhere the shell would not (an escaped `\"`, an odd count): the `<<` may
  # well sit inside a string, and INVENTING a heredoc here is the one failure
  # mode of this whole pass that scans LESS — it would elide every following line,
  # real commands included (`echo "a \" << EOF"` + a real `rm -rf ~/`). Treat the
  # line as a NON-opener; worst case the body is scanned, which is what the guard
  # did before #462.
  case "$_probe" in
    *'"'* | *"'"*) continue ;;
  esac
  # `^[^<]*` anchors on the FIRST `<` of the line: no match (a `<` redirect
  # before the heredoc) simply leaves the body under the rules.
  _open=$(printf '%s' "$_probe" \
    | sed -nE "s/^[^<]*(<<-?[[:space:]]*(${_hd_q})?[A-Za-z_][A-Za-z0-9_]*).*/\1/p")
  if [ -z "$_open" ]; then continue; fi
  _hd_delim=$(printf '%s' "$_open" | sed -E "s/^<<-?[[:space:]]*(${_hd_q})?//")
  _hd_inert=1
  _hd_expand=0
  case "$_open" in
    *"${_hd_q}"*) ;;
    *) _hd_expand=1 ;;
  esac
  # Writing a SCRIPT is not documenting: keep `cat > run.sh <<'EOF'` visible.
  # Case-INSENSITIVE (`-i`): macOS ships a case-insensitive filesystem, so
  # `cat > /tmp/p.SH` writes and runs the same file as `p.sh`.
  if printf '%s' "$_line" \
    | grep -qiE "\.(sh|bash|zsh|ksh|fish|py|rb|pl|js|jsx|mjs|cjs|ts|tsx|command|bat|ps1|scpt)([[:space:]]|[\"'\`]|\$)"; then
    _hd_inert=0
  fi
done <<< "$cmd"

# A `$(…)`/backtick substitution outside single quotes RUNS: `git commit -m
# "$(rm -rf ~)"` is an invocation wearing a message's clothes. This check must
# read the skeleton BEFORE the flag values are elided below — eliding first
# swallowed the `$(` and let exactly that command through.
#
# TWO probes, OR'd, because neither alone is enough:
#   · single-quoted spans dropped — catches a `$(` sitting outside every quote.
#   · the double-quoted spans ALONE — inside them an apostrophe is LITERAL, so
#     the first probe pairs `it's … it's` as if it were a quoted span and deletes
#     the `$(` between them. That is ordinary punctuation in the very messages
#     #462 exists to allow (`-m "it's fine $(rm -rf / ) it's"`), and it disarmed
#     the only check that catches an invocation disguised as a message.
# Over-reading here only falls back to scanning the whole command, i.e. to the
# pre-#462 behaviour: the safe side.
_hd_whole=0
if printf '%s' "$skeleton" | sed -E "s/'[^']*'//g" | grep -qE '\$\(|`'; then
  _hd_whole=1
else
  # Fast path, same idea as the `<<` one above: probe 2 costs two processes on
  # EVERY Bash call, and it can only ever fire when a substitution is present
  # somewhere in the first place.
  case "$skeleton" in
    *'$('* | *'`'*)
      if printf '%s' "$skeleton" | grep -oE '"[^"]*"' | grep -qE '\$\(|`'; then
        _hd_whole=1
      fi
      ;;
  esac
fi

# Message/body flag VALUES. The flag itself stays so rule 1 still sees the shape
# of the invocation (`git commit -m "" --no-verify` is still a skip-flag), and
# `--body-file` is untouched: `([[:space:]]+|=)` can't match its `-`.
_hd_flags='-m|--message|--body|--title|--description|--notes'
skeleton=$(printf '%s' "$skeleton" | sed -E \
  -e "s/(^|[[:space:]])(${_hd_flags})([[:space:]]+|=)'[^']*'/\1\2 ''/g" \
  -e "s/(^|[[:space:]])(${_hd_flags})([[:space:]]+|=)\"[^\"]*\"/\1\2 \"\"/g")

# The elision holds ONLY while nothing in the command can run what was written.
# A segment that STARTS with an interpreter or with a path is an execution, and
# reverts to the whole command — which is why `cat > x <<'EOF' … EOF; bash x` is
# still blocked. Anything else keeps only what the shell will interpret.
#
# `_hd_pre` — the runner may sit behind simple prefixes, WITH their own arguments:
# `sudo -u me bash x`, `env FOO=1 bash x`, `timeout 5 bash x`. Matching only a
# prefix glued to the interpreter turned every one of those into a free pass.
_hd_pre='(sudo|doas|env|command|nohup|timeout|time|nice|ionice|stdbuf|setsid)'
_hd_pre="${_hd_pre}([[:space:]]+(-[^[:space:]]+([[:space:]]+[^-[:space:]][^[:space:]]*)?"
_hd_pre="${_hd_pre}|[A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*|[0-9][^[:space:]]*))*[[:space:]]+"
_hd_run='bash|sh|zsh|ksh|dash|ash|fish|tcsh|csh|source|eval|exec|xargs'
_hd_run="${_hd_run}|python[0-9.]*|node|deno|bun|perl|ruby|osascript"
_hd_exec='(^|[;&|])[[:space:]]*([A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*[[:space:]]+)*'
_hd_exec="${_hd_exec}(${_hd_pre})*"
# `\$[A-Za-z_]` covers a runner named by a plain VARIABLE (`$SHELL x`). The
# BRACED form (`${SH} x`) is NOT covered and is one of the declared escapes: the
# same wrapper normalization that puts `{ bash x; }` back in command position
# collapses `{` to a space, so `${SH}` reaches the tell as `$ SH`. Catching it
# would mean teaching that normalization about `$`-prefixed braces — a change to
# a security-sensitive transform, worth its own unit.
# Why catching the plain form is safe: a variable in command position is never a
# legitimate WRITER, so the false-positive cost is ~0 and the declared frontier
# stays complete — which is what the denylist trade-off rests on (#462).
_hd_exec="${_hd_exec}((${_hd_run})([[:space:]]|\$)|\.[[:space:]]|[.~]?/|\\\$[A-Za-z_])"
# The tell reads a NORMALIZED copy, never the raw skeleton: `_hd_exec` anchors on
# `^`/`;&|`, so any wrapper between the boundary and the interpreter used to hide
# it. The transforms are FIX C's (below) plus quote REMOVAL, which is what puts
# `(bash x)`, `{ bash x; }`, `\bash x`, `"bash" x` and `command bash x` back in
# command position. Unquoting is safe HERE and not below: its only effect is
# deciding whether to fall back to the whole command, i.e. to the pre-#462
# behaviour — it never reaches the rules, so a quoted skip-flag is untouched.
if [ "$_hd_whole" = 1 ] || printf '%s' "$skeleton" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/[(){}]/ /g" \
  -e "s/'([^']*)'/\1/g" \
  -e 's/"([^"]*)"/\1/g' | grep -qE "$_hd_exec"; then
  live="$cmd"
else
  live="$skeleton"
fi

# Normalized copy used ONLY by the rules below. `$cmd` stays intact for the
# messages. The transforms only add boundaries / drop noise, so they always push
# toward MORE blocking:
#   FIX B — join `\<newline>` continuations into a space and flatten any other
#           newline to `;` (a boundary the rules already handle) so a multi-line
#           `git commit \<NL> --no-verify` is matched as one logical command.
#   FIX C — neutralize wrappers into boundaries: a leading `command ` word, a
#           leading backslash (`\git`), and `(` runs, so `command git …`,
#           `\git …` and `(git …)` read as a plain `git …`.
# `scan` keeps quoted spans intact, so a quoted skip-flag (`git commit
# "--no-verify"`) is still caught — stripping the quotes there was a real bypass.
scan="$live"
scan="${scan//\\$'\n'/ }"     # FIX B: join line continuations
scan="${scan//$'\n'/;}"       # FIX B: flatten remaining newlines to a boundary
scan=$(printf '%s' "$scan" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/\(/ /g")

# SEGMENTS — one segment per LINE, shared by rules 1, 2 and 3.
#
# This is the backbone of the whole file: `grep` and `sed` match LINE BY LINE, so
# once a compound command is split one-segment-per-line, every rule below is
# scoped to a single segment for free — a pattern can no longer pair a `git
# commit` in one segment with a flag in another, and `$` means "end of this
# segment", not "end of the whole command line".
# #307 first did this for the force-push rule with a private copy of the split;
# rules 1 (#A2) and 3 (#A1) had the cross-segment bug it cured, so the split now
# happens ONCE, here, and all three rules read `$segments`.
#
# Each segment is peeled so it STARTS with its command word: leading whitespace
# and `VAR=value` env prefixes go away (`FOO=1 git push …` → `git push …`); the
# `(`, `\` and `command ` wrappers were already neutralized by FIX C above.
segments=""
_split="$scan"
_split="${_split//&&/$_nl}"
_split="${_split//||/$_nl}"
_split="${_split//;/$_nl}"
_split="${_split//|/$_nl}"
while IFS= read -r _seg; do
  _seg="${_seg#"${_seg%%[![:space:]]*}"}"                 # strip leading ws
  while [[ "$_seg" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do     # strip VAR=val prefixes
    case "$_seg" in
      *[[:space:]]*)
        _seg="${_seg#*[[:space:]]}"
        _seg="${_seg#"${_seg%%[![:space:]]*}"}"
        ;;
      *) _seg=""; break ;;
    esac
  done
  segments="${segments}${_seg}"$'\n'
done <<< "$_split"

# Same list with quoted spans dropped, used ONLY by the combined-short-flag
# check, so a hyphen-word inside a commit message (`-m "add -notify option"`)
# can't trip it.
segments_unquoted=$(printf '%s' "$segments" | sed -E -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g")

# Git commit/push detector shared by rule 1. The leading boundary accepts ; & |
# so `true;git commit …` (no space after the separator) is caught; the
# `git(… -opt …)*` middle allows git global options between `git` and the
# subcommand (`git -c k=v commit …`).
git_cp='(^|[[:space:]]|[;&|])git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+(commit|push)'

# 1. Skipping quality gates / hooks — defeats the whole point of the harness.
#    Two checks: the literal `--no-verify` over `segments` (quotes kept, so a
#    quoted flag is still caught), and `-[a-zA-Z]*n[a-zA-Z]*` over
#    `segments_unquoted` to catch `-n` folded into a combined short-flag token
#    (`git commit -qn`/`-nq`) without a hyphen-word in a message tripping it.
#    Both run over the SEGMENT list, so the `.*` between the git invocation and
#    the flag can never leave the segment that holds the commit/push. Matching
#    the whole command string instead is what made `git commit -m x && git log
#    -n 3` (or `&& grep -rn TODO src/`) block as a bogus "--no-verify": any short
#    flag carrying an `n` ANYWHERE later in the line was read as the commit's.
if printf '%s' "$segments"            | grep -qE "${git_cp}.*--no-verify" \
  || printf '%s' "$segments_unquoted" | grep -qE "${git_cp}.*[[:space:]]-[a-zA-Z]*n[a-zA-Z]*([[:space:]]|\$)"; then
  block "git commit/push with --no-verify (skipping hooks/gates)"
fi

# 2. Force-push to the base branch. force-with-lease is allowed (safe rebase
#    flow on feature branches); bare --force/-f against the base branch is not.
#    #307: every sub-check is scoped to the ACTUAL `git push` invocation(s),
#    never the whole command string. Keeping only the segments that START a
#    `git … push` means a `+`
#    in a commit message (`-m "format:check + test"`), a base-branch name in a
#    sibling command (`gh pr create --base main`), or a heredoc/`--body` can no
#    longer be misread as a force-push refspec or as the pushed ref — that
#    false positive blocked legit compound commit+push+PR commands. The refspec
#    `+` is matched only when glued to a ref (`+main`, never `+ test`), the way
#    git actually spells a force-push refspec.
push_seg=$(printf '%s' "$segments" \
  | grep -E '^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+push([[:space:]]|$)' \
  || true)

if [ -n "$push_seg" ] \
  && printf '%s' "$push_seg" | grep -qE '(--force([[:space:]]|$)|[[:space:]]-f([[:space:]]|$)|[[:space:]]\+[^[:space:]])' \
  && ! printf '%s' "$push_seg" | grep -qE 'force-with-lease' \
  && printf '%s' "$push_seg" | grep -qE "(^|[[:space:]+/])${base}([[:space:]]|\$)"; then
  block "force-push to the base branch '${base}'"
fi

# 3. rm -rf with variable indirection or absolute home/system roots that static
#    deny globs miss. The deny rules in settings.json (`Bash(rm -rf ~/*)`,
#    `Bash(rm -rf /*)`) only match a command that STARTS that way, so anything
#    compound (`cd /tmp && rm -rf ~/`) walks past them — exactly the class this
#    guard exists to cover. Matching per SEGMENT is what makes that work: `$`
#    below means "end of this segment", so the target no longer has to sit at
#    the end of the whole command line.
#
#    COVERED (blocked):
#      rm -rf $VAR / "$VAR"        variable indirection (`PATH=/; rm -rf $PATH`)
#      rm -rf /   ·  rm -rf /*     the filesystem root
#      rm -rf ~   ·  ~/  ·  ~/Documents        HOME and its immediate children
#      rm -rf /Users/me  ·  /Users/me/Desktop  the same, spelled absolutely
#      rm -rf /usr  ·  /etc  ·  /var/folders   a system root or an immediate child
#      rm -rf /tmp  ·  /private/tmp            the scratch root itself, bare
#    NOT COVERED (deliberate, so everyday cleanup keeps working):
#      relative paths — `rm -rf node_modules`, `rm -rf ./dist`
#      anything INSIDE the scratch root — `rm -rf /tmp/navori-test-123`: a temp
#        dir is scratch by definition and agents create and delete them all day;
#        only wiping `/tmp` wholesale is the accident worth catching.
#      DEEP absolute paths — `rm -rf /Users/me/dev/app/node_modules`, `/tmp/x/y`:
#        past the first level under a root, a path is assumed to be project or
#        scratch data. Wiping HOME or a system dir is the accident worth
#        catching; a deep path is a targeted delete, and blocking every one of
#        them would fire daily (agents are told to use absolute paths) and only
#        teach the operator to route around the guard.
#      `sh -c`, `eval`, base64/printf obfuscation — seatbelt, not a sandbox.
rm_run='(^|[[:space:]])rm[[:space:]]+(-[a-zA-Z]*r[a-zA-Z]*[[:space:]]+|-[a-zA-Z]*f[a-zA-Z]*[[:space:]]+)*-?[a-zA-Z]*[rf][a-zA-Z]*[[:space:]]+'
rm_quote="[\"']?"                     # optional opening quote around the target
rm_var='\$'                           # `$VAR`, `${VAR}` — any variable
rm_home='~(/[^[:space:]/]*)?|/(Users|home)(/[^[:space:]/]+(/[^[:space:]/]*)?)?'
rm_root='/\*?|/(Applications|Library|System|Volumes|bin|boot|dev|etc|lib|lib64|mnt|opt|root|sbin|srv|sys|usr|var)(/[^[:space:]/]*)?'
rm_tmp='/private(/tmp)?|/tmp'         # scratch root: the root itself, never a child
rm_end='/?([[:space:]]|$)'            # optional trailing slash, then end of segment
if printf '%s' "$segments" \
  | grep -qE "${rm_run}${rm_quote}(${rm_var}|(${rm_home}|${rm_root}|${rm_tmp})${rm_end})"; then
  block "recursive rm over a variable / root / home"
fi

# 4. Fork bomb. Reads `live`, not `scan`: FIX C turns `(` into a space, which
#    would defuse the very pattern this rule looks for.
if printf '%s' "$live" | grep -qE ':\(\)[[:space:]]*\{[[:space:]]*:\|:'; then
  block "fork bomb"
fi

# 5. Writing to a raw block device (wipes a disk/partition).
if printf '%s' "$live" | grep -qE '(of=/dev/(sd|nvme|disk|hd)|>[[:space:]]*/dev/(sd|nvme|disk|hd))'; then
  block "direct write to a block device"
fi
# navori:managed end id="guard-destructive-base"

# user: add extra guards here. `$cmd` already holds the full command (compound
# commands included) and `block "<reason>"` aborts with exit 2.
# Example:
#
#   if printf '%s' "$cmd" | grep -qE 'drop[[:space:]]+(table|database)'; then
#     block "DROP TABLE/DATABASE"
#   fi

exit 0
