# navori:managed start id="managed-drift-watch-base" hash="f844ebe3" version="0.6.5" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse(Bash) watcher for managed-block drift (#530).
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST, and why this compares CONTENT rather than mtimes. The obvious cheap
# check is `find -newer <stamp>`, and it is wrong here: `find` compares mtimes at
# whatever resolution the filesystem stores, which on several (ext4 under the CI
# runner among them) is ONE SECOND. Two writes inside the same second as the
# stamp are invisible — the watcher would report the first and silently miss the
# second, which is precisely the failure it exists to prevent. It passed on APFS
# and failed in CI, so the clock was never a sound basis.
#
# So the common case costs one `shasum` pass over the managed files (~25ms
# measured over 60 files) and compares that list against the previous one. It is
# exact, it depends on no clock, and per-block hashing — the expensive part, ~3.5s
# for 53 blocks — runs ONLY for the files whose content actually changed, which
# in a normal session is none and in a bad one is one.
set -uo pipefail

# PostToolUse delivers its payload on stdin; this hook never needed it and the
# audit recorder does (session_id/cwd), so it is captured rather than ignored.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="managed-drift-watch"
navori_audit_phase="PostToolUse"
navori_audit_tool="Bash"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", .agent_id // .subagent_id // ""] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_agent=${navori_audit_rest#*
}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  navori_audit_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || navori_audit_ts=""
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg ts "$navori_audit_ts" \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    '{ts:$ts,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# This hook has SEVEN early exits (no sha, no roots, no changes, …). Wiring a
# call into each is how the set drifts the next time one is added, so the verdict
# is derived once, from the exit code, in a trap.
#
# `navori_audit_reached_check` is what separates "ran and found nothing" from
# "bailed before checking anything" — the distinction the whole exercise exists
# for. Without it every early exit would report `clean`, i.e. would claim a
# verification that never happened.
navori_audit_reached_check=0
navori_audit_on_exit() {
  navori_audit_code=$?
  if [ "$navori_audit_code" -eq 2 ]; then
    navori_audit_log "dirty" "bloque managed con hash desalineado"
  elif [ "$navori_audit_reached_check" -eq 1 ]; then
    navori_audit_log "clean"
  else
    navori_audit_log "skip" "sin nada que verificar"
  fi
  return 0
}
trap navori_audit_on_exit EXIT

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

stamp=".claude/.managed-drift-stamp"

# sha1 tool, resolved once. `shasum` on macOS, `sha1sum` on most Linuxes; both
# print `<hash>  <path>` for a file list, which is the format the stamp stores.
sha=""
command -v shasum >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This is a detector, not a gate — the guard still
# sits in front, and a noisy failure here would fire on every single command.
[ -z "$sha" ] && exit 0

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — including them would re-hash a fresh report on every
# command and find nothing. `.claude/worktrees/` too: each is a full checkout,
# so walking it would make this hook cost more than the command it follows. That
# is why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
current=$(find $roots -type f -exec $sha {} + 2>/dev/null | sort || true)
[ -z "$current" ] && exit 0

# First run in a session (or after the ephemeral dir was wiped): adopt the
# current state as the baseline and say nothing. Reporting every block on the
# first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p .claude 2>/dev/null || exit 0
  printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
  exit 0
fi

# Lines present now but not in the baseline: a file whose CONTENT changed, or a
# new one. A deleted file appears only in the baseline and is ignored — there is
# no block left to verify.
changed=$(printf '%s\n' "$current" | grep -F -x -v -f "$stamp" 2>/dev/null | sed -E 's/^[a-f0-9]+[[:space:]]+//' || true)
# Re-baseline BEFORE reporting, so one write is reported once instead of on
# every command for the rest of the session. A second write does change the
# content again, and does get its own report.
printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# From here on the work is per-CHANGED-file only. `$(…)` strips the trailing
# newline, which is what makes these hashes agree with `computeManagedHash`
# (lib/marker.ts: sha1 over the body with trailing whitespace removed, first 8
# hex); without it every hash differs and the hook cries wolf on healthy files.
drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

navori_audit_reached_check=1
[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
# navori:managed end id="managed-drift-watch-base"
