# navori:managed start id="managed-drift-watch-base" hash="dbd1e4c6" version="0.6.4" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse(Bash) watcher for managed-block drift (#530).
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST, and why this compares CONTENT rather than mtimes. The obvious cheap
# check is `find -newer <stamp>`, and it is wrong here: `find` compares mtimes at
# whatever resolution the filesystem stores, which on several (ext4 under the CI
# runner among them) is ONE SECOND. Two writes inside the same second as the
# stamp are invisible — the watcher would report the first and silently miss the
# second, which is precisely the failure it exists to prevent. It passed on APFS
# and failed in CI, so the clock was never a sound basis.
#
# So the common case costs one `shasum` pass over the managed files (~25ms
# measured over 60 files) and compares that list against the previous one. It is
# exact, it depends on no clock, and per-block hashing — the expensive part, ~3.5s
# for 53 blocks — runs ONLY for the files whose content actually changed, which
# in a normal session is none and in a bad one is one.
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

stamp=".claude/.managed-drift-stamp"

# sha1 tool, resolved once. `shasum` on macOS, `sha1sum` on most Linuxes; both
# print `<hash>  <path>` for a file list, which is the format the stamp stores.
sha=""
command -v shasum >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This is a detector, not a gate — the guard still
# sits in front, and a noisy failure here would fire on every single command.
[ -z "$sha" ] && exit 0

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — including them would re-hash a fresh report on every
# command and find nothing. `.claude/worktrees/` too: each is a full checkout,
# so walking it would make this hook cost more than the command it follows. That
# is why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
current=$(find $roots -type f -exec $sha {} + 2>/dev/null | sort || true)
[ -z "$current" ] && exit 0

# First run in a session (or after the ephemeral dir was wiped): adopt the
# current state as the baseline and say nothing. Reporting every block on the
# first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p .claude 2>/dev/null || exit 0
  printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
  exit 0
fi

# Lines present now but not in the baseline: a file whose CONTENT changed, or a
# new one. A deleted file appears only in the baseline and is ignored — there is
# no block left to verify.
changed=$(printf '%s\n' "$current" | grep -F -x -v -f "$stamp" 2>/dev/null | sed -E 's/^[a-f0-9]+[[:space:]]+//' || true)
# Re-baseline BEFORE reporting, so one write is reported once instead of on
# every command for the rest of the session. A second write does change the
# content again, and does get its own report.
printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# From here on the work is per-CHANGED-file only. `$(…)` strips the trailing
# newline, which is what makes these hashes agree with `computeManagedHash`
# (lib/marker.ts: sha1 over the body with trailing whitespace removed, first 8
# hex); without it every hash differs and the hook cries wolf on healthy files.
drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
# navori:managed end id="managed-drift-watch-base"
