# navori:managed start id="plan-gate-base" hash="6e7fee4b" version="0.11.2" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(Agent) gate — spec 0032 (#1011), R16/R17/R19: while
# `harness.planTiers` is `true`, the orchestrator may not dispatch the
# `implementer` without a workplan that passes `navori plan check`, or a
# level-0 exemption `navori plan classify` confirms. Blocks with `exit 2`,
# the same channel `guard-destructive`/`implementer-no-markdown` use,
# evaluated BEFORE permission rules.
#
# THIN ON PURPOSE. All the decision logic — reading `tool_input.subagent_type`
# / `tool_input.prompt`, resolving the workplan, running `classify`/`check`,
# counting `CHANGES_REQUESTED` rejections (R19) — lives in TypeScript
# (`navori plan gate`, `lib/plan/gate.ts`): that is what `plan-gate.test.ts`
# exercises directly. This script only resolves the `navori` binary and
# forwards the hook's own stdin payload to it unchanged; it never parses JSON
# itself. Matcher `Agent` in settings.json already restricts which calls
# reach this script, so there is nothing left to filter here.
#
# BINARY RESOLUTION. Same as `audit-mode-trigger.sh` / `session-start-context.sh`:
# `command -v navori`. Unlike those two (best-effort, silently absent), this
# is a HARD gate — `harness.planTiers` promises the workplan is enforced, so a
# missing or outdated `navori` must DENY with an actionable reason, never fail
# open. An outdated build with no `plan` subcommand exits with something other
# than this gate's own two contractual codes (0 allow, 2 deny) — citty's
# unknown-command exit — which this script tells apart from a real verdict
# below, in ONE invocation (a second `--help` probe would read the hook's
# stdin payload twice, which a pipe cannot replay).
#
# CODEX (spec 0041 R9). Registered on PreToolUse(spawn_agent$) as the last late
# row. Only `implementer` is gated, with the role from `tool_input.agent_type`.
# Codex V2 encrypts the spawn `message`, so the opening line then comes from the
# orchestrator's `.navori/state/handoffs/dispatch_<feature>.json` (TTL 10 min,
# exactly one fresh file); the decision logic stays in `navori plan gate`.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# The payload is captured (not streamed) because two readers need it: the audit
# recorder below reads `session_id`/`cwd` from it, and `navori plan gate` gets
# the same bytes re-piped unchanged. A pipe cannot be replayed, so one read.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="plan-gate"
navori_audit_phase="PreToolUse"
navori_audit_tool="Agent"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN for the recorder: an undefined function here must never turn a raw,
# un-rendered copy of this asset into exit 127 — which is neither contractual
# code of this gate.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason != "" then {reason:"unspecified"} else {} end)
     + (if (["hard","ask","advisory"]|index($kind)) != null then {kind:$kind} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

# The verdict is resolved in a trap, like `guard-destructive`: every exit below
# (missing binary, allow, deny, outdated build) is recorded without a call per
# branch, and the exit code itself stays untouched.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

if ! command -v navori >/dev/null 2>&1; then
  navori_audit_verdict="block"
  navori_audit_reason="binary missing from PATH"
  echo "[navori] BLOCKED by plan-gate: navori is not installed or not on PATH — install it before dispatching a planned implementer." >&2
  exit 2
fi

printf '%s' "$payload" | navori plan gate
navori_exit=$?
case "$navori_exit" in
  0) exit 0 ;;
  2)
    navori_audit_verdict="block"
    navori_audit_reason="plan gate denied the dispatch"
    exit 2
    ;;
  *)
    navori_audit_verdict="block"
    navori_audit_reason="plan subcommand unavailable, exit $navori_exit"
    echo "[navori] BLOCKED by plan-gate: this navori build has no working 'plan' subcommand (exit $navori_exit) — update navori (or run 'navori render --apply' after updating) before dispatching a planned implementer." >&2
    exit 2
    ;;
esac
# navori:managed end id="plan-gate-base"
