# navori:managed start id="plan-gate-base" hash="61d79ee7" version="0.11.3" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(Agent) gate — spec 0032 (#1011), R16/R17/R19: while
# `harness.planTiers` is `true`, the orchestrator may not dispatch the
# `implementer` without a workplan that passes `navori plan check`, or a
# level-0 exemption `navori plan classify` confirms. Blocks with `exit 2`,
# the same channel `guard-destructive`/`implementer-no-markdown` use,
# evaluated BEFORE permission rules.
#
# THIN ON PURPOSE. All the decision logic — reading `tool_input.subagent_type`
# / `tool_input.prompt`, resolving the workplan, running `classify`/`check`,
# counting `CHANGES_REQUESTED` rejections (R19) — lives in TypeScript
# (`navori plan gate`, `lib/plan/gate.ts`): that is what `plan-gate.test.ts`
# exercises directly. This script only resolves the `navori` binary and
# forwards the hook's own stdin payload to it unchanged; it never parses JSON
# itself. Matcher `Agent` in settings.json already restricts which calls
# reach this script, so there is nothing left to filter here.
#
# BINARY RESOLUTION. Same as `audit-mode-trigger.sh` / `session-start-context.sh`:
# `command -v navori`. Unlike those two (best-effort, silently absent), this
# is a HARD gate — `harness.planTiers` promises the workplan is enforced, so a
# real plan denial (exit 2 from `navori plan gate`) always stays a hard block.
# When navori is missing or outdated there is NO verdict to enforce (#1117): the
# gate asks the human instead of leaving a dead end — Claude only, in a mode
# that shows the prompt (`navori_can_ask`), recorded as verdict `ask`. Codex
# (drops `permissionDecision`), no payload, no jq and bypassPermissions/dontAsk/
# plan/unknown modes keep the hard block (exit 2); an ask is never a silent
# allow. The `*)` arm also catches a crashing or killed navori (exit 126/127/
# 137, ...), not only a missing `plan` subcommand; the ask text says "exit N".
# An outdated build with no `plan` subcommand exits with something other
# than this gate's own two contractual codes (0 allow, 2 deny) — citty's
# unknown-command exit — which this script tells apart from a real verdict
# below, in ONE invocation (a second `--help` probe would read the hook's
# stdin payload twice, which a pipe cannot replay).
#
# Blocking classification (#1117):
#   - navori missing / `plan` subcommand unavailable: ask (Claude, prompting
#     modes only) / hard (Codex, no payload or jq, non-prompting modes) — no verdict.
#   - `navori plan gate` denied the dispatch: hard — a real verdict.
#
# CODEX (spec 0041 R9). Registered on PreToolUse(spawn_agent$) as the last late
# row. Only `implementer` is gated, with the role from `tool_input.agent_type`.
# Codex V2 encrypts the spawn `message`, so the opening line then comes from the
# orchestrator's `.navori/state/handoffs/dispatch_<feature>.json` (TTL 10 min,
# exactly one fresh file); the decision logic stays in `navori plan gate`.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# The payload is captured (not streamed) because two readers need it: the audit
# recorder below reads `session_id`/`cwd` from it, and `navori plan gate` gets
# the same bytes re-piped unchanged. A pipe cannot be replayed, so one read.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="plan-gate"
navori_audit_phase="PreToolUse"
navori_audit_tool="Agent"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN for the recorder: an undefined function here must never turn a raw,
# un-rendered copy of this asset into exit 127 — which is neither contractual
# code of this gate.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Can this gate hand a no-verdict outcome to the user instead of blocking?
# Inlined at render time (see lib/render/hook-includes.ts). Decides only; the
# JSON that speaks to the host stays in each script (partials never carry host
# output vocabulary — hook-output-contract.test.ts).
#
# WHY (#1117): when the TOOL failed (scanner missing a flag, declared runner not
# on PATH) the gate has no verdict, and "run it yourself outside the agent" is a
# dead end. Claude Code's PreToolUse can ask the human; that is the right exit.
#
# Returns 0 only when ALL hold; any doubt is "no", and "no" is today's block:
#   - the script is not a Codex copy (Codex drops `permissionDecision`, so an
#     ask there would let the call PROCEED unasked). Decided by WHERE THE SCRIPT
#     LIVES, the same rule as the hook-input partial; hooks live in `.codex/hooks/`,
#     plugin scripts in `.codex/scripts/`.
#   - the payload is a real PreToolUse hook call. A git hook or the CLI
#     (`</dev/null`) has no payload, so there is nobody to ask.
#   - jq exists to build the reason JSON safely; without it, block.
#   - `permission_mode` is one where the host SHOWS the prompt: default,
#     acceptEdits or auto (the host docs state a hook ask there). Everything
#     else — bypassPermissions, dontAsk, plan (it can run with prompts disabled),
#     empty, missing or unknown — is "no": a hook ask is undocumented or denied
#     there, and these gates fall back to exit 2, so an ask must never turn into
#     a silent allow.
# Needs `payload`/`payload_field` from the extract-cmd partial.
navori_can_ask() {
  case "$0" in
    *".codex/hooks/"* | *".codex/scripts/"*) return 1 ;;
  esac
  command -v jq >/dev/null 2>&1 || return 1
  [ "$(payload_field hook_event_name)" = "PreToolUse" ] || return 1
  case "$(payload_field permission_mode)" in
    default | acceptEdits | auto) return 0 ;;
  esac
  return 1
}
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable","native-hook"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

# The verdict is resolved in a trap, like `guard-destructive`: every exit below
# (missing binary, allow, deny, outdated build) is recorded without a call per
# branch, and the exit code itself stays untouched.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# No verdict (navori missing or unusable). $1 = audit reason code, $2 = hard-block
# message, $3 = text shown to the human when asking. Never returns.
plan_gate_no_verdict() {
  codex_copy=0
  case "$0" in *".codex/hooks/"*) codex_copy=1 ;; esac
  if [ "$codex_copy" = 0 ] && navori_can_ask; then
    navori_audit_verdict="ask"
    navori_audit_reason="$1"
    jq -cn --arg reason "$3" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"ask",permissionDecisionReason:$reason}}'
    exit 0
  fi
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  echo "$2" >&2
  exit 2
}

if ! command -v navori >/dev/null 2>&1; then
  plan_gate_no_verdict "binary-missing" \
    "[navori] BLOCKED by plan-gate: navori is not installed or not on PATH — install it before dispatching a planned implementer." \
    "[navori] plan-gate could not check the workplan: navori is not on PATH, so there is no verdict. Approve to dispatch the implementer WITHOUT the plan gate, or deny and install navori. If you are an agent, report this to the user and wait."
fi

printf '%s' "$payload" | navori plan gate
navori_exit=$?
case "$navori_exit" in
  0) exit 0 ;;
  2)
    navori_audit_verdict="block"
    navori_audit_reason="plan-denied"
    exit 2
    ;;
  *)
    plan_gate_no_verdict "subcommand-unavailable" \
      "[navori] BLOCKED by plan-gate: this navori build has no working 'plan' subcommand (exit $navori_exit) — update navori (or run 'navori render --apply' after updating) before dispatching a planned implementer." \
      "[navori] plan-gate could not check the workplan: this navori build has no working 'plan' subcommand (exit $navori_exit), so there is no verdict. Approve to dispatch the implementer WITHOUT the plan gate, or deny and update navori. If you are an agent, report this to the user and wait."
    ;;
esac
# navori:managed end id="plan-gate-base"
