# navori:managed start id="precompact-session-summary-base" hash="652f5d0d" version="0.5.1" source="@navori/core"
#!/usr/bin/env bash
#
# PreCompact lifecycle hook — session-summary reminder.
# Fires just before Claude Code compacts the conversation (manual `/compact` or
# automatic). Compaction summarizes and drops turn-by-turn detail, so anything
# not persisted durably (decisions, root-caused bugs, conventions) is at risk of
# being lost. This hook injects a reminder to persist a session summary before
# that detail is gone.
#
# DESIGN — advisory, never blocking. A shell hook can't itself run the model's
# memory tool — that's the model's action — so this hook is honest about its
# limit: it INJECTS a reminder via `hookSpecificOutput.additionalContext` (the
# same channel session-start uses) and lets the model act on it. It never returns
# `decision: block`, so it never stalls compaction. The reminder points at the
# engram session-summary tool when available, and falls back to a plain "jot key
# decisions into progress/current.md" so it's still useful in a repo without
# engram. It deliberately does NOT spell out engram's exact tool token verbatim —
# that token is a doctor invariant the engram plugin owns; naming it here would
# let a hook mask a gutted guidance block from `doctor`.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

cat >/dev/null 2>&1 || true   # drain the PreCompact JSON on stdin (unused)

ctx="A punto de compactar el contexto: el detalle turno-a-turno se resumirá. Antes de perderlo, persiste un resumen de sesión con tu herramienta de memoria (engram: guarda el resumen de sesión) y/o anota las decisiones y los bugs con causa raíz de esta sesión en progress/current.md."

# Emit additionalContext safely: node (best escaping) → jq → give up (exit 0).
if command -v node >/dev/null 2>&1; then
  CTX="$ctx" node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"PreCompact",additionalContext:process.env.CTX}}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg ctx "$ctx" '{hookSpecificOutput:{hookEventName:"PreCompact",additionalContext:$ctx}}'
fi
exit 0
# navori:managed end id="precompact-session-summary-base"
