# navori:managed start id="qg-pre-commit-base" hash="6ab996fa" version="0.6.0" source="@navori/core"
#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit.
#
# It does NOT verify the reviewer's content receipt. That backstop lived here
# until #365 and was removed on purpose: five fail-open paths (worktree, Codex
# workspace, zsh word-splitting, non-ASCII paths, a truncated singleton receipt)
# against zero documented catches, and one of its failure modes blocked every
# PR in the repo. The receipt is a handoff between the `reviewer` and the
# `commit-pr-pilot`, which verifies it agent-side and re-signs the delta. Don't
# re-add the check here without a captured case it would have caught.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Extract .tool_input.command
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap. No command
# extracted → empty $cmd, and each caller decides what that means (the gate
# scripts scan defensively; guard-destructive waves the command through).
payload=$(cat)
extract_cmd() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r '.tool_input.command // empty' 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";process.stdin.on("data",c=>s+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(s)?.tool_input?.command??""))}catch{}})' 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p'
}
cmd=$(extract_cmd)

# Detect the project's REAL package manager from lockfiles / package.json, so a
# gate command hardcoded to one PM (e.g. `pnpm run ...`) can still run in a repo
# that actually uses another (e.g. bun). Mirrors lib/detect.ts precedence:
# `packageManager` field first, then pnpm/bun/yarn/npm lockfiles. Prints the PM
# name (or nothing) on stdout. Git runs hooks from the repo root, so relative
# paths resolve against the project root.
detect_pm() {
  if [ -f package.json ]; then
    pm=$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"\([a-z]*\)@.*/\1/p' package.json | head -n1)
    case "$pm" in pnpm|npm|yarn|bun) printf '%s' "$pm"; return 0 ;; esac
  fi
  if [ -f pnpm-lock.yaml ]; then printf 'pnpm'; return 0; fi
  if [ -f bun.lockb ] || [ -f bun.lock ]; then printf 'bun'; return 0; fi
  if [ -f yarn.lock ]; then printf 'yarn'; return 0; fi
  if [ -f package-lock.json ]; then printf 'npm'; return 0; fi
  return 0
}

# True when the argument is a JS package manager (so we only try to remap the
# leading token of the gate command when it's actually a PM, not `make`/`ruff`).
is_pm() {
  case "$1" in pnpm|npm|yarn|bun) return 0 ;; *) return 1 ;; esac
}

run_gate() {
  echo "[navori] running quality-gate fast: $1" >&2
  eval "$1" || {
    echo "[navori] quality-gate fast failed. Commit aborted." >&2
    exit 2
  }
}

# Gate to `git commit` only. $TRIGGER_RE is consumed by the shared detector
# inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Shared gate detector — inlined into each hook at render time (see the include
# directive in the source scripts + lib/hook-includes.ts). The caller MUST set
# $TRIGGER_RE (an ERE) before the include; it decides which git ops this hook
# gates. Single source of truth for the FIX B/C wrapper-peeling logic; DO NOT
# copy this body into a hook by hand.
#
# Detect whether $1 (a possibly-compound command) invokes a gated operation.
# Splits $1 on the shell separators && || ; | and newlines, strips leading
# whitespace plus wrapper words (`(`, `\`, `command `) and `VAR=value` env
# prefixes from each segment, and returns 0 if ANY segment STARTS with a gated
# `git …` invocation on a word boundary (matched by $TRIGGER_RE). Replaces
# literal-prefix `case` matching, which silently skipped the gate for
# `cd x && git commit`, `echo y; git push`, or a leading space (#88: NEVER skip
# the gate silently). Matching a segment START means a quoted `echo "git commit"`
# does NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`,
# or obfuscation — a seatbelt, not a sandbox.
is_scan_trigger() {
  local input="$1" segment
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$'\n'}"
  input="${input//||/$'\n'}"
  input="${input//;/$'\n'}"
  input="${input//|/$'\n'}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). $TRIGGER_RE's trailing boundary
    # keeps `git commitgraph` / `git config …` from matching.
    if printf '%s' "$segment" | grep -qE "$TRIGGER_RE"; then
      return 0
    fi
  done <<< "$input"
  return 1
}

if is_scan_trigger "$cmd"; then
  # Pin the cwd to the repo root before anything below runs. Claude Code fires
  # PreToolUse hooks from the session's persistent cwd, which is NOT always the
  # repo root — but the gate command and the lockfile-based PM detection both
  # assume the root. A relative gate (`cd packages/cli &&
  # pnpm lint`) otherwise fails with "No such file or directory" from a subdir.
  # Prefer $CLAUDE_PROJECT_DIR; fall back to the git top-level. When neither
  # resolves (not a git repo, no env), the substitution is empty and `cd ""`
  # is a no-op, so behavior outside a repo is unchanged. #309
  cd "${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}" || exit 2
  # qualityGate.fast is shell-quoted at render time via the shq: marker (#197).
  # The gate string is still `eval`'d by run_gate below (running the gate is the
  # feature), but quoting it here means a hostile qualityGate.fast survives as one
  # literal token instead of injecting commands at variable-assignment time.
  gate='cd packages/cli && pnpm lint'
  gate_bin="${gate%% *}"
  if command -v "$gate_bin" >/dev/null 2>&1; then
    run_gate "$gate"
  else
    # The declared runner isn't on PATH. If it's a package manager, detect the
    # repo's real one from lockfiles and retry through it (a `pnpm run x` gate
    # still runs in a bun-only checkout). #88: NEVER skip the gate silently —
    # when nothing can run it, BLOCK the commit loudly instead of the old
    # `exit 0` that handed a contributor zero quality gate without a word.
    detected_pm="$(detect_pm)"
    if is_pm "$gate_bin" && [ -n "$detected_pm" ] && [ "$detected_pm" != "$gate_bin" ] && command -v "$detected_pm" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' is not on PATH; using the lockfile-detected package manager: '$detected_pm'." >&2
      run_gate "$detected_pm ${gate#* }"
    else
      echo "[navori] quality-gate NOT run: '$gate_bin' is not on PATH and no alternative package manager was detected that could run it." >&2
      echo "[navori] Commit BLOCKED to avoid skipping the gate silently. Install '$gate_bin', or if you really want to skip it run the commit yourself outside the agent." >&2
      exit 2
    fi
  fi
fi
# navori:managed end id="qg-pre-commit-base"

# user: add extra checks here. `$cmd` is already parsed from the tool input.
# Example:
#
#   case "$cmd" in
#     'git push'*)
#       bash .claude/scripts/check-jscpd.sh || exit 2
#       ;;
#   esac
