# navori:managed start id="routing-watch-base" hash="a4ec6834" version="0.8.5" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse routing watcher (spec 0020).
#
# WHY THIS EXISTS. The routing ladder ships as CLAUDE.md context, and the host's
# own documentation says what that buys: "Claude treats them as context, NOT
# enforced configuration... If the instruction is something that must run at a
# specific point, write it as a hook instead." Measured over 48 audited
# sessions, 21 crossed the delegation threshold of the day and 12 of those (57%) delegated nothing
# — including a session in this very repo that wrote 26 files with zero
# subagents while carrying the ladder in its context. Prose was not the missing
# piece; a mechanism at the moment of the decision is.
#
# WHAT IT DOES, and what it deliberately does NOT. It counts the distinct files
# written in a session, and the first time that count reaches the threshold with
# no subagent yet invoked it hands the model ONE advisory note through
# `hookSpecificOutput.additionalContext`. It never blocks: a `PreToolUse` deny
# could stop the fifth edit until something is delegated, and was rejected on
# two measured grounds — sometimes inline IS correct (an operator can forbid
# delegation outright, and a block would leave that session with no way out),
# and a mechanism that gets ignored erodes the authority of the ones that are
# obeyed. The note turns an invisible decision into an explicit one; that is the
# gap, not a prohibition.
#
# WHY `PostToolUse` AND NOT `UserPromptSubmit`. The threshold is crossed by an
# EDIT, not by a prompt. This fires immediately after the edit that crosses it,
# which is the moment of the decision; `UserPromptSubmit` fires before the model
# has done anything that turn, i.e. at the wrong time.
#
# WHY THE THRESHOLD IS STILL "4 DISTINCT FILES". It was the objective half of a
# routing rule that has since been withdrawn — the ladder it belonged to had its
# threshold written in seven places that did not agree, so it was collapsed to a
# single route: every change to source goes through implementer -> reviewer.
#
# Under one route the honest threshold is ONE file, not four. It is deliberately
# NOT lowered yet: this hook counts `tool_input.file_path` without filtering it
# against the repo, so a scratch script under /tmp counts like source, and at a
# threshold of one that would fire on nearly every session. Both are fixed
# together when the ruling returns. Meanwhile 4-and-no-delegation still catches
# the worst deviations and stays quiet on the rest, which is the right way for a
# stale threshold to fail.
#
# WHY IT DOES NOT TRY TO TELL THE MAIN THREAD FROM A SUBAGENT — this is what
# keeps the script small. The condition is "N files AND zero delegation": if a
# subagent wrote something, then delegation happened, and the condition is
# already false by its second half. Over-counting is harmless by construction.
# It matters because the `PostToolUse` payload carries NO agent identifier (the
# `agentId` the audit log writes is really the `cwd`), so the alternative would
# have been an invented heuristic.
#
# FAIL-OPEN, ALWAYS. Every path exits 0, including "cannot read or write the
# stamp" (read-only FS, odd $HOME). A `PostToolUse` hook runs after tool calls
# all session long; failing loudly there is worse than not warning at all. Note
# the deliberate absence of `-e` in the `set` line below.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# Payload extraction (stdin → `payload` + `payload_field`). Shared body, single
# source of truth: the jq → node → sed cascade exists because jq is NOT
# preinstalled on macOS, and four hand-synced copies of it is how #225/#261
# drifted. The partial defines `extract_cmd` but does NOT call it: this hook
# never reads `tool_input.command`, and a spawn it cannot use would be charged to
# every tool call in every session.
#
# ORDER BELOW IS A COST DECISION, and these are the counts it buys. Every
# `payload_field` call may spawn a process, so nothing is read before the field
# that can end the run:
#   1 spawn  — any tool that is not Edit/Write/NotebookEdit/Agent: `tool_name`
#              alone, and the discard `case` exits.
#   2 spawns — a session already `#delegated` or `#notified`: + `session_id`,
#              which is what names the stamp, and the stamp check exits.
#   4 spawns — an edit that actually counts: + `agent_id` (the subagent guard
#              below) + the file path.
# The discard `case` therefore comes BEFORE `session_id`: a tool this hook does
# not care about must not pay to locate a stamp it will never open.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.

# R5 (spec 0020): the notice has to be COUNTABLE, not just visible. A hook is
# invisible to the transcript unless it blocks or injects, and this one injects
# exactly once per session — so without a record in the audit log there is no
# way to ask "how often did the ladder actually fire, and did delegation follow?"
# That question is the whole success criterion of the spec, and #623 is the
# standing proof that "the hook emitted it" and "the model got it" are different
# claims: the log is what lets the transcript be read back against the emission.
#
# ONLY the notify path records. This hook fires on every write tool of every
# session; recording each firing would bloat the log with the one verdict nobody
# asked about. One line per session, on the event that matters.
navori_audit_name="routing-watch"
navori_audit_phase="PostToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# Same reason as in `managed-drift-watch`: a raw, unexpanded copy of this asset
# must degrade to silence, never to exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", .agent_id // .subagent_id // ""] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_agent=${navori_audit_rest#*
}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  navori_audit_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || navori_audit_ts=""
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg ts "$navori_audit_ts" \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    '{ts:$ts,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# See the header for why this is still 4 and not 1. Changing this number changes when
# the note fires and nothing else.
threshold=4

tool=$(payload_field tool_name)
[ -n "$tool" ] || exit 0
navori_audit_tool=$tool

# The cheap discriminator, and the only thing read so far. Anything this hook has
# no business with leaves here, having spawned exactly once.
case "$tool" in
  Agent | Task | Edit | Write | NotebookEdit) ;;
  *) exit 0 ;;
esac

# One stamp per session, so two concurrent sessions never overwrite each other's
# count. Sanitised because the value lands in a path: anything that is not a
# plain identifier character is dropped rather than escaped.
sid=$(payload_field session_id | tr -cd 'A-Za-z0-9._-')
[ -n "$sid" ] || sid="unknown-session"

stamp_dir=".claude/.routing-watch"
stamp="$stamp_dir/$sid"

# Append a line unless it is already there. Silent on every failure: a stamp
# that cannot be written means no note, never an error.
mark() {
  mkdir -p "$stamp_dir" 2>/dev/null || return 0
  # First write of THIS session's stamp: sweep siblings older than 7 days.
  # One `find` over a tiny dir, once per session — without it the directory
  # grows by one file per session forever (no SessionEnd hook owns it). Age,
  # not session-end, on purpose: `--resume` reuses the session id, and a
  # delete-on-end would re-arm the once-per-session notice on every resume.
  [ -e "$stamp" ] || find "$stamp_dir" -type f -mtime +7 -delete 2>/dev/null || true
  grep -q -F -x "$1" "$stamp" 2>/dev/null && return 0
  printf '%s\n' "$1" >> "$stamp" 2>/dev/null || true
}

case "$tool" in
  # Delegation happened. `Agent` is the name this host gives the subagent tool
  # (the same string `lib/audit/parse.ts` filters transcripts by); `Task` is
  # accepted too so a rename does not silently turn the detector off.
  Agent | Task)
    mark "#delegated"
    exit 0
    ;;
esac

# Delegated, or already warned: there is nothing left to decide this session.
# This is also the guarantee behind "at most once" — the stamp survives a
# compaction, so a note that scrolled out of context is NOT re-emitted.
# Repeating is what turns a signal into noise.
grep -q -E '^#(delegated|notified)$' "$stamp" 2>/dev/null && exit 0

# Hooks run INSIDE subagents too — the host fires the same PostToolUse for a
# subagent's tool calls, adding `agent_id` to the payload (empty in the main
# conversation). And the `#delegated` mark from the `Agent` case above only
# lands when that tool RETURNS, i.e. after the subagent already finished. So
# without this check a delegated implementer's own 4th edit would fire the
# notice INTO THE SUBAGENT'S context — "no subagent has been invoked" is false
# there, the advice is unactionable there (no Agent tool in its allowlist) —
# and would burn the once-per-session note before the orchestrator could ever
# receive it. An edit arriving from inside a subagent IS proof of delegation,
# so it is recorded as exactly that.
agent=$(payload_field agent_id)
if [ -n "$agent" ]; then
  mark "#delegated"
  exit 0
fi

file=$(payload_field tool_input.file_path)
# NotebookEdit has carried its target under `notebook_path` in some host
# versions; without this the tool would contribute nothing and never say so.
[ -n "$file" ] || file=$(payload_field tool_input.notebook_path)
[ -n "$file" ] || exit 0

mark "path:$file"

count=$(grep -c '^path:' "$stamp" 2>/dev/null) || count=0
[ "${count:-0}" -ge "$threshold" ] 2>/dev/null || exit 0

mark "#notified"
navori_audit_log "notify" "$count archivos del hilo principal, sin subagente"

# Written with no `"` and no `\` on purpose: that is what makes the JSON
# escaping below exact without a JSON encoder (see the awk join).
notice=$(cat <<MSG
navori: routing check. ${count} distinct files written in this session, and no subagent has been invoked.

Every change to source goes through 1 focused implementer (explicit scope) then 1 reviewer — there is no inline route and no file count that exempts one.

If inline IS the right call here (the operator ruled delegation out, the edits are one mechanical change, the context is already paid for), say so explicitly in your next message and carry on. The point of this note is that the override stops being silent - today it leaves no trace at all.

Advisory only: nothing was blocked, and this fires at most once per session.
MSG
)

# JSON-escape by joining the lines with a literal backslash-n. Exact because the
# text above is a fixed literal free of quotes and backslashes; a payload from
# outside would need a real encoder.
escaped=$(printf '%s\n' "$notice" | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }')
printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"%s"}}\n' "$escaped"

# The last word of the script, and the contract of the whole file: advisory.
exit 0
# navori:managed end id="routing-watch-base"
