# navori:managed start id="subagent-stop-handoff-base" hash="02ce447e" version="0.6.2" source="@navori/core"
#!/usr/bin/env bash
#
# SubagentStop lifecycle hook — handoff validator.
# Fires when a subagent finishes. The harness contract is that an implementer
# closes with `impl_<feature>.md` and a reviewer with `review_<feature>.md`
# under the engine's progress dir — those files ARE the handoff the leader (and the
# commit-pr-pilot) read. A subagent that returns having left an empty or
# structurally-broken handoff silently corrupts that chain. This hook catches
# the obvious failure modes deterministically.
#
# DESIGN — advisory, never blocking. Emits a user-facing `systemMessage` only;
# it NEVER returns `decision: block`. It has no way to know WHICH subagent just
# stopped (agent identity isn't reliably in scope for a shell hook), so it can't
# demand a specific file — it only flags handoff files that already exist but
# look broken:
#   - empty / whitespace-only, OR
#   - `impl_*.md` missing its terminal `Status:` marker, OR
#   - `review_*.md` missing a verdict (APPROVED / CHANGES_REQUESTED).
# It never invents an expectation, so a legitimate report never trips it, and a
# missing file is not flagged (a subagent may not produce a handoff at all).
# Accepted limitation: during parallel work a still-in-flight report from
# ANOTHER running subagent could momentarily look incomplete — advisory-only, so
# a false positive is a harmless note, never a block.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

cat >/dev/null 2>&1 || true   # drain the SubagentStop JSON on stdin (unused)

# Resolve the progress dirs. `placeHook` copies this body VERBATIM for every
# engine — it is never retargeted the way prose assets are (#389) — so the hook
# has to know every engine's path itself or it silently no-ops there: under
# Codex the handoff lives in `.codex/progress/` (what `compat.ts` rewrites
# `.claude/progress/` into), and this loop used to stop at two names it would
# never find. Bare `progress/` stays as the fallback for a repo that relocates
# it. (Literals, not interpolated: `progress.dir` isn't exposed to the render
# interpolator — same choice as session-start-context.sh.)
#
# EVERY existing dir is scanned, not the first one found: a repo that renders
# both engines has both, and picking one by probe order would make the hook
# blind to whichever engine happens to come second. An ARRAY, never an unquoted
# string: word-splitting a `$dirs` string is a no-op under zsh, which is how the
# receipt backstop silently stopped scanning (#344).
dirs=()
for d in ".claude/progress" ".codex/progress" "progress"; do
  [ -d "$d" ] && dirs+=("$d")
done
[ ${#dirs[@]} -gt 0 ] || exit 0

# Is a file empty or whitespace-only?
is_blank() { ! grep -q '[^[:space:]]' "$1" 2>/dev/null; }

problems=""
note() { problems="${problems}${problems:+; }$1"; }

# nullglob, so an absent report class yields zero iterations instead of a
# literal pattern (bash) or a hard "no matches found" abort (zsh, which also
# has no `shopt` — under `set -e` that unknown command killed the whole hook
# there, #391). Each shell spells the option its own way.
if [ -n "${ZSH_VERSION:-}" ]; then setopt NULL_GLOB; else shopt -s nullglob; fi
# Reports are named by their PATH, not their basename: with more than one
# progress dir in play, `impl_x.md` alone wouldn't say which one to open.
for dir in "${dirs[@]}"; do
  for f in "$dir"/impl_*.md; do
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qiE '^\*{0,2}status:?\*{0,2}' "$f" 2>/dev/null; then
      note "$f sin línea 'Status:'"
    fi
  done
  for f in "$dir"/review_*.md; do
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qE 'APPROVED|CHANGES_REQUESTED' "$f" 2>/dev/null; then
      note "$f sin veredicto (APPROVED/CHANGES_REQUESTED)"
    fi
  done
done

[ -n "$problems" ] || exit 0

msg="navori: handoff(s) de subagente incompletos — ${problems}. Revisa que el reporte quedó bien escrito antes de consolidarlo."

if command -v node >/dev/null 2>&1; then
  MSG="$msg" node -e 'process.stdout.write(JSON.stringify({systemMessage:process.env.MSG}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg m "$msg" '{systemMessage:$m}'
fi
exit 0
# navori:managed end id="subagent-stop-handoff-base"
