# navori:managed start id="subagent-stop-handoff-base" hash="3b7346ed" version="0.4.2" source="@navori/core"
#!/usr/bin/env bash
#
# SubagentStop lifecycle hook — handoff validator.
# Fires when a subagent finishes. The harness contract is that an implementer
# closes with `impl_<feature>.md` and a reviewer with `review_<feature>.md`
# under `.claude/progress/` — those files ARE the handoff the leader (and the
# commit-pr-pilot) read. A subagent that returns having left an empty or
# structurally-broken handoff silently corrupts that chain. This hook catches
# the obvious failure modes deterministically.
#
# DESIGN — advisory, never blocking. Emits a user-facing `systemMessage` only;
# it NEVER returns `decision: block`. It has no way to know WHICH subagent just
# stopped (agent identity isn't reliably in scope for a shell hook), so it can't
# demand a specific file — it only flags handoff files that already exist but
# look broken:
#   - empty / whitespace-only, OR
#   - `impl_*.md` missing its terminal `Status:` marker, OR
#   - `review_*.md` missing a verdict (APPROVED / CHANGES_REQUESTED).
# It never invents an expectation, so a legitimate report never trips it, and a
# missing file is not flagged (a subagent may not produce a handoff at all).
# Accepted limitation: during parallel work a still-in-flight report from
# ANOTHER running subagent could momentarily look incomplete — advisory-only, so
# a false positive is a harmless note, never a block.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

cat >/dev/null 2>&1 || true   # drain the SubagentStop JSON on stdin (unused)

# Resolve the progress dir. Default is `.claude/progress/`; `progress/` is the
# fallback for repos that relocate it. (These are literal, not interpolated:
# progress.dir isn't exposed to the render interpolator and the default covers
# the overwhelming common case — same choice as session-start-context.sh.)
dir=""
for d in ".claude/progress" "progress"; do
  if [ -d "$d" ]; then dir="$d"; break; fi
done
[ -n "$dir" ] || exit 0

# Is a file empty or whitespace-only?
is_blank() { ! grep -q '[^[:space:]]' "$1" 2>/dev/null; }

problems=""
note() { problems="${problems}${problems:+; }$1"; }

shopt -s nullglob
for f in "$dir"/impl_*.md; do
  if is_blank "$f"; then
    note "$(basename "$f") vacío"
  elif ! grep -qiE '^\*{0,2}status:?\*{0,2}' "$f" 2>/dev/null; then
    note "$(basename "$f") sin línea 'Status:'"
  fi
done
for f in "$dir"/review_*.md; do
  if is_blank "$f"; then
    note "$(basename "$f") vacío"
  elif ! grep -qE 'APPROVED|CHANGES_REQUESTED' "$f" 2>/dev/null; then
    note "$(basename "$f") sin veredicto (APPROVED/CHANGES_REQUESTED)"
  fi
done
shopt -u nullglob

[ -n "$problems" ] || exit 0

msg="navori: handoff(s) de subagente incompletos en ${dir}/ — ${problems}. Revisa que el reporte quedó bien escrito antes de consolidarlo."

if command -v node >/dev/null 2>&1; then
  MSG="$msg" node -e 'process.stdout.write(JSON.stringify({systemMessage:process.env.MSG}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg m "$msg" '{systemMessage:$m}'
fi
exit 0
# navori:managed end id="subagent-stop-handoff-base"
