# navori:managed start id="subagent-stop-handoff-base" hash="000c826d" version="0.6.4" source="@navori/core"
#!/usr/bin/env bash
#
# SubagentStop lifecycle hook — handoff validator.
# Fires when a subagent finishes. The harness contract is that an implementer
# closes with `impl_<feature>.md` and a reviewer with `review_<feature>.md`
# under the engine's progress dir — those files ARE the handoff the leader (and the
# commit-pr-pilot) read. A subagent that returns having left an empty or
# structurally-broken handoff silently corrupts that chain. This hook catches
# the obvious failure modes deterministically.
#
# DESIGN — advisory, never blocking. Emits a user-facing `systemMessage` only;
# it NEVER returns `decision: block`. It has no way to know WHICH subagent just
# stopped (agent identity isn't reliably in scope for a shell hook), so it can't
# demand a specific file — it only flags handoff files that already exist but
# look broken:
#   - empty / whitespace-only, OR
#   - `impl_*.md` missing its terminal `Status:` marker, OR
#   - `review_*.md` missing a verdict (APPROVED / CHANGES_REQUESTED).
# It never invents an expectation, so a legitimate report never trips it, and a
# missing file is not flagged (a subagent may not produce a handoff at all).
# Accepted limitation: during parallel work a still-in-flight report from
# ANOTHER running subagent could momentarily look incomplete — advisory-only, so
# a false positive is a harmless note, never a block.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

# The payload was drained and discarded here; it is kept now because the audit
# recorder reads `session_id`/`cwd` out of it. Draining is still the point: an
# undrained stdin can leave the host writing into a closed pipe.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="subagent-stop-handoff"
navori_audit_phase="SubagentStop"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock. Called once, right after the payload is read.
navori_audit_begin() {
  # Milliseconds since epoch, portable: GNU date has %s%3N, BSD/macOS date does
  # not. `perl` is present on every macOS and virtually every Linux; when it is
  # missing the clock degrades to seconds*1000 rather than disabling the record.
  navori_audit_t0=$(perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null) \
    || navori_audit_t0=$(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  navori_audit_session=$(printf '%s' "${payload:-}" | jq -r '.session_id // ""' 2>/dev/null) || return 0
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  navori_audit_cwd=$(printf '%s' "${payload:-}" | jq -r '.cwd // ""' 2>/dev/null) || return 0
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  if [ -n "${NAVORI_AUDITS_ROOT:-}" ]; then
    navori_audit_root=$NAVORI_AUDITS_ROOT
  else
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # THE no-op that keeps audit-mode free: one stat when the mode is off, which
  # is every session that never opted in. Also the writability check — a log
  # that cannot be appended to is not an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  navori_audit_now=$(perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null) \
    || navori_audit_now=$(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
  navori_audit_ms=$(( navori_audit_now - ${navori_audit_t0:-$navori_audit_now} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  navori_audit_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || navori_audit_ts=""
  # The agent id is what lets the report attribute a hook to a subagent WITHOUT
  # guessing: with agents running in parallel their time windows overlap, so
  # attribution by timestamp is the fallback, not the primary route.
  navori_audit_agent=$(printf '%s' "${payload:-}" | jq -r '.agent_id // .subagent_id // ""' 2>/dev/null) || navori_audit_agent=""

  printf '%s\n' "$(jq -cn \
    --arg ts "$navori_audit_ts" \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    '{ts:$ts,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


# Resolve the progress dirs. `placeHook` copies this body VERBATIM for every
# engine — it is never retargeted the way prose assets are (#389) — so the hook
# has to know every engine's path itself or it silently no-ops there: under
# Codex the handoff lives in `.codex/progress/` (what `compat.ts` rewrites
# `.claude/progress/` into), and this loop used to stop at two names it would
# never find. Bare `progress/` stays as the fallback for a repo that relocates
# it. (Literals, not interpolated: `progress.dir` isn't exposed to the render
# interpolator — same choice as session-start-context.sh.)
#
# EVERY existing dir is scanned, not the first one found: a repo that renders
# both engines has both, and picking one by probe order would make the hook
# blind to whichever engine happens to come second. An ARRAY, never an unquoted
# string: word-splitting a `$dirs` string is a no-op under zsh, which is how the
# receipt backstop silently stopped scanning (#344).
dirs=()
for d in ".claude/progress" ".codex/progress" "progress"; do
  [ -d "$d" ] && dirs+=("$d")
done
[ ${#dirs[@]} -gt 0 ] || exit 0

# Is a file empty or whitespace-only?
is_blank() { ! grep -q '[^[:space:]]' "$1" 2>/dev/null; }

problems=""
note() { problems="${problems}${problems:+; }$1"; }

# nullglob, so an absent report class yields zero iterations instead of a
# literal pattern (bash) or a hard "no matches found" abort (zsh, which also
# has no `shopt` — under `set -e` that unknown command killed the whole hook
# there, #391). Each shell spells the option its own way.
if [ -n "${ZSH_VERSION:-}" ]; then setopt NULL_GLOB; else shopt -s nullglob; fi
# Reports are named by their PATH, not their basename: with more than one
# progress dir in play, `impl_x.md` alone wouldn't say which one to open.
for dir in "${dirs[@]}"; do
  for f in "$dir"/impl_*.md; do
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qiE '^\*{0,2}status:?\*{0,2}' "$f" 2>/dev/null; then
      note "$f sin línea 'Status:'"
    fi
  done
  for f in "$dir"/review_*.md; do
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qE 'APPROVED|CHANGES_REQUESTED' "$f" 2>/dev/null; then
      note "$f sin veredicto (APPROVED/CHANGES_REQUESTED)"
    fi
  done
done

# `clean` vs `dirty` is the whole value of recording this hook: it is the only
# evidence that the handoff check RAN and found nothing, as opposed to never
# having run at all.
if [ -z "$problems" ]; then
  navori_audit_verdict="clean"
  exit 0
fi

msg="navori: handoff(s) de subagente incompletos — ${problems}. Revisa que el reporte quedó bien escrito antes de consolidarlo."

if command -v node >/dev/null 2>&1; then
  MSG="$msg" node -e 'process.stdout.write(JSON.stringify({systemMessage:process.env.MSG}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg m "$msg" '{systemMessage:$m}'
fi
navori_audit_verdict="dirty"
navori_audit_reason="$problems"
exit 0
# navori:managed end id="subagent-stop-handoff-base"
