# navori:managed start id="worktree-reclaim-base" hash="daf81822" version="0.11.3" source="@navori/core"
#!/usr/bin/env bash
# navori — worktree reclaim (SessionEnd) — #527
#
# Agent worktrees accumulate a FULL CHECKOUT each and nobody reclaims them: a
# cleanup in this repo found 27 of them, ~2.6 GB, three carrying unpushed
# branches. Until now the only path was manual — `publisher` ends its
# report with a `worktree:` line, the orchestrator reads it and asks the user —
# so a session that got cut short, an agent that died mid-cycle, or an
# orchestrator that simply never reached that line left the checkout forever.
# Cleanup that depends on an agent REMEMBERING is the failure mode the rest of
# the harness keeps closing.
#
# WHY SessionEnd and not SubagentStop: when a subagent stops, its PR usually
# does not exist yet, so nothing could prove the work survived. At session end
# the answer is knowable. It also batches: one sweep instead of one check per
# agent.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# THE BAR FOR DELETING. A worktree holding uncommitted or unpushed work is the
# ONLY copy of it, so this removes one only when all three hold:
#   1. `git status --porcelain` is empty — nothing uncommitted, untracked
#      included.
#   2. The branch has an upstream and nothing ahead of it — nothing unpushed.
#   3. Its PR is MERGED, according to `gh`.
#
# On (3): this repo squash-merges, so the branch SHA is never an ancestor of the
# base and `git merge-base --is-ancestor` answers "not merged" for branches that
# shipped days ago. A hook trusting that would never delete anything (benign);
# one that inverted it would delete live work (not). `gh pr list --state merged`
# is the only cheap source of truth, so no `gh` means no deletions — the
# conservative direction on purpose.
#
# FAIL-OPEN ABSOLUTE: exit 0 on anything unexpected. This is cleanup, and
# cleanup must never be the reason a session reports a failure.

set +e

payload=$(cat 2>/dev/null)
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Spec 0035 D2/D6: nv_project_dir is the Codex-aware fallback below ($PWD is
# already correct when the payload's own `.cwd` resolves, which is the common
# case on both engines).
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent a spawn call TARGETS, never the one that makes the call (spec 0041
# H16). Claude: `tool_input.subagent_type`. Codex PreToolUse/PostToolUse of a
# spawn: `tool_input.agent_type` only — the top-level `agent_type` there is the
# CALLER's. On `SubagentStop` the top-level `agent_type` IS the finishing
# subagent, so that event reads it instead.
nv_spawn_target_type() {
  if [ "$nv_engine" = codex ]; then
    case "$(payload_field hook_event_name)" in
      SubagentStop) payload_field agent_type ;;
      *) payload_field tool_input.agent_type ;;
    esac
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent RUNNING the current event: the top-level `agent_type`, which the
# host adds only inside a subagent (empty on the main thread). Never confuse it
# with `nv_spawn_target_type` (H16). `nv_subagent_type` above keeps its legacy
# mixed behaviour for existing hooks; new code uses these two helpers.
nv_event_agent_type() {
  payload_field agent_type
}

# True for the spawn tool: Codex V1 `spawn_agent`, or any V2 name that ends in
# `spawn_agent` (V2 flattens the namespace into the tool name).
nv_is_spawn_tool() {
  case "$(payload_field tool_name)" in
    *spawn_agent) return 0 ;;
    *) return 1 ;;
  esac
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.

navori_audit_name="worktree-reclaim"
navori_audit_phase="SessionEnd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable","native-hook"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


cwd=""
if [ -n "$payload" ] && command -v jq >/dev/null 2>&1; then
  cwd=$(printf '%s' "$payload" | jq -r '.cwd // ""' 2>/dev/null)
fi
[ -n "$cwd" ] || cwd=${nv_project_dir:-$PWD}
cd "$cwd" 2>/dev/null || exit 0
# PHYSICAL path, symlinks resolved. `git worktree list` always prints the real
# path, while the payload's `cwd` carries whatever the caller had — and on macOS
# that is routinely the symlinked form (`/var/...` for `/private/var/...`,
# `/tmp/...` for `/private/tmp/...`). Comparing the two forms never matches, so
# the sweep below would find nothing and exit 0: inoperative, and silent about
# it. Any repo living under a symlinked path hits this, not just temp dirs.
cwd=$(pwd -P 2>/dev/null) || exit 0

command -v git >/dev/null 2>&1 || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0
# The main checkout is where the sweep belongs: a worktree cannot remove itself.
[ "$(git rev-parse --git-dir 2>/dev/null)" = "$(git rev-parse --git-common-dir 2>/dev/null)" ] || exit 0

wt_root="$cwd/.claude/worktrees"
[ -d "$wt_root" ] || exit 0

removed=""
kept=""

# ─── The merged-PR answer, in ONE network call for the whole sweep (#774).
#
# This used to be `gh pr list --head "$branch"` INSIDE the loop: one round trip
# per worktree. Measured it was cheap (mean 240 ms, max 2,265 ms, n=48), but
# SessionEnd hooks share a budget — "the overall budget is automatically raised
# to the highest per-hook timeout configured", so audit-close (10s) and this
# hook (30s) get 30s TOTAL, not 40 — and the scenario this hook exists for is
# the 27-worktree cleanup that motivated #527. At ~1s each that sweep dies
# halfway through, with no signal that it did.
#
# CEILING: the `--limit` most recently merged PRs. A branch whose PR merged
# further back than that simply gets KEPT — the same conservative direction the
# hook already takes when `gh` cannot answer at all, never a wrong deletion.
# TODO(scale): page or fall back to a per-branch query if a repo routinely
# holds worktrees whose PR merged more than NAVORI_MERGED_PR_LIMIT PRs ago.
NAVORI_MERGED_PR_LIMIT=${NAVORI_MERGED_PR_LIMIT:-100}
merged_prs=""
merged_prs_loaded=""

# Lazy: a sweep where every worktree is dirty or unpushed never reaches step
# (3), and must not pay a network call to discover that.
load_merged_prs() {
  [ -z "$merged_prs_loaded" ] || return 0
  merged_prs_loaded=1
  # `</dev/null` because this is called from inside the `while read` loop below,
  # which is fed by a heredoc on fd 0: a child that read stdin would swallow the
  # rest of the worktree list and the sweep would end early and silently.
  merged_prs=$(gh pr list --state merged --limit "$NAVORI_MERGED_PR_LIMIT" \
    --json number,headRefName --jq '.[] | "\(.headRefName) \(.number)"' \
    2>/dev/null </dev/null)
}

# The PR number for a branch, or empty. Branch names cannot contain spaces, so
# `read` splits the pair unambiguously; matching with `grep` would turn a branch
# name into a pattern, which is not a thing this hook gets to do.
merged_pr_for() {
  printf '%s\n' "$merged_prs" | while IFS=' ' read -r _mb _mn; do
    if [ "$_mb" = "$1" ]; then
      printf '%s' "$_mn"
      break
    fi
  done
}

# `git worktree list --porcelain` emits blank-line-separated records; only the
# ones under `.claude/worktrees/` are ours to touch. A worktree the user made
# themselves is not agent scratch and is never considered.
while IFS= read -r line; do
  case "$line" in
    "worktree "*) wt=${line#worktree } ;;
    *) continue ;;
  esac
  case "$wt" in
    "$wt_root"/*) ;;
    *) continue ;;
  esac
  [ -d "$wt" ] || continue

  branch=$(git -C "$wt" rev-parse --abbrev-ref HEAD 2>/dev/null)
  [ -n "$branch" ] && [ "$branch" != "HEAD" ] || { kept="${kept}
  ${wt} — detached HEAD, cannot tell what it holds"; continue; }

  # (1) uncommitted work, untracked files included.
  if [ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — uncommitted changes on '${branch}'"
    continue
  fi

  # (2) unpushed commits — or no upstream at all, which means the branch exists
  # nowhere else.
  if ! git -C "$wt" rev-parse --abbrev-ref "@{u}" >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — '${branch}' has no upstream (never pushed)"
    continue
  fi
  if [ -n "$(git -C "$wt" rev-list "@{u}..HEAD" 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — '${branch}' has commits not pushed"
    continue
  fi

  # (3) the PR merged. No gh, no answer, no deletion.
  if ! command -v gh >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — gh not available, cannot confirm '${branch}' merged"
    continue
  fi
  load_merged_prs
  merged=$(merged_pr_for "$branch")
  if [ -z "$merged" ]; then
    kept="${kept}
  ${wt} — no merged PR for '${branch}' among the last ${NAVORI_MERGED_PR_LIMIT} merged"
    continue
  fi

  # `git worktree remove`, never `rm -rf`: the latter leaves the entry in git's
  # index and the next `git worktree list` still reports a checkout that is gone.
  if git worktree remove "$wt" >/dev/null 2>&1; then
    removed="${removed}
  ${wt}  (${branch}, PR #${merged})"
  else
    kept="${kept}
  ${wt} — 'git worktree remove' refused it"
  fi
done <<EOF
$(git worktree list --porcelain 2>/dev/null)
EOF

[ -n "$removed" ] && git worktree prune >/dev/null 2>&1

# ─── Reporting, and what SessionEnd can actually deliver (#774).
#
# This block used to claim its stdout "goes to the transcript". It does not:
# "for most events, Claude Code writes stdout to the debug log and doesn't show
# it in the transcript", and SessionEnd is not one of the exceptions. Nor is
# there a JSON way around it — "SessionEnd hooks have no decision control…
# Claude Code discards their JSON output fields, such as `systemMessage`". So
# this hook has exactly one audience for prose, the debug log, and nothing it
# prints here reaches either the user or the model during the session.
#
# The `removed` line is fine there: the deletion already happened and the audit
# log records it. The KEPT line is not — "these hold work that exists nowhere
# else" is the half that protects live work, and it had no reader at all.
# It is persisted below instead, for the next SessionStart to re-emit.
if [ -n "$removed" ]; then
  printf 'navori: reclaimed agent worktrees (clean, pushed, PR merged):%s\n' "$removed"
fi
if [ -n "$kept" ]; then
  printf 'navori: agent worktrees KEPT — each holds work that exists nowhere else:%s\n' "$kept"
fi

# ─── Hand the KEPT notice to the next SessionStart (#774).
#
# Inside `.claude/worktrees/`, which every navori repo already gitignores (it is
# in EPHEMERAL_HARNESS_PATHS) and which must exist for this hook to have gotten
# this far — so the notice never shows up as an untracked file and needs no new
# ignore entry. `session-start-context.sh` reads it, injects it, and TRUNCATES
# it, so the warning is said once per sweep instead of on every startup forever.
#
# Truncated, never deleted, in both directions: this hook removes worktrees the
# user asked it to remove and nothing else, and a stamp file is not one of them.
# Rewritten unconditionally so a resolved situation clears the pending notice
# rather than leaving the next session a warning that is no longer true.
#
# The file carries the LIST and no prose: the sentence that frames it belongs to
# the reader, which is also the only side that knows the repo's language. This
# script is copied verbatim into every repo and never passes through the
# language layer (#422), so a wording baked in here would ship in one language
# to all of them.
kept_notice="$wt_root/.navori-kept-notice"
if [ -n "$kept" ]; then
  printf '%s\n' "$kept" >"$kept_notice" 2>/dev/null || true
elif [ -f "$kept_notice" ]; then
  : >"$kept_notice" 2>/dev/null || true
fi

# The verdict says what the sweep DID, which is what an audit needs to answer
# "where did the disk go": `noop` is the common case (no worktrees to sweep) and
# must stay distinguishable from a run that reclaimed or refused one.
if [ -n "$removed" ] || [ -n "$kept" ]; then
  navori_audit_verdict="clean"
  navori_audit_reason="reclamados:${removed:+ si} conservados:${kept:+ si}"
else
  navori_audit_verdict="noop"
fi
exit 0
# navori:managed end id="worktree-reclaim-base"
