# navori:managed start id="worktree-reclaim-base" hash="21328dfd" version="0.6.4" source="@navori/core"
#!/usr/bin/env bash
# navori — worktree reclaim (SessionEnd) — #527
#
# Agent worktrees accumulate a FULL CHECKOUT each and nobody reclaims them: a
# cleanup in this repo found 27 of them, ~2.6 GB, three carrying unpushed
# branches. Until now the only path was manual — `commit-pr-pilot` ends its
# report with a `worktree:` line, the orchestrator reads it and asks the user —
# so a session that got cut short, an agent that died mid-cycle, or an
# orchestrator that simply never reached that line left the checkout forever.
# Cleanup that depends on an agent REMEMBERING is the failure mode the rest of
# the harness keeps closing.
#
# WHY SessionEnd and not SubagentStop: when a subagent stops, its PR usually
# does not exist yet, so nothing could prove the work survived. At session end
# the answer is knowable. It also batches: one sweep instead of one check per
# agent.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# THE BAR FOR DELETING. A worktree holding uncommitted or unpushed work is the
# ONLY copy of it, so this removes one only when all three hold:
#   1. `git status --porcelain` is empty — nothing uncommitted, untracked
#      included.
#   2. The branch has an upstream and nothing ahead of it — nothing unpushed.
#   3. Its PR is MERGED, according to `gh`.
#
# On (3): this repo squash-merges, so the branch SHA is never an ancestor of the
# base and `git merge-base --is-ancestor` answers "not merged" for branches that
# shipped days ago. A hook trusting that would never delete anything (benign);
# one that inverted it would delete live work (not). `gh pr list --state merged`
# is the only cheap source of truth, so no `gh` means no deletions — the
# conservative direction on purpose.
#
# FAIL-OPEN ABSOLUTE: exit 0 on anything unexpected. This is cleanup, and
# cleanup must never be the reason a session reports a failure.

set +e

payload=$(cat 2>/dev/null)

navori_audit_name="worktree-reclaim"
navori_audit_phase="SessionEnd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", .agent_id // .subagent_id // ""] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_agent=${navori_audit_rest#*
}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  navori_audit_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || navori_audit_ts=""
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.

  printf '%s\n' "$(jq -cn \
    --arg ts "$navori_audit_ts" \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    '{ts:$ts,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


cwd=""
if [ -n "$payload" ] && command -v jq >/dev/null 2>&1; then
  cwd=$(printf '%s' "$payload" | jq -r '.cwd // ""' 2>/dev/null)
fi
[ -n "$cwd" ] || cwd=${CLAUDE_PROJECT_DIR:-$PWD}
cd "$cwd" 2>/dev/null || exit 0
# PHYSICAL path, symlinks resolved. `git worktree list` always prints the real
# path, while the payload's `cwd` carries whatever the caller had — and on macOS
# that is routinely the symlinked form (`/var/...` for `/private/var/...`,
# `/tmp/...` for `/private/tmp/...`). Comparing the two forms never matches, so
# the sweep below would find nothing and exit 0: inoperative, and silent about
# it. Any repo living under a symlinked path hits this, not just temp dirs.
cwd=$(pwd -P 2>/dev/null) || exit 0

command -v git >/dev/null 2>&1 || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0
# The main checkout is where the sweep belongs: a worktree cannot remove itself.
[ "$(git rev-parse --git-dir 2>/dev/null)" = "$(git rev-parse --git-common-dir 2>/dev/null)" ] || exit 0

wt_root="$cwd/.claude/worktrees"
[ -d "$wt_root" ] || exit 0

removed=""
kept=""

# `git worktree list --porcelain` emits blank-line-separated records; only the
# ones under `.claude/worktrees/` are ours to touch. A worktree the user made
# themselves is not agent scratch and is never considered.
while IFS= read -r line; do
  case "$line" in
    "worktree "*) wt=${line#worktree } ;;
    *) continue ;;
  esac
  case "$wt" in
    "$wt_root"/*) ;;
    *) continue ;;
  esac
  [ -d "$wt" ] || continue

  branch=$(git -C "$wt" rev-parse --abbrev-ref HEAD 2>/dev/null)
  [ -n "$branch" ] && [ "$branch" != "HEAD" ] || { kept="${kept}
  ${wt} — detached HEAD, cannot tell what it holds"; continue; }

  # (1) uncommitted work, untracked files included.
  if [ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — uncommitted changes on '${branch}'"
    continue
  fi

  # (2) unpushed commits — or no upstream at all, which means the branch exists
  # nowhere else.
  if ! git -C "$wt" rev-parse --abbrev-ref "@{u}" >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — '${branch}' has no upstream (never pushed)"
    continue
  fi
  if [ -n "$(git -C "$wt" rev-list "@{u}..HEAD" 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — '${branch}' has commits not pushed"
    continue
  fi

  # (3) the PR merged. No gh, no answer, no deletion.
  if ! command -v gh >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — gh not available, cannot confirm '${branch}' merged"
    continue
  fi
  merged=$(gh pr list --head "$branch" --state merged --limit 1 --json number \
    --jq '.[0].number // ""' 2>/dev/null)
  if [ -z "$merged" ]; then
    kept="${kept}
  ${wt} — no merged PR found for '${branch}'"
    continue
  fi

  # `git worktree remove`, never `rm -rf`: the latter leaves the entry in git's
  # index and the next `git worktree list` still reports a checkout that is gone.
  if git worktree remove "$wt" >/dev/null 2>&1; then
    removed="${removed}
  ${wt}  (${branch}, PR #${merged})"
  else
    kept="${kept}
  ${wt} — 'git worktree remove' refused it"
  fi
done <<EOF
$(git worktree list --porcelain 2>/dev/null)
EOF

[ -n "$removed" ] && git worktree prune >/dev/null 2>&1

# SessionEnd has no one to talk to, so this goes to the transcript, never to a
# blocking prompt. Silence when there was nothing to sweep.
if [ -n "$removed" ]; then
  printf 'navori: reclaimed agent worktrees (clean, pushed, PR merged):%s\n' "$removed"
fi
if [ -n "$kept" ]; then
  printf 'navori: agent worktrees KEPT — each holds work that exists nowhere else:%s\n' "$kept"
fi

# The verdict says what the sweep DID, which is what an audit needs to answer
# "where did the disk go": `noop` is the common case (no worktrees to sweep) and
# must stay distinguishable from a run that reclaimed or refused one.
if [ -n "$removed" ] || [ -n "$kept" ]; then
  navori_audit_verdict="clean"
  navori_audit_reason="reclamados:${removed:+ si} conservados:${kept:+ si}"
else
  navori_audit_verdict="noop"
fi
exit 0
# navori:managed end id="worktree-reclaim-base"
