import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeConfig } from "../../lib/config/config.ts";
import { runRender } from "../render.ts";
import { extractManagedContent } from "../../lib/render/marker.ts";

/**
 * #80 — disabling a plugin must clean up ALL its artifacts, not just its
 * CLAUDE.md managed block: the injectInto sub-blocks and the .claude/scripts/*
 * it wrote while enabled. `configure plugins`/`navori remove` set enabled:false;
 * the render reconciles.
 */

let cwd: string;

beforeEach(() => {
  cwd = mkdtempSync(join(tmpdir(), "navori-plugin-lc-"));
});
afterEach(() => rmSync(cwd, { recursive: true, force: true }));

function writeCfg(
  plugins: Record<string, { enabled: boolean }>,
  gitignoreHarness?: "off" | "local" | "full",
  engines: Array<"claude" | "codex"> = ["claude"],
): void {
  writeConfig(join(cwd, "navori.config.json"), {
    name: "demo",
    engines,
    preset: "custom",
    qualityGate: { fast: "echo fast", full: "echo full" },
    plugins,
    ...(gitignoreHarness ? { gitignoreHarness } : {}),
  });
}

// Captured verbatim from a3f05d2a^:.codex/config.toml, the parent of T5's
// plugin-gates commit. It has core Codex hooks but no plugin script registration.
const PRE_T5_CODEX_CONFIG =
  '# Codex project config generated by navori.\n\n# navori:managed start id="codex-config-base" hash="2c57065f" version="0.10.1" source="@navori/core"\nsandbox_mode = "danger-full-access"\napproval_policy = "on-request"\napprovals_reviewer = "user"\n\n[features]\nhooks = true\nmulti_agent = true\n\n[[hooks.PreToolUse]]\nmatcher = "^Bash$"\n\n[[hooks.PreToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/guard-destructive.sh\\""\ntimeout = 30\nstatusMessage = "Checking destructive command policy"\n\n[[hooks.PreToolUse]]\nmatcher = "^Bash$"\n\n[[hooks.PreToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/comment-draft-confirm.sh\\""\ntimeout = 10\nstatusMessage = "Checking for an unconfirmed comment/review draft"\n\n[[hooks.PreToolUse]]\nmatcher = "^Bash$"\n\n[[hooks.PreToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/quality-gate-pre-commit.sh\\""\ntimeout = 600\nstatusMessage = "Running pre-commit quality gate"\n\n[[hooks.SessionStart]]\n\n[[hooks.SessionStart.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/model-advisor.sh\\" codex-session-start"\ntimeout = 10\nstatusMessage = "navori: model advisor"\n\n[[hooks.SessionStart]]\nmatcher = "startup|resume|clear|compact|fork"\n\n[[hooks.SessionStart.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/session-start-context.sh\\""\ntimeout = 15\nstatusMessage = "navori: session context"\n\n[[hooks.PreToolUse]]\nmatcher = "^(Bash|apply_patch)$"\n\n[[hooks.PreToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/implementer-no-markdown.sh\\""\ntimeout = 10\nstatusMessage = "navori: implementer-no-markdown"\n\n[[hooks.PostToolUse]]\nmatcher = "^(Bash|apply_patch)$"\n\n[[hooks.PostToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/managed-drift-watch.sh\\""\ntimeout = 10\nstatusMessage = "navori: managed-block drift"\n\n[[hooks.PostToolUse]]\nmatcher = "^(Bash|apply_patch|spawn_agent)$"\n\n[[hooks.PostToolUse.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/routing-watch.sh\\""\ntimeout = 10\nstatusMessage = "navori: routing check"\n\n[[hooks.SubagentStop]]\n\n[[hooks.SubagentStop.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/subagent-stop-handoff.sh\\" codex"\ntimeout = 15\nstatusMessage = "navori: handoff check"\n\n[[hooks.UserPromptSubmit]]\n\n[[hooks.UserPromptSubmit.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/audit-mode-trigger.sh\\""\ntimeout = 10\nstatusMessage = "navori: audit-mode"\n\n[[hooks.SessionEnd]]\n\n[[hooks.SessionEnd.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/audit-mode-close.sh\\""\ntimeout = 3\nstatusMessage = "navori: audit-mode close"\n\n[[hooks.SessionStart]]\nmatcher = "startup"\n\n[[hooks.SessionStart.hooks]]\ntype = "command"\ncommand = "bash \\"$(git rev-parse --show-toplevel)/.codex/hooks/worktree-reclaim.sh\\""\ntimeout = 30\nstatusMessage = "navori: reclaim worktrees"\n\n[mcp_servers."engram"]\ncommand = "engram"\nargs = ["mcp", "--tools=mem_search,mem_get_observation,mem_context,mem_save,mem_session_summary,mem_update,mem_judge"]\n\n[mcp_servers."codegraph"]\ncommand = "codegraph"\nargs = ["serve", "--mcp"]\nenv = { "CODEGRAPH_MCP_TOOLS" = "explore", "CODEGRAPH_EXPLORE_DEDUP" = "0" }\n# navori:managed end id="codex-config-base"\n';

/** The `.gitignore` managed block content, or null when absent. */
function gitignoreBlock(): string | null {
  const path = join(cwd, ".gitignore");
  if (!existsSync(path)) return null;
  return extractManagedContent(readFileSync(path, "utf-8"), "gitignore-harness", "shell");
}

describe("plugin lifecycle cleanup (#80)", () => {
  // Covers: R18, R20
  it("upgrades the pre-T5 Codex config by first materializing plugin scripts, then stays byte-stable", () => {
    writeCfg({ semgrep: { enabled: true } }, undefined, ["claude", "codex"]);
    mkdirSync(join(cwd, ".codex"), { recursive: true });
    const configPath = join(cwd, ".codex/config.toml");
    writeFileSync(configPath, PRE_T5_CODEX_CONFIG);
    expect(PRE_T5_CODEX_CONFIG).not.toContain("check-semgrep.sh");
    expect(existsSync(join(cwd, ".codex/scripts/check-semgrep.sh"))).toBe(false);

    runRender(cwd, false);
    const upgradedConfig = readFileSync(configPath, "utf-8");
    const scriptPath = join(cwd, ".codex/scripts/check-semgrep.sh");
    const upgradedScript = readFileSync(scriptPath, "utf-8");
    expect(upgradedConfig).toContain("check-semgrep.sh");
    expect(upgradedScript).toContain('source="@navori/plugin-semgrep"');

    const second = runRender(cwd, false);
    expect(readFileSync(configPath, "utf-8")).toBe(upgradedConfig);
    expect(readFileSync(scriptPath, "utf-8")).toBe(upgradedScript);
    expect(second.engineResult?.written.some((entry) => entry.path.includes("check-semgrep"))).toBe(
      false,
    );
  });
  it("strips a disabled plugin's injectInto sub-block from its target file", () => {
    writeCfg({ engram: { enabled: true } });
    runRender(cwd, false);
    const leaderPath = join(cwd, ".claude/agents/orchestrator.md");
    expect(readFileSync(leaderPath, "utf-8")).toContain('id="engram-orchestrator-extension"');

    writeCfg({ engram: { enabled: false } });
    runRender(cwd, false);
    expect(readFileSync(leaderPath, "utf-8")).not.toContain('id="engram-orchestrator-extension"');
    // The base orchestrator block survives — only the plugin sub-block is stripped.
    expect(readFileSync(leaderPath, "utf-8")).toContain('id="orchestrator-base"');
  });

  it("deletes a disabled plugin's script from .claude/scripts/", () => {
    writeCfg({ semgrep: { enabled: true } });
    runRender(cwd, false);
    const scriptPath = join(cwd, ".claude/scripts/check-semgrep.sh");
    expect(existsSync(scriptPath)).toBe(true);

    writeCfg({ semgrep: { enabled: false } });
    runRender(cwd, false);
    expect(existsSync(scriptPath)).toBe(false);
  });

  it("removes a disabled plugin's managed block from CLAUDE.md", () => {
    // engram carries no CLAUDE.md-wide block anymore (#814; its doctrine is a
    // skill injected straight into the agents that hold `mem_*` tools) — gh
    // still does, so it covers this scenario.
    writeCfg({ gh: { enabled: true } });
    runRender(cwd, false);
    const claudeMd = join(cwd, "CLAUDE.md");
    expect(readFileSync(claudeMd, "utf-8")).toContain('id="gh-protocol"');

    writeCfg({ gh: { enabled: false } });
    runRender(cwd, false);
    expect(readFileSync(claudeMd, "utf-8")).not.toContain('id="gh-protocol"');
  });

  it("cleanup is idempotent: re-rendering a disabled plugin is a no-op", () => {
    writeCfg({ semgrep: { enabled: true } });
    runRender(cwd, false);
    writeCfg({ semgrep: { enabled: false } });
    runRender(cwd, false);
    const second = runRender(cwd, false);
    // Nothing left to remove the second time around.
    const removed = (second.engineResult?.written ?? []).filter(
      (w) => w.status === "removed-condition-false" && w.path.includes("check-semgrep"),
    );
    expect(removed).toEqual([]);
  });

  // search-v2.md §6.2/§7 — disabling a v2 search plugin must also retire its
  // `.gitignore` entry, the same cleanup contract every other plugin artifact
  // already gets in this suite (injectInto sub-block, script, CLAUDE.md block).
  it("disabling codegraph retires its .gitignore entry; tgrep's survives", () => {
    writeCfg({ codegraph: { enabled: true }, tgrep: { enabled: true } }, "full");
    runRender(cwd, false);
    expect(gitignoreBlock()?.split("\n")).toEqual(
      expect.arrayContaining([".codegraph/", ".tgrep/"]),
    );

    writeCfg({ codegraph: { enabled: false }, tgrep: { enabled: true } }, "full");
    runRender(cwd, false);
    const lines = gitignoreBlock()?.split("\n") ?? [];
    expect(lines).not.toContain(".codegraph/");
    expect(lines).toContain(".tgrep/");
  });
});
