# navori:managed start id="implementer-no-markdown-base" hash="1fa253c6" version="0.11.2" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(Bash|Edit|Write|NotebookEdit) guard — the mechanical half of R1
# (spec 0030, #985): the `implementer` does not write Markdown. Blocks a
# `Write`/`Edit`/`NotebookEdit` whose target ends in `.md`/`.mdx`, and the Bash
# write-verb forms of R4 (redirection, `tee`, `sed -i`/`perl -i`, `cp`/`mv` onto
# a `.md`/`.mdx` path) — all with `exit 2`, the same channel `guard-destructive`
# uses, evaluated BEFORE permission rules.
#
# WHY A HOOK AND NOT JUST THE CONTRACT (design.md): `implementer.md`'s own
# prose already says not to touch `.md` (R1). #985's own failure mode is a
# contract the agent follows by inertia — 520 `.md` writes since 2026-09-01,
# with the prohibition already implied by the agent's job. Prose alone did not
# hold; this is the mechanical backstop.
#
# WHO IT APPLIES TO. `agent_type` — read straight from the payload, not
# `tool_input` — is the field Claude Code adds "present only when the hook
# fires inside a subagent call" (https://code.claude.com/docs/en/hooks.md,
# confirmed against this repo's own `model-advisor.sh`, which reads the same
# field the same way). Absent → the main thread, never blocked. Any value other
# than `implementer` (`scribe`, `reviewer`, `auditor`, `scout`, `publisher`) →
# never blocked either: this rule is scoped to the one role R1 names.
#
# KNOWN, ACCEPTED LIMITATION — best-effort against inertia, NOT a sandbox
# against a deliberate adversary (same posture as `guard-destructive.sh`'s own
# header). The Bash rules read the command as TEXT, unsegmented: a `.md`
# mention inside a commit message or a heredoc body can false-positive.
# Interpreter checks require a Markdown literal and a recognizable write API;
# unrelated reads/writes in the same command can still false-positive. Dynamic
# paths, external scripts, and unenumerated runners (`dd`, `rsync`, `git apply`)
# remain outside this text-based guard (R4: "not a sandbox against evasion").
# A closed Node/JSON exception below classifies submitted source text only: it
# assumes a trusted Node runtime and filesystem. A .json symlink/hardlink is
# not proof of the physical target. Unsupported syntax retains the old block.
# The closed Python Path exception likewise parses data, never runs submitted
# code, and is not a general sandbox or a symlink/physical-target guarantee.
# The contract in `implementer.md` is the rule; this catches the slip, not the
# workaround.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# Command/field extraction (payload → $cmd, $payload). Shared body, single
# source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Spec 0035 D2: nv_tool()/nv_edited_paths() normalize Codex's `apply_patch`
# (one call can touch several files at once, unlike Claude's single-path
# Write/Edit) to the same shape this script already handles.
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent a spawn call TARGETS, never the one that makes the call (spec 0041
# H16). Claude: `tool_input.subagent_type`. Codex PreToolUse/PostToolUse of a
# spawn: `tool_input.agent_type` only — the top-level `agent_type` there is the
# CALLER's. On `SubagentStop` the top-level `agent_type` IS the finishing
# subagent, so that event reads it instead.
nv_spawn_target_type() {
  if [ "$nv_engine" = codex ]; then
    case "$(payload_field hook_event_name)" in
      SubagentStop) payload_field agent_type ;;
      *) payload_field tool_input.agent_type ;;
    esac
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent RUNNING the current event: the top-level `agent_type`, which the
# host adds only inside a subagent (empty on the main thread). Never confuse it
# with `nv_spawn_target_type` (H16). `nv_subagent_type` above keeps its legacy
# mixed behaviour for existing hooks; new code uses these two helpers.
nv_event_agent_type() {
  payload_field agent_type
}

# True for the spawn tool: Codex V1 `spawn_agent`, or any V2 name that ends in
# `spawn_agent` (V2 flattens the namespace into the tool name).
nv_is_spawn_tool() {
  case "$(payload_field tool_name)" in
    *spawn_agent) return 0 ;;
    *) return 1 ;;
  esac
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.

navori_audit_name="implementer-no-markdown"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127, and a
# recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. This fires on EVERY Bash/Edit/Write/NotebookEdit call from
# EVERY agent (and the main thread); only the implementer is ever in scope.
# Fork-free PRESENCE test before anything that spawns a process — same trade
# `model-advisor.sh` makes for the identical field: the main thread carries no
# `agent_type` key at all, so a plain substring test already proves absence
# without a fork. A VALUE read (below) still follows for the subagent case,
# because presence alone only proves "some subagent", not which one.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

navori_agent_type=$(payload_field agent_type)
if [ "$navori_agent_type" != "implementer" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="no es el implementer"
  exit 0
fi

navori_tool=$(nv_tool)

block() {
  echo "[navori] BLOCKED by implementer-no-markdown: $1" >&2
  # Both progress paths, never one alone: `placeHook` ships this byte-identical
  # to Claude and Codex (#389), so a message hardcoding `.claude/progress`
  # would misdirect a Codex implementer to a path that is not its own.
  echo "[navori] the implementer does not write Markdown (spec 0030, R1). Put the change in \"markdownRequests\", inside .claude/progress/impl_<feature>.json (or .codex/progress/impl_<feature>.json under Codex) — the scribe applies it in this worktree." >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Case-insensitive `.md`/`.mdx`: macOS ships a case-insensitive filesystem, so
# `NOTES.MD` writes the same file `notes.md` does.
is_md_path() {
  case "$1" in
    *.[mM][dD] | *.[mM][dD][xX]) return 0 ;;
    *) return 1 ;;
  esac
}

case "$navori_tool" in
  Write | Edit)
    # Codex's `apply_patch` can touch several files in ONE call (Add/Update/
    # Delete/Move headers in the same patch); `nv_edited_paths` yields one per
    # line, so every one of them is checked, not just the first.
    while IFS= read -r navori_path; do
      [ -n "$navori_path" ] || continue
      if is_md_path "$navori_path"; then
        block "$navori_tool sobre '$navori_path'"
      fi
    done <<EOF
$(nv_edited_paths)
EOF
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  NotebookEdit)
    navori_path=$(payload_field tool_input.notebook_path)
    if is_md_path "$navori_path"; then
      block "NotebookEdit sobre '$navori_path'"
    fi
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  Bash) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac

cmd=$(extract_cmd)
if [ -z "$cmd" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin comando que inspeccionar"
  exit 0
fi

# R4's write-verb forms, over the raw command text (best-effort, see header).
# Case-insensitive throughout, same reasoning as `is_md_path` above.
MD_EXT='\.(md|mdx)'

# 1. Output redirection: `>`, `>>`, `>|` onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE ">>?\\|?[[:space:]]*[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "redirección hacia un archivo .md/.mdx"
fi

# 2. `tee` (append or overwrite) onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])tee([[:space:]]+-[a-zA-Z]+)*[[:space:]]+[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'tee' hacia un archivo .md/.mdx"
fi

# 3. In-place rewrite: `sed -i`/`sed --in-place`, `perl -i`.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])sed[[:space:]]+(-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*|--in-place)([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'sed -i' sobre un archivo .md/.mdx"
fi
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])perl[[:space:]]+-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'perl -i' sobre un archivo .md/.mdx"
fi

# 4. `cp`/`mv` onto a `.md`/`.mdx` target — the atomic-write idiom (write a
# temp file, then move it onto the managed path). Anchored on the LAST operand
# of the invocation (greedy `.*` before the final `[[:space:]]`), since that is
# where `cp`/`mv` read their destination.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])(cp|mv)[[:space:]]+.*[[:space:]][^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'cp'/'mv' hacia un archivo .md/.mdx"
fi

# 5. Interpreter writes (#1129). Inspect text only: never execute supplied
# code. Flatten heredocs so an open() mode can appear on a separate line.
# Require all three clues: interpreter invocation, literal Markdown path, and
# write API/mode. Read APIs and stdout writes alone must not trigger this rule.
interpreter_cmd=$(printf '%s' "$cmd" | tr '\n' ' ')
INTERPRETER='(^|[;&|[:space:]])([^[:space:];&|]*/)?(python([0-9]+(\.[0-9]+)*)?|node|ruby|perl|deno|bun)([[:space:]]|$)'
MD_LITERAL="${MD_EXT}(['\"]|[[:space:]]|$)"
WRITE_API='(^|[^[:alnum:]_])(writeFile(Sync)?|appendFile(Sync)?|writeTextFile(Sync)?|write_text|write_bytes)[[:space:]]*\('
FILE_WRITE='(File|Bun)[[:space:]]*\.[[:space:]]*(write|binwrite)[[:space:]]*\('
OPEN_WRITE="(^|[^[:alnum:]_])open[[:space:]]*\\([^)]*,[[:space:]]*(mode[[:space:]]*=[[:space:]]*)?['\"]([wax][bt+]*|r[bt]*\\+|[+]?>>?)['\"]"
if printf '%s' "$interpreter_cmd" | grep -qE "$INTERPRETER" &&
  printf '%s' "$interpreter_cmd" | grep -qiE "$MD_LITERAL" &&
  printf '%s' "$interpreter_cmd" | grep -qE "${WRITE_API}|${FILE_WRITE}|${OPEN_WRITE}"; then
  # A fixed trusted parser recognizes only this complete, bounded Path rewrite.
  # All failures retain the original denial; no submitted Python is executed.
  IFS= read -r -d '' navori_python_analyzer <<'NAVORI_PYTHON_ANALYZER' || :
import ast
import re
import sys

def require(value):
    if not value:
        raise ValueError("unrecognized Path rewrite")

def literal(node):
    require(isinstance(node, ast.Constant) and type(node.value) is str)
    return node.value

def assignment(node):
    require(isinstance(node, ast.Assign) and len(node.targets) == 1)
    require(isinstance(node.targets[0], ast.Name))
    return node.targets[0].id, node.value

def method(node, owner, name):
    require(isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute))
    require(isinstance(node.func.value, ast.Name) and node.func.value.id == owner)
    require(node.func.attr == name)
    return node

def utf8(call):
    require(len(call.keywords) == 1 and call.keywords[0].arg == "encoding")
    require(literal(call.keywords[0].value) == "utf-8")

try:
    command = sys.stdin.buffer.read(16385)
    require(len(command) <= 16384)
    command = command.decode("utf-8", errors="strict")
    heredoc = re.fullmatch(r"[ \t]*python3[ \t]+-[ \t]+<<(['\"])([A-Za-z_][A-Za-z_0-9]*)\1[ \t]*\n(.*)\n\2\n?", command, re.S)
    if heredoc:
        source = heredoc.group(3)
    else:
        # Single shell quotes are literal; double quotes may not expand or
        # escape anything. Unsupported shell quoting is deliberately denied.
        invocation = re.fullmatch(r"[ \t]*python3[ \t]+-c[ \t]+(?:'([^']*)'|\"([^\"\\$`]*)\")[ \t]*", command, re.S)
        require(invocation is not None)
        source = invocation.group(1) if invocation.group(1) is not None else invocation.group(2)
    tree = ast.parse(source, mode="exec")
    pending = [(tree, 0)]
    nodes = 0
    while pending:
        node, depth = pending.pop()
        nodes += 1
        require(nodes <= 4096 and depth <= 16)
        pending.extend((child, depth + 1) for child in ast.iter_child_nodes(node))
    body = tree.body
    require(len(body) >= 5)
    imported = body[0]
    require(isinstance(imported, ast.ImportFrom) and imported.module == "pathlib" and imported.level == 0)
    require(len(imported.names) == 1 and imported.names[0].name == "Path" and imported.names[0].asname is None)
    path, constructor = assignment(body[1])
    require(path != "Path" and isinstance(constructor, ast.Call))
    require(isinstance(constructor.func, ast.Name) and constructor.func.id == "Path")
    require(len(constructor.args) == 1 and not constructor.keywords)
    destination = literal(constructor.args[0])
    require(destination and not any(char in destination for char in "\x00\r\n"))
    require(not destination.lower().endswith((".md", ".mdx")))
    text, read = assignment(body[2])
    require(text not in (path, "Path"))
    read = method(read, path, "read_text")
    require(not read.args)
    utf8(read)
    for statement in body[3:-1]:
        target, replacement = assignment(statement)
        require(target == text)
        replacement = method(replacement, text, "replace")
        require(len(replacement.args) == 2 and not replacement.keywords)
        for argument in replacement.args:
            literal(argument)
    require(isinstance(body[-1], ast.Expr))
    write = method(body[-1].value, path, "write_text")
    require(len(write.args) == 1 and isinstance(write.args[0], ast.Name) and write.args[0].id == text)
    utf8(write)
    print("ALLOW_PATH_REWRITE")
except Exception:
    sys.exit(1)
NAVORI_PYTHON_ANALYZER
  navori_python_safe=$(printf '%s' "$cmd" | python3 -c "$navori_python_analyzer" 2>/dev/null) || navori_python_safe=""
  if [ "$navori_python_safe" = "ALLOW_PATH_REWRITE" ]; then
    navori_audit_reason="reescritura Path no-md clasificada"
    exit 0
  fi
  # The program is fixed hook code. The submitted command enters only on
  # stdin as data; never eval it. A nonzero analyzer, missing node, empty or
  # malformed output all fall through to the existing exit-2 block.
  IFS= read -r -d '' navori_json_analyzer <<'NAVORI_JSON_ANALYZER' || :
const input = require("node:fs").readFileSync(0, "utf8");
const fail = () => { throw Error("unrecognized metadata program"); };
try {
  if (Buffer.byteLength(input) > 16384) fail();
  const shell = /^[ \t]*node[ \t]+-e[ \t]+\x27([^\x27]*)\x27[ \t]*$/s.exec(input);
  if (!shell) fail();
  const source = shell[1];
  const tokens = [];
  const forbidden = new Set(["__proto__", "prototype", "constructor", "toJSON"]);
  const reserved = new Set(["const", "for", "of", "if", "true", "false", "null", "return", "function", "class", "new", "this", "var", "let", "await", "async", "delete", "while", "do", "else", "try", "catch", "throw", "import", "export", "default", "in", "instanceof", "void", "typeof", "yield", "switch", "case", "break", "continue", "with", "super", "extends", "static", "get", "set"]);
  for (let at = 0; at < source.length;) {
    const rest = source.slice(at);
    const space = /^[\t\n\r ]+/.exec(rest);
    if (space) { at += space[0].length; continue; }
    const string = /^"(?:[^"\\\x00-\x1f]|\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))*"/.exec(rest);
    if (string) {
      tokens.push({ kind: "string", value: JSON.parse(string[0]) });
      at += string[0].length;
    } else {
      const id = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(rest);
      const number = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/.exec(rest);
      if (id) { tokens.push({ kind: "id", value: id[0] }); at += id[0].length; }
      else if (number) {
        if (!Number.isFinite(Number(number[0]))) fail();
        tokens.push({ kind: "number", value: number[0] }); at += number[0].length;
      } else if (rest.startsWith("=>")) { tokens.push({ kind: "punct", value: "=>" }); at += 2; }
      else if (".,;:=()[]{}!+".includes(rest[0])) { tokens.push({ kind: "punct", value: rest[0] }); at++; }
      else fail();
    }
    if (tokens.length > 4096) fail();
  }
  let pos = 0;
  const peek = (value) => tokens[pos]?.value === value;
  const take = (value) => {
    const token = tokens[pos++];
    const expectedKind = value === "2" ? "number" : ".,;:=()[]{}!+=>".includes(value) ? "punct" : "id";
    if (!token || token.value !== value || token.kind !== expectedKind) fail();
  };
  const kind = (wanted) => { const token = tokens[pos++]; if (!token || token.kind !== wanted) fail(); return token.value; };
  const name = () => { const value = kind("id"); if (reserved.has(value)) fail(); return value; };
  const binding = () => { const value = name(); if (forbidden.has(value) || ["JSON", "require"].includes(value)) fail(); return value; };
  const property = () => { const value = name(); if (forbidden.has(value)) fail(); return value; };
  const path = (root, stop) => {
    take(root);
    let count = 0;
    let result = "";
    while (peek(".") && tokens[pos + 1]?.value !== stop) {
      take("."); result += "." + property();
      if (++count > 8) fail();
    }
    if (!count) fail();
    return result;
  };
  const value = (depth = 0) => {
    if (depth > 16) fail();
    if (tokens[pos]?.kind === "string" || tokens[pos]?.kind === "number") { pos++; return; }
    if (peek("true") || peek("false") || peek("null")) { pos++; return; }
    if (peek("[")) {
      take("[");
      if (!peek("]")) { do { value(depth + 1); if (!peek(",")) break; take(","); if (peek("]")) fail(); } while (true); }
      take("]"); return;
    }
    if (peek("{")) {
      take("{"); const keys = new Set();
      if (!peek("}")) {
        do {
          const key = tokens[pos]?.kind === "string" ? kind("string") : property();
          if (forbidden.has(key) || keys.has(key)) fail();
          keys.add(key); take(":"); value(depth + 1);
          if (!peek(",")) break; take(","); if (peek("}")) fail();
        } while (true);
      }
      take("}"); return;
    }
    fail();
  };
  const string = (expected) => { const actual = kind("string"); if (actual !== expected) fail(); };
  take("const"); const fs = binding(); take("="); take("require"); take("("); string("node:fs"); take(")"); take(";");
  take("const"); const dest = binding(); if (dest === fs) fail(); take("=");
  const destination = kind("string");
  if (!destination || /[\x00-\x1f\x7f]/.test(destination) || !/\.json$/i.test(destination)) fail();
  take(";");
  take("const"); const doc = binding(); if (doc === fs || doc === dest) fail(); take("=");
  take("JSON"); take("."); take("parse"); take("(");
  take(fs); take("."); take("readFileSync"); take("("); take(dest); take(","); string("utf8"); take(")"); take(")"); take(";");
  let operations = 0;
  while (!(peek(fs) && tokens[pos + 1]?.value === "." && tokens[pos + 2]?.value === "writeFileSync")) {
    if (++operations > 4096) fail();
    if (peek("for")) {
      take("for"); take("("); take("const"); const item = binding();
      if ([fs, dest, doc].includes(item)) fail();
      take("of"); take("[");
      if (!peek("]")) { do { kind("string"); if (!peek(",")) break; take(","); if (peek("]")) fail(); } while (true); }
      take("]"); take(")"); take("if"); take("("); take("!");
      const checked = path(doc, "includes"); take("."); take("includes"); take("("); take(item); take(")"); take(")");
      const pushed = path(doc, "push"); if (checked !== pushed) fail();
      take("."); take("push"); take("("); take(item); take(")"); take(";");
    } else {
      const target = path(doc, "sort");
      if (peek(".") && tokens[pos + 1]?.value === "sort") {
        take("."); take("sort"); take("("); take(")"); take(";"); continue;
      }
      take("=");
      if (peek(doc)) {
        path(doc, "map"); take("."); take("map"); take("(");
        const item = binding(); if ([fs, dest, doc].includes(item)) fail();
        take("=>"); path(item); take(")");
      } else value();
      take(";");
    }
  }
  take(fs); take("."); take("writeFileSync"); take("("); take(dest); take(",");
  take("JSON"); take("."); take("stringify"); take("("); take(doc); take(","); take("null"); take(","); take("2"); take(")");
  take("+"); string("\n"); take(")"); take(";");
  if (pos !== tokens.length) fail();
  process.stdout.write("ALLOW");
} catch { process.exitCode = 1; }
NAVORI_JSON_ANALYZER
  if command -v node >/dev/null 2>&1; then
    if navori_json_result=$(printf '%s' "$cmd" | node -e "$navori_json_analyzer" 2>/dev/null) && [ "$navori_json_result" = "ALLOW" ]; then
      navori_audit_verdict="allow"
      navori_audit_reason="programa JSON estático reconocido"
      exit 0
    fi
  fi
  # Closed Python handoff grammar: parse supplied text, never run its imports,
  # reads, Git queries or writes. The producer still assumes trusted Python,
  # stdlib, Git and filesystem; this is destination classification, not isolation.
  IFS= read -r -d '' navori_python_analyzer <<'NAVORI_PYTHON_ANALYZER' || :
import ast
import math
import re
import sys

def recognize() -> bool:
    """Recognize one bounded, complete JSON handoff without evaluating source."""
    command = sys.stdin.buffer.read(16385)
    if len(command) > 16384:
        return False
    command = command.decode('utf-8')
    header = re.match(r"python3 - <<'([A-Za-z_][A-Za-z0-9_]*)'\n", command)
    if not header:
        return False
    lines = command[header.end():].split('\n')
    # Shell closes at the FIRST exact delimiter, including inside Python strings.
    close = lines.index(header.group(1))
    if lines[close + 1:] not in ([], ['']):
        return False
    tree = ast.parse('\n'.join(lines[:close]))
    if sum(1 for _ in ast.walk(tree)) > 4096 or len(tree.body) != 7:
        return False
    template = ast.parse("""import json, subprocess
from pathlib import Path
root = Path.cwd()
runtime = json.loads((root / 'INPUT').read_text())
report = {}
(root / 'OUTPUT').write_text(json.dumps(report, indent=2, ensure_ascii=False) + '\\n')
print('MESSAGE')
""")
    # Only these two exact, read-only argv shapes may occur as report values.
    expressions = {
        ast.dump(ast.parse(source, mode='eval').body)
        for source in (
            'str(root)', "runtime['repo']", "runtime['results']",
            "subprocess.check_output(['git', 'branch', '--show-current'], text=True).strip()",
            "subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip()",
        )
    }

    def data(node: ast.AST, depth: int = 0) -> bool:
        """Allow JSON literals and the fixed evidence expressions only."""
        if depth > 16:
            return False
        if isinstance(node, ast.Constant):
            return (type(node.value) in (str, int, bool, type(None)) or
                    type(node.value) is float and math.isfinite(node.value))
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return (isinstance(node.operand, ast.Constant) and
                    type(node.operand.value) in (int, float) and
                    math.isfinite(node.operand.value))
        if isinstance(node, ast.List):
            return all(data(value, depth + 1) for value in node.elts)
        if isinstance(node, ast.Dict):
            keys = [key.value for key in node.keys
                    if isinstance(key, ast.Constant) and type(key.value) is str]
            return (len(keys) == len(node.keys) == len(set(keys)) and
                    all(data(value, depth + 1) for value in node.values))
        return ast.dump(node) in expressions

    def json_path(node: ast.AST) -> bool:
        """Validate decoded literal destinations without accessing the filesystem."""
        return (isinstance(node, ast.Constant) and type(node.value) is str and
                bool(node.value) and not re.search(r'[\x00-\x1f\x7f]', node.value) and
                node.value.lower().endswith('.json'))

    input_path = tree.body[3].value.args[0].func.value.right
    output_path = tree.body[5].value.func.value.right
    message = tree.body[6].value.args[0]
    report = tree.body[4].value
    if not (json_path(input_path) and json_path(output_path) and
            isinstance(message, ast.Constant) and type(message.value) is str and
            isinstance(report, ast.Dict) and data(report)):
        return False
    for node in ast.walk(template):
        if isinstance(node, ast.Constant) and node.value in ('INPUT', 'OUTPUT', 'MESSAGE'):
            node.value = {'INPUT': input_path.value, 'OUTPUT': output_path.value,
                          'MESSAGE': message.value}[node.value]
    template.body[4].value = report
    return ast.dump(tree) == ast.dump(template)

try:
    if recognize():
        sys.stdout.write('ALLOW')
    else:
        sys.exit(1)
except Exception:
    sys.exit(1)
NAVORI_PYTHON_ANALYZER
  if command -v python3 >/dev/null 2>&1; then
    if navori_python_result=$(printf '%s' "$cmd" | python3 -I -S -c "$navori_python_analyzer" 2>/dev/null) && [ "$navori_python_result" = "ALLOW" ]; then
      navori_audit_verdict="allow"
      navori_audit_reason="programa JSON Python estático reconocido"
      exit 0
    fi
  fi
  block "intérprete con operación de escritura y ruta .md/.mdx"
fi

navori_audit_verdict="allow"
navori_audit_reason="comando no cubierto por R4"
exit 0
# navori:managed end id="implementer-no-markdown-base"
