# navori:managed start id="managed-drift-watch-base" hash="b9783c71" version="0.11.3" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse watcher for managed-block drift (#530), on every tool that can
# write a file: `Bash|Edit|Write|NotebookEdit`.
#
# WHY THE MATCHER IS THE WHOLE DECISION, and why it took #775 to widen it. This
# script audits STATE, never the command, so it has no `case "$tool_name"` to
# contradict its registration — the matcher alone decides when it runs, which
# makes a narrow one indistinguishable from a hook that works. It was `Bash`
# only, and the host's own PostToolUse doc spells out the consequence from the
# other direction: a hook matching `Edit|Write` does not run when a `Bash`
# command rewrites the same file. The inverse is the hole this had — in
# `default`/`acceptEdits`, where the host does NOT push everything through the
# shell, an `Edit` over `CLAUDE.md` broke a managed block's hash and this stayed
# quiet until the next Bash call, if one ever came. A session of pure native
# editing put the #523 freeze back into silence, which is the one thing this
# hook exists to prevent.
#
# WHY NOT `FileChanged`, which the same doc section recommends for exactly this
# ("to run a hook when a specific file changes on disk, whatever wrote it").
# The CONTRACT is not the reason, and this comment used to say it was: core can
# register the event today. `lib/config/plugins.ts:91` admits four events, but that
# enum is the schema for a PLUGIN MANIFEST and is used nowhere else —
# `buildClaudeSettings` returns `Record<string, unknown>` and validates no event
# name at all, which is how core already ships `SessionEnd` and
# `UserPromptSubmit`. Only a plugin registering `FileChanged` would need the
# vocabulary widened. Three other things stop it:
#
#   1. The watchlist would live IN the settings, and the managed file set is
#      derived per repo at render time (engine outputs plus every rendered
#      asset, ~60 files here) — so settings.json would carry a second copy of a
#      list this script already derives, and the two would drift. A watchlist
#      that drifts from the managed set is a detector with holes in it, i.e.
#      this hook's own defect class.
#   2. It loses the channel to the model. `FileChanged` has no decision
#      control: the host shows its stderr "to user only", reads `watchPaths`
#      and `systemMessage` out of the JSON output and discards `continue`, and
#      that `systemMessage` is a brief terminal notification that "doesn't
#      reach the SDK message stream". Everything this hook does ends in
#      `exit 2` → stderr → the MODEL, which is what gets the freeze repaired in
#      the same turn. Migrating would downgrade the recipient of the warning.
#   3. Its matcher cannot name these paths. `FileChanged` and `StopFailure` use
#      a narrower exact-match set — letters, digits, `_` and `|` only — and
#      every root this watches (`CLAUDE.md`, `.claude/settings.json`,
#      `.claude/agents/…`) carries a dot, a slash or a hyphen, which drops the
#      matcher onto the regular-expression path. The one viable route is
#      `watchPaths` (absolute paths) returned from `SessionStart`, which is
#      more machinery and still subject to (1) and (2).
#
# What the widening does NOT buy, stated plainly: a write from outside the
# session — a formatter in a watch process, another terminal — still surfaces
# only on the next tool call navori sees. `FileChanged` would catch that one.
# The cost of what it does buy is one shasum pass (~35ms, quoted below) per
# native edit.
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST, and why this compares CONTENT rather than mtimes. The obvious cheap
# check is `find -newer <stamp>`, and it is wrong here: `find` compares mtimes at
# whatever resolution the filesystem stores, which on several (ext4 under the CI
# runner among them) is ONE SECOND. Two writes inside the same second as the
# stamp are invisible — the watcher would report the first and silently miss the
# second, which is precisely the failure it exists to prevent. It passed on APFS
# and failed in CI, so the clock was never a sound basis.
#
# So the common case costs one `shasum` pass over the managed files (~35ms) and
# compares that list against the previous one. It is exact, it depends on no
# clock, and per-block hashing — the expensive part, ~3.5s for 53 blocks — runs
# ONLY for the files whose content actually changed, which in a normal session
# is none and in a bad one is one. That ~35ms is the MEDIAN of 13,692 recorded
# runs in `~/.navori/audits` (mean 43.7ms, p95 78ms); the "~25ms measured over
# 60 files" this used to quote was a single early sample and ran ~40% optimistic.
# Blocking classification (#1117):
#   - managed block with a misaligned hash: advisory — PostToolUse, exit 2 only reaches the model; there is
#     nothing to approve or undo here.
set -uo pipefail

# The tools this state auditor must run after, i.e. the matcher it has to be
# registered with. Read by `hook-matcher-wiring.test.ts` (#796); nothing in this
# script reads it.
#
# It exists because this hook has nothing else the wiring suite can derive an
# invariant from. A hook that dispatches on `case "$tool_name"` contradicts a
# narrow matcher by itself, and a gate that declares `$TRIGGER_TOKENS` claims
# the commands it needs handed to it — this one audits STATE, so it makes
# neither claim, and its matcher was held up only by a hand-written list of four
# tool names in `build-settings.test.ts`. Narrowing the matcher went red there
# and the obvious repair was to edit the literal, which is the drift this
# declaration removes: the edit point is now the script, where the intent lives.
#
# The rule could not be inferred from silence instead. "Every hook with no
# `case` and no `$TRIGGER_TOKENS` must receive every write tool" falsifies
# against `guard-destructive.sh` and `subagent-stop-handoff.sh` (matcher
# `Agent|Task`, correct by design).
COVERED_TOOLS='Bash Edit Write NotebookEdit'

# PostToolUse delivers its payload on stdin; this hook never needed it and the
# audit recorder does (session_id/cwd), so it is captured rather than ignored.
payload=$(cat 2>/dev/null) || payload=""
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Spec 0035 D2: nv_project_dir is $CLAUDE_PROJECT_DIR under Claude (unchanged)
# and the payload cwd's git toplevel under Codex.
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent a spawn call TARGETS, never the one that makes the call (spec 0041
# H16). Claude: `tool_input.subagent_type`. Codex PreToolUse/PostToolUse of a
# spawn: `tool_input.agent_type` only — the top-level `agent_type` there is the
# CALLER's. On `SubagentStop` the top-level `agent_type` IS the finishing
# subagent, so that event reads it instead.
nv_spawn_target_type() {
  if [ "$nv_engine" = codex ]; then
    case "$(payload_field hook_event_name)" in
      SubagentStop) payload_field agent_type ;;
      *) payload_field tool_input.agent_type ;;
    esac
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent RUNNING the current event: the top-level `agent_type`, which the
# host adds only inside a subagent (empty on the main thread). Never confuse it
# with `nv_spawn_target_type` (H16). `nv_subagent_type` above keeps its legacy
# mixed behaviour for existing hooks; new code uses these two helpers.
nv_event_agent_type() {
  payload_field agent_type
}

# True for the spawn tool: Codex V1 `spawn_agent`, or any V2 name that ends in
# `spawn_agent` (V2 flattens the namespace into the tool name).
nv_is_spawn_tool() {
  case "$(payload_field tool_name)" in
    *spawn_agent) return 0 ;;
    *) return 1 ;;
  esac
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.

navori_audit_name="managed-drift-watch"
navori_audit_phase="PostToolUse"
# The recorded tool used to be the literal "Bash", which was true while the
# matcher was. Now that four tools reach here it has to be read — and read
# without a fork, because this runs after every tool call: `#` and `%%` are
# builtins, and a tool name carries no quote to escape. Anything the parse does
# not recognise leaves the field EMPTY (the partial then omits it) rather than
# guessing, since a wrong label in the audit log is how a lane gets measured as
# working when it is not — this issue, one level up.
navori_audit_tool=""
case "$payload" in
  *'"tool_name":"'*)
    navori_audit_tool=${payload#*'"tool_name":"'}
    navori_audit_tool=${navori_audit_tool%%'"'*}
    case "$navori_audit_tool" in
      "" | *[!A-Za-z_]*) navori_audit_tool="" ;;
    esac
    ;;
esac
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

# This hook has SEVEN early exits (no sha, no roots, no changes, …). Wiring a
# call into each is how the set drifts the next time one is added, so the verdict
# is derived once, from the exit code, in a trap.
#
# `navori_audit_reached_check` is what separates "ran and found nothing" from
# "bailed before checking anything" — the distinction the whole exercise exists
# for. Without it every early exit would report `clean`, i.e. would claim a
# verification that never happened.
navori_audit_reached_check=0
navori_audit_on_exit() {
  navori_audit_code=$?
  if [ "$navori_audit_code" -eq 2 ]; then
    navori_audit_log "dirty" "bloque managed con hash desalineado" advisory
  elif [ "$navori_audit_reached_check" -eq 1 ]; then
    navori_audit_log "clean"
  else
    navori_audit_log "skip" "sin nada que verificar"
  fi
  return 0
}
trap navori_audit_on_exit EXIT

[ -n "${nv_project_dir:-}" ] || exit 0
cd "$nv_project_dir" 2>/dev/null || exit 0

# Spec 0036: stamps belong to the active checkout, not the shared Git dir.
# Old stamps are deliberately left untouched. This re-arms the baseline once
# after upgrade; a routing notice may likewise fire once more for a session.
# A missing root, non-root cwd, or symlinked state component is unsafe: this
# detector skips rather than following a path outside the checkout.
repo_root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
repo_root=$(cd "$repo_root" 2>/dev/null && pwd -P) || exit 0
[ "$repo_root" = "$(pwd -P)" ] || exit 0
state_dir="$PWD/.navori/state/hooks"
for component in .navori .navori/state .navori/state/hooks; do
  [ ! -L "$component" ] || exit 0
  if [ -e "$component" ]; then
    [ -d "$component" ] || exit 0
  else
    mkdir "$component" 2>/dev/null || exit 0
  fi
done
stamp="$state_dir/managed-drift-stamp"
[ ! -L "$stamp" ] || exit 0

# sha1 tool, resolved once. `shasum` on macOS, `sha1sum` on most Linuxes; both
# print `<hash>  <path>` for a file list, which is the format the stamp stores.
sha=""
command -v shasum >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This is a detector, not a gate — the guard still
# sits in front, and a noisy failure here would fire on every single command.
[ -z "$sha" ] && exit 0

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — including them would re-hash a fresh report on every
# command and find nothing. `.claude/worktrees/` too: each is a full checkout,
# so walking it would make this hook cost more than the command it follows. That
# is why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
current=$(find $roots -type f -exec $sha {} + 2>/dev/null | sort || true)
[ -z "$current" ] && exit 0

# First run in a session (or after the ephemeral dir was wiped): adopt the
# current state as the baseline and say nothing. Reporting every block on the
# first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p "$state_dir" 2>/dev/null || exit 0
  printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
  exit 0
fi

# Lines present now but not in the baseline: a file whose CONTENT changed, or a
# new one. A deleted file appears only in the baseline and is ignored — there is
# no block left to verify.
changed=$(printf '%s\n' "$current" | grep -F -x -v -f "$stamp" 2>/dev/null | sed -E 's/^[a-f0-9]+[[:space:]]+//' || true)
# Re-baseline BEFORE reporting, so one write is reported once instead of on
# every command for the rest of the session. A second write does change the
# content again, and does get its own report.
printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# From here on the work is per-CHANGED-file only. `$(…)` strips the trailing
# newline, which is what makes these hashes agree with `computeManagedHash`
# (lib/render/marker.ts: sha1 over the body with trailing whitespace removed, first 8
# hex); without it every hash differs and the hook cries wolf on healthy files.
drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/render/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

navori_audit_reached_check=1
[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
# navori:managed end id="managed-drift-watch-base"
