# navori:managed start id="plan-gate-base" hash="06ba896f" version="0.10.0" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(Agent) gate — spec 0032 (#1011), R16/R17/R19: while
# `harness.planTiers` is `true`, the orchestrator may not dispatch the
# `implementer` without a workplan that passes `navori plan check`, or a
# level-0 exemption `navori plan classify` confirms. Blocks with `exit 2`,
# the same channel `guard-destructive`/`implementer-no-markdown` use,
# evaluated BEFORE permission rules.
#
# THIN ON PURPOSE. All the decision logic — reading `tool_input.subagent_type`
# / `tool_input.prompt`, resolving the workplan, running `classify`/`check`,
# counting `CHANGES_REQUESTED` rejections (R19) — lives in TypeScript
# (`navori plan gate`, `lib/plan/gate.ts`): that is what `plan-gate.test.ts`
# exercises directly. This script only resolves the `navori` binary and
# forwards the hook's own stdin payload to it unchanged; it never parses JSON
# itself. Matcher `Agent` in settings.json already restricts which calls
# reach this script, so there is nothing left to filter here.
#
# BINARY RESOLUTION. Same as `audit-mode-trigger.sh` / `session-start-context.sh`:
# `command -v navori`. Unlike those two (best-effort, silently absent), this
# is a HARD gate — `harness.planTiers` promises the workplan is enforced, so a
# missing or outdated `navori` must DENY with an actionable reason, never fail
# open. An outdated build with no `plan` subcommand exits with something other
# than this gate's own two contractual codes (0 allow, 2 deny) — citty's
# unknown-command exit — which this script tells apart from a real verdict
# below, in ONE invocation (a second `--help` probe would read the hook's
# stdin payload twice, which a pipe cannot replay).
#
# CODEX. This asset still renders to `.codex/hooks/` (generic asset copy),
# but it is NOT wired into Codex's `config.toml` `[[hooks.PreToolUse]]`
# (`build-config-toml.ts`), same as `implementer-no-markdown.sh`: Codex has no
# confirmed subagent-dispatch interception equivalent
# (`engines/codex/compat.ts:113`) — `navori doctor` reports the degradation
# (R17), and the gate falls back to the reviewer's `classify` check (R21).
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

if ! command -v navori >/dev/null 2>&1; then
  echo "[navori] BLOCKED by plan-gate: navori is not installed or not on PATH — install it before dispatching a planned implementer." >&2
  exit 2
fi

navori plan gate
navori_exit=$?
case "$navori_exit" in
  0 | 2) exit "$navori_exit" ;;
  *)
    echo "[navori] BLOCKED by plan-gate: this navori build has no working 'plan' subcommand (exit $navori_exit) — update navori (or run 'navori render --apply' after updating) before dispatching a planned implementer." >&2
    exit 2
    ;;
esac
# navori:managed end id="plan-gate-base"
