# navori:managed start id="role-guard-base" hash="14702607" version="0.11.2" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(apply_patch | spawn_agent) guard, CODEX ONLY (spec 0041 D5/D13,
# R6/R7/R8/R17/R31). Claude restricts a role with the agent's `tools:`
# allowlist; a Codex agent has no such field, so this hook is the mechanical
# equivalent. It never renders into `.claude/` (`HOOK_ENGINES`).
#
# TWO BRANCHES, both keyed on the top-level `agent_type`, which the host adds
# only when the hook fires inside a subagent. Absent or empty: the main thread,
# never blocked (R8).
#   1. spawn_agent (V1 name, or any V2 name ending in `spawn_agent`): a subagent
#      may not dispatch another one, whatever its role (R17/R31, depth 1). The
#      caller is named in the message.
#   2. apply_patch: `implementer` and `scribe` pass untouched (the first writes
#      production code, the second the Markdown the implementer must not). Any
#      other role may patch only the prefixes `RosterAgent.writes` grants it, or
#      an OS temp file. `default` and unknown roles get the common set
#      (fail-closed). Every path of a multi-file patch is checked.
#
# PATH CHECK. Each path is resolved against the payload `cwd`, normalized
# lexically (`..` cannot climb out unnoticed), then resolved physically so a
# symlink that leaves the repo is judged by where it lands. Inside the repo the
# role's prefixes decide, compared by path COMPONENT, not by text. Outside the
# repo only an OS temp root passes.
#
# FAIL-OPEN WITHOUT jq AND node (accepted, spec 0041): the sed fallback of
# `payload_field` cannot tell the top-level `agent_type` from
# `tool_input.agent_type`, so a main-thread spawn would be read as a subagent
# call and wrongly denied. With neither tool installed the hook lets the call
# through; upgrade trigger: ship a parser that reads only top-level keys.
#
# WHAT IT IS NOT. Bash writes keep the same containment as Claude (none by
# path); this guards the structured `apply_patch` channel only. Best-effort
# against inertia, not a sandbox against a deliberate adversary. If the payload
# cannot be read reliably it lets the call through.
#
# The per-role prefixes are NOT written here: they come from
# `RosterAgent.writes`, compiled by `buildRolePolicyShell` at render time.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
# Blocking classification (#1117):
#   - a role touching what its contract forbids: hard — role containment; the message names the route.
set -euo pipefail

# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent a spawn call TARGETS, never the one that makes the call (spec 0041
# H16). Claude: `tool_input.subagent_type`. Codex PreToolUse/PostToolUse of a
# spawn: `tool_input.agent_type` only — the top-level `agent_type` there is the
# CALLER's. On `SubagentStop` the top-level `agent_type` IS the finishing
# subagent, so that event reads it instead.
nv_spawn_target_type() {
  if [ "$nv_engine" = codex ]; then
    case "$(payload_field hook_event_name)" in
      SubagentStop) payload_field agent_type ;;
      *) payload_field tool_input.agent_type ;;
    esac
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent RUNNING the current event: the top-level `agent_type`, which the
# host adds only inside a subagent (empty on the main thread). Never confuse it
# with `nv_spawn_target_type` (H16). `nv_subagent_type` above keeps its legacy
# mixed behaviour for existing hooks; new code uses these two helpers.
nv_event_agent_type() {
  payload_field agent_type
}

# True for the spawn tool: Codex V1 `spawn_agent`, or any V2 name that ends in
# `spawn_agent` (V2 flattens the namespace into the tool name).
nv_is_spawn_tool() {
  case "$(payload_field tool_name)" in
    *spawn_agent) return 0 ;;
    *) return 1 ;;
  esac
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.

navori_audit_name="role-guard"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. Fork-free presence test: the main thread carries no top-level
# `agent_type`, so the substring test proves absence without a process.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

# Without jq or node the field reader is a sed fallback that cannot tell the
# top-level `agent_type` from `tool_input.agent_type`; a wrong guess would deny
# the main thread's own spawn. Let the call through instead (best-effort).
if ! command -v jq >/dev/null 2>&1 && ! command -v node >/dev/null 2>&1; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin jq ni node: payload ilegible"
  exit 0
fi

navori_role=$(nv_event_agent_type)
if [ -z "$navori_role" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="agent_type vacío (hilo principal)"
  exit 0
fi

block() {
  echo "[navori] BLOCKED by role-guard: $1" >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Spawn branch: BEFORE the role allow-list, so an `implementer` cannot dispatch
# a catch-all child either (challenge C2).
if nv_is_spawn_tool; then
  block "$navori_role no despacha subagentes (profundidad 1); el orquestador del hilo principal los lanza"
fi

if [ "$(nv_tool)" != "Edit" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="tool_name no cubierto"
  exit 0
fi

case "$navori_role" in
  implementer | scribe)
    navori_audit_verdict="skip"
    navori_audit_reason="rol exento"
    exit 0
    ;;
esac

# Prefixes the role may patch, one per line. The case is generated from
# `RosterAgent.writes`; nothing path-like is spelled in this asset.
nv_role_prefixes() {
  case "$1" in
    reviewer) printf '%s\n' '.navori/state/handoffs/' ;;
    scout) printf '%s\n' '.navori/state/handoffs/' 'specs/' ;;
    auditor) printf '%s\n' '.navori/state/handoffs/' 'specs/' ;;
    publisher) printf '%s\n' '.navori/state/handoffs/' ;;
    architect) printf '%s\n' '.navori/state/handoffs/' 'specs/' ;;
    *) printf '%s\n' '.navori/state/handoffs/' ;;
  esac
}

# Lexical normalization of an absolute path: drops `.` and empty segments and
# folds `..`. Written with parameter expansion only (no word splitting), so it
# behaves the same under bash and zsh.
nv_normalize() {
  local rest=${1#/} seg out=""
  while [ -n "$rest" ]; do
    case "$rest" in
      */*)
        seg=${rest%%/*}
        rest=${rest#*/}
        ;;
      *)
        seg=$rest
        rest=""
        ;;
    esac
    case "$seg" in
      "" | .) ;;
      ..) out=${out%/*} ;;
      *) out="$out/$seg" ;;
    esac
  done
  printf '%s' "${out:-/}"
}

# Physical form of an absolute normalized path: the nearest existing ancestor is
# resolved with `cd -P`, and the not-yet-existing tail is appended as written.
# Empty output means it could not be resolved.
nv_realdir() {
  local d=$1 suffix="" real parent
  while [ ! -e "$d" ] && [ ! -L "$d" ] && [ "$d" != "/" ]; do
    suffix="/${d##*/}$suffix"
    d=${d%/*}
    [ -n "$d" ] || d=/
  done
  if [ -d "$d" ]; then
    real=$(cd -P "$d" 2>/dev/null && pwd -P) || return 0
  else
    parent=${d%/*}
    [ -n "$parent" ] || parent=/
    real=$(cd -P "$parent" 2>/dev/null && pwd -P) || return 0
    real="${real%/}/${d##*/}"
  fi
  printf '%s' "${real%/}$suffix"
}

# Follow a leaf symlink chain (bounded) on top of `nv_realdir`.
nv_realpath() {
  local p=$1 n=0 target
  while :; do
    p=$(nv_realdir "$p")
    [ -n "$p" ] || return 0
    if [ -L "$p" ] && [ "$n" -lt 20 ]; then
      target=$(readlink "$p") || break
      case "$target" in
        /*) p=$(nv_normalize "$target") ;;
        *) p=$(nv_normalize "${p%/*}/$target") ;;
      esac
      n=$((n + 1))
    else
      break
    fi
  done
  printf '%s' "$p"
}

# 0 when the physical path sits under an OS temp root (resolved the same way, so
# `/tmp` -> `/private/tmp` and `$TMPDIR` -> `/private/var/folders/...` compare).
nv_in_temp() {
  local root real
  for root in /tmp /var/tmp "${TMPDIR:-}"; do
    [ -n "$root" ] || continue
    real=$(cd -P "$root" 2>/dev/null && pwd -P) || continue
    case "$1" in
      "${real%/}"/*) return 0 ;;
    esac
  done
  return 1
}

navori_cwd=$(payload_field cwd)
navori_cwd=${navori_cwd:-${nv_project_dir:-.}}
navori_root=$(cd -P "${nv_project_dir:-$navori_cwd}" 2>/dev/null && pwd -P) || navori_root=""
if [ -z "$navori_root" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="raíz del repo ilegible"
  exit 0
fi

navori_allowed=$(nv_role_prefixes "$navori_role")
navori_allowed_list=$(printf '%s' "$navori_allowed" | tr '\n' ' ')
navori_allowed_list=${navori_allowed_list% }

while IFS= read -r navori_path; do
  [ -n "$navori_path" ] || continue
  case "$navori_path" in
    /*) navori_abs=$(nv_normalize "$navori_path") ;;
    *) navori_abs=$(nv_normalize "$navori_cwd/$navori_path") ;;
  esac
  navori_real=$(nv_realpath "$navori_abs")
  if [ -z "$navori_real" ]; then
    block "$navori_role no escribe '$navori_path' (ruta no resoluble; permitido: $navori_allowed_list)"
  fi
  case "$navori_real" in
    "$navori_root"/*)
      navori_rel=${navori_real#"$navori_root"/}
      navori_ok=0
      while IFS= read -r navori_prefix; do
        [ -n "$navori_prefix" ] || continue
        navori_prefix=${navori_prefix%/}
        case "$navori_rel" in
          "$navori_prefix" | "$navori_prefix"/*)
            navori_ok=1
            break
            ;;
        esac
      done <<EOF
$navori_allowed
EOF
      if [ "$navori_ok" -ne 1 ]; then
        block "$navori_role no escribe '$navori_path' (permitido: $navori_allowed_list)"
      fi
      ;;
    "$navori_root")
      block "$navori_role no escribe '$navori_path' (permitido: $navori_allowed_list)"
      ;;
    *)
      if ! nv_in_temp "$navori_real"; then
        block "$navori_role no escribe '$navori_path' (fuera del repo; permitido: $navori_allowed_list)"
      fi
      ;;
  esac
done <<EOF
$(nv_edited_paths)
EOF

navori_audit_verdict="allow"
navori_audit_reason="rutas dentro del rol"
exit 0
# navori:managed end id="role-guard-base"
