# navori:managed start id="subagent-stop-handoff-base" hash="2ecc1d24" version="0.11.3" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse(`Agent`|`Task`) lifecycle hook — handoff validator.
# Fires in the PARENT session the moment a subagent returns. The harness contract
# is that an implementer closes with `impl_<feature>.md` and a reviewer with
# `review_<feature>.md` under the engine's progress dir — those files ARE the
# handoff the orchestrator (and the publisher) read. A subagent that returns
# having left an empty or structurally-broken handoff silently corrupts that
# chain. This hook catches the obvious failure modes deterministically.
#
# WHY NOT SubagentStop, the event this hook is still NAMED after (#774). The
# reader of this note is the ORCHESTRATOR, and SubagentStop cannot reach it: there the
# `additionalContext` goes to the subagent that just stopped — it keeps that
# child running — and the host's doc names the alternative outright, "to inject
# context into the parent session after a subagent returns, use a `PostToolUse`
# hook on the `Agent` tool instead". Registered on SubagentStop the only channel
# left was `systemMessage`, which the doc defines as a "warning message shown to
# the user", so a note written in the imperative to the model arrived at the
# human's UI and nowhere else.
#
# The move also settles the firing rate #560 measured: SubagentStop fired 117
# times for 19 subagents in one session, each firing re-reporting the identical
# handoff. A PostToolUse on the Agent tool fires exactly once per return.
#
# The id and the filename keep the old spelling on purpose: they are a managed
# marker stamped into every already-rendered repo and the name the audit log has
# recorded under for a year of sessions. Renaming them would buy tidiness and
# cost the continuity of the measurement.
#
# DESIGN — advisory, never blocking. Emits `hookSpecificOutput.additionalContext`
# for the orchestrator plus a `systemMessage` so the human sees it too; it NEVER
# returns `decision: block`.
#
# Since spec 0030 (#985, R10) it reads `tool_input.subagent_type` — the
# Agent/Task tool call's OWN parameter, mirrored into every PreToolUse/PostToolUse
# payload (https://code.claude.com/docs/en/hooks.md: "payload carries `tool_name`,
# `tool_input`, `session_id`, `cwd`"). This is NOT the `agent_id`/`agent_type` pair
# the same doc says is "present only when the hook fires inside a subagent call" —
# that pair answers "am I running INSIDE a subagent", a question this hook (firing
# on the PARENT's own PostToolUse(Agent|Task)) never needs to ask. `subagent_type`
# is simply the argument the orchestrator passed to dispatch, so it is present on
# this exact event regardless of nesting. So the hook now knows WHICH subagent
# just returned and demands the matching contract:
#   - `implementer` → `impl_*.json` (R2): missing, unparseable, a `status` other
#     than `DONE`/`BLOCKED`, or any required key absent.
#   - `scribe` → `impl_*.md` missing its terminal `Status:` marker.
#   - anything else — another role, another engine, or a payload where the field
#     is absent — falls back to checking BOTH shapes wherever a matching file
#     exists. That is the identity-blind behavior this hook always had, kept as
#     the safety net for what `subagent_type` doesn't cover.
# It also always flags, regardless of identity:
#   - empty / whitespace-only handoffs, OR
#   - `review_*.md` missing a verdict (APPROVED / CHANGES_REQUESTED).
# It never invents an expectation, so a legitimate report never trips it, and a
# missing file is not flagged (a subagent may not produce a handoff at all).
# Accepted limitation: during parallel work a still-in-flight report from
# ANOTHER running subagent could momentarily look incomplete — advisory-only, so
# a false positive is a harmless note, never a block.
#
# Spec 0039 R44 adds a second, independent lane: compaction advice (Claude only,
# main thread, after a `publisher` dispatch). It shares this hook's single output
# because one firing may carry at most one JSON document.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

# The payload was drained and discarded here; it is kept now because the audit
# recorder reads `session_id`/`cwd` out of it. Draining is still the point: an
# undrained stdin can leave the host writing into a closed pipe.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="subagent-stop-handoff"
navori_audit_phase="PostToolUse"

# Where the problem set last REPORTED in this session is remembered (#560).
#
# The 117-firings-for-19-subagents problem this was written for is gone: on
# PostToolUse(`Agent`) the host fires once per return (#774). The stamp STAYS,
# and the move is what makes it matter more rather than less. A broken handoff
# stays broken until somebody fixes it, so without this every later subagent
# return in the same session re-reports it — and the note now travels through
# `additionalContext`, i.e. it is spent out of the orchestrator's context window, not
# out of a UI line the host draws for free.
#
# Parsed with parameter expansion, never jq: this must work whether or not
# audit-mode is on, and jq may not exist. Keyed by session AND repo so two
# sessions never silence each other. In the OS temp dir, so nothing lands in the
# user's tree and a reboot is a clean slate.
# A raw, unexpanded asset must remain advisory rather than exiting 127.
# Rendered includes replace these no-ops with the shared Spec 0035 adapter.
payload_field() { :; }
nv_subagent_type() { :; }
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent a spawn call TARGETS, never the one that makes the call (spec 0041
# H16). Claude: `tool_input.subagent_type`. Codex PreToolUse/PostToolUse of a
# spawn: `tool_input.agent_type` only — the top-level `agent_type` there is the
# CALLER's. On `SubagentStop` the top-level `agent_type` IS the finishing
# subagent, so that event reads it instead.
nv_spawn_target_type() {
  if [ "$nv_engine" = codex ]; then
    case "$(payload_field hook_event_name)" in
      SubagentStop) payload_field agent_type ;;
      *) payload_field tool_input.agent_type ;;
    esac
  else
    payload_field tool_input.subagent_type
  fi
}

# The agent RUNNING the current event: the top-level `agent_type`, which the
# host adds only inside a subagent (empty on the main thread). Never confuse it
# with `nv_spawn_target_type` (H16). `nv_subagent_type` above keeps its legacy
# mixed behaviour for existing hooks; new code uses these two helpers.
nv_event_agent_type() {
  payload_field agent_type
}

# True for the spawn tool: Codex V1 `spawn_agent`, or any V2 name that ends in
# `spawn_agent` (V2 flattens the namespace into the tool name).
nv_is_spawn_tool() {
  case "$(payload_field tool_name)" in
    *spawn_agent) return 0 ;;
    *) return 1 ;;
  esac
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.
navori_audit_repo_from_cwd() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}

# Observe only native Codex child lifecycle payloads. The CLI validates source
# ownership/version and private marker identity; this guard only avoids spawning
# capture when the exact root session has not opted in. Never use the stop
# payload's common transcript_path: it belongs to the immediate parent.
navori_capture_child() {
  [ "${nv_engine:-}" = codex ] || return 0
  local event root_id child_id source audit_root repo
  event=$(payload_field hook_event_name)
  case "$event" in
    SubagentStart) source=$(payload_field transcript_path) ;;
    SubagentStop) source=$(payload_field agent_transcript_path) ;;
    *) return 0 ;;
  esac
  root_id=$(payload_field session_id)
  child_id=$(payload_field agent_id)
  case "$root_id" in "" | *[!A-Za-z0-9_-]*) return 0 ;; esac
  case "$child_id" in "" | *[!A-Za-z0-9_-]*) return 0 ;; esac
  [ -n "$source" ] || return 0
  audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    audit_root=$HOME/.navori/audits
  fi
  repo=$(navori_audit_repo_from_cwd "${nv_project_dir:-}")
  [ -n "$repo" ] || return 0
  [ -f "$audit_root/$repo/session-$root_id.log" ] || return 0
  [ ! -L "$audit_root/$repo/session-$root_id.log" ] || return 0
  command -v navori >/dev/null 2>&1 || return 0
  navori audit --capture-child "$child_id" --root-session "$root_id" \
    --rollout "$source" --cwd "${nv_cwd:-${nv_project_dir:-.}}" >/dev/null 2>&1 || true
  return 0
}
navori_capture_child || true
# Startup is observation-only, before handoff stamps/scans and the historical
# PostToolUse EXIT recorder. Missing sources retry at stop; never poll or wait.
[ "${2:-}" != capture-start ] || exit 0

navori_handoff_key=$(payload_field session_id)
case "$navori_handoff_key" in
  "" | *[!A-Za-z0-9_-]*) navori_handoff_key="anon" ;;
esac
navori_handoff_repo=${PWD##*/}
case "$navori_handoff_repo" in
  "" | *[!A-Za-z0-9_.-]*) navori_handoff_repo="repo" ;;
esac
navori_handoff_stamp="${TMPDIR:-/tmp}/navori-handoff-$navori_handoff_repo-$navori_handoff_key"

# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared advisory metadata recorder. The CLI is the single private-FD writer.
# No shell redirects, human content, or fallback writes are permitted here.
# Missing CLI or failed validation leaves an observation gap, never a hook failure.
# zsh replaces $0 with the function name; preserve the enclosing script identity.
navori_audit_script=$0
navori_audit_begin() {
  navori_audit_on=0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# Resolve one exact marker before invoking the metadata writer. Startup may
# offer a repo-scoped arm candidate; the CLI authoritatively validates private
# modes, ownership and header identity before either append or spool creation.
navori_audit_record_metadata() {
  [ -n "${payload:-}" ] || return 0
  navori_audit_root=${NAVORI_AUDITS_ROOT:-${HOME:-}/.navori/audits}
  [ -n "${HOME:-}${NAVORI_AUDITS_ROOT:-}" ] || return 0
  [ -d "$navori_audit_root" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  navori_audit_fields=$(printf '%s' "$payload" | jq -er '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    select(.session_id | id) |
    [.session_id, (if (.cwd | type) == "string" then .cwd else "" end),
     ([.agent_id, .subagent_id] | map(select(id)) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  case "$navori_audit_repo" in "" | . | .. | *[!A-Za-z0-9_.-]*) return 0 ;; esac
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log
  if [ ! -f "$navori_audit_file" ] || [ -L "$navori_audit_file" ]; then
    [ "${navori_audit_phase:-}" = SessionStart ] || return 0
    navori_audit_arm=$navori_audit_root/$navori_audit_repo/.armed
    [ -f "$navori_audit_arm" ] && [ ! -L "$navori_audit_arm" ] || return 0
  fi
  command -v navori >/dev/null 2>&1 || return 0
  case "${nv_engine:-}" in
    claude | codex) navori_audit_host=$nv_engine ;;
    *) case "$navori_audit_script" in *".codex/hooks/"* | *".codex/scripts/"*) navori_audit_host=codex ;; *) navori_audit_host=claude ;; esac ;;
  esac
  # The writer assigns eventId/wireVersion before first persistence. Replay
  # keeps those identifiers; this transport never generates replacement IDs.
  printf '%s' "$1" | navori audit --record-metadata --host "$navori_audit_host" \
    --root-session "$navori_audit_session" --repo "$navori_audit_repo" \
    --root "$navori_audit_root" >/dev/null 2>&1 || :
  return 0
}

# Only closed categories and bounded technical identifiers cross this bridge.
# Args: verdict, reason, kind. `reason` is recorded only when it is one of the
# allowlisted codes below (mirrored by HOOK_REASON_CODES in lib/audit/model.ts,
# pinned by a drift test); any other non-empty text is stored as "unspecified".
# `kind` defaults from the verdict (block -> hard, ask -> ask); `deny` stays
# explicit because the confirm hooks use it as deny-as-confirmation on Codex.
navori_audit_log() {
  [ "${navori_audit_on:-0}" = 1 ] || return 0
  command -v jq >/dev/null 2>&1 || return 0
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = 1 ]; then
    case "${1:-}" in skip | noop) return 0 ;; esac
  fi
  navori_audit_end=$(navori_audit_now)
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0
  navori_audit_metadata=$(printf '%s' "${payload:-}" | jq -c \
    --arg name "${navori_audit_name:-unknown}" --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" --arg source "${navori_audit_source:-core}" \
    --arg kind "${3:-}" --argjson ms "$navori_audit_ms" --argjson tsMs "$navori_audit_end" '
    def id: type == "string" and length > 0 and length <= 256 and test("^[A-Za-z0-9_-]+$");
    def technical_label: if length <= 256 and test("^[A-Za-z0-9_.:-]+$") then . else "unknown" end;
    {event:"hook",name:($name|technical_label),source:($source|technical_label),ms:$ms,tsMs:$tsMs,
     phase:(if (["PreToolUse","PostToolUse","SessionStart","SessionEnd","Stop","SubagentStart","SubagentStop","UserPromptSubmit","PreCompact"]|index($phase)) != null then $phase else "unknown" end),
     verdict:(if (["allow","ask","block","deny","skip","noop","clean","dirty","inject","repeat","partial","compact-advice","gate-started","gate-killed"]|index($verdict)) != null then $verdict else "unknown" end),
     agentId:(([.agent_id,.subagent_id]|map(select(id))|first)//"orchestrator")}
     + (if (.tool_use_id|id) then {toolUseId:.tool_use_id} else {} end)
     + (if (["Bash","Edit","Read","Write","Agent","Task","NotebookEdit"]|index($tool)) != null then {tool:$tool} else {} end)
     + (if $reason == "" then {}
        elif (["oversize","no-verify","force-push-base","rm-root","rm-var","no-preserve-root","fork-bomb","block-device","managed-rewrite","binary-missing","plan-denied","subcommand-unavailable","native-hook"]|index($reason)) != null then {reason:$reason}
        else {reason:"unspecified"} end)
     + (($kind | if . == "" then (if $verdict == "block" then "hard" elif $verdict == "ask" then "ask" else "" end) else . end) as $k
        | if (["hard","ask","advisory"]|index($k)) != null then {kind:$k} else {} end)' 2>/dev/null) || return 0
  navori_audit_record_metadata "$navori_audit_metadata"
  return 0
}
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


# Resolve the neutral handoff root plus the two one-release legacy roots.
# `placeHook` copies this body verbatim for every engine, so no engine-specific
# retargeting is involved. Bare `progress/` remains a historical fallback.
#
# EVERY existing dir is scanned, not the first one found: a repo that renders
# both engines has both, and picking one by probe order would make the hook
# blind to whichever engine happens to come second. An ARRAY, never an unquoted
# string: word-splitting a `$dirs` string is a no-op under zsh, which is how the
# receipt backstop silently stopped scanning (#344).
dirs=()
for d in ".navori/state/handoffs" ".claude/progress" ".codex/progress" "progress"; do
  [ -d "$d" ] && dirs+=("$d")
done

# Is a file empty or whitespace-only?
is_blank() { ! grep -q '[^[:space:]]' "$1" 2>/dev/null; }

problems=""
# Spec 0039 R26: the stamp identifies a report by (path, content), not by the
# problem text alone. `navori_fingerprint` accumulates one POSIX `cksum` of each
# flagged file (`$f`, set by every caller before `note`), so the SAME handoff
# reported twice is one warning, while a rewrite that still has the same problem
# is news and warns again. `cksum` reads the file once, no fork beyond itself.
navori_fingerprint=""
note() {
  problems="${problems}${problems:+; }$1"
  navori_fingerprint="${navori_fingerprint}$(cksum <"${f:-/dev/null}" 2>/dev/null | tr ' ' '-');"
}

# Spec 0035 D2 owns Claude/Codex subagent normalization and the single stdin
# drain through extract-cmd; this hook must not grow a second payload parser.
navori_subagent_type=$(nv_subagent_type)

# Spec 0039 R42: only the parent's foreground PostToolUse(Agent) response
# carries the host's turn-limit marker. A missing handoff is not evidence of
# truncation, and background/SendMessage completions do not reach this event.
navori_partial_msg=""
if [ "${1:-}" != "codex" ] && [ "${nv_engine:-claude}" != "codex" ] &&
  [ -z "$(payload_field agent_id)" ] &&
  [[ "$payload" == *"stopped at its "* ]] && command -v node >/dev/null 2>&1; then
  navori_partial_found=$(printf '%s' "$payload" | node -e '
    let event;
    try { event = JSON.parse(require("fs").readFileSync(0, "utf8")); } catch { process.exit(0); }
    if (event.hook_event_name !== "PostToolUse" || event.tool_name !== "Agent" ||
        event.tool_input?.run_in_background === true) process.exit(0);
    const content = event.tool_response?.content;
    if (Array.isArray(content) && content.some((item) =>
      item?.type === "text" && typeof item.text === "string" &&
      /\bstopped at its \d+-turn limit\b/.test(item.text))) process.stdout.write("yes");
  ' 2>/dev/null) || navori_partial_found=""
  if [ "$navori_partial_found" = "yes" ]; then
    navori_partial_msg="navori: handoff PARCIAL de ${navori_subagent_type:-subagente} — alcanzó su límite de turnos. Continúa con SendMessage para conservar su estado; usa un redespacho fresco solo si el trabajo restante está acotado."
  fi
fi

# Spec 0039 R44 — compaction advice lane. Claude mode only (Codex has no
# PostToolUse context channel), main thread only (`agent_id` is present just
# inside a subagent) and only when the dispatch that returned is the `publisher`:
# the end of a cycle is the cheap moment to compact. `usage` comes from the LAST
# COMPLETE transcript line in a 256 KB tail (the writer may be mid-line, and the
# tail's first line is cut by construction), so unparseable lines are skipped.
# The threshold is `harness.compactAdviceTokens`; an unrendered or non-numeric
# value (harness section absent) falls back to 175000, `0` turns the lane off.
navori_compact_msg=""
navori_compact_threshold='175000'
case "$navori_compact_threshold" in
  "" | *[!0-9]*) navori_compact_threshold=175000 ;;
esac
navori_compact_mark="${TMPDIR:-/tmp}/navori-compact-$navori_handoff_repo-$navori_handoff_key"
navori_compact_done=""
{ IFS= read -r navori_compact_done <"$navori_compact_mark"; } 2>/dev/null ||
  navori_compact_done=""
if [ "${1:-}" != "codex" ] && [ "${nv_engine:-claude}" != "codex" ] &&
  [ "$navori_compact_threshold" -gt 0 ] && [ "$navori_subagent_type" = "publisher" ] &&
  [ -z "$(payload_field agent_id)" ] && [ -z "$navori_compact_done" ] &&
  command -v node >/dev/null 2>&1; then
  navori_compact_tp=$(payload_field transcript_path)
  navori_compact_total=""
  if [ -n "$navori_compact_tp" ]; then
    navori_compact_total=$(tail -c 262144 "$navori_compact_tp" 2>/dev/null | node -e '
      const lines = require("fs").readFileSync(0, "utf-8").split("\n");
      for (let i = lines.length - 1; i >= 0; i--) {
        let o;
        try { o = JSON.parse(lines[i]); } catch { continue; }
        const u = (o && o.message && o.message.usage) || (o && o.usage);
        if (!u || typeof u !== "object") continue;
        const n = (k) => (typeof u[k] === "number" ? u[k] : 0);
        process.stdout.write(String(n("input_tokens") + n("cache_read_input_tokens") + n("cache_creation_input_tokens")));
        break;
      }
    ' 2>/dev/null) || navori_compact_total=""
  fi
  case "$navori_compact_total" in
    "" | *[!0-9]*) ;;
    *)
      if [ "$navori_compact_total" -gt "$navori_compact_threshold" ]; then
        navori_compact_msg="navori: el contexto del hilo principal va en ${navori_compact_total} tokens (umbral ${navori_compact_threshold}). Guarda el resumen de la sesión y usa /compact o /clear antes del siguiente ciclo."
      fi
      ;;
  esac
fi

# R2's contract: `impl_<feature>.json` must parse and carry every required key
# with a valid `status`. Validated with node (already required by navori) → a
# grep-based key sweep when it is missing, same fail-open posture as the rest
# of this file: no new dependency, and an unparseable environment still gets a
# best-effort check instead of silence.
navori_check_impl_json() {
  f="$1"
  if is_blank "$f"; then
    note "$f vacío"
    return
  fi
  if command -v node >/dev/null 2>&1; then
    navori_json_verdict=$(node -e '
      const fs = require("fs");
      let data;
      try {
        data = JSON.parse(fs.readFileSync(process.argv[1], "utf-8"));
      } catch {
        process.stdout.write("parse");
        process.exit(0);
      }
      const required = ["feature","status","worktree","branch","commits","filesTouched","verification","markdownRequests"];
      const missing = required.filter((k) => !(k in data));
      if (missing.length > 0) {
        process.stdout.write("missing:" + missing.join(","));
        process.exit(0);
      }
      if (data.status !== "DONE" && data.status !== "BLOCKED") {
        process.stdout.write("status");
        process.exit(0);
      }
      process.stdout.write("ok");
    ' "$f" 2>/dev/null) || navori_json_verdict="parse"
  else
    navori_json_verdict="ok"
    navori_json_missing=""
    for navori_json_key in feature status worktree branch commits filesTouched verification markdownRequests; do
      grep -q "\"$navori_json_key\"[[:space:]]*:" "$f" 2>/dev/null \
        || navori_json_missing="${navori_json_missing}${navori_json_missing:+,}$navori_json_key"
    done
    if [ -n "$navori_json_missing" ]; then
      navori_json_verdict="missing:$navori_json_missing"
    elif ! grep -qE '"status"[[:space:]]*:[[:space:]]*"(DONE|BLOCKED)"' "$f" 2>/dev/null; then
      navori_json_verdict="status"
    fi
  fi
  case "$navori_json_verdict" in
    ok) ;;
    parse) note "$f no parsea como JSON" ;;
    status) note "$f con 'status' inválido (no DONE/BLOCKED)" ;;
    missing:*) note "$f sin clave '${navori_json_verdict#missing:}'" ;;
    *) note "$f no parsea como JSON" ;;
  esac
}

# R10's `scribe` half: same `Status:` check R5's `.md` handoff always had.
navori_check_impl_md() {
  f="$1"
  if is_blank "$f"; then
    note "$f vacío"
  elif ! grep -qiE '^\*{0,2}status:?\*{0,2}' "$f" 2>/dev/null; then
    note "$f sin línea 'Status:'"
  fi
}

# Only handoffs touched inside this window are checked (48h in minutes).
#
# The hook fires as a subagent returns, so the handoff it exists to police is
# the one just written. It used to check the WHOLE directory, which nothing prunes, and
# that broke it three ways on every repo measured (#606):
#
#   1. Handoffs written under an older format failed forever — 44 files in one
#      repo, 19 in another. The `clean` verdict this script calls "the whole
#      value of recording this hook" was unreachable in all four.
#   2. The stamp compares the full problem string, so a genuinely broken new
#      handoff injected N+1 paths (44 of them from August in one repo) and
#      fixing it re-injected the N old ones. The real warning arrived buried.
#   3. Two greps per file, unbounded: the median run tracked the file count
#      almost linearly — 46 files/165ms, 57/197ms, 80/333ms, 138/419ms — making
#      this the most expensive hook of the six, the other five sitting at
#      16-59ms.
#
# 48h and not less because a session can be long (10h41m measured) and a handoff
# written early in one must still be checked when it ends. Everything older is
# closed work: PRs in the repo this was measured on merge in under 10 hours,
# p90 8.5h.
HANDOFF_WINDOW_MIN=2880

# `find` replaces the globs rather than filtering inside them: it does the
# selection in ONE fork per directory instead of two greps per stale file, which
# is the cost above. Read through `while read` (not `$(...)` word-splitting) so
# a path with spaces survives, and via process substitution so `note` writes to
# the real `problems` and not to a subshell's copy.
#
# Reports are named by their PATH, not their basename: with more than one
# progress dir in play, `impl_x.md` alone wouldn't say which one to open.
#
# Which shape gets checked is now gated on `$navori_subagent_type` (R10): the
# `implementer` only ever produces `.json` under R2, the `scribe` only `.md`
# under R5, and everyone else (or a payload the field never reached) falls back
# to checking whichever of the two exists — the identity-blind behavior this
# hook always had.
# An empty `dirs` is no longer an early exit: the compaction lane above does
# not depend on any handoff directory existing. Guarded, not iterated blindly,
# because expanding an empty array under `set -u` fails on bash < 4.4.
for dir in ${dirs[@]+"${dirs[@]}"}; do
  case "$navori_subagent_type" in
    implementer)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_json "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.json' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
    scribe)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_md "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
    *)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_json "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.json' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_md "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
  esac
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qE 'APPROVED|CHANGES_REQUESTED' "$f" 2>/dev/null; then
      note "$f sin veredicto (APPROVED/CHANGES_REQUESTED)"
    fi
  done < <(find "$dir" -maxdepth 1 -name 'review_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
done

# `clean` vs `dirty` is the whole value of recording this hook: it is the only
# evidence that the handoff check RAN and found nothing, as opposed to never
# having run at all.
#
# One firing, one JSON document: the handoff warning and the compaction advice
# (R44) are emitted separately by exactly one path each, never both. A repeat or
# clean handoff still lets the compaction advice through; a NEW handoff warning
# carries the advice appended to its own message. `navori_emit` returns 0 only
# when the document was written, so neither the handoff stamp nor the
# once-per-session compaction mark records an undelivered warning.
navori_mode="${1:-}"
navori_emit() {
  local m="$1" out=""
  if command -v node >/dev/null 2>&1; then
    out=$(MSG="$m" node -e 'const m=process.env.MSG;process.stdout.write(JSON.stringify(process.argv[1]==="codex"?{systemMessage:m}:{systemMessage:m,hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:m}}))' "$navori_mode" 2>/dev/null) || out=""
  fi
  if [ -z "$out" ] && command -v jq >/dev/null 2>&1; then
    if [ "$navori_mode" = "codex" ]; then
      out=$(jq -n --arg m "$m" '{systemMessage:$m}' 2>/dev/null) || out=""
    else
      out=$(jq -n --arg m "$m" '{systemMessage:$m,hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$m}}' 2>/dev/null) || out=""
    fi
  fi
  [ -n "$out" ] && printf '%s\n' "$out"
}
# Emits the compaction advice alone and marks the session as advised.
navori_emit_advice() {
  local advice="$navori_partial_msg"
  if [ -n "$navori_compact_msg" ]; then
    advice="${advice}${advice:+ }${navori_compact_msg}"
  fi
  [ -n "$advice" ] || return 0
  if navori_emit "$advice"; then
    if [ -n "$navori_compact_msg" ]; then
      printf '1\n' >"$navori_compact_mark" 2>/dev/null || true
      navori_audit_verdict="compact-advice"
      navori_audit_reason="$navori_compact_total"
    elif [ -n "$navori_partial_msg" ]; then
      navori_audit_verdict="partial"
      navori_audit_reason="$navori_subagent_type"
    fi
  fi
  return 0
}

if [ -z "$problems" ]; then
  # Emptying the stamp is what keeps a RECURRENCE audible: the same problem
  # coming back after being fixed is news, and a stamp left behind would
  # swallow it. Truncated rather than deleted — one redirection, no process,
  # and no delete inside a hook that runs in the user's repo.
  : >"$navori_handoff_stamp" 2>/dev/null || true
  navori_audit_verdict="clean"
  navori_emit_advice
  exit 0
fi

# Same problem set as the previous firing of this session → the message was
# already delivered. The run is still RECORDED (verdict `repeat`), because "the
# check ran and found the same thing" is evidence the audit needs; what is
# skipped is only the injection.
#
# Read WITHOUT testing the path first, and that is deliberate: a failed
# redirection already answers "no stamp yet", and this script must keep having
# no existence test in it. `hook-claims-vs-scripts.test.ts` reads that absence
# as proof that the hook cannot notice a handoff that never landed — a `-f`
# here, on an unrelated file, would silently license every asset that claims it
# does.
#
# stderr is silenced AROUND THE GROUP, not on the `read`. Redirections are
# applied left to right, so `read … <"$stamp" 2>/dev/null` opens the input
# first: when the stamp does not exist yet the shell's "no such file" is
# written before anything has redirected stderr, which printed one line of noise
# on the first firing of every session under both bash and zsh.
navori_handoff_prev=""
{ IFS= read -r navori_handoff_prev <"$navori_handoff_stamp"; } 2>/dev/null ||
  navori_handoff_prev=""
navori_handoff_sig="${problems}|${navori_fingerprint}"
if [ "$navori_handoff_prev" = "$navori_handoff_sig" ]; then
  navori_audit_verdict="repeat"
  navori_audit_reason="$problems"
  navori_emit_advice
  exit 0
fi
msg="navori: handoff(s) de subagente incompletos — ${problems}. Revisa que el reporte quedó bien escrito antes de consolidarlo."
if [ -n "$navori_partial_msg" ]; then
  msg="${msg} ${navori_partial_msg}"
fi
if [ -n "$navori_compact_msg" ]; then
  msg="${msg} ${navori_compact_msg}"
fi

# BOTH channels, and they are not redundant: `additionalContext` is the one that
# reaches the orchestrator — the only reader that can act on this — while
# `systemMessage` is what puts it in front of the human. The text is imperative
# because it asks for an action; before #774 it went out on the user channel
# alone, so it asked the model for something the model never heard.
if navori_emit "$msg"; then
  printf '%s\n' "$navori_handoff_sig" >"$navori_handoff_stamp" 2>/dev/null || true
  if [ -n "$navori_compact_msg" ]; then
    printf '1\n' >"$navori_compact_mark" 2>/dev/null || true
  fi
fi
navori_audit_verdict="dirty"
navori_audit_reason="$problems"
exit 0
# navori:managed end id="subagent-stop-handoff-base"
