#!/usr/bin/env bash
# Generated by @navori/plugin-jscpd. Runs jscpd over TS/TSX files changed vs
# the configured base branch. Skips silently if jscpd or git are absent — the
# tool is optional, not a hard dependency of the project.
#
# Triggered as a PreToolUse(Bash) hook, gated to git commit — so the
# duplication check runs right before code lands, not on every turn.

set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# navori:include extract-cmd
cmd=$(extract_cmd)

navori_audit_name="check-jscpd"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# `source` names the PLUGIN, not core: disabling a plugin changes which hooks
# run, and without this the report cannot explain why a phase thinned out
# between two sessions.
navori_audit_source="plugin:jscpd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# Same shape as quality-gate-pre-commit: fires on every Bash call, works on
# almost none, so the verdict comes from the exit code rather than from a call
# per branch.
navori_audit_on_exit() {
  navori_audit_code=$?
  # A cancelled hook reaches this trap with `$?` == 0 (#797), so the exit code
  # below cannot tell "finished green" from "was killed mid-scan". The signal
  # handler can, and it already recorded the run.
  if [ -n "${navori_audit_signal:-}" ]; then
    return 0
  fi
  if [ "$navori_audit_code" -eq 0 ]; then
    navori_audit_log "allow" || true
  else
    # `navori_jscpd_block_reason` names the actual cause (e.g. a jscpd binary
    # that lacks the flags this hook needs) when the capability probe below
    # sets it; otherwise the audit log falls back to the generic reason.
    navori_audit_log "block" "${navori_jscpd_block_reason:-el escaneo de jscpd no paso}" || true
  fi
  return 0
}
trap navori_audit_on_exit EXIT
# Signal traps (TERM/INT/HUP) + `navori_audit_signal`. Shared body, single
# source of truth: the three gates are killed the same way and must record it
# the same way.
# navori:include audit-signal

# Gate to `git commit` only (this copy runs on commit, not push). $TRIGGER_RE is
# consumed by the shared detector inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Literal substrings every branch of $TRIGGER_RE needs; read by the fast
# path in the shared detector below (spec 0016). Keep NEXT to the regex:
# a branch added there without its token here silently loses the shortcut
# (fail-open to the slow path), and the inlined tests pin the pairing.
TRIGGER_TOKENS='commit'
# navori:include gate-trigger

# Resolution of the working tree the commit acts on (#454). Shared body.
# navori:include resolve-worktree

# Baseline resolution + the list of files in scope (#777). Shared body with
# check-semgrep, so the two scanners can never disagree about what they compare
# against or about which files they read. `$navori_scan_label` names this hook
# in its messages.
#
# THE UNTRACKED DECISION (#777), written here because it is this hook's whole
# second chance: jscpd gates `git commit` and nothing else, while semgrep also
# gates `git push` and `gh pr create`. So a new file that slipped past semgrep
# at commit time is still caught on the push; one that slips past jscpd is
# never looked at again, and duplicated new code lands unseen. Two ways to fix
# it: include untracked files in the scan, or add a push trigger. This hook
# takes the FIRST — it closes the hole in the layer where it lives (the scan
# reads what the commit is about to contain), it is symmetric with semgrep so
# one shared partial serves both, and it does not make a duplication check fire
# on an operation that adds no code. Revisit only if commits start landing
# content that is neither tracked nor untracked at hook time.
navori_scan_label="jscpd"
# navori:include scan-scope

# No command extracted (empty $cmd) → run unconditionally. A real command that
# is NOT a git commit → skip. Anything else → fall through and scan.
if [ -n "$cmd" ] && ! is_scan_trigger "$cmd"; then
  exit 0
fi

# Resolve jscpd: prefer the repo-pinned binary (node_modules/.bin) over a global
# one. A global jscpd can be a DIFFERENT major (e.g. 4.x vs the repo's 5.x) whose
# tokenizer reports different duplication than `pnpm run dup`, so the commit gate
# would measure something other than what the repo declares. Local-first fixes it.
# Availability is settled BEFORE the tree is resolved: a missing tool is the
# cheapest reason to stop, and it must not be masked by a tree that fails to
# resolve.
JSCPD_BIN=""
hook_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$hook_root" ] && [ -x "$hook_root/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$hook_root/node_modules/.bin/jscpd"
elif command -v jscpd >/dev/null 2>&1; then
  JSCPD_BIN="jscpd"
fi
if [ -z "$JSCPD_BIN" ]; then
  echo "⊘ jscpd not available (neither pinned in the repo nor installed globally) — skip (install: pnpm add -D jscpd)" >&2
  exit 0
fi

# Run from the tree the commit acts on — NOT from the hook process's cwd, which
# is the main repo even when the diff lives in an agent worktree (#454). Also
# keeps changed paths relative, so a repo path with spaces stays robust; the
# NUL-delimited read handles spaces in filenames, and the
# `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
tree=$(navori_worktree)
if [ -z "$tree" ]; then
  echo "⊘ jscpd: no git working tree resolved for this command — skip" >&2
  exit 0
fi
cd "$tree"

# Now that the tree is known, its OWN pinned binary wins: same rationale as
# above — measure what the scanned repo declares, not what the repo the hook
# process happens to sit in does.
if [ -x "$tree/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$tree/node_modules/.bin/jscpd"
fi

# branchBase is shell-quoted at render time via the shq: marker (#197/#249):
# hostile values in navori.config.json land here as inert literals, never
# executable (this hook runs on every git commit via PreToolUse(Bash)).
base={{shq:branchBase}}

if ! navori_resolve_base; then
  echo "⊘ neither 'origin/$base' nor '$base' exists in $tree — skip jscpd" >&2
  exit 0
fi

if ! navori_collect_scan_files; then
  echo "✗ jscpd: listing the changed files FAILED (exit ${scan_files_status:-unknown}) in $tree — NOTHING was scanned" >&2
  echo "  this is not a duplication verdict: no file was compared against $base_ref" >&2
  exit 1
fi

# An empty scan is NOT a silent green (#454): say which tree and which base
# produced it, so "there was nothing to scan" reads differently from "I scanned
# and found nothing".
if [ ${#files[@]} -eq 0 ]; then
  echo "⊘ jscpd: 0 files to scan — no *.ts/*.tsx differ from $base_ref in $tree" >&2
  exit 0
fi

echo "▶ jscpd: ${#files[@]} changed file(s) vs $base_ref in $tree" >&2

# Capability probe (only reached when there are files to scan): jscpd added
# `--baseline-from-ref`/`--fail-on-new-clones` in 5.1.1. A binary older than
# that silently ignores or rejects the flags this hook depends on, and its
# own `--version` self-report is not reliable enough to gate on (5.1.0
# prints `cpd 5.0.16`) — so the question is asked directly, of the actual
# binary, via `--help`.
#
# Captured to a variable and matched with `case`, never piped into `grep -q`:
# under `set -o pipefail` a `grep -q` that finds its match early closes the
# pipe, jscpd gets SIGPIPE, and the probe would misread a supported binary as
# unsupported.
navori_jscpd_help=$("$JSCPD_BIN" --help 2>&1 || true)
navori_jscpd_has_baseline=0
navori_jscpd_has_new_clones=0
case "$navori_jscpd_help" in
  *--baseline-from-ref*) navori_jscpd_has_baseline=1 ;;
esac
case "$navori_jscpd_help" in
  *--fail-on-new-clones*) navori_jscpd_has_new_clones=1 ;;
esac
if [ "$navori_jscpd_has_baseline" -ne 1 ] || [ "$navori_jscpd_has_new_clones" -ne 1 ]; then
  navori_jscpd_block_reason="jscpd binario sin --baseline-from-ref/--fail-on-new-clones (< 5.1.1)"
  echo "✗ jscpd: $JSCPD_BIN lacks --baseline-from-ref/--fail-on-new-clones (needs jscpd >= 5.1.1) — upgrade it (global: pnpm add -g jscpd@^5.1.1 · repo-pinned: pnpm add -D jscpd@^5.1.1) — BLOCKED, this is not a duplication verdict" >&2
  exit 2
fi

tmpdir=$(mktemp -d)
# COMPOSED, not replaced: bash keeps exactly ONE EXIT trap, so a bare
# `trap 'rm -rf ...' EXIT` here silently discards the audit recorder installed
# above — and it does so precisely on the path where this hook does real work,
# which is the one worth recording. The cleanup runs first so the temp dir goes
# away even if the recorder were ever to hang.
trap 'rm -rf "$tmpdir"; navori_audit_on_exit' EXIT

# The host can kill this process at its hook timeout, before any trap records a
# verdict. Persist a start marker first; audit correlates it with the terminal
# record by tool_use_id and reports an unfinished gate. #797 brought it here
# from `quality-gate-pre-commit`, the only gate that had one: for the other two
# a SIGKILL was undetectable, so the detector covered one gate of three.
navori_audit_log "gate-started" "inicio del escaneo de jscpd" || true

# `>&2` is not cosmetic (#510): a PreToolUse hook shows the user its stderr and
# swallows its stdout, so the console reporter's clone table — the whole point
# of the gate — used to be written where nobody could read it.
scan_status=0
"$JSCPD_BIN" \
  --min-tokens 100 \
  --min-lines 10 \
  --mode strict \
  --baseline-from-ref "$base_sha" \
  --fail-on-new-clones 0 \
  --reporters console \
  --output "$tmpdir" \
  -- "${files[@]}" >&2 || scan_status=$?

# PreToolUse EXIT CONTRACT (#510). Claude Code blocks a tool call ONLY on exit
# 2; every other non-zero code is shown to the user and the call PROCEEDS. This
# script used to END on the `jscpd` invocation, so `set -e` handed jscpd's own
# code straight through — and jscpd maps "new clones" to 1. The gate printed a
# progress line and blocked exactly nothing.
#
# The explicit `0` after `--fail-on-new-clones` and the `--` before the paths
# are both load-bearing: the flag is `[<N>]`-greedy and swallows the first path
# as its own value when either is missing, turning it into a jscpd usage error
# (exit 2, read below as "not a verdict") — the gate would then silently stop
# blocking new clones instead of announcing it.
#
# TODO(fidelity): jscpd spends exit 1 on BOTH "new clones" and an internal
# crash, so a crash is read here as a duplication verdict and blocks. That is
# the strict direction, and it is the ceiling of this mapping — split it if
# jscpd ever gives the two outcomes distinct codes, or if a crash starts firing
# often enough to teach people to route around the gate.
if [ "$scan_status" -eq 0 ]; then
  echo "✓ jscpd: ${#files[@]} file(s) scanned — no new clones vs $base_ref" >&2
  exit 0
fi
if [ "$scan_status" -eq 1 ]; then
  echo "✗ jscpd: new clones vs $base_ref — BLOCKED" >&2
  exit 2
fi
echo "✗ jscpd: the run FAILED with exit $scan_status (not a duplication verdict) — nothing was validated" >&2
exit 1
