#!/usr/bin/env bash
# Generated by @navori/plugin-jscpd. Runs jscpd over TS/TSX files changed vs
# `{{branchBase}}`. Skips silently if jscpd or git are absent — the tool is
# optional, not a hard dependency of the project.
#
# Triggered as a PreToolUse(Bash) hook, but only fires on `git commit` /
# `git push` (the gate is inline below).

set -euo pipefail

cmd=$(jq -r '.tool_input.command // empty' 2>/dev/null || true)
case "$cmd" in
  'git commit'*|'git push'*) ;;
  *) exit 0 ;;
esac

if ! command -v jscpd >/dev/null 2>&1; then
  echo "⊘ jscpd no instalado localmente — skip (install: pnpm add -g jscpd)" >&2
  exit 0
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

if ! git rev-parse --verify {{branchBase}} >/dev/null 2>&1; then
  echo "⊘ branch '{{branchBase}}' no existe localmente — skip jscpd" >&2
  exit 0
fi

files=$(git diff --name-only --diff-filter=ACMRT {{branchBase}} 2>/dev/null | grep -E '\.tsx?$' || true)
if [ -z "$files" ]; then
  echo "✓ jscpd: sin cambios vs {{branchBase}}" >&2
  exit 0
fi

count=$(echo "$files" | wc -l | tr -d ' ')
echo "▶ jscpd: $count archivo(s) modificados vs {{branchBase}}" >&2

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

echo "$files" | xargs jscpd \
  --min-tokens 100 \
  --min-lines 10 \
  --mode strict \
  --threshold 3 \
  --reporters console \
  --output "$tmpdir"
