#!/usr/bin/env bash
# Generated by @navori/plugin-jscpd. Runs jscpd over TS/TSX files changed vs
# the configured base branch. Skips silently if jscpd or git are absent — the
# tool is optional, not a hard dependency of the project.
#
# Triggered as a PreToolUse(Bash) hook, gated to git commit — so the
# duplication check runs right before code lands, not on every turn.

set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# navori:include extract-cmd

# Gate to `git commit` only (this copy runs on commit, not push). $TRIGGER_RE is
# consumed by the shared detector inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# navori:include gate-trigger

# Resolution of the working tree the commit acts on (#454). Shared body.
# navori:include resolve-worktree

# No command extracted (empty $cmd) → run unconditionally. A real command that
# is NOT a git commit → skip. Anything else → fall through and scan.
if [ -n "$cmd" ] && ! is_scan_trigger "$cmd"; then
  exit 0
fi

# Resolve jscpd: prefer the repo-pinned binary (node_modules/.bin) over a global
# one. A global jscpd can be a DIFFERENT major (e.g. 4.x vs the repo's 5.x) whose
# tokenizer reports different duplication than `pnpm run dup`, so the commit gate
# would measure something other than what the repo declares. Local-first fixes it.
# Availability is settled BEFORE the tree is resolved: a missing tool is the
# cheapest reason to stop, and it must not be masked by a tree that fails to
# resolve.
JSCPD_BIN=""
hook_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$hook_root" ] && [ -x "$hook_root/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$hook_root/node_modules/.bin/jscpd"
elif command -v jscpd >/dev/null 2>&1; then
  JSCPD_BIN="jscpd"
fi
if [ -z "$JSCPD_BIN" ]; then
  echo "⊘ jscpd not available (neither pinned in the repo nor installed globally) — skip (install: pnpm add -D jscpd)" >&2
  exit 0
fi

# Run from the tree the commit acts on — NOT from the hook process's cwd, which
# is the main repo even when the diff lives in an agent worktree (#454). Also
# keeps changed paths relative, so a repo path with spaces stays robust; the
# NUL-delimited read handles spaces in filenames, and the
# `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
tree=$(navori_worktree)
if [ -z "$tree" ]; then
  echo "⊘ jscpd: no git working tree resolved for this command — skip" >&2
  exit 0
fi
cd "$tree"

# Now that the tree is known, its OWN pinned binary wins: same rationale as
# above — measure what the scanned repo declares, not what the repo the hook
# process happens to sit in does.
if [ -x "$tree/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$tree/node_modules/.bin/jscpd"
fi

# branchBase / jscpdThreshold are shell-quoted at render time via the shq:
# marker (#197/#249): hostile values in navori.config.json land here as inert
# literals, never executable (this hook runs on every git commit via
# PreToolUse(Bash)).
base={{shq:branchBase}}
threshold={{shq:jscpdThreshold}}

if ! git rev-parse --verify "$base" >/dev/null 2>&1; then
  echo "⊘ branch '$base' does not exist in $tree — skip jscpd" >&2
  exit 0
fi

# `git diff` runs inside a process substitution, whose exit status the shell
# never reports, and its stderr used to go to /dev/null — so a diff that FAILED
# (exit 128: unborn HEAD, a corrupt index, a base that vanished mid-run)
# produced zero records and was indistinguishable from "nothing changed": the
# hook printed `0 files to scan` and exited 0 (#511). The sentinel carries the
# status back out of the subshell. It can never collide with a real record: the
# pathspec restricts the list to `*.ts`/`*.tsx`.
diff_sentinel='@navori-diff-status:'
diff_status=""
files=()
while IFS= read -r -d '' f; do
  case "$f" in
    "${diff_sentinel}"*) diff_status="${f#"${diff_sentinel}"}"; continue ;;
  esac
  files+=("$f")
done < <(
  # `|| diff_rc=$?` and not a bare `$?`: the subshell inherits `set -e`, which
  # would kill it on a failing `git diff` before the sentinel is ever written.
  diff_rc=0
  git diff --name-only -z --diff-filter=ACMRT "$base" -- '*.ts' '*.tsx' || diff_rc=$?
  printf '%s%s\0' "$diff_sentinel" "$diff_rc"
)
if [ "$diff_status" != "0" ]; then
  echo "✗ jscpd: \`git diff\` FAILED (exit ${diff_status:-unknown}) in $tree — NOTHING was scanned" >&2
  echo "  this is not a duplication verdict: no file was compared against $base" >&2
  exit 1
fi

# An empty scan is NOT a silent green (#454): say which tree and which base
# produced it, so "there was nothing to scan" reads differently from "I scanned
# and found nothing".
if [ ${#files[@]} -eq 0 ]; then
  echo "⊘ jscpd: 0 files to scan — no *.ts/*.tsx differ from $base in $tree" >&2
  exit 0
fi

echo "▶ jscpd: ${#files[@]} changed file(s) vs $base in $tree" >&2

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# `>&2` is not cosmetic (#510): a PreToolUse hook shows the user its stderr and
# swallows its stdout, so the console reporter's clone table — the whole point
# of the gate — used to be written where nobody could read it.
scan_status=0
"$JSCPD_BIN" \
  --min-tokens 100 \
  --min-lines 10 \
  --mode strict \
  --threshold "$threshold" \
  --reporters console \
  --output "$tmpdir" \
  "${files[@]}" >&2 || scan_status=$?

# PreToolUse EXIT CONTRACT (#510). Claude Code blocks a tool call ONLY on exit
# 2; every other non-zero code is shown to the user and the call PROCEEDS. This
# script used to END on the `jscpd` invocation, so `set -e` handed jscpd's own
# code straight through — and jscpd maps "over threshold" to 1. The gate printed
# a progress line and blocked exactly nothing.
#
# TODO(fidelity): jscpd spends exit 1 on BOTH "over threshold" and an internal
# crash, so a crash is read here as a duplication verdict and blocks. That is
# the strict direction, and it is the ceiling of this mapping — split it if
# jscpd ever gives the two outcomes distinct codes, or if a crash starts firing
# often enough to teach people to route around the gate.
if [ "$scan_status" -eq 0 ]; then
  echo "✓ jscpd: ${#files[@]} file(s) scanned vs $base — duplication under the ${threshold}% threshold" >&2
  exit 0
fi
if [ "$scan_status" -eq 1 ]; then
  echo "✗ jscpd: duplication over the ${threshold}% threshold — BLOCKED" >&2
  exit 2
fi
echo "✗ jscpd: the run FAILED with exit $scan_status (not a duplication verdict) — nothing was validated" >&2
exit 1
