#!/usr/bin/env bash
# Generated by @navori/plugin-jscpd. Runs jscpd over TS/TSX files changed vs
# the configured base branch. Skips silently if jscpd or git are absent — the
# tool is optional, not a hard dependency of the project.
#
# Triggered as a PreToolUse(Bash) hook, gated to git commit — so the
# duplication check runs right before code lands, not on every turn.

set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
cmd=$(extract_cmd)

navori_audit_name="check-jscpd"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# `source` names the PLUGIN, not core: disabling a plugin changes which hooks
# run, and without this the report cannot explain why a phase thinned out
# between two sessions.
navori_audit_source="plugin:jscpd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock. Called once, right after the payload is read.
navori_audit_begin() {
  # Milliseconds since epoch, portable: GNU date has %s%3N, BSD/macOS date does
  # not. `perl` is present on every macOS and virtually every Linux; when it is
  # missing the clock degrades to seconds*1000 rather than disabling the record.
  navori_audit_t0=$(perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null) \
    || navori_audit_t0=$(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  navori_audit_session=$(printf '%s' "${payload:-}" | jq -r '.session_id // ""' 2>/dev/null) || return 0
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  navori_audit_cwd=$(printf '%s' "${payload:-}" | jq -r '.cwd // ""' 2>/dev/null) || return 0
  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  if [ -n "${NAVORI_AUDITS_ROOT:-}" ]; then
    navori_audit_root=$NAVORI_AUDITS_ROOT
  else
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi
  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # THE no-op that keeps audit-mode free: one stat when the mode is off, which
  # is every session that never opted in. Also the writability check — a log
  # that cannot be appended to is not an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  navori_audit_now=$(perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null) \
    || navori_audit_now=$(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
  navori_audit_ms=$(( navori_audit_now - ${navori_audit_t0:-$navori_audit_now} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  navori_audit_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || navori_audit_ts=""
  # The agent id is what lets the report attribute a hook to a subagent WITHOUT
  # guessing: with agents running in parallel their time windows overlap, so
  # attribution by timestamp is the fallback, not the primary route.
  navori_audit_agent=$(printf '%s' "${payload:-}" | jq -r '.agent_id // .subagent_id // ""' 2>/dev/null) || navori_audit_agent=""

  printf '%s\n' "$(jq -cn \
    --arg ts "$navori_audit_ts" \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    '{ts:$ts,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# Same shape as quality-gate-pre-commit: fires on every Bash call, works on
# almost none, so the verdict comes from the exit code rather than from a call
# per branch.
navori_audit_on_exit() {
  navori_audit_code=$?
  if [ "$navori_audit_code" -eq 0 ]; then
    navori_audit_log "allow" || true
  else
    navori_audit_log "block" "el escaneo de jscpd no paso" || true
  fi
  return 0
}
trap navori_audit_on_exit EXIT

# Gate to `git commit` only (this copy runs on commit, not push). $TRIGGER_RE is
# consumed by the shared detector inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Shared gate detector — inlined into each hook at render time (see the include
# directive in the source scripts + lib/hook-includes.ts). The caller MUST set
# $TRIGGER_RE (an ERE) before the include; it decides which git ops this hook
# gates. Single source of truth for the FIX B/C wrapper-peeling logic; DO NOT
# copy this body into a hook by hand.
#
# Detect whether $1 (a possibly-compound command) invokes a gated operation.
# Splits $1 on the shell separators && || ; | and newlines, strips leading
# whitespace plus wrapper words (`(`, `\`, `command `) and `VAR=value` env
# prefixes from each segment, and returns 0 if ANY segment STARTS with a gated
# `git …` invocation on a word boundary (matched by $TRIGGER_RE). Replaces
# literal-prefix `case` matching, which silently skipped the gate for
# `cd x && git commit`, `echo y; git push`, or a leading space (#88: NEVER skip
# the gate silently). Matching a segment START means a quoted `echo "git commit"`
# does NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`,
# or obfuscation — a seatbelt, not a sandbox.
is_scan_trigger() {
  # Pre-expanded newline: zsh does NOT expand $'\n' in the REPLACEMENT of
  # ${var//pat/repl} (it inserts the literal characters), so an inline $'\n'
  # left compound commands unsplit there and the gate silently skipped
  # `cd x && git commit` (#391). A plain variable expands identically in
  # bash and zsh. ($'\n' in PATTERN position expands fine in both.)
  local input="$1" segment nl=$'\n'
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$nl}"
  input="${input//||/$nl}"
  input="${input//;/$nl}"
  input="${input//|/$nl}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). $TRIGGER_RE's trailing boundary
    # keeps `git commitgraph` / `git config …` from matching.
    if printf '%s' "$segment" | grep -qE "$TRIGGER_RE"; then
      return 0
    fi
  done <<< "$input"
  return 1
}

# Resolution of the working tree the commit acts on (#454). Shared body.
# Shared worktree resolver — inlined into each gate hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Requires the
# `extract-cmd` partial to have run first ($payload and $cmd in scope).
#
# WHY (#454): settings.json invokes these hooks as
# `bash "$CLAUDE_PROJECT_DIR/.claude/scripts/check-semgrep.sh"`, so the hook
# PROCESS starts in the MAIN repo even when the commit happens inside an agent
# worktree under `.claude/worktrees/`. The old `cd "$(git rev-parse
# --show-toplevel)"` therefore resolved the main repo — whose tree is clean — so
# `git diff --name-only main` returned 0 files and the gate exited 0. Not a false
# negative from the scanner: the scanner never ran. A `cd` to an arbitrary tree
# is exactly the bug, so nothing below ever guesses: every candidate must prove
# it is a git working tree, or the next one is tried — and the one the COMMAND
# names must additionally prove it is part of the repository being protected
# (see the same-repository constraint in `navori_worktree`).
#
# `navori_worktree` prints the absolute root of the working tree the gated git
# command will act on, or nothing when none resolves. It is a FUNCTION, not a
# top-level assignment, because `quality-gate-pre-commit` inlines this partial on
# a path that runs on EVERY Bash tool call: callers pay the git/jq probes only
# after their own trigger matched.

# First shell token of $1: a leading single/double-quoted string (so a path with
# spaces survives) or an unquoted run of non-space characters.
navori_first_token() {
  local s="$1"
  case "$s" in
    \"*) s="${s#\"}"; printf '%s' "${s%%\"*}" ;;
    \'*) s="${s#\'}"; printf '%s' "${s%%\'*}" ;;
    *) printf '%s' "${s%%[[:space:]]*}" ;;
  esac
}

# Directory named by the command itself, if any. Two shapes, both real in this
# harness: `git -C <dir> commit …` (git names its own tree) and
# `cd <dir> && git commit …` (how an agent commits into its worktree from a
# session anchored elsewhere). Prints the raw token; the caller resolves it.
#
# TODO(scope): only the FIRST segment is inspected for `cd`. A `cd` buried
# mid-chain (`pnpm build && cd sub && git commit`) falls through to the payload
# cwd, which is right whenever that `cd` stays inside the same repo. Walk the
# segments if a real command shows up where it does not.
navori_cmd_dir() {
  local text="$1" rest="" head=""
  case "$text" in
    *"git -C "*)
      rest="${text#*git -C }"
      ;;
    *)
      head="${text%%&&*}"
      head="${head#"${head%%[![:space:]]*}"}"
      case "$head" in
        "cd "*) rest="${head#cd }" ;;
      esac
      ;;
  esac
  [ -n "$rest" ] || return 1
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # A token that needs the shell to expand it ($VAR, `sub`, ~, globs) is NOT
  # resolved here: guessing wrong points the scan at the wrong tree, which is
  # the very failure this partial exists to kill. Ignoring it just falls through
  # to the next candidate.
  case "$rest" in
    ""|*'$'*|*'`'*|*'*'*|*'?'*|"~"*) return 1 ;;
  esac
  navori_first_token "$rest"
}

# Absolute, symlink-resolved path of a working tree's SHARED git dir, or nothing
# when $1 is not inside a git working tree. `--git-common-dir` names the `.git`
# of the MAIN checkout, so every linked worktree of one repository — and every
# subdirectory of it — reports the SAME value, while a different repository
# reports its own and a submodule reports `<main>/.git/modules/<name>`. That
# makes it an identity test for "same repository", which `--show-toplevel` (one
# per working tree) and `--git-dir` (one per worktree) are not.
navori_repo_id() {
  local dir="$1" common=""
  common=$(git -C "$dir" rev-parse --git-common-dir 2>/dev/null) || return 1
  [ -n "$common" ] || return 1
  # `git -C <dir>` chdirs to <dir> first, so a relative answer (`.git`,
  # `../../.git`) is relative to <dir>. `pwd -P` canonicalises both sides the
  # same way, which also settles macOS's /var vs /private/var symlink.
  (cd "$dir" && cd "$common" && pwd -P) 2>/dev/null
}

# First argument that resolves to a git working tree; prints its root.
navori_first_tree() {
  local candidate toplevel
  for candidate in "$@"; do
    [ -n "$candidate" ] || continue
    [ -d "$candidate" ] || continue
    toplevel=$(git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) || continue
    [ -n "$toplevel" ] || continue
    printf '%s' "$toplevel"
    return 0
  done
  return 1
}

# Resolution, most specific first:
#   1. the directory the command names (`git -C` / a leading `cd`), ONLY when it
#      belongs to the same repository as the anchor (see the constraint below);
#   2. the payload's `.cwd` — Claude Code sends the CURRENT working directory of
#      the tool call, a documented field distinct from $CLAUDE_PROJECT_DIR (the
#      project root). In an agent worktree these differ; that gap IS #454;
#   3. the hook process's own cwd — the pre-#454 behaviour, still correct for a
#      plain terminal or git-hook invocation.
navori_worktree() {
  local payload_cwd anchor named anchor_repo="" named_repo=""
  payload_cwd=$(payload_field cwd)
  # A relative `cd sub` resolves against the shell's cwd, which is the payload's
  # when Claude Code sends one and the hook process's otherwise.
  anchor="$payload_cwd"
  [ -d "$anchor" ] || anchor="$PWD"
  named=$(navori_cmd_dir "$cmd" || true)
  case "$named" in
    "") ;;
    /*) ;;
    *) named="$anchor/$named" ;;
  esac
  # SAME-REPOSITORY CONSTRAINT — DO NOT REMOVE (#454, review finding).
  # Candidate 1 is the only one the COMMAND controls, and it is tried first, so
  # accepting any git tree it happens to name lets that command OVERRIDE the
  # trustworthy candidates below it: `git -C <other-repo> log && git commit`,
  # `cd <other> && cd <wt> && git commit`, `cd <sub> && cd .. && git commit`, or
  # merely the bytes `git -C <path>` inside a commit MESSAGE, all aimed the scan
  # at a foreign tree with nothing to scan — exit 0 with the scanner never run,
  # which is the very failure #454 is about (and, for a commit in the main repo,
  # strictly worse than not resolving worktrees at all).
  # So a directory the command names is accepted only when it is part of the
  # repository the hook is protecting, i.e. the anchor's. Linked worktrees share
  # the main checkout's git dir, so every legitimate agent worktree passes; a
  # different repository and a submodule (its own git dir under
  # `<main>/.git/modules/`) do not, and fall through to the payload cwd — the
  # stricter direction. An unresolvable anchor drops candidate 1 for the same
  # reason: nothing to check it against.
  # Ceiling: two linked worktrees of the SAME repository are indistinguishable
  # this way, so naming a sibling worktree still beats the payload cwd. Both are
  # trees of the repo being protected, so the scan stays inside it. Walk the
  # segments to the one that actually carries the `git commit` if a real command
  # shows up where that is not enough.
  if [ -n "$named" ]; then
    anchor_repo=$(navori_repo_id "$anchor" || true)
    named_repo=$(navori_repo_id "$named" || true)
    if [ -z "$anchor_repo" ] || [ "$named_repo" != "$anchor_repo" ]; then
      named=""
    fi
  fi
  navori_first_tree "$named" "$payload_cwd" "$PWD" || true
}

# No command extracted (empty $cmd) → run unconditionally. A real command that
# is NOT a git commit → skip. Anything else → fall through and scan.
if [ -n "$cmd" ] && ! is_scan_trigger "$cmd"; then
  exit 0
fi

# Resolve jscpd: prefer the repo-pinned binary (node_modules/.bin) over a global
# one. A global jscpd can be a DIFFERENT major (e.g. 4.x vs the repo's 5.x) whose
# tokenizer reports different duplication than `pnpm run dup`, so the commit gate
# would measure something other than what the repo declares. Local-first fixes it.
# Availability is settled BEFORE the tree is resolved: a missing tool is the
# cheapest reason to stop, and it must not be masked by a tree that fails to
# resolve.
JSCPD_BIN=""
hook_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$hook_root" ] && [ -x "$hook_root/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$hook_root/node_modules/.bin/jscpd"
elif command -v jscpd >/dev/null 2>&1; then
  JSCPD_BIN="jscpd"
fi
if [ -z "$JSCPD_BIN" ]; then
  echo "⊘ jscpd not available (neither pinned in the repo nor installed globally) — skip (install: pnpm add -D jscpd)" >&2
  exit 0
fi

# Run from the tree the commit acts on — NOT from the hook process's cwd, which
# is the main repo even when the diff lives in an agent worktree (#454). Also
# keeps changed paths relative, so a repo path with spaces stays robust; the
# NUL-delimited read handles spaces in filenames, and the
# `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
tree=$(navori_worktree)
if [ -z "$tree" ]; then
  echo "⊘ jscpd: no git working tree resolved for this command — skip" >&2
  exit 0
fi
cd "$tree"

# Now that the tree is known, its OWN pinned binary wins: same rationale as
# above — measure what the scanned repo declares, not what the repo the hook
# process happens to sit in does.
if [ -x "$tree/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$tree/node_modules/.bin/jscpd"
fi

# branchBase / jscpdThreshold are shell-quoted at render time via the shq:
# marker (#197/#249): hostile values in navori.config.json land here as inert
# literals, never executable (this hook runs on every git commit via
# PreToolUse(Bash)).
base='main'
threshold='5'

if ! git rev-parse --verify "$base" >/dev/null 2>&1; then
  echo "⊘ branch '$base' does not exist in $tree — skip jscpd" >&2
  exit 0
fi

# `git diff` runs inside a process substitution, whose exit status the shell
# never reports, and its stderr used to go to /dev/null — so a diff that FAILED
# (exit 128: unborn HEAD, a corrupt index, a base that vanished mid-run)
# produced zero records and was indistinguishable from "nothing changed": the
# hook printed `0 files to scan` and exited 0 (#511). The sentinel carries the
# status back out of the subshell. It can never collide with a real record: the
# pathspec restricts the list to `*.ts`/`*.tsx`.
diff_sentinel='@navori-diff-status:'
diff_status=""
files=()
while IFS= read -r -d '' f; do
  case "$f" in
    "${diff_sentinel}"*) diff_status="${f#"${diff_sentinel}"}"; continue ;;
  esac
  files+=("$f")
done < <(
  # `|| diff_rc=$?` and not a bare `$?`: the subshell inherits `set -e`, which
  # would kill it on a failing `git diff` before the sentinel is ever written.
  diff_rc=0
  git diff --name-only -z --diff-filter=ACMRT "$base" -- '*.ts' '*.tsx' || diff_rc=$?
  printf '%s%s\0' "$diff_sentinel" "$diff_rc"
)
if [ "$diff_status" != "0" ]; then
  echo "✗ jscpd: \`git diff\` FAILED (exit ${diff_status:-unknown}) in $tree — NOTHING was scanned" >&2
  echo "  this is not a duplication verdict: no file was compared against $base" >&2
  exit 1
fi

# An empty scan is NOT a silent green (#454): say which tree and which base
# produced it, so "there was nothing to scan" reads differently from "I scanned
# and found nothing".
if [ ${#files[@]} -eq 0 ]; then
  echo "⊘ jscpd: 0 files to scan — no *.ts/*.tsx differ from $base in $tree" >&2
  exit 0
fi

echo "▶ jscpd: ${#files[@]} changed file(s) vs $base in $tree" >&2

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# `>&2` is not cosmetic (#510): a PreToolUse hook shows the user its stderr and
# swallows its stdout, so the console reporter's clone table — the whole point
# of the gate — used to be written where nobody could read it.
scan_status=0
"$JSCPD_BIN" \
  --min-tokens 100 \
  --min-lines 10 \
  --mode strict \
  --threshold "$threshold" \
  --reporters console \
  --output "$tmpdir" \
  "${files[@]}" >&2 || scan_status=$?

# PreToolUse EXIT CONTRACT (#510). Claude Code blocks a tool call ONLY on exit
# 2; every other non-zero code is shown to the user and the call PROCEEDS. This
# script used to END on the `jscpd` invocation, so `set -e` handed jscpd's own
# code straight through — and jscpd maps "over threshold" to 1. The gate printed
# a progress line and blocked exactly nothing.
#
# TODO(fidelity): jscpd spends exit 1 on BOTH "over threshold" and an internal
# crash, so a crash is read here as a duplication verdict and blocks. That is
# the strict direction, and it is the ceiling of this mapping — split it if
# jscpd ever gives the two outcomes distinct codes, or if a crash starts firing
# often enough to teach people to route around the gate.
if [ "$scan_status" -eq 0 ]; then
  echo "✓ jscpd: ${#files[@]} file(s) scanned vs $base — duplication under the ${threshold}% threshold" >&2
  exit 0
fi
if [ "$scan_status" -eq 1 ]; then
  echo "✗ jscpd: duplication over the ${threshold}% threshold — BLOCKED" >&2
  exit 2
fi
echo "✗ jscpd: the run FAILED with exit $scan_status (not a duplication verdict) — nothing was validated" >&2
exit 1
