# navori:managed start id="tgrep-script-guard-search-routing" hash="702b3aef" version="0.8.6" source="@navori/plugin-tgrep"
#!/usr/bin/env bash
#
# PreToolUse(Bash) guard: content search goes through the tgrep wrapper.
#
# WHY THIS IS A GUARD AND NOT A SENTENCE IN CLAUDE.md. The doctrine telling the
# model to route content search through the wrapper has shipped since 0.7.8 and
# is measured at 7.4% adoption over 2,761 real searches. The session that
# produced the best analysis of tgrep anyone has written still went through
# shell for 9 of every 10 searches (#668), so comprehension was never the
# bottleneck. In this harness the mechanical layers hold — guard-destructive 14
# blocks out of 14, quality-gate-pre-commit 7 out of 7 — and the advisory ones
# do not. This moves one doctrine across that line.
#
# WHAT IT BLOCKS, and nothing else: a segment that STARTS a command (never one
# after a pipe) and invokes `grep`/`egrep`/`fgrep` recursively, or `rg` with no
# single file target. Measured against the 8,562 real grep/rg invocations of the
# park: it fires on 55% of genuine content searches and on ZERO extractions.
#
# WHAT IT DELIBERATELY LETS THROUGH, because a false block teaches the model to
# route AROUND the guard — which is worse than the search it would have stopped:
#
#   · `… | grep x`        filtering another command's output (46% of all
#                         invocations). Not a repo search; the wrapper cannot
#                         replace it.
#   · `grep -n x file.ts` extracting from an ALREADY KNOWN file (22%). The
#                         harness's own doctrine prefers this to the wrapper.
#   · anything it cannot parse with certainty — a quoted pattern carrying a
#                         newline, an unbalanced quote. Unsure means allow.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add repo-specific exceptions in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# $2 overrides the sed fallback's capture. `.*` (greedy, to the last quote on the
# line) is right for `command`, whose value can itself contain escaped quotes and
# which Claude Code sends LAST. Every other field takes the default `[^"]*` run,
# so a value with more JSON after it is not swallowed whole.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"\(${2:-[^\"]*}\)\".*/\1/p"
}
extract_cmd() {
  payload_field tool_input.command '.*'
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
cmd=$(extract_cmd)

navori_audit_name="guard-search-routing"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# `source` names the PLUGIN, not core: disabling tgrep changes which hooks run,
# and without this the report cannot explain why a phase thinned out between two
# sessions.
navori_audit_source="plugin:tgrep"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(basename "$navori_audit_cwd" 2>/dev/null) || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  [ -f "$navori_audit_file" ] || return 0
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# The verdict is resolved in a trap, not by a call at the end of the file: this
# hook's managed block ends before its user section, so a call placed after it
# would live in the user's territory and never reach the mirror.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

if [ -z "$cmd" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin comando que inspeccionar"
  exit 0
fi

# The wrapper itself is never blocked — it runs `grep -rn` internally on the
# fallback path, and this hook sees the command the agent typed, not the one the
# wrapper spawns. Checked FIRST so no rule below can ever fire on it.
case "$cmd" in
  *tgrep-search.sh*)
    navori_audit_verdict="skip"
    navori_audit_reason="es el wrapper"
    exit 0
    ;;
esac

# INERT CONTENT: a heredoc body is DATA, not a call.
#
# Every rule below reads the command as TEXT, so a script or a test file written
# with `python3 - <<'PY' … PY` that merely QUOTES a search was blocked even
# though nothing ran. That is not hypothetical: it fired on the very session that
# was adding this guard's own regression tests, because one of the test cases IS
# the string `grep -rn "..." src/`.
#
# `guard-destructive` solves this properly, with a ~60-line pass that tells a
# documentation heredoc from a write-then-execute one. This guard does NOT copy
# it, and the asymmetry is the point: that guard defends against data loss and
# must resist an adversary, while this one redirects a search and fails open by
# design. Measured on the park, only 2.9% of its blocks (25 of 852) involve a
# heredoc at all, so giving them up costs almost nothing and removes an entire
# false-positive class in three lines instead of sixty.
#
# Yes, this means `… <<EOF` is an escape hatch. That is acceptable here: this
# guard is a mechanism against habit, not a sandbox.
case "$cmd" in
  *"<<"*)
    navori_audit_verdict="skip"
    navori_audit_reason="heredoc: el cuerpo es dato, no una llamada"
    exit 0
    ;;
esac

# BOUNDED WORK: the guard runs under a wall-clock timeout it does not control,
# and being killed is indistinguishable from approving. Every pass below is one
# linear `sed`/`grep` over the command; a command past the ceiling is ALLOWED
# rather than inspected, because this guard redirects a search — it does not
# protect against data loss, so failing open is the right failure here (and the
# opposite of what guard-destructive does with the same trade-off).
if [ "${#cmd}" -gt 20000 ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="comando demasiado grande para inspeccionar"
  exit 0
fi

# SEGMENTS. A command is split so each rule only ever matches WITHIN one
# segment, and each segment carries whether it starts a command or continues a
# pipe. That distinction is the whole design: `grep -n foo` is extraction from
# stdin after a `|`, and a repo search at the start of a line. The segment alone
# cannot tell them apart.
#
# Order matters: `||` must be rewritten before `|`, or the first `|` of a `||`
# is consumed and the second starts a bogus "piped" segment.
#
# A line continuation is NOT a separator: without joining it first, `\` + newline
# splits a quoted pattern in half and the fragment lands with no target, which
# every heuristic below reads as a recursive search. Measured on the park: that
# alone mislabelled over a thousand extractions.
#
# QUOTES. The split walks the command character by character and only cuts on a
# separator that is OUTSIDE a quoted span (#721 A3). The two blind `sed`
# substitutions it replaces cut inside quotes too, so a command that merely
# QUOTED a search — `git commit -m "arregla el guard && rg ya no bloquea"` —
# produced a fake segment starting with the verb and got blocked. Verified: with
# a separator inside the quotes it blocked, without one it passed, and the
# difference was never about what the command does.
#
# That class is the guard's own stated worst failure ("a false block teaches the
# model to route AROUND the guard"), and it is not hypothetical: it fired on the
# session that was writing the test for it.
#
# One awk pass over a command already capped at 20k characters, replacing two
# `sed` passes — same order of work, and the escaping stays in awk where a
# backslash means one thing instead of three.
segments=$(printf '%s' "$cmd" \
  | sed -e ':a' -e '$!N' -e 's/\\\n/ /' -e 'ta' -e 'P' -e 'D' \
  | awk '
    {
      line = $0
      out = ""
      inq = ""      # "", "\047" (single) or "\042" (double)
      n = length(line)
      for (i = 1; i <= n; i++) {
        c = substr(line, i, 1)
        if (inq == "") {
          if (c == "\047" || c == "\042") { inq = c; out = out c; continue }
          # `||` before `|`, or the first pipe of a `||` starts a bogus segment.
          if (c == "|" && substr(line, i + 1, 1) == "|") { out = out "\n@C@"; i++; continue }
          if (c == "&" && substr(line, i + 1, 1) == "&") { out = out "\n@C@"; i++; continue }
          if (c == ";") { out = out "\n@C@"; continue }
          if (c == "|") { out = out "\n@P@"; continue }
          out = out c
          continue
        }
        # Inside a quoted span every separator is DATA. The span ends only on
        # its own quote character, which is what keeps `"a ; b"` whole while
        # `'"'"'a'"'"' ; b` still splits.
        if (c == inq) inq = ""
        out = out c
      }
      printf "%s", out
    }
  ')

# Does this segment name at least ONE concrete file among its TARGET operands?
#
# This is the difference between searching the repo and reading files you have
# already found, and it cannot be read off the flags: `grep -rn "oxlint"
# apps/a/package.json apps/b/package.json` carries `-r` and is pure extraction —
# grep ignores recursion once you hand it files. Blocking that shape cost a real
# session a round-trip for nothing, and it is 9.3% of every recursive grep in the
# park (124 of 1,328), concentrated on reading single files under `node_modules/`.
#
# ONE file is enough to allow, not all of them: this guard fails open by design,
# and a mixed `src/ extra.ts` is more likely a reader being sloppy than a search
# worth a round-trip.
#
# The first non-flag operand is the PATTERN and is skipped — otherwise
# `grep -rn "config.json" src/` would look like it names a file when what it
# names is what it is looking FOR.
#
# An extension is NOT what makes something a file (#721 A3). Defining it that way
# blocked `rg foo Makefile`, `rg TODO Dockerfile`, `grep -rn foo LICENSE` and
# `grep -rn x CODEOWNERS` — all verified, all pure extraction from one named
# file, all exactly the shape this function exists to let through. So the awk
# below no longer decides: it PRINTS the target operands and the shell answers
# with three signals, cheapest first.
names_a_file() {
  navori_operands=$(printf '%s' "$1" | awk '
    {
      seen_pattern = 0
      for (i = 2; i <= NF; i++) {
        t = $i
        if (substr(t, 1, 1) == "-") continue
        if (!seen_pattern) { seen_pattern = 1; continue }
        gsub(/^["'"'"']+|["'"'"']+$/, "", t)
        if (t ~ /\*/) continue
        if (t ~ /\/$/) continue
        print t
      }
    }
  ')
  [ -n "$navori_operands" ] || return 1

  while IFS= read -r navori_operand; do
    [ -n "$navori_operand" ] || continue

    # 1. An extension still answers most of them, and costs nothing.
    case "$navori_operand" in
      *.[A-Za-z0-9] | *.[A-Za-z0-9][A-Za-z0-9] | *.[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9] | \
        *.[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]) return 0 ;;
    esac

    # 2. The files a repo keeps without one. Not a taste list: these are the
    #    names that appear at a repo root, so a search naming one is naming a
    #    file and not a tree.
    navori_base=${navori_operand##*/}
    case "$navori_base" in
      Makefile | makefile | GNUmakefile | Dockerfile | dockerfile | Containerfile | \
        LICENSE | LICENCE | COPYING | NOTICE | AUTHORS | CONTRIBUTORS | CODEOWNERS | \
        README | CHANGELOG | TODO | VERSION | Procfile | Gemfile | Rakefile | Brewfile | \
        Jenkinsfile | Vagrantfile | Caddyfile | Justfile | justfile | Taskfile | Podfile)
        return 0
        ;;
    esac

    # 3. Whatever is left, ask the filesystem — the only signal that settles
    #    `bin/deploy` (a script) against `src` (a tree) without guessing from
    #    the shape. A stat per operand, and there are at most a handful.
    [ -f "$navori_operand" ] && return 0
  done <<NAVORI_OPERANDS
$navori_operands
NAVORI_OPERANDS

  return 1
}

block() {
  echo "[navori] BLOCKED by guard-search-routing: $1" >&2
  echo "[navori] route content search through the indexed wrapper:" >&2
  echo "[navori]   bash .claude/scripts/tgrep-search.sh <same ripgrep flags>" >&2
  echo "[navori] it carries its own 'allow' rule: no prompt, no classifier round-trip." >&2
  # The path is relative BECAUSE the allow rule is a literal
  # (`Bash(bash .claude/scripts/tgrep-search.sh *)`): any other spelling —
  # absolute, `cd … &&`, `$CLAUDE_PROJECT_DIR` (which is NOT set in the agent's
  # shell, only in a hook's) — stops matching it and buys a prompt. So the cwd
  # is a real constraint of the remedy, and saying so beats an exit 127 the
  # caller has to diagnose after already obeying (#724).
  echo "[navori] run it from the repo root: the path is relative because the" >&2
  echo "[navori] 'allow' rule is literal, and the shell keeps whatever cwd the" >&2
  echo "[navori] last 'cd' left." >&2
  echo "[navori] exit contract: 0 = match, 1 = no match, 2 = NOTHING WAS SEARCHED." >&2
  echo "[navori] this does NOT apply to '| grep' (filtering output) nor to" >&2
  echo "[navori] 'grep -n x known-file' (extracting from a file you already found):" >&2
  echo "[navori] both of those stay correct, and the wrapper cannot replace them." >&2
  # Only assignments here: nothing may come between the decision and `exit 2`.
  # The recording happens in the trap, after the exit is already committed.
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Walk the command-start segments only. `@P@` lines are dropped here, and that
# is what keeps every pipe-filter out of every rule below: the first line of the
# command carries no marker (it starts the command), and each `@C@` line starts
# a new one.
starts=$(printf '%s\n' "$segments" | sed -n -e 's/^@C@//p' -e '1{/^@[CP]@/!p;}')

while IFS= read -r seg; do
  [ -n "$seg" ] || continue

  # Peel `VAR=value` prefixes so the verb anchor below sees the real command
  # (#724 B2). `LC_ALL=C grep -rn foo src/` evaded every rule here by sitting
  # one token to the right of the anchor — verified: exit 0 against exit 2 for
  # the same command without the prefix.
  #
  # Parameter expansion, not a `sed` fork: this runs once per segment next to
  # two `grep -qE` forks that are already there, and a heredoc is many segments.
  # The idiom is the one `gate-trigger.sh` uses (its FIX C) and it is the third
  # place this peel lives — `guard-destructive.sh` does it with a sed loop and
  # `parse.ts`'s `leadingBinary` in TypeScript. A fourth earns a shared partial.
  seg="${seg#"${seg%%[![:space:]]*}"}"
  while [[ "$seg" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do
    case "$seg" in
      *[[:space:]]*)
        seg="${seg#*[[:space:]]}"
        seg="${seg#"${seg%%[![:space:]]*}"}"
        ;;
      *) seg=""; break ;;
    esac
  done
  [ -n "$seg" ] || continue

  # Recursive grep: the flag may sit anywhere among the options, so the verb is
  # anchored at the segment start and the flag matched as its own token.
  # `-[a-zA-Z]*[rR][a-zA-Z]*` matches `-r`, `-R`, `-rn`, `-nr`; it cannot match
  # `--include` or `--color`, because after the leading `-` the class does not
  # accept another `-`.
  if printf '%s' "$seg" | grep -qE '^[[:space:]]*(grep|egrep|fgrep)([[:space:]]|$)' \
    && printf '%s' "$seg" | grep -qE '(^|[[:space:]])(-[a-zA-Z]*[rR][a-zA-Z]*|--recursive)([[:space:]]|=|$)' \
    && ! names_a_file "$seg"; then
    block "busqueda de contenido recursiva por shell"
  fi

  # `rg` is recursive by DEFAULT, so the question inverts: it is extraction only
  # when a single concrete file is named. The test is deliberately loose — any
  # token that looks like a path with an extension — because the cost of the two
  # errors is not symmetric. Missing a search costs one unmeasured call; blocking
  # a legitimate extraction teaches the model to work around the guard.
  if printf '%s' "$seg" | grep -qE '^[[:space:]]*rg([[:space:]]|$)' \
    && ! names_a_file "$seg"; then
    block "busqueda de contenido por shell (rg es recursivo por defecto)"
  fi

  # `git grep` — the route that was invisible to all three layers at once
  # (#720). The guard anchored only `grep|egrep|fgrep|rg`, the miner scored the
  # same four verbs, and `READ_LANE_BINARIES` excluded `git` wholesale with a
  # rationale ("no native lane to switch to") that is false for exactly this
  # subcommand: its native lane IS `Grep`. So after the guard shipped, `git
  # grep` was the minimum-friction migration — no prompt, no index, and outside
  # every measurement.
  #
  # ONE exception, and it is the one the doctrine already documents: tracked
  # files under a dot-directory, where the wrapper's `--hidden` degrades into
  # the brute-force scan the index exists to avoid. Naming a dot-path is what
  # makes that case legible, so it is what the guard reads — and keeping the
  # exception is what stops this rule from becoming the contradiction #721 just
  # removed, where the core prescribed what the guard blocked.
  # The `git(… -opt …)*` middle is the shape `guard-destructive` already uses for
  # `git -C … commit` (its `git_cp`): a global option may carry its value glued
  # with `=` or as the next token, and without that `git -C /repo grep` slips
  # through the anchor.
  if printf '%s' "$seg" | grep -qE '^[[:space:]]*git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+grep([[:space:]]|$)'; then
    if ! printf '%s' "$seg" | grep -qE '(^|[[:space:]])['"'"'"]?\.[A-Za-z]'; then
      block "busqueda de contenido por shell (git grep; el wrapper cubre el mismo arbol)"
    fi
  fi
done <<EOF
$starts
EOF
# navori:managed end id="tgrep-script-guard-search-routing"

# user: add repo-specific exceptions or extra redirects here. `$cmd` holds the
# full command and `block "<reason>"` aborts with exit 2.

exit 0
