import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { safeHomedir } from "../../lib/home.ts";
import { CORE_MANAGED_ASSETS, resolveAssetPath } from "../../lib/render-plan.ts";
import { resolveLang, tc } from "../../lib/i18n.ts";
import { deepMerge } from "./deep-merge.ts";
import type { GlobalConfig } from "../../lib/global-config.ts";

/**
 * Renders the OPTIONAL global harness (Spec 0010 F1) into Claude Code's global
 * config dir. This module is Claude-specific — it targets `~/.claude` and reuses
 * Claude's `deepMerge` — so it lives in `engines/claude/`, not the engine-agnostic
 * `lib/` layer (#227). It stays entirely OUTSIDE the repo render pipeline
 * (render-plan / execute-plan / engine adapters), so it cannot alter repo-scoped
 * behaviour — the zero-footprint invariant (§2.4). It only *reads* from the core
 * (block bodies via `lib/render-plan`) and merges to preserve whatever the user
 * already has in `~/.claude/settings.json`.
 *
 * The baseline is delivered by a SessionStart hook with a gate, NOT a static
 * `~/.claude/CLAUDE.md` block: Claude Code loads that file unconditionally, so
 * a static block could never step aside for a repo's own harness. The hook can
 * (§3.1).
 */

/** Path of the gate hook relative to the global config dir. */
export const GLOBAL_HOOK_REL = "hooks/navori-global-baseline.sh";

/** Heredoc delimiter for the embedded baseline. Unique enough to never collide. */
const HEREDOC = "NAVORI_GLOBAL_BASELINE_EOF_9f3a";

/**
 * Claude Code's global config dir: `CLAUDE_CONFIG_DIR` if set (that is how
 * Claude Code itself resolves it), else `~/.claude`. A relative override is
 * resolved against the cwd.
 */
export function globalTargetDir(): string {
  const override = process.env.CLAUDE_CONFIG_DIR;
  if (override && override.trim().length > 0) return resolve(override.trim());
  return join(safeHomedir(), ".claude");
}

/** Absolute path of the installed gate hook under the global config dir. */
export function globalHookPath(dir = globalTargetDir()): string {
  return join(dir, GLOBAL_HOOK_REL);
}

/**
 * Compose the baseline prose from the selected core blocks. Enforces the §4
 * audit at runtime: a block that interpolates repo config (`{{...}}`) is NOT
 * global-safe, so it is rejected loudly instead of shipping a broken `<not
 * configured>` placeholder into every session.
 */
export function composeBaseline(config: GlobalConfig): string {
  const parts: string[] = [];
  for (const id of config.blocks.include) {
    const asset = CORE_MANAGED_ASSETS.find((a) => a.id === id);
    if (!asset) {
      throw new Error(`Global baseline references unknown core block '${id}'.`);
    }
    const raw = readFileSync(resolveAssetPath(asset, config.language).path, "utf-8").trim();
    if (/\{\{/.test(raw)) {
      throw new Error(
        `Block '${id}' interpolates repo config ({{...}}), so it can't be part of ` +
          `the global baseline (Spec 0010 §4). Remove it from blocks.include.`,
      );
    }
    if (raw.includes(HEREDOC)) {
      throw new Error(`Block '${id}' collides with the hook heredoc delimiter.`);
    }
    parts.push(raw);
  }
  const intro = tc(resolveLang(config.language)).engine.globalBaselineIntro;
  return `${intro}\n\n${parts.join("\n\n")}\n`;
}

/**
 * Generate the gate hook script. It defers (emits nothing) when the current
 * project has a `navori.config.json` at cwd or any ancestor — repo-local or a
 * workspace member — because that repo already carries the harness. Otherwise
 * it emits the baseline as SessionStart `additionalContext`.
 */
export function generateHookScript(baseline: string): string {
  return `#!/usr/bin/env bash
#
# navori global baseline — Spec 0010. MANAGED BY NAVORI; do not edit by hand.
# Installed by \`navori global init\`, regenerated by \`navori global render\`,
# removed by \`navori global uninstall\`.
#
# Delivers a repo-agnostic harness baseline as SessionStart context, but ONLY
# when the current project has NO navori config of its own. A repo with a
# navori.config.json (local or workspace member) already carries the harness,
# so this global layer steps aside (defer) — the zero-double-emission gate of
# Spec 0010 §3.1.
set -euo pipefail
cat >/dev/null 2>&1 || true   # drain the SessionStart JSON on stdin (unused)

# --- Gate: defer if the project has its own navori config -------------------
dir="$PWD"
while :; do
  [ -f "$dir/navori.config.json" ] && exit 0   # repo harness present -> defer
  [ "$dir" = "/" ] && break
  dir="$(dirname "$dir")"
done

# --- No repo navori config -> emit the global baseline ----------------------
BASELINE=$(cat <<'${HEREDOC}'
${baseline}
${HEREDOC}
)

[ -n "$BASELINE" ] || exit 0
if command -v node >/dev/null 2>&1; then
  BASELINE="$BASELINE" node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:process.env.BASELINE}}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg c "$BASELINE" '{hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:$c}}'
fi
exit 0
`;
}

/** The SessionStart registration navori merges into `~/.claude/settings.json`. */
export function hookSettingsFragment(hookAbsPath: string): Record<string, unknown> {
  return {
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume|compact",
          hooks: [
            {
              type: "command",
              command: `bash "${hookAbsPath}"`,
              timeout: 15,
              statusMessage: "navori: global baseline",
            },
          ],
        },
      ],
    },
  };
}

/**
 * The personal permissions navori merges additively into `~/.claude/settings.json`
 * (Spec 0010 — `global.json.permissions`). Only non-empty buckets are emitted so
 * an empty config leaves no `permissions` residue; `deepMerge` then concatenates
 * and dedupes them against whatever the user already has (never clobbers).
 */
export function permissionsFragment(config: GlobalConfig): Record<string, unknown> {
  const perms: Record<string, string[]> = {};
  for (const kind of ["allow", "deny", "ask"] as const) {
    const list = config.permissions[kind];
    if (list.length > 0) perms[kind] = list;
  }
  return Object.keys(perms).length > 0 ? { permissions: perms } : {};
}

/** Read the existing global settings.json (empty object if absent/corrupt). */
function readExistingSettings(dir: string): Record<string, unknown> {
  const path = join(dir, "settings.json");
  if (!existsSync(path)) return {};
  try {
    const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

/** True iff `<dir>/settings.json` already registers navori's baseline hook. */
export function settingsHasBaseline(dir = globalTargetDir()): boolean {
  const hooks = readExistingSettings(dir).hooks;
  if (!hooks || typeof hooks !== "object" || Array.isArray(hooks)) return false;
  const sessionStart = (hooks as Record<string, unknown>).SessionStart;
  if (!Array.isArray(sessionStart)) return false;
  return sessionStart.some((bucket) => {
    const inner = (bucket as { hooks?: unknown })?.hooks;
    return Array.isArray(inner) && inner.some(isNavoriBaselineHook);
  });
}

/**
 * True iff every permission configured in `global.json` is already present in
 * `<dir>/settings.json`. Vacuously true when nothing is configured — `doctor`
 * only surfaces this check when the user actually declared permissions.
 */
export function settingsHasPermissions(config: GlobalConfig, dir = globalTargetDir()): boolean {
  const perms = readExistingSettings(dir).permissions;
  const bag =
    perms && typeof perms === "object" && !Array.isArray(perms)
      ? (perms as Record<string, unknown>)
      : {};
  for (const kind of ["allow", "deny", "ask"] as const) {
    const want = config.permissions[kind];
    if (want.length === 0) continue;
    const have = Array.isArray(bag[kind]) ? (bag[kind] as unknown[]) : [];
    if (!want.every((w) => have.includes(w))) return false;
  }
  return true;
}

/** Total number of permission entries configured across allow/deny/ask. */
export function configuredPermissionsCount(config: GlobalConfig): number {
  return (
    config.permissions.allow.length + config.permissions.deny.length + config.permissions.ask.length
  );
}

export interface GlobalRenderPlan {
  dir: string;
  hookPath: string;
  hookScript: string;
  settingsPath: string;
  settings: Record<string, unknown>;
}

/**
 * Compute (without writing) every file the global render would produce: the
 * gate hook and the merged settings.json. The merged fragment carries BOTH the
 * SessionStart hook registration and the personal `permissions` from
 * `global.json` (Spec 0010). Merging over the user's existing settings means
 * navori never clobbers their other global hooks/permissions.
 */
export function planGlobalRender(config: GlobalConfig, dir = globalTargetDir()): GlobalRenderPlan {
  const baseline = composeBaseline(config);
  const hookPath = globalHookPath(dir);
  const existing = readExistingSettings(dir);
  const fragment = deepMerge(hookSettingsFragment(hookPath), permissionsFragment(config));
  const settings = deepMerge(existing, fragment);
  return {
    dir,
    hookPath,
    hookScript: generateHookScript(baseline),
    settingsPath: join(dir, "settings.json"),
    settings,
  };
}

/** Write the plan to disk: gate hook (executable) + merged settings.json. */
export function applyGlobalRender(plan: GlobalRenderPlan): void {
  mkdirSync(dirname(plan.hookPath), { recursive: true });
  writeFileSync(plan.hookPath, plan.hookScript);
  chmodSync(plan.hookPath, 0o755);
  writeFileSync(plan.settingsPath, `${JSON.stringify(plan.settings, null, 2)}\n`);
}

/** True iff a SessionStart hook entry points at navori's global baseline. */
function isNavoriBaselineHook(entry: unknown): boolean {
  if (!entry || typeof entry !== "object") return false;
  const cmd = (entry as { command?: unknown }).command;
  return typeof cmd === "string" && cmd.includes("navori-global-baseline.sh");
}

/**
 * Strip navori's global baseline from an existing settings object, leaving every
 * other hook, permission and key untouched. Returns a new object (no mutation).
 * Empty `hooks`/`SessionStart` containers are pruned so uninstall leaves no
 * navori residue.
 */
export function stripBaselineFromSettings(
  settings: Record<string, unknown>,
): Record<string, unknown> {
  const hooks = settings.hooks;
  if (!hooks || typeof hooks !== "object" || Array.isArray(hooks)) return settings;
  const sessionStart = (hooks as Record<string, unknown>).SessionStart;
  if (!Array.isArray(sessionStart)) return settings;

  const cleanedBuckets = sessionStart
    .map((bucket) => {
      if (!bucket || typeof bucket !== "object") return bucket;
      const inner = (bucket as { hooks?: unknown }).hooks;
      if (!Array.isArray(inner)) return bucket;
      const kept = inner.filter((h) => !isNavoriBaselineHook(h));
      return { ...(bucket as object), hooks: kept };
    })
    .filter((bucket) => {
      const inner = (bucket as { hooks?: unknown })?.hooks;
      return !Array.isArray(inner) || inner.length > 0;
    });

  const nextHooks: Record<string, unknown> = { ...(hooks as Record<string, unknown>) };
  if (cleanedBuckets.length > 0) nextHooks.SessionStart = cleanedBuckets;
  else delete nextHooks.SessionStart;

  const next: Record<string, unknown> = { ...settings };
  if (Object.keys(nextHooks).length > 0) next.hooks = nextHooks;
  else delete next.hooks;
  return next;
}

export interface GlobalUninstallResult {
  removedHook: boolean;
  updatedSettings: boolean;
}

/**
 * Remove ONLY navori's global footprint: the gate hook file and its SessionStart
 * registration. Any other global hook/skill/plugin/permission the user has is
 * left intact (§3.1 requirement 3).
 */
export function uninstallGlobalRender(dir = globalTargetDir()): GlobalUninstallResult {
  const hookPath = globalHookPath(dir);
  let removedHook = false;
  if (existsSync(hookPath)) {
    rmSync(hookPath);
    removedHook = true;
  }

  const settingsPath = join(dir, "settings.json");
  let updatedSettings = false;
  if (existsSync(settingsPath)) {
    const before = readExistingSettings(dir);
    const after = stripBaselineFromSettings(before);
    if (JSON.stringify(after) !== JSON.stringify(before)) {
      writeFileSync(settingsPath, `${JSON.stringify(after, null, 2)}\n`);
      updatedSettings = true;
    }
  }
  return { removedHook, updatedSettings };
}
