import { isDowngrade } from "./semver.ts";

/**
 * The JSON notation of navori's authorship marker: a top-level `$navori` key.
 *
 * Everywhere else navori declares "I wrote this" with a comment marker
 * (`<!-- navori:managed … -->`, `# navori:managed …`). JSON has no comments, so
 * every JSON file navori generates whole is UNREACHABLE by that notation — not
 * as an oversight but by the format's design. `$navori` is its equivalent, and
 * it carries the same two facts the comment marker does: navori generated the
 * file (`managed`) and which navori release did (`version`, on the CLI's release
 * scale, the one `isDowngrade` compares).
 *
 * It lives in `lib/` and not next to the Claude engine that first needed it
 * because two very different questions read it: "may the adapter overwrite this
 * settings.json?" and "may `render --prune` delete this file?" (#538 — the prune
 * kept every generated JSON as "we did not write it", which was a lie about a
 * file navori had written whole). Two copies of the marker's shape is how the
 * second question got answered wrong for a year.
 */

export const NAVORI_OWNERSHIP_KEY = "$navori";

/** What the `$navori` key declares about the file that carries it. */
export interface NavoriOwnership {
  /** navori generated this file WHOLE — the JSON twin of a managed block that
   *  spans the entire file. A hybrid file navori only edits by key (`.mcp.json`,
   *  a coexisting `settings.json`) deliberately leaves this false. */
  managed: boolean;
  /** The navori release that wrote it, or undefined when the marker predates
   *  the stamp. Same scale as a managed block's `version=`. */
  version?: string;
}

/** Read the marker out of an ALREADY parsed JSON value. `null` when the value
 *  is not an object or carries no `$navori` object. */
export function parseNavoriOwnership(parsed: unknown): NavoriOwnership | null {
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  const navori = (parsed as Record<string, unknown>)[NAVORI_OWNERSHIP_KEY];
  if (!navori || typeof navori !== "object" || Array.isArray(navori)) return null;
  const record = navori as Record<string, unknown>;
  const version = record.version;
  return {
    managed: record.managed === true,
    version: typeof version === "string" && version.length > 0 ? version : undefined,
  };
}

/** Read the marker out of a file's raw text. `null` when the text is not JSON —
 *  which is the answer for every non-JSON file, so callers can try this
 *  notation on any content without checking the extension first. Deciding by
 *  CONTENT and not by path is the whole lesson of #496. */
export function readNavoriOwnership(content: string): NavoriOwnership | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    return null;
  }
  return parseNavoriOwnership(parsed);
}

/**
 * Whether a parsed `.claude/settings.json` was generated by navori. When it was
 * not, the engine adapter treats the file as the user's and refuses to overwrite
 * it (DT-2 in spec 0002).
 */
export function isNavoriOwnedSettings(parsed: unknown): boolean {
  return parseNavoriOwnership(parsed)?.managed === true;
}

/** Outcome of {@link planStampedJson}. */
export type StampedJsonPlan =
  | { kind: "noop" }
  | { kind: "write"; content: string }
  /** A real change, but the file's stamp (or the harness floor) is newer than
   *  the CLI: writing would roll a newer navori's output back (#79). */
  | { kind: "downgrade-skipped"; existingVersion: string };

/**
 * Decide whether a navori-stamped JSON file (`.claude/settings.json`,
 * `.mcp.json`) must be rewritten, without letting the release number alone
 * force a write. The stamp records the release that last CHANGED the file:
 *
 *  - candidate identical to the file once the candidate carries the EXISTING
 *    stamp → `noop` (a newer CLI over unchanged content leaves it untouched);
 *  - otherwise it is a real change: when the existing stamp or the harness
 *    `floor` is newer than the CLI → `downgrade-skipped` (unless `force`);
 *    else `write` the candidate, stamped with the CLI version.
 *
 * `candidate` is the full serialized file stamped with the CLI version. A file
 * with no readable stamp, or a candidate with none, falls back to byte equality.
 */
export function planStampedJson(
  current: string,
  candidate: string,
  cliVersion: string,
  floor?: string,
  force = false,
): StampedJsonPlan {
  if (current === candidate) return { kind: "noop" };
  const existingVersion = readNavoriOwnership(current)?.version;
  if (existingVersion !== undefined) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(candidate);
    } catch {
      parsed = null;
    }
    const ownership = parseNavoriOwnership(parsed);
    if (ownership !== null && parsed !== null && typeof parsed === "object") {
      const record = parsed as Record<string, unknown>;
      // Reassigning an existing key keeps its position (the stamp stays first).
      const frozen = {
        ...record,
        [NAVORI_OWNERSHIP_KEY]: {
          ...(record[NAVORI_OWNERSHIP_KEY] as Record<string, unknown>),
          version: existingVersion,
        },
      };
      if (JSON.stringify(frozen, null, 2) + "\n" === current) return { kind: "noop" };
    }
  }
  if (!force) {
    if (isDowngrade(existingVersion, cliVersion)) {
      return { kind: "downgrade-skipped", existingVersion: existingVersion as string };
    }
    if (isDowngrade(floor, cliVersion)) {
      return { kind: "downgrade-skipped", existingVersion: floor as string };
    }
  }
  return { kind: "write", content: candidate };
}
