import { existsSync, readFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { parse as parseToml } from "smol-toml";
import { effectiveConfig, type NavoriConfig } from "../../lib/config/config.ts";
import { getCoreRoot, readCliVersion } from "../../lib/render/bundled-assets.ts";
import {
  loadDisabledPlugins,
  loadEnabledPlugins,
  type LoadedPlugin,
} from "../../lib/config/plugins.ts";
import { unknownLibraries } from "../../lib/assets/library-skills.ts";
import {
  droppedLibrariesWarnings,
  isPresetLoaded,
  loadPreset,
  PresetError,
} from "../../lib/config/presets.ts";
import { tc, resolveLang } from "../../lib/i18n.ts";
import { parseAsset } from "../claude/parse-asset.ts";
import { renderManagedFile } from "../shared/render-managed-file.ts";
import { interpolate } from "../../lib/render/interpolate.ts";
import { conditionOrchestration } from "../../lib/render/render-plan.ts";
import {
  getFrontmatterField,
  removeFrontmatterField,
  splitFrontmatter,
  stripFrontmatter,
} from "../../lib/render/frontmatter.ts";
import {
  extractManagedContent,
  injectManagedSection,
  removeManagedSection,
} from "../../lib/render/marker.ts";
import { buildHarnessProse, type ProseEngineResult } from "../shared/prose-harness.ts";
import {
  hoistedPlannedSkill,
  hoistTransform,
  type HoistedSkill,
  type WorkspaceHarness,
} from "../shared/workspace-skills.ts";
import { buildAgentsIndexBlock } from "../shared/agents-index.ts";
import { pluginExtraVars } from "../shared/plugin-extra-vars.ts";
import { buildEngramPolicyShell } from "../shared/engram-grant-policy.ts";
import { buildRolePolicyShell } from "../shared/role-policy.ts";
import { pluginScriptCollisions, pluginScriptPlacements } from "../shared/plugin-scripts.ts";
import {
  resolveHarnessPlan,
  type HarnessPlan,
  type PlannedAgent,
  type PlannedHook,
  type PlannedSkill,
} from "../shared/harness-plan.ts";
import {
  collectPlan,
  collisionWarnings,
  commitWrites,
  type AdapterCtx,
  type EngineAdapter,
  type PlacementRequest,
} from "../shared/execute-plan.ts";
import {
  applyHookExtension,
  hookExtensionTarget,
  removeHookExtension,
} from "../shared/hook-extension.ts";
import { buildCodexConfigToml } from "./build-config-toml.ts";
import {
  codexHookCommand,
  resolveCodexHooks,
  resolvePluginCodexHooks,
} from "./hook-registrations.ts";
import { buildCodexRules } from "./build-rules.ts";
import { collectShellPermissionRules } from "../shared/permission-rules.ts";
import { adaptHarnessTextForCodex } from "./compat.ts";
import {
  buildLocalSkillPointerContent,
  classifyLocalSkills,
  isManualOnlyLocalSkill,
  localSkillPointerDestRel,
  localSkillPointerMarkerId,
  localSkillSourceAbs,
  type ClassifiedLocalSkills,
} from "../shared/local-skill-pointer.ts";

import { readRenderedCodexModel, resolveCodexModel } from "../../lib/assets/model-profile.ts";

const NAVORI_VERSION = readCliVersion();

// A plugin skill declared with `injectInto: .claude/skills/<id>/SKILL.md` (or the
// flat legacy `.claude/skills/<id>.md`) extends an existing skill. Captures the
// target skill id; skill→agent injectInto (`.claude/agents/<id>.md`) does NOT
// match here — that path is handled inside buildAgentToml.
const SKILL_INJECT_RE = /^\.claude\/skills\/([a-z0-9-]+)(?:\/SKILL)?\.md$/;

// A plugin skill can also inject into an agent (`injectInto: .claude/agents/<id>.md`).
// The orchestrator is embodied by the main thread (appended to AGENTS.md); other rendered
// agents are covered by buildAgentToml. A target that is NEITHER — a disabled or
// otherwise non-rendered agent — would drop silently, so we warn (#277).
const AGENT_INJECT_RE = /^\.claude\/agents\/([a-z0-9-]+)\.md$/;

/**
 * Codex's confirmed native equivalent of Claude's `disable-model-invocation`
 * (https://developers.openai.com/codex/skills, verified): a sibling
 * `agents/openai.yaml` inside the skill dir with `allow_implicit_invocation:
 * false` stops implicit (natural-language) triggering; explicit `$<skill>`
 * invocation still works. #823.
 */
const OPENAI_MANUAL_ONLY_POLICY = "policy:\n  allow_implicit_invocation: false\n";

/** Read straight off the skill's own frontmatter rather than a per-skill list,
 * so any skill that opts out of model invocation gets the Codex sidecar
 * automatically — never keyed to one skill's id. */
function isManualOnlySkill(assetPath: string): boolean {
  const { frontmatter } = splitFrontmatter(readFileSync(assetPath, "utf-8"));
  return getFrontmatterField(frontmatter, "disable-model-invocation") === "true";
}

export type CodexEngineResult = ProseEngineResult;

/** The header navori seeds a fresh `.codex/config.toml` with. */
const CODEX_CONFIG_HEADER = "# Codex project config generated by navori.\n";
/** The header navori seeds a fresh `.codex/rules/navori.rules` with. */
const CODEX_RULES_HEADER = "# Codex terminal permission rules generated by navori.\n";

/**
 * Where Codex places a skill and how it renders it. One definition for the
 * adapter, the fresh-render oracle and the skills the root writes for a
 * workspace (`transform` is the `slug-id` rewrite), so they cannot disagree.
 */
function codexSkillRequest(
  skill: PlannedSkill,
  config: NavoriConfig,
  hoist?: (text: string) => string,
): PlacementRequest {
  return {
    assetPath: skill.assetPath,
    // #364: skills ship as raw assets, so without this the body kept
    // pointing at `.claude/progress/` while the adapted agents read and
    // write `.codex/progress/` — the 8-phase pipeline scattered its
    // artifacts across two directories and the gates found nothing.
    //
    // #823: `disable-model-invocation` is dropped AFTER the vocabulary
    // pass, here rather than in `adaptHarnessTextForCodex` — that function
    // is a generic prose adapter that also runs over AGENTS.md and every
    // agent `.toml`, neither of which has skill frontmatter to strip.
    // Codex's own equivalent is emitted separately, as `agents/openai.yaml`
    // (see `extraFiles`), not as a frontmatter key.
    transform: (text) =>
      removeFrontmatterField(
        adaptHarnessTextForCodex(hoist ? hoist(text) : text, config),
        "disable-model-invocation",
      ),
    destRelPath: `.agents/skills/${skill.id}/SKILL.md`,
    managedId: skill.managedId,
    commentStyle: "html",
  };
}

/** The body a plugin skill contributes as a sub-block of `.agents/skills/<id>/SKILL.md`. */
function codexSubBlockBody(skill: LoadedPlugin["skillAssets"][number], config: NavoriConfig) {
  return adaptHarnessTextForCodex(
    interpolate(stripFrontmatter(readFileSync(skill.absPath, "utf-8")), config, {
      extraVars: pluginExtraVars(config),
    }),
    config,
  );
}

/**
 * A skill as `renderCodexEngine` writes it — `existingContent` null for the fresh
 * bytes, an on-disk copy to refresh it the way a render would — with every plugin
 * sub-block aimed at it.
 */
function composeCodexSkill(
  skill: PlannedSkill,
  config: NavoriConfig,
  plugins: readonly LoadedPlugin[],
  existingContent: string | null,
  hoist?: (text: string) => string,
): string {
  const effective = effectiveConfig(config);
  const request = codexSkillRequest(skill, effective, hoist);
  let content = renderManagedFile({
    assetPath: skill.assetPath,
    existingContent,
    managedId: skill.managedId,
    meta: { source: "@navori/core", version: NAVORI_VERSION },
    config: effective,
    commentStyle: "html",
    transform: request.transform,
    engine: "codex",
  }).content;
  for (const plugin of plugins) {
    for (const asset of plugin.skillAssets) {
      if (asset.injectInto?.match(SKILL_INJECT_RE)?.[1] !== skill.id) continue;
      content = injectManagedSection(
        content,
        asset.id,
        codexSubBlockBody(asset, effective),
        { source: `@navori/plugin-${plugin.manifest.id}`, version: NAVORI_VERSION },
        "html",
      ).output;
    }
  }
  return content;
}

/** The bytes `renderCodexEngine` writes for one skill into an empty directory (spec 0043). */
export function composeFreshCodexSkill(
  skill: PlannedSkill,
  config: NavoriConfig,
  plugins: readonly LoadedPlugin[],
  hoist?: (text: string) => string,
): string {
  return composeCodexSkill(skill, config, plugins, null, hoist);
}

/** An on-disk Codex skill copy refreshed the way a render would write it now (spec 0043). */
export function normalizeCodexSkill(
  onDisk: string,
  skill: PlannedSkill,
  config: NavoriConfig,
  plugins: readonly LoadedPlugin[],
  hoist?: (text: string) => string,
): string {
  return composeCodexSkill(skill, config, plugins, onDisk, hoist);
}

/**
 * The skills `renderCodexEngine` would plan for `config`, without rendering
 * anything (spec 0043): the single plan producer Codex's workspace decision
 * shares with the engine. `presetLoaded` is false when the declared preset did
 * not load, so its skills are missing from `skills`. Emits no warnings.
 */
export function planCodexSkills(
  _cwd: string,
  inputConfig: NavoriConfig,
  opts: { repoRoot: string },
): {
  skills: readonly PlannedSkill[];
  presetLoaded: boolean;
  plugins: readonly LoadedPlugin[];
} {
  const config = effectiveConfig(inputConfig);
  const preset = loadActivePreset(config, opts.repoRoot, []);
  return {
    skills: resolveHarnessPlan(config, resolve(getCoreRoot(), "core-assets"), preset, {
      engine: "codex",
    }).skills,
    presetLoaded: isPresetLoaded(config, preset),
    plugins: loadEnabledPlugins(config.plugins).loaded,
  };
}

/** A skill a scan may judge against its fresh bytes: the planned skill, the config it renders with, its `slug-id` rewrite. */
interface CodexUnit {
  skill: PlannedSkill;
  config: NavoriConfig;
  hoist?: (text: string) => string;
}

/** What `createCodexAdapter` needs to know about the workspace-skill scope of this render. */
interface CodexScope {
  /** A workspace under `workspaceHarness: "root"` (spec 0043 R8): its context file and nothing else. */
  root: boolean;
  /** Skills the root writes on a workspace's behalf, desired at the root under their final name. */
  hoisted: readonly HoistedSkill[];
  /** Units a scan may judge against their fresh bytes instead of by marker alone. */
  units: ReadonlyMap<string, CodexUnit>;
}

/**
 * Full Codex adapter (Spec 0007, Capa 2). Codex v0.145 discovers repo skills
 * from `.agents/skills`, project config/hooks/agents from `.codex/`, and
 * durable guidance from `AGENTS.md`. This module only maps each planned asset
 * to a destination + serialization; the render pipeline lives in executePlan.
 */
export function renderCodexEngine(
  cwd: string,
  inputConfig: NavoriConfig,
  options: {
    dryRun?: boolean;
    repoRoot?: string;
    /**
     * Spec 0043 R8: only `root` trims a Codex workspace. `minimal` and `full`
     * leave it exactly as it was (Codex under `minimal` is the user's decision).
     */
    harnessScope?: WorkspaceHarness;
    /**
     * Skills the root provides, so a workspace under `root` does not write them;
     * `prune: false` (`sync`) only stops writing and deletes nothing. Read only
     * under `root`.
     */
    workspaceSkills?: { omitted: ReadonlySet<string>; prune: boolean };
    /** Passed by the ROOT render: what the workspaces hand up and the dirs a previous hoist may have left. */
    rootHoist?: {
      skills: readonly HoistedSkill[];
      pruneCandidates: readonly HoistedSkill[];
    };
  } = {},
): CodexEngineResult {
  const config = effectiveConfig(inputConfig);
  const lang = resolveLang(config.language);
  const dryRun = options.dryRun === true;
  const repoRoot = options.repoRoot ?? cwd;
  const isWorkspace = resolve(repoRoot) !== resolve(cwd);
  const rootScope = isWorkspace && options.harnessScope === "root";
  const coreAssets = resolve(getCoreRoot(), "core-assets");
  const pluginsResult = loadEnabledPlugins(config.plugins);
  const plugins = pluginsResult.loaded;

  const warnings = pluginsResult.missing.map(({ id, reason }) =>
    tc(lang).engine.pluginLoadFailedCodex(id, reason),
  );
  // Spec 0035 D10/T10: the unconditional "review with /hooks" reminder moved
  // to `renderNonClaudeEngines` (render.ts), which only prints it when
  // `readCodexTrustState` finds something actually missing, and points at
  // `navori codex trust` instead of the deprecated `/hooks` flow.

  const preset = loadActivePreset(config, repoRoot, warnings);
  const presetLoadedSafely = isPresetLoaded(config, preset);

  // Subpath from the repo root to this render's cwd ("" at the root, e.g.
  // "apps/backend" in a workspace), normalized to POSIX for the bash hook command
  // (#279). Lets config.toml point at the hook co-located with THIS workspace.
  const wsSubpath = isWorkspace
    ? relative(resolve(repoRoot), resolve(cwd)).split(sep).join("/")
    : "";

  const fullPlan = resolveHarnessPlan(config, coreAssets, preset, { engine: "codex" });
  // Spec 0043 R8: under `root` a workspace keeps no agents, no hooks and only the
  // skills the root does not provide; everything else is the root's.
  const omittedSkills = rootScope
    ? (options.workspaceSkills?.omitted ?? new Set<string>())
    : new Set<string>();
  const plan: HarnessPlan = rootScope
    ? { agents: [], hooks: [], skills: fullPlan.skills.filter((s) => !omittedSkills.has(s.id)) }
    : fullPlan;
  // Mirror of the Claude engine's unknown-library warning (audit v0.5.1 A1):
  // an id the plan skipped silently would lose its guidance without signal.
  for (const lib of unknownLibraries([
    ...(config.project?.libraries ?? []),
    ...(config.project?.extraLibraries ?? []),
  ])) {
    warnings.push(
      lib.removed
        ? tc(lang).engine.libraryRemovedFromRegistry(lib.id, lib.successors)
        : tc(lang).engine.libraryUnknownInRegistry(lib.id),
    );
  }

  // Spec 0033 D2 (R9-R12): classify `project.localSkills` ids once — `plan`
  // already exists here, so this is the one call site that gets `plan.skills`
  // for free instead of re-deriving it. `emit` is threaded into the adapter
  // below so `extraFiles`/`orphanScans` never re-derive the same question with
  // a different criterion. `missing` is NOT reported here: R11 requires
  // `render` to name it regardless of which engines are configured, exactly
  // once per run — `commands/render.ts` owns that (a single centralized
  // check), so a claude+codex repo never sees it twice. `foreign` stays here:
  // it's specifically about the `.agents/skills/<id>/` destination, which only
  // exists when Codex renders.
  const localSkills = classifyLocalSkills(
    cwd,
    config.project?.localSkills ?? [],
    new Set(fullPlan.skills.map((s) => s.id)),
  );
  for (const id of localSkills.foreign) {
    warnings.push(tc(lang).engine.localSkillForeignCodex(localSkillPointerDestRel(id)));
  }

  // Floor / safety net (#277): a plugin skill targeting an agent Codex neither
  // renders as a `.toml` (buildAgentToml) nor embodies as the orchestrator (appended to
  // AGENTS.md) is dropped silently. Warn so a disabled/unknown agent target surfaces
  // instead of vanishing — mirroring how the prose engines report their omissions.
  const renderedAgentIds = new Set(plan.agents.map((a) => a.id));
  for (const plugin of plugins) {
    for (const skill of plugin.skillAssets) {
      const injectInto = skill.injectInto;
      if (injectInto === undefined) continue;
      const agentId = injectInto.match(AGENT_INJECT_RE)?.[1];
      if (agentId === undefined || agentId === "orchestrator" || renderedAgentIds.has(agentId))
        continue;
      warnings.push(
        tc(lang).engine.pluginSkillNotInjected(skill.id, plugin.manifest.id, injectInto),
      );
    }
  }

  const ctx: AdapterCtx = { cwd, config, repoRoot, isWorkspace, coreAssets, preset, plugins };
  // Spec 0035 T6/T7 (D5, D8): `.codex/config.toml` and `.codex/rules/navori.rules`
  // are now built INSIDE `extraFiles`, after `AGENTS.md`'s planned body is known
  // — `project_doc_max_bytes` needs its byte size (R12), and both need only
  // `wsSubpath`/`localSkills`, already closed over here. `codexWarnings` is the
  // channel back out: `extraFiles` runs deep inside `collectPlan`, so it can't
  // push onto the outer `warnings` array directly.
  const codexWarnings: string[] = [];
  const units = new Map<string, CodexUnit>();
  // Judged against their fresh bytes, not by marker alone: the workspace's own copies of
  // what it omits, and the root dirs a previous hoist may have left (spec 0043).
  if (rootScope) for (const skill of fullPlan.skills) units.set(skill.id, { skill, config });
  for (const c of options.rootHoist?.pruneCandidates ?? []) {
    const hoist = hoistTransform(c);
    units.set(c.id, {
      skill: hoistedPlannedSkill(c),
      config: effectiveConfig(c.config),
      ...(hoist ? { hoist } : {}),
    });
  }
  const adapter = createCodexAdapter(wsSubpath, localSkills, codexWarnings, {
    root: rootScope,
    hoisted: options.rootHoist?.skills ?? [],
    units,
  });

  // Split collect/commit so plugin skills that extend another skill (injectInto
  // a `.claude/skills/<id>/SKILL.md`, e.g. jscpd → review-diff) can be
  // appended as a managed sub-block BEFORE the single write — mirroring the
  // Claude adapter, but into Codex's `.agents/skills/<id>/SKILL.md` and adapted
  // to Codex's vocabulary. (skill→agent injectInto is handled in buildAgentToml.)
  const { pending, removals, skipped, kept, collisions } = collectPlan(plan, adapter, ctx, {
    prune: presetLoadedSafely && (!rootScope || (options.workspaceSkills?.prune ?? true)),
    lang,
  });
  // Spec 0043 R5: skills a workspace hands up, each rendered with ITS config under its final name.
  for (const h of options.rootHoist?.skills ?? []) {
    const hoistConfig = effectiveConfig(h.config);
    const hoisted = collectPlan(
      { agents: [], hooks: [], skills: [hoistedPlannedSkill(h)] },
      createHoistAdapter(h, hoistConfig),
      { ...ctx, config: hoistConfig },
      { prune: false, lang },
    );
    pending.push(...hoisted.pending);
    skipped.push(...hoisted.skipped);
    collisions.push(...hoisted.collisions);
  }
  warnings.push(...codexWarnings);
  for (const write of pending) {
    if (!write.relPath.startsWith(".codex/scripts/") || write.status !== "updated") continue;
    const old = readFileSync(write.path, "utf-8");
    const oldBody = extractManagedContent(old, scriptManagedId(old), "shell");
    const newBody = extractManagedContent(write.content, scriptManagedId(write.content), "shell");
    if (oldBody !== null && newBody !== null && oldBody !== newBody) {
      warnings.push(tc(lang).engine.codexPluginScriptChanged(write.relPath));
    }
  }
  if (skipped.some((item) => item.path === ".codex/config.toml")) {
    const configPath = join(cwd, ".codex/config.toml");
    if (existsSync(configPath)) {
      const configText = readFileSync(configPath, "utf-8");
      const registered = projectHookCommands(configText);
      for (const hook of resolvePluginCodexHooks(loadDisabledPlugins(config.plugins).loaded)
        .hooks) {
        const command = codexHookCommand(hook, wsSubpath);
        if (registered.has(command) || configText.includes(command)) {
          warnings.push(tc(lang).engine.codexResidualPluginHook(hook.scriptPath ?? hook.script));
        }
      }
    }
  }
  // R39/R41 (spec 0026 T10): Codex reports a kept orphan the same way Claude's
  // §8.7b–d retirement loops do — path + reason, plain text in `warnings`,
  // never silently skipped. Generic over every orphan scan (agents/skills/
  // hooks), a superset of "retired ids" that stays correct once T11 starts
  // pruning old agent ids here too.
  for (const k of kept) {
    warnings.push(tc(lang).engine.keptOrphanCodex(k.path, k.reason));
  }
  for (const plugin of plugins) {
    for (const skill of plugin.skillAssets) {
      const m = skill.injectInto?.match(SKILL_INJECT_RE);
      if (!m) continue;
      const targetRel = `.agents/skills/${m[1]}/SKILL.md`;
      const targetAbs = join(cwd, targetRel);
      // The base skill may not be in `pending` if it's unchanged this render
      // (e.g. `navori add jscpd` on an already-rendered repo). Fall back to
      // the on-disk copy and add it back to the write set, like the Claude adapter.
      const inPending = pending.find((p) => p.path === targetAbs);
      const baseContent =
        inPending?.content ?? (existsSync(targetAbs) ? readFileSync(targetAbs, "utf-8") : null);
      if (baseContent === null) {
        warnings.push(
          tc(lang).engine.pluginSkillNotInjected(skill.id, plugin.manifest.id, targetRel),
        );
        continue;
      }
      const injected = injectManagedSection(
        baseContent,
        skill.id,
        codexSubBlockBody(skill, config),
        { source: `@navori/plugin-${plugin.manifest.id}`, version: NAVORI_VERSION },
        "html",
      );
      if (inPending) {
        inPending.content = injected.output;
      } else if (injected.status === "created" || injected.status === "updated") {
        pending.push({
          path: targetAbs,
          relPath: targetRel,
          content: injected.output,
          status: injected.status,
        });
      }
    }
  }

  // Reconcile DISABLED plugins — mirror of the Claude engine's §8.5 (#80), here
  // for Codex (#211). A plugin turned off via `navori remove` (phase 1 renders
  // with `enabled: false` BEFORE phase 2 drops the config key) still has its
  // injectInto sub-block sitting in `.agents/skills/<id>/SKILL.md`: that file was
  // only ever touched on the enabled path above, so without this it would orphan
  // permanently — no future render could see the plugin to clean it. Strip the
  // sub-block by id while the disabled entry still declares the plugin.
  for (const plugin of loadDisabledPlugins(config.plugins).loaded) {
    for (const skill of plugin.skillAssets) {
      const m = skill.injectInto?.match(SKILL_INJECT_RE);
      if (!m) continue;
      const targetRel = `.agents/skills/${m[1]}/SKILL.md`;
      const targetAbs = join(cwd, targetRel);
      const inPending = pending.find((p) => p.path === targetAbs);
      const currentContent =
        inPending?.content ?? (existsSync(targetAbs) ? readFileSync(targetAbs, "utf-8") : null);
      if (currentContent === null) continue; // target file gone — nothing to strip
      const stripped = removeManagedSection(currentContent, skill.id, "html");
      if (stripped === currentContent) continue; // sub-block not present
      if (inPending) {
        inPending.content = stripped;
      } else {
        pending.push({ path: targetAbs, relPath: targetRel, content: stripped, status: "updated" });
      }
    }
  }

  // Spec 0041 R29: plugin hook extensions (the tgrep search lane) ride inside the
  // Codex copy of the hook they extend, so no hook of their own is registered.
  // The extension body is engine-neutral; only the hook path moves.
  for (const plugin of plugins) {
    for (const extension of plugin.hookExtensionAssets ?? []) {
      const target = hookExtensionTarget(extension.target, "codex");
      if (target === null) continue;
      applyHookExtension({
        cwd,
        plugin,
        extension,
        target,
        config,
        pending,
        skipped,
        updatesAvailable: [],
        downgrades: [],
        withRelPath: true,
      });
    }
  }
  for (const plugin of loadDisabledPlugins(config.plugins).loaded) {
    for (const extension of plugin.hookExtensionAssets ?? []) {
      const target = hookExtensionTarget(extension.target, "codex");
      if (target === null) continue;
      removeHookExtension({ cwd, extension, target, pending, withRelPath: true });
    }
  }

  const { written, backupPath } = commitWrites({
    pending,
    removals,
    cwd,
    dryRun,
    writeLast: (p) => p.path.endsWith("/AGENTS.md"),
    engineLabel: adapter.label ?? adapter.id,
    lang,
  });
  // #1114: after commitWrites so the backup path is known (null in a dry run).
  warnings.push(...collisionWarnings(collisions, backupPath, lang));

  return {
    written,
    skipped,
    // A workspace render drops the repo-level advisories (the root run already said
    // them), except under `root`: what a workspace keeps is only ITS to report.
    warnings: rootScope
      ? kept.map((k) => tc(lang).engine.keptOrphanCodex(k.path, k.reason))
      : isWorkspace
        ? []
        : warnings,
    backupPath,
  };
}

/**
 * Spec 0041 D15 (R13, R30): the ONE set of repo-relative script paths Codex
 * installs under `.codex/hooks/` and `.codex/scripts/`. A script lands only if
 * a registered hook (core row or plugin hook) runs it, or a hook extension that
 * rides inside an installed hook sources it (R29: the tgrep guard under
 * `guard-destructive`). Shell partials (`# navori:include`) are inlined at
 * render time, so no extra file backs a registered script. A script nothing
 * runs (unsupported rows, plugin scripts with no registration and no extension
 * host) is not installed, and a previously installed one is retired by the
 * orphan scan.
 */
export function codexInstalledScripts(
  config: NavoriConfig,
  plugins: readonly LoadedPlugin[],
): ReadonlySet<string> {
  const installed = new Set(
    resolveCodexHooks(config, plugins).map(
      (hook) => hook.scriptPath ?? `.codex/hooks/${hook.script}.sh`,
    ),
  );
  for (const plugin of plugins) {
    const hosted = (plugin.hookExtensionAssets ?? []).some((extension) => {
      const target = hookExtensionTarget(extension.target, "codex");
      return target !== null && installed.has(target);
    });
    if (!hosted) continue;
    for (const script of plugin.scriptAssets) installed.add(`.codex/scripts/${script.dest}`);
  }
  return installed;
}

/** Read only executable command handlers, not comments or incidental TOML text. */
function projectHookCommands(content: string): Set<string> {
  try {
    const parsed: unknown = parseToml(content);
    if (typeof parsed !== "object" || parsed === null || !("hooks" in parsed)) return new Set();
    const groups = parsed.hooks;
    if (typeof groups !== "object" || groups === null) return new Set();
    const commands = new Set<string>();
    for (const entries of Object.values(groups)) {
      if (!Array.isArray(entries)) continue;
      for (const entry of entries) {
        if (typeof entry !== "object" || entry === null || !("hooks" in entry)) continue;
        if (!Array.isArray(entry.hooks)) continue;
        for (const handler of entry.hooks) {
          if (
            typeof handler === "object" &&
            handler !== null &&
            "type" in handler &&
            handler.type === "command" &&
            "command" in handler &&
            typeof handler.command === "string"
          )
            commands.add(handler.command);
        }
      }
    }
    return commands;
  } catch {
    return new Set();
  }
}

/** The generated script's opening marker carries its unique managed id. */
function scriptManagedId(content: string): string {
  return content.match(/^# navori:managed start id="([^"]+)"/m)?.[1] ?? "";
}

/**
 * Builds a fresh, stateful adapter per render. `placeAgent` accumulates the
 * agent catalog that `extraFiles` folds into AGENTS.md, and `placeSkill`
 * accumulates the manual-only skills that `extraFiles` turns into
 * `agents/openai.yaml` sidecars (#823) — so the executor must place
 * agents/skills before calling extraFiles (it does, see `collectPlan`).
 */
function createCodexAdapter(
  wsSubpath: string,
  localSkills: ClassifiedLocalSkills,
  /** Mutated in place — `extraFiles` runs inside `collectPlan`, so this is the
   *  only channel back to the caller's `warnings` array (spec 0035 T6/T7). */
  warningsSink: string[],
  scope: CodexScope,
): EngineAdapter {
  const agentCatalog: Array<{ id: string; description: string }> = [];
  const manualOnlySkillIds: string[] = [];
  let installed: ReadonlySet<string> | null = null;
  // Under `root` no script is installed in the workspace, so none is desired there.
  const installedScripts = (ctx: AdapterCtx): ReadonlySet<string> =>
    (installed ??= scope.root ? new Set() : codexInstalledScripts(ctx.config, ctx.plugins));

  return {
    id: "codex",
    label: "Codex",

    placeAgent(agent, ctx): PlacementRequest {
      const { body, description } = buildAgentToml(
        agent,
        ctx.config,
        ctx.plugins,
        warningsSink,
        ctx.cwd,
      );
      agentCatalog.push({ id: agent.id, description });
      // Codex auto-discovers standalone project agents from `.codex/agents/`;
      // config.toml does not need one registration table per file.
      return {
        body,
        destRelPath: `.codex/agents/${agent.id}.toml`,
        managedId: `${agent.id}-codex-base`,
        commentStyle: "shell",
      };
    },

    placeSkill(skill, ctx): PlacementRequest {
      if (isManualOnlySkill(skill.assetPath)) manualOnlySkillIds.push(skill.id);
      return codexSkillRequest(skill, ctx.config);
    },

    placeHook(hook, ctx): PlacementRequest | null {
      const request = hookRequest(hook, ctx.config);
      return installedScripts(ctx).has(request.destRelPath) ? request : null;
    },

    extraFiles(ctx): PlacementRequest[] {
      // Spec 0033 D2: one pointer per `emit` id, `assetPath` pointed at the
      // SOURCE (`.claude/skills/<id>/SKILL.md`) so frontmatter merge, version
      // stamping and anti-rollback all come from `renderManagedFile` for free
      // — `transform` swaps the body for the pointer text, never the source's
      // own prose. `missing`/`foreign` get no request at all (R11, R12).
      const localSkillManualOnlyIds: string[] = [];
      const localSkillRequests: PlacementRequest[] = [];
      for (const id of scope.root ? [] : localSkills.emit) {
        const sourceAbs = localSkillSourceAbs(ctx.cwd, id);
        if (sourceAbs === null) continue; // classify guarantees this for `emit`, guard for TS
        if (isManualOnlyLocalSkill(sourceAbs)) localSkillManualOnlyIds.push(id);
        localSkillRequests.push({
          assetPath: sourceAbs,
          transform: (text) => buildLocalSkillPointerContent(text, id),
          destRelPath: localSkillPointerDestRel(id),
          managedId: localSkillPointerMarkerId(id),
          commentStyle: "html",
        });
      }
      // R12/D8: `project_doc_max_bytes` needs the PLANNED AGENTS.md size, not
      // whatever is on disk — both files are written by this same render.
      const agentsMdRequest = buildAgentsMdRequest(ctx, agentCatalog);
      // Spec 0043 R8: under `root` the workspace holds its AGENTS file and nothing else.
      if (scope.root) return [agentsMdRequest];
      const agentsMdBytes = Buffer.byteLength(agentsMdRequest.body ?? "", "utf-8");

      // R9/R10 (D5): translate the SAME permission source Claude writes into
      // `.claude/settings.json` into `.codex/rules/navori.rules`.
      const permissionRules = collectShellPermissionRules(ctx.config, ctx.plugins);
      const codexRules = buildCodexRules(permissionRules);
      const droppedNotBash = codexRules.dropped.filter((d) => d.reason === "not-bash").length;
      const droppedWildcard = codexRules.dropped.filter(
        (d) => d.reason === "inner-wildcard",
      ).length;
      if (codexRules.dropped.length > 0 || codexRules.narrowed.length > 0) {
        warningsSink.push(
          tc(resolveLang(ctx.config.language)).engine.codexRulesSummary(
            droppedNotBash,
            droppedWildcard,
            codexRules.narrowed.length,
          ),
        );
      }

      const codexConfig = buildCodexConfigToml(ctx.config, ctx.plugins, wsSubpath, agentsMdBytes);
      warningsSink.push(...codexConfig.warnings);

      const collisions = pluginScriptCollisions(ctx.plugins);
      const pluginScripts: PlacementRequest[] = [];
      for (const plugin of ctx.plugins) {
        for (const script of pluginScriptPlacements(plugin, "codex")) {
          if (collisions.has(script.dest)) continue;
          if (!installedScripts(ctx).has(script.destRelPath)) continue;
          pluginScripts.push({
            assetPath: script.src,
            destRelPath: script.destRelPath,
            managedId: script.managedId,
            meta: script.meta,
            extraVars: pluginExtraVars(ctx.config),
            commentStyle: "shell",
            chmodExec: script.exec,
          });
        }
      }

      return [
        agentsMdRequest,
        orchestratorRequest(ctx),
        configTomlRequest(codexConfig.body),
        rulesRequest(codexRules.body),
        ...localSkillRequests,
        ...pluginScripts,
        // #823: one `agents/openai.yaml` sidecar per manual-only skill — Codex's
        // native `allow_implicit_invocation: false`, shell-comment managed so it
        // gets the same backup/anti-downgrade/prune treatment as every other file.
        ...[...manualOnlySkillIds, ...localSkillManualOnlyIds].map((id): PlacementRequest => ({
          body: OPENAI_MANUAL_ONLY_POLICY,
          destRelPath: `.agents/skills/${id}/agents/openai.yaml`,
          managedId: `${id}-openai-policy`,
          commentStyle: "shell",
        })),
      ];
    },

    orphanScans(plan, ctx): ReturnType<EngineAdapter["orphanScans"]> {
      // `emit ∪ foreign` protects a declared local skill's destination from
      // ever being pruned or reported as an orphan — `foreign` because it
      // isn't navori's to touch either way, `emit` because it IS the desired
      // pointer path. Only ids that fell out of both (`missing`, or removed
      // from `project.localSkills`) may be pruned.
      const localSkillDesired = scope.root ? [] : [...localSkills.emit, ...localSkills.foreign];
      const localSkillManualOnlyIds = (scope.root ? [] : localSkills.emit).filter((id) => {
        const sourceAbs = localSkillSourceAbs(ctx.cwd, id);
        return sourceAbs !== null && isManualOnlyLocalSkill(sourceAbs);
      });
      return [
        {
          dir: ".codex/agents",
          match: (name) => name.endsWith(".toml"),
          desired: new Set(plan.agents.map(({ id }) => `.codex/agents/${id}.toml`)),
          shape: "file",
        },
        {
          dir: ".agents/skills",
          match: () => true,
          desired: new Set([
            ...plan.skills.map(({ id }) => `.agents/skills/${id}/SKILL.md`),
            ...scope.hoisted.map(({ id }) => `.agents/skills/${id}/SKILL.md`),
            ...localSkillDesired.map((id) => localSkillPointerDestRel(id)),
          ]),
          shape: "skill-dir",
          // Spec 0043 R7/R8: the units this render may judge against their fresh
          // bytes (a workspace's own copies, a previous hoist's leftovers) go only
          // when navori wrote them untouched; any other id keeps the marker test.
          expected: (rel) => {
            const unit = skillUnitAt(scope.units, rel);
            return unit
              ? composeFreshCodexSkill(unit.skill, unit.config, ctx.plugins, unit.hoist)
              : null;
          },
          normalize: (onDisk, rel) => {
            const unit = skillUnitAt(scope.units, rel);
            return unit
              ? normalizeCodexSkill(onDisk, unit.skill, unit.config, ctx.plugins, unit.hoist)
              : onDisk;
          },
          ...(scope.root ? { removalStatus: "removed-trimmed" as const } : {}),
        },
        // #823: prunes a skill's openai.yaml the moment it stops declaring
        // `disable-model-invocation` — independent of the accumulator above
        // (re-reads each skill's own frontmatter) so it never depends on
        // `placeSkill` having run first in THIS scan's call order.
        {
          dir: ".agents/skills",
          match: () => true,
          desired: new Set([
            ...plan.skills
              .filter((s: PlannedSkill) => isManualOnlySkill(s.assetPath))
              .map(({ id }) => `.agents/skills/${id}/agents/openai.yaml`),
            ...scope.hoisted
              .filter((h) => isManualOnlySkill(h.source.assetPath))
              .map(({ id }) => `.agents/skills/${id}/agents/openai.yaml`),
            ...localSkillManualOnlyIds.map((id) => `.agents/skills/${id}/agents/openai.yaml`),
          ]),
          shape: "skill-nested-file",
          nestedRelPath: "agents/openai.yaml",
        },
        {
          dir: ".codex/hooks",
          match: () => true,
          desired: new Set(
            [...installedScripts(ctx)].filter((rel) => rel.startsWith(".codex/hooks/")),
          ),
          shape: "file",
          expected: (rel) => {
            // A hook the config no longer plans (e.g. planTiers turned off) is
            // not in `plan.hooks`; its core asset still tells what pristine was.
            const id = rel.slice(".codex/hooks/".length, -".sh".length);
            const hook: PlannedHook = plan.hooks.find((h) => h.id === id) ?? {
              id,
              assetPath: join(ctx.coreAssets, `hooks/${id}.sh`),
              managedId: `${id}-base`,
            };
            return existsSync(hook.assetPath)
              ? freshRender(hookRequest(hook, ctx.config), ctx.config)
              : null;
          },
        },
        {
          dir: ".codex/scripts",
          match: (name) => name.endsWith(".sh"),
          desired: new Set(
            [...installedScripts(ctx)].filter((rel) => rel.startsWith(".codex/scripts/")),
          ),
          shape: "file",
          expected: (rel) => {
            for (const plugin of ctx.plugins) {
              const script = pluginScriptPlacements(plugin, "codex").find(
                (item) => item.destRelPath === rel,
              );
              if (!script) continue;
              return freshRender(
                {
                  assetPath: script.src,
                  destRelPath: script.destRelPath,
                  managedId: script.managedId,
                  meta: script.meta,
                  extraVars: pluginExtraVars(ctx.config),
                  commentStyle: "shell",
                },
                ctx.config,
              );
            }
            return null;
          },
        },
        // Spec 0043 R8: the three files a workspace under `root` no longer writes,
        // removed only when nothing the user wrote sits outside navori's block (a
        // `config.toml` with the user's own keys outside it stays, and is reported).
        ...(scope.root
          ? [
              {
                dir: ".codex",
                match: (name: string) => name === "config.toml" || name === "orchestrator.md",
                desired: new Set<string>(),
                shape: "file" as const,
                expected: (rel: string) =>
                  rel.endsWith("config.toml")
                    ? freshBody(configTomlRequest(""))
                    : freshRender(orchestratorRequest(ctx), ctx.config),
              },
              {
                dir: ".codex/rules",
                match: (name: string) => name === "navori.rules",
                desired: new Set<string>(),
                shape: "file" as const,
                expected: () => freshBody(rulesRequest("")),
              },
            ]
          : []),
      ];
    },
  };
}

/** The `.codex/orchestrator` playbook placement. */
function orchestratorRequest(ctx: AdapterCtx): PlacementRequest {
  return {
    assetPath: join(ctx.coreAssets, "agents/orchestrator.md"),
    transform: (content) => adaptOrchestratorPlaybookForCodex(content, ctx.config),
    destRelPath: ".codex/orchestrator.md",
    managedId: "orchestrator-codex-base",
    commentStyle: "html",
  };
}

function configTomlRequest(body: string): PlacementRequest {
  return {
    body,
    destRelPath: ".codex/config.toml",
    managedId: "codex-config-base",
    commentStyle: "shell",
    firstRenderSeed: { header: CODEX_CONFIG_HEADER },
  };
}

function rulesRequest(body: string): PlacementRequest {
  return {
    body,
    destRelPath: ".codex/rules/navori.rules",
    managedId: "codex-rules-base",
    commentStyle: "shell",
    firstRenderSeed: { header: CODEX_RULES_HEADER },
  };
}

/**
 * A body-type file as navori writes it the first time: the seed header and the
 * managed block. What a pristine comparison reads outside the block, so the block's
 * own body is whatever the caller passed.
 */
function freshBody(request: PlacementRequest): string {
  return injectManagedSection(
    request.firstRenderSeed?.header ?? "",
    request.managedId,
    request.body ?? "",
    request.meta ?? { source: "@navori/core", version: NAVORI_VERSION },
    request.commentStyle,
  ).output;
}

/**
 * The unit this render may judge for the skill dir at `rel`
 * (`.agents/skills/<id>/SKILL.md`), or undefined: the scan then keeps its
 * marker-only test for that path.
 */
function skillUnitAt(units: CodexScope["units"], rel: string): CodexUnit | undefined {
  const id = rel.match(/^\.agents\/skills\/([^/]+)\/SKILL\.md$/)?.[1];
  return id === undefined ? undefined : units.get(id);
}

/**
 * A minimal adapter for ONE skill the root writes on a workspace's behalf: the
 * skill under its final name, and its manual-only sidecar when it has one.
 */
function createHoistAdapter(h: HoistedSkill, config: NavoriConfig): EngineAdapter {
  const hoist = hoistTransform(h);
  return {
    id: "codex",
    label: "Codex",
    placeAgent: () => null,
    placeHook: () => null,
    placeSkill: (skill) => codexSkillRequest(skill, config, hoist),
    extraFiles: () =>
      isManualOnlySkill(h.source.assetPath)
        ? [
            {
              body: OPENAI_MANUAL_ONLY_POLICY,
              destRelPath: `.agents/skills/${h.id}/agents/openai.yaml`,
              managedId: `${h.id}-openai-policy`,
              commentStyle: "shell",
            },
          ]
        : [],
    orphanScans: () => [],
  };
}

/** The Codex placement of a core hook script (installed only if registered). */
function hookRequest(hook: PlannedHook, config: NavoriConfig): PlacementRequest {
  return {
    assetPath: hook.assetPath,
    destRelPath: `.codex/hooks/${hook.id}.sh`,
    managedId: hook.managedId,
    commentStyle: "shell",
    chmodExec: true,
    // Spec 0041 D6: `role-guard`'s per-role prefixes are compiled from the roster.
    ...(hook.id === "role-guard"
      ? { extraVars: { rolePolicy: buildRolePolicyShell(config) } }
      : {}),
    // The engram allowlist is compiled from the same grants Claude renders into `tools:`.
    ...(hook.id === "engram-write-guard"
      ? { extraVars: { engramPolicy: buildEngramPolicyShell() } }
      : {}),
  };
}

/**
 * The file as navori renders it fresh (no existing content), for the orphan
 * scan's `requirePristine` comparison; null when the request has no asset.
 */
function freshRender(request: PlacementRequest, config: NavoriConfig): string | null {
  if (request.assetPath === undefined) return null;
  return renderManagedFile({
    assetPath: request.assetPath,
    existingContent: null,
    managedId: request.managedId,
    meta: request.meta ?? { source: "@navori/core", version: NAVORI_VERSION },
    config,
    extraVars: request.extraVars,
    commentStyle: request.commentStyle,
    transform: request.transform,
    engine: "codex",
  }).content;
}

/** Keep one playbook source while removing Claude-only navigation from its Codex reference. */
function adaptOrchestratorPlaybookForCodex(content: string, config: NavoriConfig): string {
  return adaptHarnessTextForCodex(stripFrontmatter(content), config)
    .replaceAll("(../../AGENTS.md)", "(../AGENTS.md)")
    .replaceAll(
      "which the `SessionStart` hook delivers to the session, not to a subagent:",
      "which `AGENTS.md` supplies to the main thread:",
    )
    .replace(
      /^2\. The catalog of subagents and skills is in .*$/m,
      "2. The catalog of subagents and skills is in `AGENTS.md`, inside its managed `navori-agents` block; read the rendered headings there, not a Claude-only block id.",
    )
    .replaceAll(
      'In Claude Code you can reference `subagent_type: "Explore"` when it exists; in other engines, `scout` is the replacement.',
      "Use the `scout` role for this scope.",
    )
    .replaceAll(
      "The command lives in a cross-review sub-block that navori injects into THIS file, and only in that case. Scroll to the end: no such sub-block below means this repo renders Claude only and the option does not apply here. (Never re-derive this from a `grep` for the sub-block's id — you are reading the file that would match.)",
      "The optional cross-review guidance lives in `AGENTS.md`, not in this reference. Its absence here does not establish whether another engine is configured.",
    );
}

/**
 * One short clause per agent for the root roster: the "Use ..." trigger
 * sentence cut at its first comma (the full text stays in `.codex/agents/<id>.toml`).
 * Falls back to the first sentence when the description has no trigger.
 */
export function compactAgentDescription(description: string): string {
  const trigger = description.match(/(?:^|\. )(Use [^.]*)/)?.[1];
  const clause = trigger ?? description.split(/\. /)[0] ?? description;
  return (clause.split(",")[0] ?? clause).replace(/\.$/, "").trim();
}

function buildAgentsMdRequest(
  ctx: AdapterCtx,
  agents: ReadonlyArray<{ id: string; description: string }>,
): PlacementRequest {
  const baseBody = buildHarnessProse(ctx.config, ctx.repoRoot, ctx.isWorkspace, {
    includeOrchestration: true,
    includePluginBlocks: true,
    engine: "codex",
    omitSkillsIndex: true,
  });
  // Same localized "## Available agents" prose as the Claude engine (#289), but
  // without the orchestrator intro — AGENTS.md IS the catalog Codex reads, so it
  // appends the list bare, matching its prior output. The descriptions here come
  // from each agent's own frontmatter (collected in placeAgent), not from the
  // Claude "when to reach for it" map.
  const agentCatalog =
    buildAgentsIndexBlock(
      resolveLang(ctx.config.language),
      agents.map(({ id, description }) => ({
        id,
        description: compactAgentDescription(description),
      })),
      { withIntro: false },
    ) ?? "";
  let body = adaptHarnessTextForCodex(`${baseBody}\n${agentCatalog}`, ctx.config);
  // The main thread embodies the orchestrator in Codex (no `.codex/agents/orchestrator.toml`),
  // so a plugin skill injecting into a target agent (e.g. engram's
  // orchestrator extension) has no agent .toml to land in — buildAgentToml only runs for
  // rendered agents. Append it here as a managed sub-block of AGENTS.md, the orchestrator's
  // durable guide, mirroring buildAgentToml's per-agent injection but into prose.
  // Same managed-marker treatment as the skill sub-block loop (`@navori/plugin-<id>`
  // source) so re-render is idempotent and disabling the plugin drops it: AGENTS.md
  // is fully regenerated each render, and a disabled plugin is absent from
  // `ctx.plugins`, so the sub-block simply isn't re-emitted (#277).
  for (const plugin of ctx.plugins) {
    for (const skill of plugin.skillAssets) {
      if (skill.injectInto !== ".claude/agents/orchestrator.md") continue;
      const subBlock = adaptHarnessTextForCodex(
        interpolate(stripFrontmatter(readFileSync(skill.absPath, "utf-8")), ctx.config, {
          extraVars: pluginExtraVars(ctx.config),
        }),
        ctx.config,
      );
      body = injectManagedSection(
        body,
        skill.id,
        subBlock,
        { source: `@navori/plugin-${plugin.manifest.id}`, version: NAVORI_VERSION },
        "html",
      ).output;
    }
  }
  // Share the universal adapter's managed id so switching from `agents-md` to
  // full Codex upgrades one block in place instead of duplicating guidance.
  return {
    body,
    destRelPath: "AGENTS.md",
    managedId: "navori-agents",
    commentStyle: "html",
    firstRenderSeed: {
      header: "# AGENTS.md\n",
      trailer: "\n<!-- navori:user-section -->\n<!-- user: additional rules for Codex -->\n",
    },
  };
}

/**
 * Builds one `.codex/agents/<id>.toml`. The agent asset (and any plugin
 * extension injected into it) is run through `conditionOrchestration` BEFORE
 * interpolation: unlike `renderManagedFile`, which resolves `navori:if` /
 * `navori:if-not` for every Markdown asset, this function reads the asset
 * itself, so without the call the TOML carried both branches of each
 * condition (e.g. the report and the JSON-evidence instructions) plus the raw
 * markers (spec 0041 R28). An unbalanced marker throws, as on every engine.
 */
function buildAgentToml(
  source: PlannedAgent,
  config: NavoriConfig,
  plugins: readonly LoadedPlugin[],
  warningsSink: string[],
  cwd: string,
): { body: string; description: string } {
  const raw = readFileSync(source.assetPath, "utf-8");
  const parsed = parseAsset(raw, "html");
  const description = adaptHarnessTextForCodex(
    interpolate(parsed.frontmatter.description ?? source.id, config),
    config,
  );
  let instructions = adaptHarnessTextForCodex(
    interpolate(conditionOrchestration(parsed.managedBody, config, "codex"), config, {
      extraVars: pluginExtraVars(config),
    }),
    config,
  );

  for (const plugin of plugins) {
    for (const skill of plugin.skillAssets) {
      if (skill.injectInto !== `.claude/agents/${source.id}.md`) continue;
      const extension = parseAsset(readFileSync(skill.absPath, "utf-8"), "html");
      instructions += `\n\n${adaptHarnessTextForCodex(
        interpolate(conditionOrchestration(extension.managedBody, config, "codex"), config, {
          extraVars: pluginExtraVars(config),
        }),
        config,
      )}`;
    }
  }

  const modelTier = source.modelKey ? config.models?.[source.modelKey] : undefined;
  const effort = source.modelKey ? config.effort?.[source.modelKey] : undefined;
  const sandbox = source.sandbox ?? "workspace-write";
  const lines = [
    `name = ${JSON.stringify(source.id)}`,
    `description = ${JSON.stringify(description)}`,
    `developer_instructions = ${JSON.stringify(instructions.trim())}`,
  ];
  if (sandbox === "read-only") lines.push('sandbox_mode = "read-only"');
  if (modelTier) {
    const choice = resolveCodexModel(
      config,
      modelTier,
      undefined,
      readRenderedCodexModel(cwd, source.id),
    );
    if (choice.source === "fallback") {
      const warning = tc(resolveLang(config.language)).engine.codexModelFamilyFallback(
        choice.family ?? choice.model,
        choice.model,
      );
      if (!warningsSink.includes(warning)) warningsSink.push(warning);
    }
    lines.push(`model = ${JSON.stringify(choice.model)}`);
  }
  if (effort) lines.push(`model_reasoning_effort = ${JSON.stringify(effort)}`);

  return { body: lines.join("\n") + "\n", description };
}

function loadActivePreset(
  config: NavoriConfig,
  repoRoot: string,
  warnings: string[],
): ReturnType<typeof loadPreset> {
  if (!config.preset || config.preset === "custom") return null;
  try {
    const preset = loadPreset(config.preset, repoRoot);
    if (!preset)
      warnings.push(tc(resolveLang(config.language)).engine.presetNotFoundCodex(config.preset));
    warnings.push(...droppedLibrariesWarnings(preset));
    return preset;
  } catch (error) {
    if (error instanceof PresetError) {
      warnings.push(
        tc(resolveLang(config.language)).engine.presetInvalid(config.preset, error.message),
      );
      return null;
    }
    throw error;
  }
}
