import { execFileSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { detectNativeHooks, listWorktreePaths } from "../native-hooks.ts";

const git = (cwd: string, ...args: string[]): void => {
  execFileSync("git", ["-C", cwd, "-c", "user.name=t", "-c", "user.email=t@t", ...args], {
    stdio: "ignore",
  });
};

function repo(): string {
  const cwd = realpathSync(mkdtempSync(join(tmpdir(), "navori-native-hooks-")));
  git(cwd, "init", "-q");
  return cwd;
}

function write(cwd: string, rel: string, body: string, mode = 0o755): string {
  const path = join(cwd, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  chmodSync(path, mode);
  return path;
}

const SHEBANG = "#!/bin/sh\n";
const HUSKY_STUB = `#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n`;
const PRE_COMMIT_HEADER =
  "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexec true\n";
const LEFTHOOK_HOOK = "#!/bin/sh\ncall_lefthook run pre-commit\n# lefthook\n";

const commit = (cwd: string) => detectNativeHooks(cwd).hooks["pre-commit"];

describe("detectNativeHooks", () => {
  // Covers: R5, R6
  describe("fixtures por gestor y worktree", () => {
    it("reports unknown (absent) outside a git work tree", () => {
      const cwd = realpathSync(mkdtempSync(join(tmpdir(), "navori-native-hooks-nogit-")));
      const d = detectNativeHooks(cwd);
      expect(d.top).toBeNull();
      expect(d.hooks["pre-commit"]).toMatchObject({ active: false, absence: "unknown-git" });
      expect(d.hooks["pre-push"]).toMatchObject({ active: false, absence: "unknown-git" });
    });

    it("counts a missing, empty, non-executable or comment-only plain hook as absent", () => {
      const cwd = repo();
      expect(commit(cwd)).toMatchObject({ active: false, absence: "missing" });
      write(cwd, ".git/hooks/pre-commit", "");
      expect(commit(cwd).absence).toBe("empty");
      write(cwd, ".git/hooks/pre-commit", `${SHEBANG}echo hi\n`, 0o644);
      expect(commit(cwd).absence).toBe("not-executable");
      write(cwd, ".git/hooks/pre-commit", `${SHEBANG}# nothing here\n\n`);
      expect(commit(cwd)).toMatchObject({ active: false, absence: "no-user-content" });
    });

    it("recognises a plain executable hook with user content, per event", () => {
      const cwd = repo();
      const path = write(cwd, ".git/hooks/pre-commit", `${SHEBANG}bun run check:fast\n`);
      expect(commit(cwd)).toMatchObject({ active: true, manager: "plain", path });
      expect(detectNativeHooks(cwd).hooks["pre-push"].active).toBe(false);
    });

    it("husky: the generated stub alone is absent; the user's .husky/<hook> makes it active", () => {
      const cwd = repo();
      git(cwd, "config", "core.hooksPath", ".husky/_");
      write(cwd, ".husky/_/h", "#!/usr/bin/env sh\nexit 0\n");
      write(cwd, ".husky/_/pre-commit", HUSKY_STUB);
      expect(commit(cwd)).toMatchObject({ active: false, manager: "husky", absence: "husky-stub" });
      write(cwd, ".husky/pre-commit", "bun run check:fast\n", 0o644);
      expect(commit(cwd)).toMatchObject({ active: true, manager: "husky" });
      // An empty user file is a stub too.
      write(cwd, ".husky/pre-commit", "", 0o644);
      expect(commit(cwd).absence).toBe("husky-stub");
    });

    it("lefthook: needs a config that declares the event at top level", () => {
      const cwd = repo();
      write(cwd, ".git/hooks/pre-commit", LEFTHOOK_HOOK);
      expect(commit(cwd)).toMatchObject({
        active: false,
        manager: "lefthook",
        absence: "no-lefthook-config",
      });
      write(cwd, "lefthook.yml", "pre-push:\n  commands: {}\n", 0o644);
      expect(commit(cwd).active).toBe(false);
      write(cwd, "lefthook.yml", "pre-commit:\n  commands:\n    x:\n      run: true\n", 0o644);
      expect(commit(cwd)).toMatchObject({ active: true, manager: "lefthook" });
    });

    it("pre-commit framework: needs .pre-commit-config.yaml, and a pre-push mention for pre-push", () => {
      const cwd = repo();
      write(cwd, ".git/hooks/pre-commit", PRE_COMMIT_HEADER);
      write(cwd, ".git/hooks/pre-push", PRE_COMMIT_HEADER);
      expect(commit(cwd)).toMatchObject({ active: false, absence: "no-pre-commit-config" });
      write(cwd, ".pre-commit-config.yaml", "repos: []\n", 0o644);
      expect(commit(cwd)).toMatchObject({ active: true, manager: "pre-commit" });
      expect(detectNativeHooks(cwd).hooks["pre-push"]).toMatchObject({
        active: false,
        absence: "pre-commit-stage-missing",
      });
      write(cwd, ".pre-commit-config.yaml", "default_install_hook_types: [pre-push]\n", 0o644);
      expect(detectNativeHooks(cwd).hooks["pre-push"].active).toBe(true);
    });

    it("resolves a relative core.hooksPath against the toplevel", () => {
      const cwd = repo();
      git(cwd, "config", "core.hooksPath", "scripts/git-hooks");
      const path = write(cwd, "scripts/git-hooks/pre-commit", `${SHEBANG}bun run check:fast\n`);
      expect(detectNativeHooks(cwd).hooksDir).toBe(join(cwd, "scripts/git-hooks"));
      expect(commit(cwd)).toMatchObject({ active: true, path });
      // From a subdirectory the answer is the same clone's.
      mkdirSync(join(cwd, "sub"));
      expect(detectNativeHooks(join(cwd, "sub")).hooks["pre-commit"].active).toBe(true);
    });

    it("evaluates each worktree against its own toplevel", () => {
      const cwd = repo();
      write(cwd, ".githooks/pre-commit", `${SHEBANG}bun run check:fast\n`);
      git(cwd, "add", "-A");
      git(cwd, "commit", "-q", "-m", "init");
      // Set after the commit so the fixture never runs its own hook.
      git(cwd, "config", "core.hooksPath", ".githooks");
      const wt = join(cwd, ".claude", "worktrees", "w1");
      git(cwd, "worktree", "add", "-q", "-b", "w1", wt);
      const real = realpathSync(wt);
      expect(listWorktreePaths(cwd)).toContain(real);
      expect(detectNativeHooks(real).hooks["pre-commit"]).toMatchObject({
        active: true,
        path: join(real, ".githooks/pre-commit"),
      });
      // A hook that is only in the main checkout (untracked) is absent in the worktree.
      write(cwd, ".githooks/pre-push", `${SHEBANG}true\n`);
      expect(detectNativeHooks(cwd).hooks["pre-push"].active).toBe(true);
      expect(detectNativeHooks(real).hooks["pre-push"]).toMatchObject({
        active: false,
        absence: "missing",
      });
    });
  });
});
