#!/usr/bin/env bash
#
# PreToolUse(mcp__engram__*) guard, CODEX ONLY. Claude gives a role its engram
# tools through the agent's `tools:` allowlist; a Codex agent has no such field
# and the upstream engram plugin tells every thread to save, so this hook is the
# mechanical equivalent. It never renders into `.claude/` (`HOOK_ENGINES`).
#
# It is a SEPARATE hook from `role-guard` on purpose: Codex keys trust by
# registration position and hash, so widening role-guard's matcher would switch
# role-guard off until re-approved. This one is new and trails the table.
#
# Keyed on the top-level `agent_type`, which the host adds only inside a
# subagent. Absent or empty: the main thread, never blocked. Inside a subagent
# the tool is compared by its bare suffix (`${tool##*__}`) against the role's
# allowlist; anything not listed is denied, so a write tool engram adds later is
# denied without touching this file.
#
# FAIL-OPEN WITHOUT jq AND node (same accepted trade-off as role-guard): the sed
# fallback of `payload_field` cannot tell the top-level `agent_type` from a
# nested one. With neither tool installed the hook lets the call through.
#
# The per-role allowlist is NOT written here: it is compiled by
# `buildEngramPolicyShell` at render time from the grants Claude renders into
# `tools:` (engram plugin `skills[].mcpTools` + core agents' `tools:`).
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# navori:include extract-cmd
# navori:include hook-input

navori_audit_name="engram-write-guard"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. Fork-free presence test: the main thread carries no top-level
# `agent_type`, so the substring test proves absence without a process.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

if ! command -v jq >/dev/null 2>&1 && ! command -v node >/dev/null 2>&1; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin jq ni node: payload ilegible"
  exit 0
fi

navori_role=$(nv_event_agent_type)
if [ -z "$navori_role" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="agent_type vacío (hilo principal)"
  exit 0
fi

block() {
  echo "[navori] BLOCKED by engram-write-guard: $1" >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

navori_tool=$(nv_tool)
case "$navori_tool" in
  mcp__engram__* | mcp__plugin_engram_engram__*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac
navori_name=${navori_tool##*__}

# Bare engram tool names the role may call, one per line. The case is generated
# from the grants Claude applies; no role or tool name is spelled in this asset.
nv_engram_allowed() {
{{engramPolicy}}
}

while IFS= read -r navori_allowed; do
  if [ "$navori_allowed" = "*" ] || [ "$navori_allowed" = "$navori_name" ]; then
    navori_audit_verdict="allow"
    navori_audit_reason="$navori_name concedida a $navori_role"
    exit 0
  fi
done <<EOF
$(nv_engram_allowed "$navori_role")
EOF

block "$navori_name is not granted to the $navori_role role. This is a fixed harness policy, not a transient error: do NOT retry it and do NOT use another memory tool. Report what you found in your normal output; the main thread decides whether to save it."
