#!/usr/bin/env bash
#
# PreToolUse(Bash) gate on `gh pr create` (#705).
#
# The `commit-pr-pilot` is the single owner of commit+PR by doctrine, and it is
# invoked on 15% of the PRs that get opened — 37 of 232 across 58 audited
# sessions. The split is what matters: `alertaciudadana-backend` reaches 48%,
# so the pilot does get invoked when a cycle runs to its end, while THIS repo —
# the one that publishes it — sits at 0 of 101.
#
# The measured reason is not that the pilot gets skipped: its antechamber is
# never entered. The doctrine names it "after the reviewer approves", the work
# here rarely passes through a reviewer, and the PR then opens as the natural
# continuation of what was already being done by hand. Nothing intercepts
# `gh pr create`, and this harness has measured the same dividing line
# everywhere else: every layer that BLOCKS works (guard-destructive 14/14,
# quality-gate 7/7), every layer that SUGGESTS does not.
#
# So this blocks, with the escape the doctrine already defines. A hook cannot
# invoke the pilot; what it can do is refuse a PR that neither came from a
# subagent nor says why it did not, and name both ways out.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add repo-specific rules in the user section at the bottom.
set -euo pipefail

# navori:include extract-cmd

# The cheap gate comes FIRST, on the raw payload, and spawns nothing.
#
# This hook runs on every Bash call of every session, next to a guard that
# already pays a payload parse there. `payload_field` may fork jq or node, so
# a `case` over the string navori already has in memory is what keeps the cost
# of this hook at zero for the 99.9% of commands that are not opening a PR.
case "${payload:-}" in
  *"gh pr create"*) ;;
  *) exit 0 ;;
esac

cmd=$(extract_cmd)

navori_audit_name="guard-pr-pilot"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# Fail-open no-ops, overwritten by the include. Same reason as in
# `guard-destructive.sh`: an undefined function under `set -e` is exit 127, and
# a recorder may never kill the thing it observes.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# The raw payload can carry the phrase in another field (a prompt that quotes
# it, a previous result). The COMMAND is what actually runs.
case "$cmd" in
  *"gh pr create"*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="the phrase was not in the command"
    exit 0
    ;;
esac

# A subagent opened it. `agent_id` is empty in the main thread and set inside a
# sidechain, which is the only signal the payload carries about WHO is running.
#
# It cannot say WHICH subagent: the payload names no subagent type, so a PR
# opened from any sidechain passes here. That is deliberate imprecision, not an
# oversight — the failure this gate exists for is the main thread opening PRs
# by hand (101 of them in this repo), and a rule that guessed the agent's type
# from an id would block the pilot itself the day the host changes that field.
if [ -n "$(payload_field agent_id)" ]; then
  navori_audit_reason="opened from a subagent"
  exit 0
fi

# The escape the orchestration block ALREADY requires in prose: when delegation
# is impossible (the operator forbade subagents, the Agent tool is unavailable),
# the PR body has to state it. This turns that sentence into something a machine
# can check and a human can count — free prose cannot be verified, and an
# exception nobody can count is indistinguishable from a violation.
case "$cmd" in
  *"navori:no-pilot"*)
    navori_audit_reason="declared navori:no-pilot"
    exit 0
    ;;
esac

echo "[navori] BLOCKED by guard-pr-pilot: this PR did not go through commit-pr-pilot" >&2
echo "[navori] and its body does not say why." >&2
echo "[navori] Two ways forward:" >&2
echo "[navori]   1. Agent(commit-pr-pilot) — the default route: it runs the pre-flight," >&2
echo "[navori]      writes the Conventional commits and opens the PR." >&2
echo "[navori]   2. If delegation is genuinely impossible (the operator forbade" >&2
echo "[navori]      subagents, the Agent tool is unavailable), add one line to the PR" >&2
echo "[navori]      body: 'navori:no-pilot — <reason>'. The exception is legitimate;" >&2
echo "[navori]      leaving no trace of it is what is not." >&2
navori_audit_verdict="block"
navori_audit_reason="gh pr create with neither pilot nor declaration"
exit 2
