#!/usr/bin/env bash
#
# Defensive PreToolUse(Bash) guard.
# Reads the full command (compound commands included) from Claude Code's tool
# input and HARD-BLOCKS (exit 2) the destructive patterns that static deny
# rules in settings.json can't reliably catch: variable-indirected `rm -rf`,
# force-push to the base branch, hook-skipping, fork bombs, and writes to block
# devices. Exit 2 in a PreToolUse hook is evaluated BEFORE permission rules, so
# this is the strongest line of defense — it overrides even an `allow` match.
#
# KNOWN, ACCEPTED LIMITATION: matching is regex-based over the command string.
# Multi-line continuations, git global options (`git -C … commit`), and simple
# wrappers (`command`/`\git`/parens) ARE normalized before matching now, and a
# quoted skip-flag (`git commit "--no-verify"`) is still caught. Still unhandled:
# `sh -c`, `eval`, base64/printf obfuscation, and escaped-quote edge cases inside
# quoted spans. This guard is a SEATBELT against accidental
# destructive commands, NOT a sandbox against a deliberate adversary.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific guards in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

# Extract .tool_input.command from the PreToolUse payload WITHOUT hard-depending
# on jq (NOT preinstalled on macOS — a missing jq used to make this guard wave
# every command through). Try jq, then node (Claude Code's own runtime), and if
# no JSON parser is on PATH fall back to a best-effort sed unwrap so the guard
# still inspects the command instead of failing open.
payload=$(cat)
extract_cmd() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r '.tool_input.command // empty' 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";process.stdin.on("data",c=>s+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(s)?.tool_input?.command??""))}catch{}})' 2>/dev/null && return 0
  fi
  # No JSON parser on PATH: pull the "command" string out with sed. Best-effort
  # (won't handle a literal embedded quote), but far better than failing open.
  printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p'
}
cmd=$(extract_cmd)
[ -z "$cmd" ] && exit 0

base="{{branchBase}}"

block() {
  echo "[navori] BLOQUEADO por guard-destructive: $1" >&2
  echo "[navori] comando: $cmd" >&2
  echo "[navori] si es intencional, corre el comando tú mismo fuera del agente." >&2
  exit 2
}

# Normalized copies used ONLY by the hook-skip (1) and force-push (2) rules
# below. `$cmd` stays intact for the messages and the other rules. The transforms
# only add boundaries / drop noise, so they always push toward MORE blocking:
#   FIX B — join `\<newline>` continuations into a space and flatten any other
#           newline to `;` (a boundary the rules already handle) so a multi-line
#           `git commit \<NL> --no-verify` is matched as one logical command.
#   FIX C — neutralize wrappers into boundaries: a leading `command ` word, a
#           leading backslash (`\git`), and `(` runs, so `command git …`,
#           `\git …` and `(git …)` read as a plain `git …`.
# `scan` keeps quoted spans intact, so a quoted skip-flag (`git commit
# "--no-verify"`) is still caught — stripping the quotes there was a real bypass.
# `scan_flags` additionally drops quoted spans and is used ONLY by the
# combined-short-flag check, so a hyphen-word inside a commit message
# (`-m "add -notify option"`) can't trip it.
scan="$cmd"
scan="${scan//\\$'\n'/ }"     # FIX B: join line continuations
scan="${scan//$'\n'/;}"       # FIX B: flatten remaining newlines to a boundary
scan=$(printf '%s' "$scan" | sed -E \
  -e "s/(^|[;&|]|[[:space:]])command[[:space:]]+/\1/g" \
  -e "s/\\\\([A-Za-z])/ \1/g" \
  -e "s/\(/ /g")
scan_flags=$(printf '%s' "$scan" | sed -E -e "s/'[^']*'//g" -e "s/\"[^\"]*\"//g")

# Git commit/push detector shared by rule 1. The leading boundary accepts ; & |
# so `true;git commit …` (no space after the separator) is caught; the
# `git(… -opt …)*` middle allows git global options between `git` and the
# subcommand (`git -c k=v commit …`).
git_cp='(^|[[:space:]]|[;&|])git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+(commit|push)'

# 1. Skipping quality gates / hooks — defeats the whole point of the harness.
#    Two checks: the literal `--no-verify` over `scan` (quotes kept, so a quoted
#    flag is still caught), and `-[a-zA-Z]*n[a-zA-Z]*` over `scan_flags` (quotes
#    dropped) to catch `-n` folded into a combined short-flag token
#    (`git commit -qn`/`-nq`) without a hyphen-word in a message tripping it.
if printf '%s' "$scan"       | grep -qE "${git_cp}([[:space:]]|.)*--no-verify" \
  || printf '%s' "$scan_flags" | grep -qE "${git_cp}([[:space:]]|.)*[[:space:]]-[a-zA-Z]*n[a-zA-Z]*([[:space:]]|\$)"; then
  block "git commit/push con --no-verify (saltarse los hooks/gates)"
fi

# 2. Force-push to the base branch. force-with-lease is allowed (safe rebase
#    flow on feature branches); bare --force/-f against the base branch is not.
#    The leading boundary accepts ; & | so `true;git push --force main` (no
#    space after the separator) is caught too. The `git(… -opt …)*` middle
#    allows git global options before `push` (`git -C /repo push --force …`).
if printf '%s' "$scan" | grep -qE '(^|[[:space:]]|[;&|])git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+push' \
  && printf '%s' "$scan" | grep -qE '(--force([[:space:]]|$)|[[:space:]]-f([[:space:]]|$)|[[:space:]]\+)' \
  && ! printf '%s' "$scan" | grep -qE 'force-with-lease' \
  && printf '%s' "$scan" | grep -qE "(^|[[:space:]+/])${base}([[:space:]]|\$)"; then
  block "force-push a la rama base '${base}'"
fi

# 3. rm -rf with variable indirection or absolute/home roots that static deny
#    globs miss (e.g. PATH=/; rm -rf $PATH).
if printf '%s' "$cmd" | grep -qE '(^|[[:space:]])rm[[:space:]]+(-[a-zA-Z]*r[a-zA-Z]*[[:space:]]+|-[a-zA-Z]*f[a-zA-Z]*[[:space:]]+)*-?[a-zA-Z]*[rf][a-zA-Z]*[[:space:]]+("?\$|/[[:space:]]*$|~[[:space:]]*$)'; then
  block "rm recursivo sobre variable / raíz / home"
fi

# 4. Fork bomb.
if printf '%s' "$cmd" | grep -qE ':\(\)[[:space:]]*\{[[:space:]]*:\|:'; then
  block "fork bomb"
fi

# 5. Writing to a raw block device (wipes a disk/partition).
if printf '%s' "$cmd" | grep -qE '(of=/dev/(sd|nvme|disk|hd)|>[[:space:]]*/dev/(sd|nvme|disk|hd))'; then
  block "escritura directa a un dispositivo de bloque"
fi

# navori:user-section
# user: agrega guards adicionales acá. `$cmd` ya tiene el comando completo
# (incluye comandos compuestos) y `block "<motivo>"` aborta con exit 2.
# Ejemplo:
#
#   if printf '%s' "$cmd" | grep -qE 'drop[[:space:]]+(table|database)'; then
#     block "DROP TABLE/DATABASE"
#   fi

exit 0
