#!/usr/bin/env bash
#
# Defensive PreToolUse(Bash) guard.
# Reads the full command (compound commands included) from Claude Code's tool
# input and HARD-BLOCKS (exit 2) the destructive patterns that static deny
# rules in settings.json can't reliably catch: variable-indirected `rm -rf`,
# force-push to the base branch, hook-skipping, fork bombs, and writes to block
# devices. Exit 2 in a PreToolUse hook is evaluated BEFORE permission rules, so
# this is the strongest line of defense — it overrides even an `allow` match.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific guards in the user section at the
# bottom — `$cmd` is already parsed and in scope there.
set -euo pipefail

cmd=$(jq -r '.tool_input.command // empty' 2>/dev/null || true)
[ -z "$cmd" ] && exit 0

base="{{branchBase}}"

block() {
  echo "[navori] BLOQUEADO por guard-destructive: $1" >&2
  echo "[navori] comando: $cmd" >&2
  echo "[navori] si es intencional, corré el comando vos mismo fuera del agente." >&2
  exit 2
}

# 1. Skipping quality gates / hooks — defeats the whole point of the harness.
if printf '%s' "$cmd" | grep -qE '(^|[[:space:]])git[[:space:]]+(commit|push)([[:space:]]|.)*(--no-verify|[[:space:]]-n([[:space:]]|$))'; then
  block "git commit/push con --no-verify (saltarse los hooks/gates)"
fi

# 2. Force-push to the base branch. force-with-lease is allowed (safe rebase
#    flow on feature branches); bare --force/-f against the base branch is not.
if printf '%s' "$cmd" | grep -qE '(^|[[:space:]])git[[:space:]]+push' \
  && printf '%s' "$cmd" | grep -qE '(--force([[:space:]]|$)|[[:space:]]-f([[:space:]]|$)|[[:space:]]\+)' \
  && ! printf '%s' "$cmd" | grep -qE 'force-with-lease' \
  && printf '%s' "$cmd" | grep -qE "(^|[[:space:]+/])${base}([[:space:]]|\$)"; then
  block "force-push a la rama base '${base}'"
fi

# 3. rm -rf with variable indirection or absolute/home roots that static deny
#    globs miss (e.g. PATH=/; rm -rf $PATH).
if printf '%s' "$cmd" | grep -qE '(^|[[:space:]])rm[[:space:]]+(-[a-zA-Z]*r[a-zA-Z]*[[:space:]]+|-[a-zA-Z]*f[a-zA-Z]*[[:space:]]+)*-?[a-zA-Z]*[rf][a-zA-Z]*[[:space:]]+("?\$|/[[:space:]]*$|~[[:space:]]*$)'; then
  block "rm recursivo sobre variable / raíz / home"
fi

# 4. Fork bomb.
if printf '%s' "$cmd" | grep -qE ':\(\)[[:space:]]*\{[[:space:]]*:\|:'; then
  block "fork bomb"
fi

# 5. Writing to a raw block device (wipes a disk/partition).
if printf '%s' "$cmd" | grep -qE '(of=/dev/(sd|nvme|disk|hd)|>[[:space:]]*/dev/(sd|nvme|disk|hd))'; then
  block "escritura directa a un dispositivo de bloque"
fi

# navori:user-section
# user: agregá guards adicionales acá. `$cmd` ya tiene el comando completo
# (incluye comandos compuestos) y `block "<motivo>"` aborta con exit 2.
# Ejemplo:
#
#   if printf '%s' "$cmd" | grep -qE 'drop[[:space:]]+(table|database)'; then
#     block "DROP TABLE/DATABASE"
#   fi

exit 0
