#!/usr/bin/env bash
#
# PreToolUse(Bash|Edit|Write|NotebookEdit) guard — the mechanical half of R1
# (spec 0030, #985): the `implementer` does not write Markdown. Blocks a
# `Write`/`Edit`/`NotebookEdit` whose target ends in `.md`/`.mdx`, and the Bash
# write-verb forms of R4 (redirection, `tee`, `sed -i`/`perl -i`, `cp`/`mv` onto
# a `.md`/`.mdx` path) — all with `exit 2`, the same channel `guard-destructive`
# uses, evaluated BEFORE permission rules.
#
# WHY A HOOK AND NOT JUST THE CONTRACT (design.md): `implementer.md`'s own
# prose already says not to touch `.md` (R1). #985's own failure mode is a
# contract the agent follows by inertia — 520 `.md` writes since 2026-09-01,
# with the prohibition already implied by the agent's job. Prose alone did not
# hold; this is the mechanical backstop.
#
# WHO IT APPLIES TO. `agent_type` — read straight from the payload, not
# `tool_input` — is the field Claude Code adds "present only when the hook
# fires inside a subagent call" (https://code.claude.com/docs/en/hooks.md,
# confirmed against this repo's own `model-advisor.sh`, which reads the same
# field the same way). Absent → the main thread, never blocked. Any value other
# than `implementer` (`scribe`, `reviewer`, `auditor`, `scout`, `publisher`) →
# never blocked either: this rule is scoped to the one role R1 names.
#
# KNOWN, ACCEPTED LIMITATION — best-effort against inertia, NOT a sandbox
# against a deliberate adversary (same posture as `guard-destructive.sh`'s own
# header). The Bash rules read the command as TEXT, unsegmented: a `.md`
# mention inside a commit message or a heredoc body can false-positive.
# Interpreter checks require a Markdown literal and a recognizable write API;
# unrelated reads/writes in the same command can still false-positive. Dynamic
# paths, external scripts, and unenumerated runners (`dd`, `rsync`, `git apply`)
# remain outside this text-based guard (R4: "not a sandbox against evasion").
# A closed Node/JSON exception below classifies submitted source text only: it
# assumes a trusted Node runtime and filesystem. A .json symlink/hardlink is
# not proof of the physical target. Unsupported syntax retains the old block.
# The closed Python Path exception likewise parses data, never runs submitted
# code, and is not a general sandbox or a symlink/physical-target guarantee.
# The contract in `implementer.md` is the rule; this catches the slip, not the
# workaround.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# Command/field extraction (payload → $cmd, $payload). Shared body, single
# source of truth.
# navori:include extract-cmd
# Spec 0035 D2: nv_tool()/nv_edited_paths() normalize Codex's `apply_patch`
# (one call can touch several files at once, unlike Claude's single-path
# Write/Edit) to the same shape this script already handles.
# navori:include hook-input

navori_audit_name="implementer-no-markdown"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127, and a
# recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. This fires on EVERY Bash/Edit/Write/NotebookEdit call from
# EVERY agent (and the main thread); only the implementer is ever in scope.
# Fork-free PRESENCE test before anything that spawns a process — same trade
# `model-advisor.sh` makes for the identical field: the main thread carries no
# `agent_type` key at all, so a plain substring test already proves absence
# without a fork. A VALUE read (below) still follows for the subagent case,
# because presence alone only proves "some subagent", not which one.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

navori_agent_type=$(payload_field agent_type)
if [ "$navori_agent_type" != "implementer" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="no es el implementer"
  exit 0
fi

navori_tool=$(nv_tool)

block() {
  echo "[navori] BLOCKED by implementer-no-markdown: $1" >&2
  # Both progress paths, never one alone: `placeHook` ships this byte-identical
  # to Claude and Codex (#389), so a message hardcoding `.claude/progress`
  # would misdirect a Codex implementer to a path that is not its own.
  echo "[navori] the implementer does not write Markdown (spec 0030, R1). Put the change in \"markdownRequests\", inside .claude/progress/impl_<feature>.json (or .codex/progress/impl_<feature>.json under Codex) — the scribe applies it in this worktree." >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Case-insensitive `.md`/`.mdx`: macOS ships a case-insensitive filesystem, so
# `NOTES.MD` writes the same file `notes.md` does.
is_md_path() {
  case "$1" in
    *.[mM][dD] | *.[mM][dD][xX]) return 0 ;;
    *) return 1 ;;
  esac
}

case "$navori_tool" in
  Write | Edit)
    # Codex's `apply_patch` can touch several files in ONE call (Add/Update/
    # Delete/Move headers in the same patch); `nv_edited_paths` yields one per
    # line, so every one of them is checked, not just the first.
    while IFS= read -r navori_path; do
      [ -n "$navori_path" ] || continue
      if is_md_path "$navori_path"; then
        block "$navori_tool sobre '$navori_path'"
      fi
    done <<EOF
$(nv_edited_paths)
EOF
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  NotebookEdit)
    navori_path=$(payload_field tool_input.notebook_path)
    if is_md_path "$navori_path"; then
      block "NotebookEdit sobre '$navori_path'"
    fi
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  Bash) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac

cmd=$(extract_cmd)
if [ -z "$cmd" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin comando que inspeccionar"
  exit 0
fi

# R4's write-verb forms, over the raw command text (best-effort, see header).
# Case-insensitive throughout, same reasoning as `is_md_path` above.
MD_EXT='\.(md|mdx)'

# 1. Output redirection: `>`, `>>`, `>|` onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE ">>?\\|?[[:space:]]*[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "redirección hacia un archivo .md/.mdx"
fi

# 2. `tee` (append or overwrite) onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])tee([[:space:]]+-[a-zA-Z]+)*[[:space:]]+[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'tee' hacia un archivo .md/.mdx"
fi

# 3. In-place rewrite: `sed -i`/`sed --in-place`, `perl -i`.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])sed[[:space:]]+(-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*|--in-place)([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'sed -i' sobre un archivo .md/.mdx"
fi
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])perl[[:space:]]+-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'perl -i' sobre un archivo .md/.mdx"
fi

# 4. `cp`/`mv` onto a `.md`/`.mdx` target — the atomic-write idiom (write a
# temp file, then move it onto the managed path). Anchored on the LAST operand
# of the invocation (greedy `.*` before the final `[[:space:]]`), since that is
# where `cp`/`mv` read their destination.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])(cp|mv)[[:space:]]+.*[[:space:]][^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'cp'/'mv' hacia un archivo .md/.mdx"
fi

# 5. Interpreter writes (#1129). Inspect text only: never execute supplied
# code. Flatten heredocs so an open() mode can appear on a separate line.
# Require all three clues: interpreter invocation, literal Markdown path, and
# write API/mode. Read APIs and stdout writes alone must not trigger this rule.
interpreter_cmd=$(printf '%s' "$cmd" | tr '\n' ' ')
INTERPRETER='(^|[;&|[:space:]])([^[:space:];&|]*/)?(python([0-9]+(\.[0-9]+)*)?|node|ruby|perl|deno|bun)([[:space:]]|$)'
MD_LITERAL="${MD_EXT}(['\"]|[[:space:]]|$)"
WRITE_API='(^|[^[:alnum:]_])(writeFile(Sync)?|appendFile(Sync)?|writeTextFile(Sync)?|write_text|write_bytes)[[:space:]]*\('
FILE_WRITE='(File|Bun)[[:space:]]*\.[[:space:]]*(write|binwrite)[[:space:]]*\('
OPEN_WRITE="(^|[^[:alnum:]_])open[[:space:]]*\\([^)]*,[[:space:]]*(mode[[:space:]]*=[[:space:]]*)?['\"]([wax][bt+]*|r[bt]*\\+|[+]?>>?)['\"]"
if printf '%s' "$interpreter_cmd" | grep -qE "$INTERPRETER" &&
  printf '%s' "$interpreter_cmd" | grep -qiE "$MD_LITERAL" &&
  printf '%s' "$interpreter_cmd" | grep -qE "${WRITE_API}|${FILE_WRITE}|${OPEN_WRITE}"; then
  # A fixed trusted parser recognizes only this complete, bounded Path rewrite.
  # All failures retain the original denial; no submitted Python is executed.
  IFS= read -r -d '' navori_python_analyzer <<'NAVORI_PYTHON_ANALYZER' || :
import ast
import re
import sys

def require(value):
    if not value:
        raise ValueError("unrecognized Path rewrite")

def literal(node):
    require(isinstance(node, ast.Constant) and type(node.value) is str)
    return node.value

def assignment(node):
    require(isinstance(node, ast.Assign) and len(node.targets) == 1)
    require(isinstance(node.targets[0], ast.Name))
    return node.targets[0].id, node.value

def method(node, owner, name):
    require(isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute))
    require(isinstance(node.func.value, ast.Name) and node.func.value.id == owner)
    require(node.func.attr == name)
    return node

def utf8(call):
    require(len(call.keywords) == 1 and call.keywords[0].arg == "encoding")
    require(literal(call.keywords[0].value) == "utf-8")

try:
    command = sys.stdin.buffer.read(16385)
    require(len(command) <= 16384)
    command = command.decode("utf-8", errors="strict")
    heredoc = re.fullmatch(r"[ \t]*python3[ \t]+-[ \t]+<<(['\"])([A-Za-z_][A-Za-z_0-9]*)\1[ \t]*\n(.*)\n\2\n?", command, re.S)
    if heredoc:
        source = heredoc.group(3)
    else:
        # Single shell quotes are literal; double quotes may not expand or
        # escape anything. Unsupported shell quoting is deliberately denied.
        invocation = re.fullmatch(r"[ \t]*python3[ \t]+-c[ \t]+(?:'([^']*)'|\"([^\"\\$`]*)\")[ \t]*", command, re.S)
        require(invocation is not None)
        source = invocation.group(1) if invocation.group(1) is not None else invocation.group(2)
    tree = ast.parse(source, mode="exec")
    pending = [(tree, 0)]
    nodes = 0
    while pending:
        node, depth = pending.pop()
        nodes += 1
        require(nodes <= 4096 and depth <= 16)
        pending.extend((child, depth + 1) for child in ast.iter_child_nodes(node))
    body = tree.body
    require(len(body) >= 5)
    imported = body[0]
    require(isinstance(imported, ast.ImportFrom) and imported.module == "pathlib" and imported.level == 0)
    require(len(imported.names) == 1 and imported.names[0].name == "Path" and imported.names[0].asname is None)
    path, constructor = assignment(body[1])
    require(path != "Path" and isinstance(constructor, ast.Call))
    require(isinstance(constructor.func, ast.Name) and constructor.func.id == "Path")
    require(len(constructor.args) == 1 and not constructor.keywords)
    destination = literal(constructor.args[0])
    require(destination and not any(char in destination for char in "\x00\r\n"))
    require(not destination.lower().endswith((".md", ".mdx")))
    text, read = assignment(body[2])
    require(text not in (path, "Path"))
    read = method(read, path, "read_text")
    require(not read.args)
    utf8(read)
    for statement in body[3:-1]:
        target, replacement = assignment(statement)
        require(target == text)
        replacement = method(replacement, text, "replace")
        require(len(replacement.args) == 2 and not replacement.keywords)
        for argument in replacement.args:
            literal(argument)
    require(isinstance(body[-1], ast.Expr))
    write = method(body[-1].value, path, "write_text")
    require(len(write.args) == 1 and isinstance(write.args[0], ast.Name) and write.args[0].id == text)
    utf8(write)
    print("ALLOW_PATH_REWRITE")
except Exception:
    sys.exit(1)
NAVORI_PYTHON_ANALYZER
  navori_python_safe=$(printf '%s' "$cmd" | python3 -c "$navori_python_analyzer" 2>/dev/null) || navori_python_safe=""
  if [ "$navori_python_safe" = "ALLOW_PATH_REWRITE" ]; then
    navori_audit_reason="reescritura Path no-md clasificada"
    exit 0
  fi
  # The program is fixed hook code. The submitted command enters only on
  # stdin as data; never eval it. A nonzero analyzer, missing node, empty or
  # malformed output all fall through to the existing exit-2 block.
  IFS= read -r -d '' navori_json_analyzer <<'NAVORI_JSON_ANALYZER' || :
const input = require("node:fs").readFileSync(0, "utf8");
const fail = () => { throw Error("unrecognized metadata program"); };
try {
  if (Buffer.byteLength(input) > 16384) fail();
  const shell = /^[ \t]*node[ \t]+-e[ \t]+\x27([^\x27]*)\x27[ \t]*$/s.exec(input);
  if (!shell) fail();
  const source = shell[1];
  const tokens = [];
  const forbidden = new Set(["__proto__", "prototype", "constructor", "toJSON"]);
  const reserved = new Set(["const", "for", "of", "if", "true", "false", "null", "return", "function", "class", "new", "this", "var", "let", "await", "async", "delete", "while", "do", "else", "try", "catch", "throw", "import", "export", "default", "in", "instanceof", "void", "typeof", "yield", "switch", "case", "break", "continue", "with", "super", "extends", "static", "get", "set"]);
  for (let at = 0; at < source.length;) {
    const rest = source.slice(at);
    const space = /^[\t\n\r ]+/.exec(rest);
    if (space) { at += space[0].length; continue; }
    const string = /^"(?:[^"\\\x00-\x1f]|\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))*"/.exec(rest);
    if (string) {
      tokens.push({ kind: "string", value: JSON.parse(string[0]) });
      at += string[0].length;
    } else {
      const id = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(rest);
      const number = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/.exec(rest);
      if (id) { tokens.push({ kind: "id", value: id[0] }); at += id[0].length; }
      else if (number) {
        if (!Number.isFinite(Number(number[0]))) fail();
        tokens.push({ kind: "number", value: number[0] }); at += number[0].length;
      } else if (rest.startsWith("=>")) { tokens.push({ kind: "punct", value: "=>" }); at += 2; }
      else if (".,;:=()[]{}!+".includes(rest[0])) { tokens.push({ kind: "punct", value: rest[0] }); at++; }
      else fail();
    }
    if (tokens.length > 4096) fail();
  }
  let pos = 0;
  const peek = (value) => tokens[pos]?.value === value;
  const take = (value) => {
    const token = tokens[pos++];
    const expectedKind = value === "2" ? "number" : ".,;:=()[]{}!+=>".includes(value) ? "punct" : "id";
    if (!token || token.value !== value || token.kind !== expectedKind) fail();
  };
  const kind = (wanted) => { const token = tokens[pos++]; if (!token || token.kind !== wanted) fail(); return token.value; };
  const name = () => { const value = kind("id"); if (reserved.has(value)) fail(); return value; };
  const binding = () => { const value = name(); if (forbidden.has(value) || ["JSON", "require"].includes(value)) fail(); return value; };
  const property = () => { const value = name(); if (forbidden.has(value)) fail(); return value; };
  const path = (root, stop) => {
    take(root);
    let count = 0;
    let result = "";
    while (peek(".") && tokens[pos + 1]?.value !== stop) {
      take("."); result += "." + property();
      if (++count > 8) fail();
    }
    if (!count) fail();
    return result;
  };
  const value = (depth = 0) => {
    if (depth > 16) fail();
    if (tokens[pos]?.kind === "string" || tokens[pos]?.kind === "number") { pos++; return; }
    if (peek("true") || peek("false") || peek("null")) { pos++; return; }
    if (peek("[")) {
      take("[");
      if (!peek("]")) { do { value(depth + 1); if (!peek(",")) break; take(","); if (peek("]")) fail(); } while (true); }
      take("]"); return;
    }
    if (peek("{")) {
      take("{"); const keys = new Set();
      if (!peek("}")) {
        do {
          const key = tokens[pos]?.kind === "string" ? kind("string") : property();
          if (forbidden.has(key) || keys.has(key)) fail();
          keys.add(key); take(":"); value(depth + 1);
          if (!peek(",")) break; take(","); if (peek("}")) fail();
        } while (true);
      }
      take("}"); return;
    }
    fail();
  };
  const string = (expected) => { const actual = kind("string"); if (actual !== expected) fail(); };
  take("const"); const fs = binding(); take("="); take("require"); take("("); string("node:fs"); take(")"); take(";");
  take("const"); const dest = binding(); if (dest === fs) fail(); take("=");
  const destination = kind("string");
  if (!destination || /[\x00-\x1f\x7f]/.test(destination) || !/\.json$/i.test(destination)) fail();
  take(";");
  take("const"); const doc = binding(); if (doc === fs || doc === dest) fail(); take("=");
  take("JSON"); take("."); take("parse"); take("(");
  take(fs); take("."); take("readFileSync"); take("("); take(dest); take(","); string("utf8"); take(")"); take(")"); take(";");
  let operations = 0;
  while (!(peek(fs) && tokens[pos + 1]?.value === "." && tokens[pos + 2]?.value === "writeFileSync")) {
    if (++operations > 4096) fail();
    if (peek("for")) {
      take("for"); take("("); take("const"); const item = binding();
      if ([fs, dest, doc].includes(item)) fail();
      take("of"); take("[");
      if (!peek("]")) { do { kind("string"); if (!peek(",")) break; take(","); if (peek("]")) fail(); } while (true); }
      take("]"); take(")"); take("if"); take("("); take("!");
      const checked = path(doc, "includes"); take("."); take("includes"); take("("); take(item); take(")"); take(")");
      const pushed = path(doc, "push"); if (checked !== pushed) fail();
      take("."); take("push"); take("("); take(item); take(")"); take(";");
    } else {
      const target = path(doc, "sort");
      if (peek(".") && tokens[pos + 1]?.value === "sort") {
        take("."); take("sort"); take("("); take(")"); take(";"); continue;
      }
      take("=");
      if (peek(doc)) {
        path(doc, "map"); take("."); take("map"); take("(");
        const item = binding(); if ([fs, dest, doc].includes(item)) fail();
        take("=>"); path(item); take(")");
      } else value();
      take(";");
    }
  }
  take(fs); take("."); take("writeFileSync"); take("("); take(dest); take(",");
  take("JSON"); take("."); take("stringify"); take("("); take(doc); take(","); take("null"); take(","); take("2"); take(")");
  take("+"); string("\n"); take(")"); take(";");
  if (pos !== tokens.length) fail();
  process.stdout.write("ALLOW");
} catch { process.exitCode = 1; }
NAVORI_JSON_ANALYZER
  if command -v node >/dev/null 2>&1; then
    if navori_json_result=$(printf '%s' "$cmd" | node -e "$navori_json_analyzer" 2>/dev/null) && [ "$navori_json_result" = "ALLOW" ]; then
      navori_audit_verdict="allow"
      navori_audit_reason="programa JSON estático reconocido"
      exit 0
    fi
  fi
  # Closed Python handoff grammar: parse supplied text, never run its imports,
  # reads, Git queries or writes. The producer still assumes trusted Python,
  # stdlib, Git and filesystem; this is destination classification, not isolation.
  IFS= read -r -d '' navori_python_analyzer <<'NAVORI_PYTHON_ANALYZER' || :
import ast
import math
import re
import sys

def recognize() -> bool:
    """Recognize one bounded, complete JSON handoff without evaluating source."""
    command = sys.stdin.buffer.read(16385)
    if len(command) > 16384:
        return False
    command = command.decode('utf-8')
    header = re.match(r"python3 - <<'([A-Za-z_][A-Za-z0-9_]*)'\n", command)
    if not header:
        return False
    lines = command[header.end():].split('\n')
    # Shell closes at the FIRST exact delimiter, including inside Python strings.
    close = lines.index(header.group(1))
    if lines[close + 1:] not in ([], ['']):
        return False
    tree = ast.parse('\n'.join(lines[:close]))
    if sum(1 for _ in ast.walk(tree)) > 4096 or len(tree.body) != 7:
        return False
    template = ast.parse("""import json, subprocess
from pathlib import Path
root = Path.cwd()
runtime = json.loads((root / 'INPUT').read_text())
report = {}
(root / 'OUTPUT').write_text(json.dumps(report, indent=2, ensure_ascii=False) + '\\n')
print('MESSAGE')
""")
    # Only these two exact, read-only argv shapes may occur as report values.
    expressions = {
        ast.dump(ast.parse(source, mode='eval').body)
        for source in (
            'str(root)', "runtime['repo']", "runtime['results']",
            "subprocess.check_output(['git', 'branch', '--show-current'], text=True).strip()",
            "subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip()",
        )
    }

    def data(node: ast.AST, depth: int = 0) -> bool:
        """Allow JSON literals and the fixed evidence expressions only."""
        if depth > 16:
            return False
        if isinstance(node, ast.Constant):
            return (type(node.value) in (str, int, bool, type(None)) or
                    type(node.value) is float and math.isfinite(node.value))
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return (isinstance(node.operand, ast.Constant) and
                    type(node.operand.value) in (int, float) and
                    math.isfinite(node.operand.value))
        if isinstance(node, ast.List):
            return all(data(value, depth + 1) for value in node.elts)
        if isinstance(node, ast.Dict):
            keys = [key.value for key in node.keys
                    if isinstance(key, ast.Constant) and type(key.value) is str]
            return (len(keys) == len(node.keys) == len(set(keys)) and
                    all(data(value, depth + 1) for value in node.values))
        return ast.dump(node) in expressions

    def json_path(node: ast.AST) -> bool:
        """Validate decoded literal destinations without accessing the filesystem."""
        return (isinstance(node, ast.Constant) and type(node.value) is str and
                bool(node.value) and not re.search(r'[\x00-\x1f\x7f]', node.value) and
                node.value.lower().endswith('.json'))

    input_path = tree.body[3].value.args[0].func.value.right
    output_path = tree.body[5].value.func.value.right
    message = tree.body[6].value.args[0]
    report = tree.body[4].value
    if not (json_path(input_path) and json_path(output_path) and
            isinstance(message, ast.Constant) and type(message.value) is str and
            isinstance(report, ast.Dict) and data(report)):
        return False
    for node in ast.walk(template):
        if isinstance(node, ast.Constant) and node.value in ('INPUT', 'OUTPUT', 'MESSAGE'):
            node.value = {'INPUT': input_path.value, 'OUTPUT': output_path.value,
                          'MESSAGE': message.value}[node.value]
    template.body[4].value = report
    return ast.dump(tree) == ast.dump(template)

try:
    if recognize():
        sys.stdout.write('ALLOW')
    else:
        sys.exit(1)
except Exception:
    sys.exit(1)
NAVORI_PYTHON_ANALYZER
  if command -v python3 >/dev/null 2>&1; then
    if navori_python_result=$(printf '%s' "$cmd" | python3 -I -S -c "$navori_python_analyzer" 2>/dev/null) && [ "$navori_python_result" = "ALLOW" ]; then
      navori_audit_verdict="allow"
      navori_audit_reason="programa JSON Python estático reconocido"
      exit 0
    fi
  fi
  block "intérprete con operación de escritura y ruta .md/.mdx"
fi

navori_audit_verdict="allow"
navori_audit_reason="comando no cubierto por R4"
exit 0
