#!/usr/bin/env bash
#
# PreToolUse(Bash|Edit|Write|NotebookEdit) guard — the mechanical half of R1
# (spec 0030, #985): the `implementer` does not write Markdown. Blocks a
# `Write`/`Edit`/`NotebookEdit` whose target ends in `.md`/`.mdx`, and the Bash
# write-verb forms of R4 (redirection, `tee`, `sed -i`/`perl -i`, `cp`/`mv` onto
# a `.md`/`.mdx` path) — all with `exit 2`, the same channel `guard-destructive`
# uses, evaluated BEFORE permission rules.
#
# WHY A HOOK AND NOT JUST THE CONTRACT (design.md): `implementer.md`'s own
# prose already says not to touch `.md` (R1). #985's own failure mode is a
# contract the agent follows by inertia — 520 `.md` writes since 2026-09-01,
# with the prohibition already implied by the agent's job. Prose alone did not
# hold; this is the mechanical backstop.
#
# WHO IT APPLIES TO. `agent_type` — read straight from the payload, not
# `tool_input` — is the field Claude Code adds "present only when the hook
# fires inside a subagent call" (https://code.claude.com/docs/en/hooks.md,
# confirmed against this repo's own `model-advisor.sh`, which reads the same
# field the same way). Absent → the main thread, never blocked. Any value other
# than `implementer` (`scribe`, `reviewer`, `auditor`, `scout`, `publisher`) →
# never blocked either: this rule is scoped to the one role R1 names.
#
# KNOWN, ACCEPTED LIMITATION — best-effort against inertia, NOT a sandbox
# against a deliberate adversary (same posture as `guard-destructive.sh`'s own
# header). The Bash rules read the command as TEXT, unsegmented: a `.md`
# mention inside a commit message or a heredoc body can false-positive, and a
# runner this hook does not enumerate — `python3 -c`, `node -e`, `dd`, `rsync`,
# `git apply` — walks straight past it (R4's own wording: "not a sandbox
# against evasion"). The contract in `implementer.md` is the rule; this catches
# the slip, not the workaround.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# Command/field extraction (payload → $cmd, $payload). Shared body, single
# source of truth.
# navori:include extract-cmd

navori_audit_name="implementer-no-markdown"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127, and a
# recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. This fires on EVERY Bash/Edit/Write/NotebookEdit call from
# EVERY agent (and the main thread); only the implementer is ever in scope.
# Fork-free PRESENCE test before anything that spawns a process — same trade
# `model-advisor.sh` makes for the identical field: the main thread carries no
# `agent_type` key at all, so a plain substring test already proves absence
# without a fork. A VALUE read (below) still follows for the subagent case,
# because presence alone only proves "some subagent", not which one.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

navori_agent_type=$(payload_field agent_type)
if [ "$navori_agent_type" != "implementer" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="no es el implementer"
  exit 0
fi

navori_tool=$(payload_field tool_name)

block() {
  echo "[navori] BLOCKED by implementer-no-markdown: $1" >&2
  # Both progress paths, never one alone: `placeHook` ships this byte-identical
  # to Claude and Codex (#389), so a message hardcoding `.claude/progress`
  # would misdirect a Codex implementer to a path that is not its own.
  echo "[navori] the implementer does not write Markdown (spec 0030, R1). Put the change in \"markdownRequests\", inside .claude/progress/impl_<feature>.json (or .codex/progress/impl_<feature>.json under Codex) — the scribe applies it in this worktree." >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Case-insensitive `.md`/`.mdx`: macOS ships a case-insensitive filesystem, so
# `NOTES.MD` writes the same file `notes.md` does.
is_md_path() {
  case "$1" in
    *.[mM][dD] | *.[mM][dD][xX]) return 0 ;;
    *) return 1 ;;
  esac
}

case "$navori_tool" in
  Write | Edit)
    navori_path=$(payload_field tool_input.file_path)
    if is_md_path "$navori_path"; then
      block "$navori_tool sobre '$navori_path'"
    fi
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  NotebookEdit)
    navori_path=$(payload_field tool_input.notebook_path)
    if is_md_path "$navori_path"; then
      block "NotebookEdit sobre '$navori_path'"
    fi
    navori_audit_verdict="allow"
    navori_audit_reason="ruta no-md"
    exit 0
    ;;
  Bash) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac

cmd=$(extract_cmd)
if [ -z "$cmd" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin comando que inspeccionar"
  exit 0
fi

# R4's write-verb forms, over the raw command text (best-effort, see header).
# Case-insensitive throughout, same reasoning as `is_md_path` above.
MD_EXT='\.(md|mdx)'

# 1. Output redirection: `>`, `>>`, `>|` onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE ">>?\\|?[[:space:]]*[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "redirección hacia un archivo .md/.mdx"
fi

# 2. `tee` (append or overwrite) onto a `.md`/`.mdx` target.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])tee([[:space:]]+-[a-zA-Z]+)*[[:space:]]+[^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'tee' hacia un archivo .md/.mdx"
fi

# 3. In-place rewrite: `sed -i`/`sed --in-place`, `perl -i`.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])sed[[:space:]]+(-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*|--in-place)([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'sed -i' sobre un archivo .md/.mdx"
fi
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])perl[[:space:]]+-[a-zA-Z]*i[a-zA-Z]*[^[:space:]]*([[:space:]]|=).*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'perl -i' sobre un archivo .md/.mdx"
fi

# 4. `cp`/`mv` onto a `.md`/`.mdx` target — the atomic-write idiom (write a
# temp file, then move it onto the managed path). Anchored on the LAST operand
# of the invocation (greedy `.*` before the final `[[:space:]]`), since that is
# where `cp`/`mv` read their destination.
if printf '%s' "$cmd" | grep -qiE "(^|[;&|[:space:]])(cp|mv)[[:space:]]+.*[[:space:]][^[:space:];&|]*${MD_EXT}([[:space:]]|;|&|\\||\$)"; then
  block "'cp'/'mv' hacia un archivo .md/.mdx"
fi

navori_audit_verdict="allow"
navori_audit_reason="comando no cubierto por R4"
exit 0
