#!/usr/bin/env bash
#
# PostToolUse(Bash) watcher for managed-block drift (#530).
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST. The common case is "nothing changed", and it costs ONE `find` against a
# stamp file — not a stat of every managed file, and never a hash. Hashing only
# happens for files that actually changed since the last tool call, which in a
# normal session is zero and in a bad one is one or two.
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

stamp=".claude/.managed-drift-stamp"

# First run in a session (or after a `render` wiped the ephemeral dir): adopt
# the current state as the baseline and say nothing. Reporting every block on
# the first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p .claude 2>/dev/null || exit 0
  : > "$stamp" 2>/dev/null || exit 0
  exit 0
fi

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — walking them would hash a fresh report on every command
# and find nothing. `.claude/worktrees/` too: each is a full checkout, so
# walking it would make this hook cost more than the command it follows. That is
# why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
changed=$(find $roots -type f -newer "$stamp" 2>/dev/null || true)
# Re-stamp BEFORE reporting, so one broken file is reported once instead of on
# every command for the rest of the session. A second write to the same file
# moves its mtime again and does get a second report.
: > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# sha1, first 8 hex, over the body with trailing whitespace removed — the exact
# algorithm `computeManagedHash` uses (lib/marker.ts). `$(…)` strips the
# trailing newline, which is what makes the two agree; without it every hash
# differs and the hook cries wolf on healthy files.
sha=""
command -v shasum  >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This hook is a detector, not a gate — the guard is
# still in front, and a noisy failure here would fire on every command.
[ -z "$sha" ] && exit 0

drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
