#!/usr/bin/env bash
#
# PostToolUse watcher for managed-block drift (#530), on every tool that can
# write a file: `Bash|Edit|Write|NotebookEdit`.
#
# WHY THE MATCHER IS THE WHOLE DECISION, and why it took #775 to widen it. This
# script audits STATE, never the command, so it has no `case "$tool_name"` to
# contradict its registration — the matcher alone decides when it runs, which
# makes a narrow one indistinguishable from a hook that works. It was `Bash`
# only, and the host's own PostToolUse doc spells out the consequence from the
# other direction: a hook matching `Edit|Write` does not run when a `Bash`
# command rewrites the same file. The inverse is the hole this had — in
# `default`/`acceptEdits`, where the host does NOT push everything through the
# shell, an `Edit` over `CLAUDE.md` broke a managed block's hash and this stayed
# quiet until the next Bash call, if one ever came. A session of pure native
# editing put the #523 freeze back into silence, which is the one thing this
# hook exists to prevent.
#
# WHY NOT `FileChanged`, which the same doc section recommends for exactly this
# ("to run a hook when a specific file changes on disk, whatever wrote it").
# The CONTRACT is not the reason, and this comment used to say it was: core can
# register the event today. `lib/plugins.ts:91` admits four events, but that
# enum is the schema for a PLUGIN MANIFEST and is used nowhere else —
# `buildClaudeSettings` returns `Record<string, unknown>` and validates no event
# name at all, which is how core already ships `SessionEnd` and
# `UserPromptSubmit`. Only a plugin registering `FileChanged` would need the
# vocabulary widened. Three other things stop it:
#
#   1. The watchlist would live IN the settings, and the managed file set is
#      derived per repo at render time (engine outputs plus every rendered
#      asset, ~60 files here) — so settings.json would carry a second copy of a
#      list this script already derives, and the two would drift. A watchlist
#      that drifts from the managed set is a detector with holes in it, i.e.
#      this hook's own defect class.
#   2. It loses the channel to the model. `FileChanged` has no decision
#      control: the host shows its stderr "to user only", reads `watchPaths`
#      and `systemMessage` out of the JSON output and discards `continue`, and
#      that `systemMessage` is a brief terminal notification that "doesn't
#      reach the SDK message stream". Everything this hook does ends in
#      `exit 2` → stderr → the MODEL, which is what gets the freeze repaired in
#      the same turn. Migrating would downgrade the recipient of the warning.
#   3. Its matcher cannot name these paths. `FileChanged` and `StopFailure` use
#      a narrower exact-match set — letters, digits, `_` and `|` only — and
#      every root this watches (`CLAUDE.md`, `.claude/settings.json`,
#      `.claude/agents/…`) carries a dot, a slash or a hyphen, which drops the
#      matcher onto the regular-expression path. The one viable route is
#      `watchPaths` (absolute paths) returned from `SessionStart`, which is
#      more machinery and still subject to (1) and (2).
#
# What the widening does NOT buy, stated plainly: a write from outside the
# session — a formatter in a watch process, another terminal — still surfaces
# only on the next tool call navori sees. `FileChanged` would catch that one.
# The cost of what it does buy is one shasum pass (~35ms, quoted below) per
# native edit.
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST, and why this compares CONTENT rather than mtimes. The obvious cheap
# check is `find -newer <stamp>`, and it is wrong here: `find` compares mtimes at
# whatever resolution the filesystem stores, which on several (ext4 under the CI
# runner among them) is ONE SECOND. Two writes inside the same second as the
# stamp are invisible — the watcher would report the first and silently miss the
# second, which is precisely the failure it exists to prevent. It passed on APFS
# and failed in CI, so the clock was never a sound basis.
#
# So the common case costs one `shasum` pass over the managed files (~35ms) and
# compares that list against the previous one. It is exact, it depends on no
# clock, and per-block hashing — the expensive part, ~3.5s for 53 blocks — runs
# ONLY for the files whose content actually changed, which in a normal session
# is none and in a bad one is one. That ~35ms is the MEDIAN of 13,692 recorded
# runs in `~/.navori/audits` (mean 43.7ms, p95 78ms); the "~25ms measured over
# 60 files" this used to quote was a single early sample and ran ~40% optimistic.
set -uo pipefail

# The tools this state auditor must run after, i.e. the matcher it has to be
# registered with. Read by `hook-matcher-wiring.test.ts` (#796); nothing in this
# script reads it.
#
# It exists because this hook has nothing else the wiring suite can derive an
# invariant from. A hook that dispatches on `case "$tool_name"` contradicts a
# narrow matcher by itself, and a gate that declares `$TRIGGER_TOKENS` claims
# the commands it needs handed to it — this one audits STATE, so it makes
# neither claim, and its matcher was held up only by a hand-written list of four
# tool names in `build-settings.test.ts`. Narrowing the matcher went red there
# and the obvious repair was to edit the literal, which is the drift this
# declaration removes: the edit point is now the script, where the intent lives.
#
# The rule could not be inferred from silence instead. "Every hook with no
# `case` and no `$TRIGGER_TOKENS` must receive every write tool" falsifies
# against `guard-destructive.sh`, `guard-search-routing.sh` and
# `subagent-stop-handoff.sh` (matcher `Agent|Task`, correct by design).
COVERED_TOOLS='Bash Edit Write NotebookEdit'

# PostToolUse delivers its payload on stdin; this hook never needed it and the
# audit recorder does (session_id/cwd), so it is captured rather than ignored.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="managed-drift-watch"
navori_audit_phase="PostToolUse"
# The recorded tool used to be the literal "Bash", which was true while the
# matcher was. Now that four tools reach here it has to be read — and read
# without a fork, because this runs after every tool call: `#` and `%%` are
# builtins, and a tool name carries no quote to escape. Anything the parse does
# not recognise leaves the field EMPTY (the partial then omits it) rather than
# guessing, since a wrong label in the audit log is how a lane gets measured as
# working when it is not — this issue, one level up.
navori_audit_tool=""
case "$payload" in
  *'"tool_name":"'*)
    navori_audit_tool=${payload#*'"tool_name":"'}
    navori_audit_tool=${navori_audit_tool%%'"'*}
    case "$navori_audit_tool" in
      "" | *[!A-Za-z_]*) navori_audit_tool="" ;;
    esac
    ;;
esac
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# This hook has SEVEN early exits (no sha, no roots, no changes, …). Wiring a
# call into each is how the set drifts the next time one is added, so the verdict
# is derived once, from the exit code, in a trap.
#
# `navori_audit_reached_check` is what separates "ran and found nothing" from
# "bailed before checking anything" — the distinction the whole exercise exists
# for. Without it every early exit would report `clean`, i.e. would claim a
# verification that never happened.
navori_audit_reached_check=0
navori_audit_on_exit() {
  navori_audit_code=$?
  if [ "$navori_audit_code" -eq 2 ]; then
    navori_audit_log "dirty" "bloque managed con hash desalineado"
  elif [ "$navori_audit_reached_check" -eq 1 ]; then
    navori_audit_log "clean"
  else
    navori_audit_log "skip" "sin nada que verificar"
  fi
  return 0
}
trap navori_audit_on_exit EXIT

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

stamp=".claude/.managed-drift-stamp"

# sha1 tool, resolved once. `shasum` on macOS, `sha1sum` on most Linuxes; both
# print `<hash>  <path>` for a file list, which is the format the stamp stores.
sha=""
command -v shasum >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This is a detector, not a gate — the guard still
# sits in front, and a noisy failure here would fire on every single command.
[ -z "$sha" ] && exit 0

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — including them would re-hash a fresh report on every
# command and find nothing. `.claude/worktrees/` too: each is a full checkout,
# so walking it would make this hook cost more than the command it follows. That
# is why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
current=$(find $roots -type f -exec $sha {} + 2>/dev/null | sort || true)
[ -z "$current" ] && exit 0

# First run in a session (or after the ephemeral dir was wiped): adopt the
# current state as the baseline and say nothing. Reporting every block on the
# first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p .claude 2>/dev/null || exit 0
  printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
  exit 0
fi

# Lines present now but not in the baseline: a file whose CONTENT changed, or a
# new one. A deleted file appears only in the baseline and is ignored — there is
# no block left to verify.
changed=$(printf '%s\n' "$current" | grep -F -x -v -f "$stamp" 2>/dev/null | sed -E 's/^[a-f0-9]+[[:space:]]+//' || true)
# Re-baseline BEFORE reporting, so one write is reported once instead of on
# every command for the rest of the session. A second write does change the
# content again, and does get its own report.
printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# From here on the work is per-CHANGED-file only. `$(…)` strips the trailing
# newline, which is what makes these hashes agree with `computeManagedHash`
# (lib/marker.ts: sha1 over the body with trailing whitespace removed, first 8
# hex); without it every hash differs and the hook cries wolf on healthy files.
drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

navori_audit_reached_check=1
[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
