#!/usr/bin/env bash
# SessionStart master-plan status. Advisory and fail-open: no startup failure
# may block the user's unrelated request. Render fills the specsDir placeholder.
set +e

payload=$(cat 2>/dev/null) || payload=""
navori_audit_name="master-plan-context"
navori_audit_phase="SessionStart"
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

specs_dir={{shq:sdd.specsDir}}
NAVORI_MASTER_LINE_BUDGET=600
project_dir=${CLAUDE_PROJECT_DIR:-$PWD}
index_path=$project_dir/$specs_dir/_master/INDEX.md
offer='En tu primera respuesta de la sesión, ofrece continuar con el plan maestro en una sola línea, sin interrumpir lo que el usuario pidió.'

if command -v navori >/dev/null 2>&1; then
  line=$(cd "$project_dir" && navori master status --line 2>/dev/null)
  code=$?
  if [ "$code" -eq 0 ] && [ -n "$line" ] && [ "${#line}" -le "$NAVORI_MASTER_LINE_BUDGET" ]; then
    case "$line" in
      *$'\n'* | *$'\r'*) ;;
      *)
        printf '%s\n' "$line"
        navori_audit_verdict="allow"
        navori_audit_reason="status-line"
        exit 0
        ;;
    esac
  fi
fi

# The first line is generated by renderIndexMd; never interpret it as shell.
first_line=""
if [ -r "$index_path" ]; then
  IFS= read -r first_line < "$index_path" || true
fi
case "$first_line" in
  'Etapa activa: '*'/STATUS.md')
    status_path=${first_line#Etapa activa: }
    case "$status_path" in
      '' | /* | *[!A-Za-z0-9._/-]*) ;;
      *)
        printf 'Plan maestro — consulta %s. %s\n' "$status_path" "$offer"
        navori_audit_verdict="allow"
        navori_audit_reason="status-pointer"
        exit 0
        ;;
    esac
    ;;
esac
printf 'Plan maestro — consulta %s/_master/INDEX.md. %s\n' "$specs_dir" "$offer"
navori_audit_verdict="allow"
navori_audit_reason="index-pointer"
exit 0
