#!/usr/bin/env bash
#
# PreToolUse(Agent) gate — spec 0032 (#1011), R16/R17/R19: while
# `harness.planTiers` is `true`, the orchestrator may not dispatch the
# `implementer` without a workplan that passes `navori plan check`, or a
# level-0 exemption `navori plan classify` confirms. Blocks with `exit 2`,
# the same channel `guard-destructive`/`implementer-no-markdown` use,
# evaluated BEFORE permission rules.
#
# THIN ON PURPOSE. All the decision logic — reading `tool_input.subagent_type`
# / `tool_input.prompt`, resolving the workplan, running `classify`/`check`,
# counting `CHANGES_REQUESTED` rejections (R19) — lives in TypeScript
# (`navori plan gate`, `lib/plan/gate.ts`): that is what `plan-gate.test.ts`
# exercises directly. This script only resolves the `navori` binary and
# forwards the hook's own stdin payload to it unchanged; it never parses JSON
# itself. Matcher `Agent` in settings.json already restricts which calls
# reach this script, so there is nothing left to filter here.
#
# BINARY RESOLUTION. Same as `audit-mode-trigger.sh` / `session-start-context.sh`:
# `command -v navori`. Unlike those two (best-effort, silently absent), this
# is a HARD gate — `harness.planTiers` promises the workplan is enforced, so a
# real plan denial (exit 2 from `navori plan gate`) always stays a hard block.
# When navori is missing or outdated there is NO verdict to enforce (#1117): the
# gate asks the human instead of leaving a dead end — Claude only, in a mode
# that shows the prompt (`navori_can_ask`), recorded as verdict `ask`. Codex
# (drops `permissionDecision`), no payload, no jq and bypassPermissions/dontAsk/
# plan/unknown modes keep the hard block (exit 2); an ask is never a silent
# allow. The `*)` arm also catches a crashing or killed navori (exit 126/127/
# 137, ...), not only a missing `plan` subcommand; the ask text says "exit N".
# An outdated build with no `plan` subcommand exits with something other
# than this gate's own two contractual codes (0 allow, 2 deny) — citty's
# unknown-command exit — which this script tells apart from a real verdict
# below, in ONE invocation (a second `--help` probe would read the hook's
# stdin payload twice, which a pipe cannot replay).
#
# Blocking classification (#1117):
#   - navori missing / `plan` subcommand unavailable: ask (Claude, prompting
#     modes only) / hard (Codex, no payload or jq, non-prompting modes) — no verdict.
#   - `navori plan gate` denied the dispatch: hard — a real verdict.
#
# CODEX (spec 0041 R9). Registered on PreToolUse(spawn_agent$) as the last late
# row. Only `implementer` is gated, with the role from `tool_input.agent_type`.
# Codex V2 encrypts the spawn `message`, so the opening line then comes from the
# orchestrator's `.navori/state/handoffs/dispatch_<feature>.json` (TTL 10 min,
# exactly one fresh file); the decision logic stays in `navori plan gate`.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# The payload is captured (not streamed) because two readers need it: the audit
# recorder below reads `session_id`/`cwd` from it, and `navori plan gate` gets
# the same bytes re-piped unchanged. A pipe cannot be replayed, so one read.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="plan-gate"
navori_audit_phase="PreToolUse"
navori_audit_tool="Agent"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN for the recorder: an undefined function here must never turn a raw,
# un-rendered copy of this asset into exit 127 — which is neither contractual
# code of this gate.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include extract-cmd
# navori:include gate-ask
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# The verdict is resolved in a trap, like `guard-destructive`: every exit below
# (missing binary, allow, deny, outdated build) is recorded without a call per
# branch, and the exit code itself stays untouched.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# No verdict (navori missing or unusable). $1 = audit reason code, $2 = hard-block
# message, $3 = text shown to the human when asking. Never returns.
plan_gate_no_verdict() {
  codex_copy=0
  case "$0" in *".codex/hooks/"*) codex_copy=1 ;; esac
  if [ "$codex_copy" = 0 ] && navori_can_ask; then
    navori_audit_verdict="ask"
    navori_audit_reason="$1"
    jq -cn --arg reason "$3" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"ask",permissionDecisionReason:$reason}}'
    exit 0
  fi
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  echo "$2" >&2
  exit 2
}

if ! command -v navori >/dev/null 2>&1; then
  plan_gate_no_verdict "binary-missing" \
    "[navori] BLOCKED by plan-gate: navori is not installed or not on PATH — install it before dispatching a planned implementer." \
    "[navori] plan-gate could not check the workplan: navori is not on PATH, so there is no verdict. Approve to dispatch the implementer WITHOUT the plan gate, or deny and install navori. If you are an agent, report this to the user and wait."
fi

printf '%s' "$payload" | navori plan gate
navori_exit=$?
case "$navori_exit" in
  0) exit 0 ;;
  2)
    navori_audit_verdict="block"
    navori_audit_reason="plan-denied"
    exit 2
    ;;
  *)
    plan_gate_no_verdict "subcommand-unavailable" \
      "[navori] BLOCKED by plan-gate: this navori build has no working 'plan' subcommand (exit $navori_exit) — update navori (or run 'navori render --apply' after updating) before dispatching a planned implementer." \
      "[navori] plan-gate could not check the workplan: this navori build has no working 'plan' subcommand (exit $navori_exit), so there is no verdict. Approve to dispatch the implementer WITHOUT the plan gate, or deny and update navori. If you are an agent, report this to the user and wait."
    ;;
esac
