#!/usr/bin/env bash
#
# PreToolUse(Agent) gate — spec 0032 (#1011), R16/R17/R19: while
# `harness.planTiers` is `true`, the orchestrator may not dispatch the
# `implementer` without a workplan that passes `navori plan check`, or a
# level-0 exemption `navori plan classify` confirms. Blocks with `exit 2`,
# the same channel `guard-destructive`/`implementer-no-markdown` use,
# evaluated BEFORE permission rules.
#
# THIN ON PURPOSE. All the decision logic — reading `tool_input.subagent_type`
# / `tool_input.prompt`, resolving the workplan, running `classify`/`check`,
# counting `CHANGES_REQUESTED` rejections (R19) — lives in TypeScript
# (`navori plan gate`, `lib/plan/gate.ts`): that is what `plan-gate.test.ts`
# exercises directly. This script only resolves the `navori` binary and
# forwards the hook's own stdin payload to it unchanged; it never parses JSON
# itself. Matcher `Agent` in settings.json already restricts which calls
# reach this script, so there is nothing left to filter here.
#
# BINARY RESOLUTION. Same as `audit-mode-trigger.sh` / `session-start-context.sh`:
# `command -v navori`. Unlike those two (best-effort, silently absent), this
# is a HARD gate — `harness.planTiers` promises the workplan is enforced, so a
# missing or outdated `navori` must DENY with an actionable reason, never fail
# open. An outdated build with no `plan` subcommand exits with something other
# than this gate's own two contractual codes (0 allow, 2 deny) — citty's
# unknown-command exit — which this script tells apart from a real verdict
# below, in ONE invocation (a second `--help` probe would read the hook's
# stdin payload twice, which a pipe cannot replay).
#
# CODEX. Spec 0035 defers registration of this hook: a live Codex smoke
# created an implementer without a workplan despite PreToolUse registration.
# The workplan procedure remains advisory until the host reliably blocks it.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# The payload is captured (not streamed) because two readers need it: the audit
# recorder below reads `session_id`/`cwd` from it, and `navori plan gate` gets
# the same bytes re-piped unchanged. A pipe cannot be replayed, so one read.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="plan-gate"
navori_audit_phase="PreToolUse"
navori_audit_tool="Agent"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN for the recorder: an undefined function here must never turn a raw,
# un-rendered copy of this asset into exit 127 — which is neither contractual
# code of this gate.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# The verdict is resolved in a trap, like `guard-destructive`: every exit below
# (missing binary, allow, deny, outdated build) is recorded without a call per
# branch, and the exit code itself stays untouched.
navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

if ! command -v navori >/dev/null 2>&1; then
  navori_audit_verdict="block"
  navori_audit_reason="binary missing from PATH"
  echo "[navori] BLOCKED by plan-gate: navori is not installed or not on PATH — install it before dispatching a planned implementer." >&2
  exit 2
fi

printf '%s' "$payload" | navori plan gate
navori_exit=$?
case "$navori_exit" in
  0) exit 0 ;;
  2)
    navori_audit_verdict="block"
    navori_audit_reason="plan gate denied the dispatch"
    exit 2
    ;;
  *)
    navori_audit_verdict="block"
    navori_audit_reason="plan subcommand unavailable, exit $navori_exit"
    echo "[navori] BLOCKED by plan-gate: this navori build has no working 'plan' subcommand (exit $navori_exit) — update navori (or run 'navori render --apply' after updating) before dispatching a planned implementer." >&2
    exit 2
    ;;
esac
