#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit.
#
# It does NOT verify the reviewer's content receipt. That backstop lived here
# until #365 and was removed on purpose: five fail-open paths (worktree, Codex
# workspace, zsh word-splitting, non-ASCII paths, a truncated singleton receipt)
# against zero documented catches, and one of its failure modes blocked every
# PR in the repo. The receipt is a handoff between the `reviewer` and the
# `commit-pr-pilot`, which verifies it agent-side and re-signs the delta. Don't
# re-add the check here without a captured case it would have caught.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# navori:include extract-cmd

# Detect the project's REAL package manager from lockfiles / package.json, so a
# gate command hardcoded to one PM (e.g. `pnpm run ...`) can still run in a repo
# that actually uses another (e.g. bun). Mirrors lib/detect.ts precedence:
# `packageManager` field first, then pnpm/bun/yarn/npm lockfiles. Prints the PM
# name (or nothing) on stdout. Git runs hooks from the repo root, so relative
# paths resolve against the project root.
detect_pm() {
  if [ -f package.json ]; then
    pm=$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"\([a-z]*\)@.*/\1/p' package.json | head -n1)
    case "$pm" in pnpm|npm|yarn|bun) printf '%s' "$pm"; return 0 ;; esac
  fi
  if [ -f pnpm-lock.yaml ]; then printf 'pnpm'; return 0; fi
  if [ -f bun.lockb ] || [ -f bun.lock ]; then printf 'bun'; return 0; fi
  if [ -f yarn.lock ]; then printf 'yarn'; return 0; fi
  if [ -f package-lock.json ]; then printf 'npm'; return 0; fi
  return 0
}

# True when the argument is a JS package manager (so we only try to remap the
# leading token of the gate command when it's actually a PM, not `make`/`ruff`).
is_pm() {
  case "$1" in pnpm|npm|yarn|bun) return 0 ;; *) return 1 ;; esac
}

run_gate() {
  echo "[navori] running quality-gate fast: $1" >&2
  eval "$1" || {
    echo "[navori] quality-gate fast failed. Commit aborted." >&2
    exit 2
  }
}

# Gate to `git commit` only. $TRIGGER_RE is consumed by the shared detector
# inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# navori:include gate-trigger

# Resolution of the working tree the commit acts on (#454). Shared body; defines
# `navori_worktree` but resolves nothing until it is called, so a Bash call that
# is not a commit still pays nothing for it.
# navori:include resolve-worktree

# An EMPTY `$cmd` is not "some command that isn't a commit": it means nothing
# could be read out of the tool input at all (no JSON parser, a malformed or
# truncated payload). `is_scan_trigger ""` simply finds no git segment, so the
# whole block below was skipped WITHOUT A WORD — a gate that omits itself in
# silence is indistinguishable from a gate that passed (#511). Its two siblings
# (`check-semgrep.sh`, `check-jscpd.sh`) already scan unconditionally there,
# which is the contract the shared extractor documents; this one drifted. The
# verdict is now stated out loud in both directions, per #88.
run_needed=0
if [ -z "$cmd" ]; then
  echo "[navori] no command could be read from the tool input; running the quality gate anyway rather than skipping it silently." >&2
  run_needed=1
elif is_scan_trigger "$cmd"; then
  run_needed=1
fi

if [ "$run_needed" = 1 ]; then
  # Pin the cwd to the root of the tree BEING COMMITTED before anything below
  # runs. Claude Code fires PreToolUse hooks from a cwd that is neither always
  # the repo root (#309: a relative gate like `cd packages/cli && pnpm lint`
  # fails from a subdir) nor always the right repo (#454: it is the MAIN repo
  # even when the commit happens in an agent worktree, so the gate validated a
  # tree that did not hold the diff).
  # $CLAUDE_PROJECT_DIR stays as a fallback for the no-git case; when nothing
  # resolves the substitution is empty and `cd ""` is a no-op, so behavior
  # outside a repo is unchanged.
  gate_root=$(navori_worktree)
  cd "${gate_root:-${CLAUDE_PROJECT_DIR:-}}" || exit 2
  # qualityGate.fast is shell-quoted at render time via the shq: marker (#197).
  # The gate string is still `eval`'d by run_gate below (running the gate is the
  # feature), but quoting it here means a hostile qualityGate.fast survives as one
  # literal token instead of injecting commands at variable-assignment time.
  gate={{shq:qualityGate.fast}}
  gate_bin="${gate%% *}"
  if command -v "$gate_bin" >/dev/null 2>&1; then
    run_gate "$gate"
  else
    # The declared runner isn't on PATH. If it's a package manager, detect the
    # repo's real one from lockfiles and retry through it (a `pnpm run x` gate
    # still runs in a bun-only checkout). #88: NEVER skip the gate silently —
    # when nothing can run it, BLOCK the commit loudly instead of the old
    # `exit 0` that handed a contributor zero quality gate without a word.
    detected_pm="$(detect_pm)"
    if is_pm "$gate_bin" && [ -n "$detected_pm" ] && [ "$detected_pm" != "$gate_bin" ] && command -v "$detected_pm" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' is not on PATH; using the lockfile-detected package manager: '$detected_pm'." >&2
      run_gate "$detected_pm ${gate#* }"
    else
      echo "[navori] quality-gate NOT run: '$gate_bin' is not on PATH and no alternative package manager was detected that could run it." >&2
      echo "[navori] Commit BLOCKED to avoid skipping the gate silently. Install '$gate_bin', or if you really want to skip it run the commit yourself outside the agent." >&2
      exit 2
    fi
  fi
fi

# navori:user-section
# user: add extra checks here. `$cmd` is already parsed from the tool input.
# Example:
#
#   case "$cmd" in
#     'git push'*)
#       bash scripts/check-licenses.sh || exit 2
#       ;;
#   esac
#
# Use a path your own repo owns. The example used to point at a plugin script
# under `.claude/scripts/`, which only exists when that plugin is installed AND
# the engine is Claude — copied verbatim it fails under Codex (#389).
