#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit/push.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

cmd=$(jq -r '.tool_input.command // empty' 2>/dev/null || true)

case "$cmd" in
  'git commit'*|'git push'*)
    gate="{{qualityGate.fast}}"
    # Defensive: skip cleanly (exit 0) when the gate's runtime isn't on PATH —
    # e.g. a Nix/nvm shell that hasn't loaded the project env. Never block a
    # commit just because the tool is missing from THIS shell.
    gate_bin="${gate%% *}"
    if ! command -v "$gate_bin" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' no está en PATH — skip quality-gate (¿shell sin el entorno del proyecto?)" >&2
      exit 0
    fi
    echo "[navori] running quality-gate fast: $gate" >&2
    eval "$gate" || {
      echo "[navori] quality-gate fast failed. Commit/push aborted." >&2
      exit 2
    }
    ;;
esac

# navori:user-section
# user: agregá checks adicionales acá. `$cmd` ya está parseado del input
# de la tool. Ejemplo:
#
#   case "$cmd" in
#     'git push'*)
#       bash .claude/scripts/check-jscpd.sh || exit 2
#       ;;
#   esac
