#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit/push.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

# Extract .tool_input.command WITHOUT hard-depending on jq (not preinstalled on
# macOS). Try jq, then node (Claude Code's own runtime), then a best-effort sed
# unwrap. If nothing extracts a command $cmd stays empty and the gate skips.
payload=$(cat)
extract_cmd() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r '.tool_input.command // empty' 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";process.stdin.on("data",c=>s+=c).on("end",()=>{try{process.stdout.write(String(JSON.parse(s)?.tool_input?.command??""))}catch{}})' 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p'
}
cmd=$(extract_cmd)

case "$cmd" in
  'git commit'*|'git push'*)
    gate="{{qualityGate.fast}}"
    # Defensive: skip cleanly (exit 0) when the gate's runtime isn't on PATH —
    # e.g. a Nix/nvm shell that hasn't loaded the project env. Never block a
    # commit just because the tool is missing from THIS shell.
    gate_bin="${gate%% *}"
    if ! command -v "$gate_bin" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' no está en PATH — skip quality-gate (¿shell sin el entorno del proyecto?)" >&2
      exit 0
    fi
    echo "[navori] running quality-gate fast: $gate" >&2
    eval "$gate" || {
      echo "[navori] quality-gate fast failed. Commit/push aborted." >&2
      exit 2
    }
    ;;
esac

# navori:user-section
# user: agrega checks adicionales acá. `$cmd` ya está parseado del input
# de la tool. Ejemplo:
#
#   case "$cmd" in
#     'git push'*)
#       bash .claude/scripts/check-jscpd.sh || exit 2
#       ;;
#   esac
