#!/usr/bin/env bash
#
# PreToolUse(apply_patch | spawn_agent) guard, CODEX ONLY (spec 0041 D5/D13,
# R6/R7/R8/R17/R31). Claude restricts a role with the agent's `tools:`
# allowlist; a Codex agent has no such field, so this hook is the mechanical
# equivalent. It never renders into `.claude/` (`HOOK_ENGINES`).
#
# TWO BRANCHES, both keyed on the top-level `agent_type`, which the host adds
# only when the hook fires inside a subagent. Absent or empty: the main thread,
# never blocked (R8).
#   1. spawn_agent (V1 name, or any V2 name ending in `spawn_agent`): a subagent
#      may not dispatch another one, whatever its role (R17/R31, depth 1). The
#      caller is named in the message.
#   2. apply_patch: `implementer` and `scribe` pass untouched (the first writes
#      production code, the second the Markdown the implementer must not). Any
#      other role may patch only the prefixes `RosterAgent.writes` grants it, or
#      an OS temp file. `default` and unknown roles get the common set
#      (fail-closed). Every path of a multi-file patch is checked.
#
# PATH CHECK. Each path is resolved against the payload `cwd`, normalized
# lexically (`..` cannot climb out unnoticed), then resolved physically so a
# symlink that leaves the repo is judged by where it lands. Inside the repo the
# role's prefixes decide, compared by path COMPONENT, not by text. Outside the
# repo only an OS temp root passes.
#
# FAIL-OPEN WITHOUT jq AND node (accepted, spec 0041): the sed fallback of
# `payload_field` cannot tell the top-level `agent_type` from
# `tool_input.agent_type`, so a main-thread spawn would be read as a subagent
# call and wrongly denied. With neither tool installed the hook lets the call
# through; upgrade trigger: ship a parser that reads only top-level keys.
#
# WHAT IT IS NOT. Bash writes keep the same containment as Claude (none by
# path); this guards the structured `apply_patch` channel only. Best-effort
# against inertia, not a sandbox against a deliberate adversary. If the payload
# cannot be read reliably it lets the call through.
#
# The per-role prefixes are NOT written here: they come from
# `RosterAgent.writes`, compiled by `buildRolePolicyShell` at render time.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# navori:include extract-cmd
# navori:include hook-input

navori_audit_name="role-guard"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. Fork-free presence test: the main thread carries no top-level
# `agent_type`, so the substring test proves absence without a process.
case "$payload" in
  *'"agent_type"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_type (hilo principal)"
    exit 0
    ;;
esac

# Without jq or node the field reader is a sed fallback that cannot tell the
# top-level `agent_type` from `tool_input.agent_type`; a wrong guess would deny
# the main thread's own spawn. Let the call through instead (best-effort).
if ! command -v jq >/dev/null 2>&1 && ! command -v node >/dev/null 2>&1; then
  navori_audit_verdict="skip"
  navori_audit_reason="sin jq ni node: payload ilegible"
  exit 0
fi

navori_role=$(nv_event_agent_type)
if [ -z "$navori_role" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="agent_type vacío (hilo principal)"
  exit 0
fi

block() {
  echo "[navori] BLOCKED by role-guard: $1" >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

# Spawn branch: BEFORE the role allow-list, so an `implementer` cannot dispatch
# a catch-all child either (challenge C2).
if nv_is_spawn_tool; then
  block "$navori_role no despacha subagentes (profundidad 1); el orquestador del hilo principal los lanza"
fi

if [ "$(nv_tool)" != "Edit" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="tool_name no cubierto"
  exit 0
fi

case "$navori_role" in
  implementer | scribe)
    navori_audit_verdict="skip"
    navori_audit_reason="rol exento"
    exit 0
    ;;
esac

# Prefixes the role may patch, one per line. The case is generated from
# `RosterAgent.writes`; nothing path-like is spelled in this asset.
nv_role_prefixes() {
{{rolePolicy}}
}

# Lexical normalization of an absolute path: drops `.` and empty segments and
# folds `..`. Written with parameter expansion only (no word splitting), so it
# behaves the same under bash and zsh.
nv_normalize() {
  local rest=${1#/} seg out=""
  while [ -n "$rest" ]; do
    case "$rest" in
      */*)
        seg=${rest%%/*}
        rest=${rest#*/}
        ;;
      *)
        seg=$rest
        rest=""
        ;;
    esac
    case "$seg" in
      "" | .) ;;
      ..) out=${out%/*} ;;
      *) out="$out/$seg" ;;
    esac
  done
  printf '%s' "${out:-/}"
}

# Physical form of an absolute normalized path: the nearest existing ancestor is
# resolved with `cd -P`, and the not-yet-existing tail is appended as written.
# Empty output means it could not be resolved.
nv_realdir() {
  local d=$1 suffix="" real parent
  while [ ! -e "$d" ] && [ ! -L "$d" ] && [ "$d" != "/" ]; do
    suffix="/${d##*/}$suffix"
    d=${d%/*}
    [ -n "$d" ] || d=/
  done
  if [ -d "$d" ]; then
    real=$(cd -P "$d" 2>/dev/null && pwd -P) || return 0
  else
    parent=${d%/*}
    [ -n "$parent" ] || parent=/
    real=$(cd -P "$parent" 2>/dev/null && pwd -P) || return 0
    real="${real%/}/${d##*/}"
  fi
  printf '%s' "${real%/}$suffix"
}

# Follow a leaf symlink chain (bounded) on top of `nv_realdir`.
nv_realpath() {
  local p=$1 n=0 target
  while :; do
    p=$(nv_realdir "$p")
    [ -n "$p" ] || return 0
    if [ -L "$p" ] && [ "$n" -lt 20 ]; then
      target=$(readlink "$p") || break
      case "$target" in
        /*) p=$(nv_normalize "$target") ;;
        *) p=$(nv_normalize "${p%/*}/$target") ;;
      esac
      n=$((n + 1))
    else
      break
    fi
  done
  printf '%s' "$p"
}

# 0 when the physical path sits under an OS temp root (resolved the same way, so
# `/tmp` -> `/private/tmp` and `$TMPDIR` -> `/private/var/folders/...` compare).
nv_in_temp() {
  local root real
  for root in /tmp /var/tmp "${TMPDIR:-}"; do
    [ -n "$root" ] || continue
    real=$(cd -P "$root" 2>/dev/null && pwd -P) || continue
    case "$1" in
      "${real%/}"/*) return 0 ;;
    esac
  done
  return 1
}

navori_cwd=$(payload_field cwd)
navori_cwd=${navori_cwd:-${nv_project_dir:-.}}
navori_root=$(cd -P "${nv_project_dir:-$navori_cwd}" 2>/dev/null && pwd -P) || navori_root=""
if [ -z "$navori_root" ]; then
  navori_audit_verdict="skip"
  navori_audit_reason="raíz del repo ilegible"
  exit 0
fi

navori_allowed=$(nv_role_prefixes "$navori_role")
navori_allowed_list=$(printf '%s' "$navori_allowed" | tr '\n' ' ')
navori_allowed_list=${navori_allowed_list% }

while IFS= read -r navori_path; do
  [ -n "$navori_path" ] || continue
  case "$navori_path" in
    /*) navori_abs=$(nv_normalize "$navori_path") ;;
    *) navori_abs=$(nv_normalize "$navori_cwd/$navori_path") ;;
  esac
  navori_real=$(nv_realpath "$navori_abs")
  if [ -z "$navori_real" ]; then
    block "$navori_role no escribe '$navori_path' (ruta no resoluble; permitido: $navori_allowed_list)"
  fi
  case "$navori_real" in
    "$navori_root"/*)
      navori_rel=${navori_real#"$navori_root"/}
      navori_ok=0
      while IFS= read -r navori_prefix; do
        [ -n "$navori_prefix" ] || continue
        navori_prefix=${navori_prefix%/}
        case "$navori_rel" in
          "$navori_prefix" | "$navori_prefix"/*)
            navori_ok=1
            break
            ;;
        esac
      done <<EOF
$navori_allowed
EOF
      if [ "$navori_ok" -ne 1 ]; then
        block "$navori_role no escribe '$navori_path' (permitido: $navori_allowed_list)"
      fi
      ;;
    "$navori_root")
      block "$navori_role no escribe '$navori_path' (permitido: $navori_allowed_list)"
      ;;
    *)
      if ! nv_in_temp "$navori_real"; then
        block "$navori_role no escribe '$navori_path' (fuera del repo; permitido: $navori_allowed_list)"
      fi
      ;;
  esac
done <<EOF
$(nv_edited_paths)
EOF

navori_audit_verdict="allow"
navori_audit_reason="rutas dentro del rol"
exit 0
