#!/usr/bin/env bash
#
# PostToolUse routing watcher (spec 0020, R2/R3).
#
# WHY THIS EXISTS. The routing ladder ships as CLAUDE.md context, and the host's
# own documentation says what that buys: "Claude treats them as context, NOT
# enforced configuration... If the instruction is something that must run at a
# specific point, write it as a hook instead." Measured over 48 audited
# sessions, 21 crossed the R2 threshold and 12 of those (57%) delegated nothing
# — including a session in this very repo that wrote 26 files with zero
# subagents while carrying the ladder in its context. Prose was not the missing
# piece; a mechanism at the moment of the decision is.
#
# WHAT IT DOES, and what it deliberately does NOT. It counts the distinct files
# written in a session, and the first time that count reaches the threshold with
# no subagent yet invoked it hands the model ONE advisory note through
# `hookSpecificOutput.additionalContext`. It never blocks: a `PreToolUse` deny
# could stop the fifth edit until something is delegated, and was rejected on
# two measured grounds — sometimes inline IS correct (an operator can forbid
# delegation outright, and a block would leave that session with no way out),
# and a mechanism that gets ignored erodes the authority of the ones that are
# obeyed. The note turns an invisible decision into an explicit one; that is the
# gap, not a prohibition.
#
# WHY `PostToolUse` AND NOT `UserPromptSubmit`. The threshold is crossed by an
# EDIT, not by a prompt. This fires immediately after the edit that crosses it,
# which is the moment of the decision; `UserPromptSubmit` fires before the model
# has done anything that turn, i.e. at the wrong time.
#
# WHY THE THRESHOLD IS "4 DISTINCT FILES" AND NOT THE FULL R2 RULE. R2 reads
# "4+ files; or the change touches 2+ non-trivial files". "Non-trivial" is a
# judgement about the CONTENT of a diff, and a hook cannot make it without
# guessing. So this takes the objective half. A hook that guesses is noise, and
# noise is what erodes.
#
# WHY IT DOES NOT TRY TO TELL THE MAIN THREAD FROM A SUBAGENT — this is what
# keeps the script small. The condition is "N files AND zero delegation": if a
# subagent wrote something, then delegation happened, and the condition is
# already false by its second half. Over-counting is harmless by construction.
# It matters because the `PostToolUse` payload carries NO agent identifier (the
# `agentId` the audit log writes is really the `cwd`), so the alternative would
# have been an invented heuristic.
#
# FAIL-OPEN, ALWAYS. Every path exits 0, including "cannot read or write the
# stamp" (read-only FS, odd $HOME). A `PostToolUse` hook runs after tool calls
# all session long; failing loudly there is worse than not warning at all. Note
# the deliberate absence of `-e` in the `set` line below.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# Payload extraction (stdin → `payload` + `payload_field`). Shared body, single
# source of truth: the jq → node → sed cascade exists because jq is NOT
# preinstalled on macOS, and four hand-synced copies of it is how #225/#261
# drifted. The partial defines `extract_cmd` but does NOT call it: this hook
# never reads `tool_input.command`, and a spawn it cannot use would be charged to
# every tool call in every session.
#
# ORDER BELOW IS A COST DECISION, and these are the counts it buys. Every
# `payload_field` call may spawn a process, so nothing is read before the field
# that can end the run:
#   1 spawn  — any tool that is not Edit/Write/NotebookEdit/Agent: `tool_name`
#              alone, and the discard `case` exits.
#   2 spawns — a session already `#delegated` or `#notified`: + `session_id`,
#              which is what names the stamp, and the stamp check exits.
#   4 spawns — an edit that actually counts: + `agent_id` (the subagent guard
#              below) + the file path.
# The discard `case` therefore comes BEFORE `session_id`: a tool this hook does
# not care about must not pay to locate a stamp it will never open.
# navori:include extract-cmd

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# The objective half of R2 (see the header). Changing this number changes when
# the note fires and nothing else.
threshold=4

tool=$(payload_field tool_name)
[ -n "$tool" ] || exit 0

# The cheap discriminator, and the only thing read so far. Anything this hook has
# no business with leaves here, having spawned exactly once.
case "$tool" in
  Agent | Task | Edit | Write | NotebookEdit) ;;
  *) exit 0 ;;
esac

# One stamp per session, so two concurrent sessions never overwrite each other's
# count. Sanitised because the value lands in a path: anything that is not a
# plain identifier character is dropped rather than escaped.
sid=$(payload_field session_id | tr -cd 'A-Za-z0-9._-')
[ -n "$sid" ] || sid="unknown-session"

stamp_dir=".claude/.routing-watch"
stamp="$stamp_dir/$sid"

# Append a line unless it is already there. Silent on every failure: a stamp
# that cannot be written means no note, never an error.
mark() {
  mkdir -p "$stamp_dir" 2>/dev/null || return 0
  # First write of THIS session's stamp: sweep siblings older than 7 days.
  # One `find` over a tiny dir, once per session — without it the directory
  # grows by one file per session forever (no SessionEnd hook owns it). Age,
  # not session-end, on purpose: `--resume` reuses the session id, and a
  # delete-on-end would re-arm the once-per-session notice on every resume.
  [ -e "$stamp" ] || find "$stamp_dir" -type f -mtime +7 -delete 2>/dev/null || true
  grep -q -F -x "$1" "$stamp" 2>/dev/null && return 0
  printf '%s\n' "$1" >> "$stamp" 2>/dev/null || true
}

case "$tool" in
  # Delegation happened. `Agent` is the name this host gives the subagent tool
  # (the same string `lib/audit/parse.ts` filters transcripts by); `Task` is
  # accepted too so a rename does not silently turn the detector off.
  Agent | Task)
    mark "#delegated"
    exit 0
    ;;
esac

# Delegated, or already warned: there is nothing left to decide this session.
# This is also the guarantee behind "at most once" — the stamp survives a
# compaction, so a note that scrolled out of context is NOT re-emitted.
# Repeating is what turns a signal into noise.
grep -q -E '^#(delegated|notified)$' "$stamp" 2>/dev/null && exit 0

# Hooks run INSIDE subagents too — the host fires the same PostToolUse for a
# subagent's tool calls, adding `agent_id` to the payload (empty in the main
# conversation). And the `#delegated` mark from the `Agent` case above only
# lands when that tool RETURNS, i.e. after the subagent already finished. So
# without this check a delegated implementer's own 4th edit would fire the
# notice INTO THE SUBAGENT'S context — "no subagent has been invoked" is false
# there, the advice is unactionable there (no Agent tool in its allowlist) —
# and would burn the once-per-session note before the orchestrator could ever
# receive it. An edit arriving from inside a subagent IS proof of delegation,
# so it is recorded as exactly that.
agent=$(payload_field agent_id)
if [ -n "$agent" ]; then
  mark "#delegated"
  exit 0
fi

file=$(payload_field tool_input.file_path)
# NotebookEdit has carried its target under `notebook_path` in some host
# versions; without this the tool would contribute nothing and never say so.
[ -n "$file" ] || file=$(payload_field tool_input.notebook_path)
[ -n "$file" ] || exit 0

mark "path:$file"

count=$(grep -c '^path:' "$stamp" 2>/dev/null) || count=0
[ "${count:-0}" -ge "$threshold" ] 2>/dev/null || exit 0

mark "#notified"

# Written with no `"` and no `\` on purpose: that is what makes the JSON
# escaping below exact without a JSON encoder (see the awk join).
notice=$(cat <<MSG
navori: routing check. ${count} distinct files written in this session, and no subagent has been invoked.

R2 of the routing ladder fires at 4+ files: 1 focused implementer (explicit scope) then 1 reviewer, instead of writing them all inline.

If inline IS the right call here (the operator ruled delegation out, the edits are one mechanical change, the context is already paid for), say so explicitly in your next message and carry on. The point of this note is that the override stops being silent - today it leaves no trace at all.

Advisory only: nothing was blocked, and this fires at most once per session.
MSG
)

# JSON-escape by joining the lines with a literal backslash-n. Exact because the
# text above is a fixed literal free of quotes and backslashes; a payload from
# outside would need a real encoder.
escaped=$(printf '%s\n' "$notice" | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }')
printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"%s"}}\n' "$escaped"

# The last word of the script, and the contract of the whole file: advisory.
exit 0
