#!/usr/bin/env bash
#
# PostToolUse routing watcher (spec 0020).
#
# WHY THIS EXISTS. The routing ladder ships as CLAUDE.md context, and the host's
# own documentation says what that buys: "Claude treats them as context, NOT
# enforced configuration... If the instruction is something that must run at a
# specific point, write it as a hook instead." Measured over 48 audited
# sessions, 21 crossed the delegation threshold of the day and 12 of those (57%) delegated nothing
# — including a session in this very repo that wrote 26 files with zero
# subagents while carrying the ladder in its context. Prose was not the missing
# piece; a mechanism at the moment of the decision is.
#
# WHAT IT DOES, and what it deliberately does NOT. It counts the distinct files
# written in a session, and the first time that count reaches the threshold with
# no subagent yet invoked it hands the model ONE advisory note through
# `hookSpecificOutput.additionalContext`. It never blocks: a `PreToolUse` deny
# could stop the fifth edit until something is delegated, and was rejected on
# two measured grounds — sometimes inline IS correct (an operator can forbid
# delegation outright, and a block would leave that session with no way out),
# and a mechanism that gets ignored erodes the authority of the ones that are
# obeyed. The note turns an invisible decision into an explicit one; that is the
# gap, not a prohibition.
#
# WHY `PostToolUse` AND NOT `UserPromptSubmit`. The threshold is crossed by an
# EDIT, not by a prompt. This fires immediately after the edit that crosses it,
# which is the moment of the decision; `UserPromptSubmit` fires before the model
# has done anything that turn, i.e. at the wrong time.
#
# WHY THE THRESHOLD IS STILL "4 DISTINCT FILES". It was the objective half of a
# routing rule that has since been withdrawn — the ladder it belonged to had its
# threshold written in seven places that did not agree, so it was collapsed to a
# single route: every change to source goes through implementer -> reviewer.
#
# Under one route the honest threshold is ONE file, not four. What it counts is
# now right — repo-relative, and only paths that carry behavior, from the same
# definition the miner and the pilot use — but the NUMBER stays at four until the
# ruling returns, because lowering it is a decision about how loud this should
# be, not about what it measures. Meanwhile 4-and-no-delegation catches the worst
# deviations and stays quiet on the rest.
#
# WHY IT DOES NOT TRY TO TELL THE MAIN THREAD FROM A SUBAGENT — this is what
# keeps the script small. The condition is "N files AND zero delegation": if a
# subagent wrote something, then delegation happened, and the condition is
# already false by its second half. Over-counting is harmless by construction.
# It matters because the `PostToolUse` payload carries NO agent identifier (the
# `agentId` the audit log writes is really the `cwd`), so the alternative would
# have been an invented heuristic.
#
# FAIL-OPEN, ALWAYS. Every path exits 0, including "cannot read or write the
# stamp" (read-only FS, odd $HOME). A `PostToolUse` hook runs after tool calls
# all session long; failing loudly there is worse than not warning at all. Note
# the deliberate absence of `-e` in the `set` line below.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# Payload extraction (stdin → `payload` + `payload_field`). Shared body, single
# source of truth: the jq → node → sed cascade exists because jq is NOT
# preinstalled on macOS, and four hand-synced copies of it is how #225/#261
# drifted. The partial defines `extract_cmd` but does NOT call it: this hook
# never reads `tool_input.command`, and a spawn it cannot use would be charged to
# every tool call in every session.
#
# ORDER BELOW IS A COST DECISION, and these are the counts it buys. Every
# `payload_field` call may spawn a process, so nothing is read before the field
# that can end the run:
#   1 spawn  — any tool that is not Edit/Write/NotebookEdit/Agent: `tool_name`
#              alone, and the discard `case` exits.
#   2 spawns — a session already `#delegated` or `#notified`: + `session_id`,
#              which is what names the stamp, and the stamp check exits.
#   4 spawns — an edit that actually counts: + `agent_id` (the subagent guard
#              below) + the file path.
# The discard `case` therefore comes BEFORE `session_id`: a tool this hook does
# not care about must not pay to locate a stamp it will never open.
# navori:include extract-cmd

# R5 (spec 0020): the notice has to be COUNTABLE, not just visible. A hook is
# invisible to the transcript unless it blocks or injects, and this one injects
# exactly once per session — so without a record in the audit log there is no
# way to ask "how often did the ladder actually fire, and did delegation follow?"
# That question is the whole success criterion of the spec, and #623 is the
# standing proof that "the hook emitted it" and "the model got it" are different
# claims: the log is what lets the transcript be read back against the emission.
#
# ONLY the notify path records. This hook fires on every write tool of every
# session; recording each firing would bloat the log with the one verdict nobody
# asked about. One line per session, on the event that matters.
navori_audit_name="routing-watch"
navori_audit_phase="PostToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# Same reason as in `managed-drift-watch`: a raw, unexpanded copy of this asset
# must degrade to silence, never to exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-log
navori_audit_begin

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# See the header for why this is still 4 and not 1. Changing this number changes when
# the note fires and nothing else.
threshold=4

tool=$(payload_field tool_name)
[ -n "$tool" ] || exit 0
navori_audit_tool=$tool

# The cheap discriminator, and the only thing read so far. Anything this hook has
# no business with leaves here, having spawned exactly once.
case "$tool" in
  Agent | Task | Edit | Write | NotebookEdit) ;;
  *) exit 0 ;;
esac

# One stamp per session, so two concurrent sessions never overwrite each other's
# count. Sanitised because the value lands in a path: anything that is not a
# plain identifier character is dropped rather than escaped.
sid=$(payload_field session_id | tr -cd 'A-Za-z0-9._-')
[ -n "$sid" ] || sid="unknown-session"

stamp_dir=".claude/.routing-watch"
stamp="$stamp_dir/$sid"

# Append a line unless it is already there. Silent on every failure: a stamp
# that cannot be written means no note, never an error.
mark() {
  mkdir -p "$stamp_dir" 2>/dev/null || return 0
  # First write of THIS session's stamp: sweep siblings older than 7 days.
  # One `find` over a tiny dir, once per session — without it the directory
  # grows by one file per session forever (no SessionEnd hook owns it). Age,
  # not session-end, on purpose: `--resume` reuses the session id, and a
  # delete-on-end would re-arm the once-per-session notice on every resume.
  [ -e "$stamp" ] || find "$stamp_dir" -type f -mtime +7 -delete 2>/dev/null || true
  grep -q -F -x "$1" "$stamp" 2>/dev/null && return 0
  printf '%s\n' "$1" >> "$stamp" 2>/dev/null || true
}

case "$tool" in
  # Delegation happened. `Agent` is the name this host gives the subagent tool
  # (the same string `lib/audit/parse.ts` filters transcripts by); `Task` is
  # accepted too so a rename does not silently turn the detector off.
  Agent | Task)
    mark "#delegated"
    exit 0
    ;;
esac

# Delegated, or already warned: there is nothing left to decide this session.
# This is also the guarantee behind "at most once" — the stamp survives a
# compaction, so a note that scrolled out of context is NOT re-emitted.
# Repeating is what turns a signal into noise.
grep -q -E '^#(delegated|notified)$' "$stamp" 2>/dev/null && exit 0

# Hooks run INSIDE subagents too — the host fires the same PostToolUse for a
# subagent's tool calls, adding `agent_id` to the payload (empty in the main
# conversation). And the `#delegated` mark from the `Agent` case above only
# lands when that tool RETURNS, i.e. after the subagent already finished. So
# without this check a delegated implementer's own 4th edit would fire the
# notice INTO THE SUBAGENT'S context — "no subagent has been invoked" is false
# there, the advice is unactionable there (no Agent tool in its allowlist) —
# and would burn the once-per-session note before the orchestrator could ever
# receive it. An edit arriving from inside a subagent IS proof of delegation,
# so it is recorded as exactly that.
agent=$(payload_field agent_id)
if [ -n "$agent" ]; then
  mark "#delegated"
  exit 0
fi

# Clause (a) of "non-trivial source file", generated from the single TypeScript
# definition (`lib/source-classify.ts`). Inlined rather than called: this hook
# runs on EVERY PostToolUse, and `navori_is_source` is `[[ =~ ]]` — a builtin, so
# classifying a path costs no process.
# navori:include classify-source

file=$(payload_field tool_input.file_path)
# NotebookEdit has carried its target under `notebook_path` in some host
# versions; without this the tool would contribute nothing and never say so.
[ -n "$file" ] || file=$(payload_field tool_input.notebook_path)
[ -n "$file" ] || exit 0

# Repo-relative, or not counted at all. The hook `cd`s to CLAUDE_PROJECT_DIR
# above, so $PWD is the repo root.
#
# Without this the count included files that reach no diff: a scratch script
# under /tmp, another repo's file opened in the same session. Measured on the
# park, 13.4% of what the activation miner called "source writes" were exactly
# that — and this hook had the same hole, so its notice could fire on a session
# that had written nothing but scaffolding.
case $file in
  "$PWD"/*) file=${file#"$PWD"/} ;;
  /*) exit 0 ;;
esac

# And only what carries behavior. A render that rewrites 45 mirror files is not
# a change anyone should delegate, and counting it as four was how this notice
# could fire on a release.
navori_is_source "$file" || exit 0

mark "path:$file"

count=$(grep -c '^path:' "$stamp" 2>/dev/null) || count=0
[ "${count:-0}" -ge "$threshold" ] 2>/dev/null || exit 0

mark "#notified"
navori_audit_log "notify" "$count archivos del hilo principal, sin subagente"

# Written with no `"` and no `\` on purpose: that is what makes the JSON
# escaping below exact without a JSON encoder (see the awk join).
notice=$(cat <<MSG
navori: routing check. ${count} distinct files written in this session, and no subagent has been invoked.

Every change to source goes through 1 focused implementer (explicit scope) then 1 reviewer — there is no inline route and no file count that exempts one.

If inline IS the right call here (the operator ruled delegation out, the edits are one mechanical change, the context is already paid for), say so explicitly in your next message and carry on. The point of this note is that the override stops being silent - today it leaves no trace at all.

Advisory only: nothing was blocked, and this fires at most once per session.
MSG
)

# JSON-escape by joining the lines with a literal backslash-n. Exact because the
# text above is a fixed literal free of quotes and backslashes; a payload from
# outside would need a real encoder.
escaped=$(printf '%s\n' "$notice" | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }')
printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"%s"}}\n' "$escaped"

# The last word of the script, and the contract of the whole file: advisory.
exit 0
