#!/usr/bin/env bash
#
# Stop lifecycle hook — verify-before-done reminder (P4).
# Fires when the main agent finishes a turn. Its job is to nudge — NOT block —
# when the session is winding down with uncommitted work, so "I'm done" isn't
# claimed before the quality gate ran and the change is committed.
#
# DESIGN — advisory, never blocking. It NEVER returns `decision: block`, so it
# can't trap the model in a "keep working" loop or force a turn the user didn't
# ask for. A hard, deterministic "did the model actually run
# verify-before-done?" gate is not reliably knowable from a shell hook (the
# model's intent isn't in the payload), so we intentionally downgrade to a
# reminder — see the PR for the rationale.
#
# TWO CHANNELS, and they are not redundant (#774). The reminder asks the MODEL
# for an action ("run the quality gate, then commit"), and `systemMessage` is
# documented as a "Warning message shown to the user" — on its own it reached
# the human's UI and nobody else, so the one reader that could act on it never
# heard it. `Stop` is one of the events that does have a channel to the model:
# "Stop and SubagentStop also accept `hookSpecificOutput.additionalContext` for
# non-error feedback that continues the conversation". So both go out in a
# single emission: `additionalContext` for the agent, `systemMessage` for the
# human. Neither blocks.
#
# OPT-IN. This hook is only wired into settings.json when
# `hooks.verifyOnStop` is true in navori.config.json (mirrors how
# `qualityGate.fast` gates the quality-gate hook). It stays OFF by default
# because a per-turn reminder can be noisy during active development; a repo
# that wants the nudge turns it on explicitly.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

# The payload was drained and discarded here; it is kept now because the audit
# recorder reads `session_id`/`cwd` out of it. Draining is still the point: an
# undrained stdin can leave the host writing into a closed pipe.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="stop-verify-reminder"
navori_audit_phase="Stop"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


# Only meaningful inside a git repo.
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

# Hard evidence that work is unfinished: tracked files changed but not committed
# (staged or unstaged). Untracked files alone don't count — scratch/output files
# are common and shouldn't trigger the nudge.
if git diff --quiet --ignore-submodules HEAD 2>/dev/null; then
  navori_audit_verdict="noop"
  navori_audit_reason="arbol limpio: nada que recordar"
  exit 0
fi

msg="navori: cambios sin commitear en el árbol. Antes de dar la tarea por terminada, corre el quality gate (evidencia fresca este turno) y haz commit — verify-before-done (P4)."

# Emit the advisory on both channels at once (see "TWO CHANNELS" above).
# node (Claude Code's own runtime) → jq → give up silently. Neither field is a
# decision, so this stays non-blocking by contract.
if command -v node >/dev/null 2>&1; then
  MSG="$msg" node -e 'process.stdout.write(JSON.stringify({systemMessage:process.env.MSG,hookSpecificOutput:{hookEventName:"Stop",additionalContext:process.env.MSG}}))'
elif command -v jq >/dev/null 2>&1; then
  jq -n --arg m "$msg" '{systemMessage:$m,hookSpecificOutput:{hookEventName:"Stop",additionalContext:$m}}'
fi
navori_audit_verdict="inject"
navori_audit_reason="cambios sin commitear"
exit 0
