#!/usr/bin/env bash
#
# PostToolUse(`Agent`|`Task`) lifecycle hook — handoff validator.
# Fires in the PARENT session the moment a subagent returns. The harness contract
# is that an implementer closes with `impl_<feature>.md` and a reviewer with
# `review_<feature>.md` under the engine's progress dir — those files ARE the
# handoff the orchestrator (and the publisher) read. A subagent that returns
# having left an empty or structurally-broken handoff silently corrupts that
# chain. This hook catches the obvious failure modes deterministically.
#
# WHY NOT SubagentStop, the event this hook is still NAMED after (#774). The
# reader of this note is the ORCHESTRATOR, and SubagentStop cannot reach it: there the
# `additionalContext` goes to the subagent that just stopped — it keeps that
# child running — and the host's doc names the alternative outright, "to inject
# context into the parent session after a subagent returns, use a `PostToolUse`
# hook on the `Agent` tool instead". Registered on SubagentStop the only channel
# left was `systemMessage`, which the doc defines as a "warning message shown to
# the user", so a note written in the imperative to the model arrived at the
# human's UI and nowhere else.
#
# The move also settles the firing rate #560 measured: SubagentStop fired 117
# times for 19 subagents in one session, each firing re-reporting the identical
# handoff. A PostToolUse on the Agent tool fires exactly once per return.
#
# The id and the filename keep the old spelling on purpose: they are a managed
# marker stamped into every already-rendered repo and the name the audit log has
# recorded under for a year of sessions. Renaming them would buy tidiness and
# cost the continuity of the measurement.
#
# DESIGN — advisory, never blocking. Emits `hookSpecificOutput.additionalContext`
# for the orchestrator plus a `systemMessage` so the human sees it too; it NEVER
# returns `decision: block`.
#
# Since spec 0030 (#985, R10) it reads `tool_input.subagent_type` — the
# Agent/Task tool call's OWN parameter, mirrored into every PreToolUse/PostToolUse
# payload (https://code.claude.com/docs/en/hooks.md: "payload carries `tool_name`,
# `tool_input`, `session_id`, `cwd`"). This is NOT the `agent_id`/`agent_type` pair
# the same doc says is "present only when the hook fires inside a subagent call" —
# that pair answers "am I running INSIDE a subagent", a question this hook (firing
# on the PARENT's own PostToolUse(Agent|Task)) never needs to ask. `subagent_type`
# is simply the argument the orchestrator passed to dispatch, so it is present on
# this exact event regardless of nesting. So the hook now knows WHICH subagent
# just returned and demands the matching contract:
#   - `implementer` → `impl_*.json` (R2): missing, unparseable, a `status` other
#     than `DONE`/`BLOCKED`, or any required key absent.
#   - `scribe` → `impl_*.md` missing its terminal `Status:` marker.
#   - anything else — another role, another engine, or a payload where the field
#     is absent — falls back to checking BOTH shapes wherever a matching file
#     exists. That is the identity-blind behavior this hook always had, kept as
#     the safety net for what `subagent_type` doesn't cover.
# It also always flags, regardless of identity:
#   - empty / whitespace-only handoffs, OR
#   - `review_*.md` missing a verdict (APPROVED / CHANGES_REQUESTED).
# It never invents an expectation, so a legitimate report never trips it, and a
# missing file is not flagged (a subagent may not produce a handoff at all).
# Accepted limitation: during parallel work a still-in-flight report from
# ANOTHER running subagent could momentarily look incomplete — advisory-only, so
# a false positive is a harmless note, never a block.
#
# Spec 0039 R44 adds a second, independent lane: compaction advice (Claude only,
# main thread, after a `publisher` dispatch). It shares this hook's single output
# because one firing may carry at most one JSON document.
#
# The managed block is regenerated by `navori render`; do NOT edit by hand.
set -euo pipefail

# The payload was drained and discarded here; it is kept now because the audit
# recorder reads `session_id`/`cwd` out of it. Draining is still the point: an
# undrained stdin can leave the host writing into a closed pipe.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="subagent-stop-handoff"
navori_audit_phase="PostToolUse"

# Where the problem set last REPORTED in this session is remembered (#560).
#
# The 117-firings-for-19-subagents problem this was written for is gone: on
# PostToolUse(`Agent`) the host fires once per return (#774). The stamp STAYS,
# and the move is what makes it matter more rather than less. A broken handoff
# stays broken until somebody fixes it, so without this every later subagent
# return in the same session re-reports it — and the note now travels through
# `additionalContext`, i.e. it is spent out of the orchestrator's context window, not
# out of a UI line the host draws for free.
#
# Parsed with parameter expansion, never jq: this must work whether or not
# audit-mode is on, and jq may not exist. Keyed by session AND repo so two
# sessions never silence each other. In the OS temp dir, so nothing lands in the
# user's tree and a reboot is a clean slate.
# A raw, unexpanded asset must remain advisory rather than exiting 127.
# Rendered includes replace these no-ops with the shared Spec 0035 adapter.
payload_field() { :; }
nv_subagent_type() { :; }
# navori:include extract-cmd
# navori:include hook-input
navori_handoff_key=$(payload_field session_id)
case "$navori_handoff_key" in
  "" | *[!A-Za-z0-9_-]*) navori_handoff_key="anon" ;;
esac
navori_handoff_repo=${PWD##*/}
case "$navori_handoff_repo" in
  "" | *[!A-Za-z0-9_.-]*) navori_handoff_repo="repo" ;;
esac
navori_handoff_stamp="${TMPDIR:-/tmp}/navori-handoff-$navori_handoff_repo-$navori_handoff_key"

# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


# Resolve the neutral handoff root plus the two one-release legacy roots.
# `placeHook` copies this body verbatim for every engine, so no engine-specific
# retargeting is involved. Bare `progress/` remains a historical fallback.
#
# EVERY existing dir is scanned, not the first one found: a repo that renders
# both engines has both, and picking one by probe order would make the hook
# blind to whichever engine happens to come second. An ARRAY, never an unquoted
# string: word-splitting a `$dirs` string is a no-op under zsh, which is how the
# receipt backstop silently stopped scanning (#344).
dirs=()
for d in ".navori/state/handoffs" ".claude/progress" ".codex/progress" "progress"; do
  [ -d "$d" ] && dirs+=("$d")
done

# Is a file empty or whitespace-only?
is_blank() { ! grep -q '[^[:space:]]' "$1" 2>/dev/null; }

problems=""
# Spec 0039 R26: the stamp identifies a report by (path, content), not by the
# problem text alone. `navori_fingerprint` accumulates one POSIX `cksum` of each
# flagged file (`$f`, set by every caller before `note`), so the SAME handoff
# reported twice is one warning, while a rewrite that still has the same problem
# is news and warns again. `cksum` reads the file once, no fork beyond itself.
navori_fingerprint=""
note() {
  problems="${problems}${problems:+; }$1"
  navori_fingerprint="${navori_fingerprint}$(cksum <"${f:-/dev/null}" 2>/dev/null | tr ' ' '-');"
}

# Spec 0035 D2 owns Claude/Codex subagent normalization and the single stdin
# drain through extract-cmd; this hook must not grow a second payload parser.
navori_subagent_type=$(nv_subagent_type)

# Spec 0039 R42: only the parent's foreground PostToolUse(Agent) response
# carries the host's turn-limit marker. A missing handoff is not evidence of
# truncation, and background/SendMessage completions do not reach this event.
navori_partial_msg=""
if [ "${1:-}" != "codex" ] && [ "${nv_engine:-claude}" != "codex" ] &&
  [ -z "$(payload_field agent_id)" ] &&
  [[ "$payload" == *"stopped at its "* ]] && command -v node >/dev/null 2>&1; then
  navori_partial_found=$(printf '%s' "$payload" | node -e '
    let event;
    try { event = JSON.parse(require("fs").readFileSync(0, "utf8")); } catch { process.exit(0); }
    if (event.hook_event_name !== "PostToolUse" || event.tool_name !== "Agent" ||
        event.tool_input?.run_in_background === true) process.exit(0);
    const content = event.tool_response?.content;
    if (Array.isArray(content) && content.some((item) =>
      item?.type === "text" && typeof item.text === "string" &&
      /\bstopped at its \d+-turn limit\b/.test(item.text))) process.stdout.write("yes");
  ' 2>/dev/null) || navori_partial_found=""
  if [ "$navori_partial_found" = "yes" ]; then
    navori_partial_msg="navori: handoff PARCIAL de ${navori_subagent_type:-subagente} — alcanzó su límite de turnos. Continúa con SendMessage para conservar su estado; usa un redespacho fresco solo si el trabajo restante está acotado."
  fi
fi

# Spec 0039 R44 — compaction advice lane. Claude mode only (Codex has no
# PostToolUse context channel), main thread only (`agent_id` is present just
# inside a subagent) and only when the dispatch that returned is the `publisher`:
# the end of a cycle is the cheap moment to compact. `usage` comes from the LAST
# COMPLETE transcript line in a 256 KB tail (the writer may be mid-line, and the
# tail's first line is cut by construction), so unparseable lines are skipped.
# The threshold is `harness.compactAdviceTokens`; an unrendered or non-numeric
# value (harness section absent) falls back to 175000, `0` turns the lane off.
navori_compact_msg=""
navori_compact_threshold={{shq:harness.compactAdviceTokens}}
case "$navori_compact_threshold" in
  "" | *[!0-9]*) navori_compact_threshold=175000 ;;
esac
navori_compact_mark="${TMPDIR:-/tmp}/navori-compact-$navori_handoff_repo-$navori_handoff_key"
navori_compact_done=""
{ IFS= read -r navori_compact_done <"$navori_compact_mark"; } 2>/dev/null ||
  navori_compact_done=""
if [ "${1:-}" != "codex" ] && [ "${nv_engine:-claude}" != "codex" ] &&
  [ "$navori_compact_threshold" -gt 0 ] && [ "$navori_subagent_type" = "publisher" ] &&
  [ -z "$(payload_field agent_id)" ] && [ -z "$navori_compact_done" ] &&
  command -v node >/dev/null 2>&1; then
  navori_compact_tp=$(payload_field transcript_path)
  navori_compact_total=""
  if [ -n "$navori_compact_tp" ]; then
    navori_compact_total=$(tail -c 262144 "$navori_compact_tp" 2>/dev/null | node -e '
      const lines = require("fs").readFileSync(0, "utf-8").split("\n");
      for (let i = lines.length - 1; i >= 0; i--) {
        let o;
        try { o = JSON.parse(lines[i]); } catch { continue; }
        const u = (o && o.message && o.message.usage) || (o && o.usage);
        if (!u || typeof u !== "object") continue;
        const n = (k) => (typeof u[k] === "number" ? u[k] : 0);
        process.stdout.write(String(n("input_tokens") + n("cache_read_input_tokens") + n("cache_creation_input_tokens")));
        break;
      }
    ' 2>/dev/null) || navori_compact_total=""
  fi
  case "$navori_compact_total" in
    "" | *[!0-9]*) ;;
    *)
      if [ "$navori_compact_total" -gt "$navori_compact_threshold" ]; then
        navori_compact_msg="navori: el contexto del hilo principal va en ${navori_compact_total} tokens (umbral ${navori_compact_threshold}). Guarda el resumen de la sesión y usa /compact o /clear antes del siguiente ciclo."
      fi
      ;;
  esac
fi

# R2's contract: `impl_<feature>.json` must parse and carry every required key
# with a valid `status`. Validated with node (already required by navori) → a
# grep-based key sweep when it is missing, same fail-open posture as the rest
# of this file: no new dependency, and an unparseable environment still gets a
# best-effort check instead of silence.
navori_check_impl_json() {
  f="$1"
  if is_blank "$f"; then
    note "$f vacío"
    return
  fi
  if command -v node >/dev/null 2>&1; then
    navori_json_verdict=$(node -e '
      const fs = require("fs");
      let data;
      try {
        data = JSON.parse(fs.readFileSync(process.argv[1], "utf-8"));
      } catch {
        process.stdout.write("parse");
        process.exit(0);
      }
      const required = ["feature","status","worktree","branch","commits","filesTouched","verification","markdownRequests"];
      const missing = required.filter((k) => !(k in data));
      if (missing.length > 0) {
        process.stdout.write("missing:" + missing.join(","));
        process.exit(0);
      }
      if (data.status !== "DONE" && data.status !== "BLOCKED") {
        process.stdout.write("status");
        process.exit(0);
      }
      process.stdout.write("ok");
    ' "$f" 2>/dev/null) || navori_json_verdict="parse"
  else
    navori_json_verdict="ok"
    navori_json_missing=""
    for navori_json_key in feature status worktree branch commits filesTouched verification markdownRequests; do
      grep -q "\"$navori_json_key\"[[:space:]]*:" "$f" 2>/dev/null \
        || navori_json_missing="${navori_json_missing}${navori_json_missing:+,}$navori_json_key"
    done
    if [ -n "$navori_json_missing" ]; then
      navori_json_verdict="missing:$navori_json_missing"
    elif ! grep -qE '"status"[[:space:]]*:[[:space:]]*"(DONE|BLOCKED)"' "$f" 2>/dev/null; then
      navori_json_verdict="status"
    fi
  fi
  case "$navori_json_verdict" in
    ok) ;;
    parse) note "$f no parsea como JSON" ;;
    status) note "$f con 'status' inválido (no DONE/BLOCKED)" ;;
    missing:*) note "$f sin clave '${navori_json_verdict#missing:}'" ;;
    *) note "$f no parsea como JSON" ;;
  esac
}

# R10's `scribe` half: same `Status:` check R5's `.md` handoff always had.
navori_check_impl_md() {
  f="$1"
  if is_blank "$f"; then
    note "$f vacío"
  elif ! grep -qiE '^\*{0,2}status:?\*{0,2}' "$f" 2>/dev/null; then
    note "$f sin línea 'Status:'"
  fi
}

# Only handoffs touched inside this window are checked (48h in minutes).
#
# The hook fires as a subagent returns, so the handoff it exists to police is
# the one just written. It used to check the WHOLE directory, which nothing prunes, and
# that broke it three ways on every repo measured (#606):
#
#   1. Handoffs written under an older format failed forever — 44 files in one
#      repo, 19 in another. The `clean` verdict this script calls "the whole
#      value of recording this hook" was unreachable in all four.
#   2. The stamp compares the full problem string, so a genuinely broken new
#      handoff injected N+1 paths (44 of them from August in one repo) and
#      fixing it re-injected the N old ones. The real warning arrived buried.
#   3. Two greps per file, unbounded: the median run tracked the file count
#      almost linearly — 46 files/165ms, 57/197ms, 80/333ms, 138/419ms — making
#      this the most expensive hook of the six, the other five sitting at
#      16-59ms.
#
# 48h and not less because a session can be long (10h41m measured) and a handoff
# written early in one must still be checked when it ends. Everything older is
# closed work: PRs in the repo this was measured on merge in under 10 hours,
# p90 8.5h.
HANDOFF_WINDOW_MIN=2880

# `find` replaces the globs rather than filtering inside them: it does the
# selection in ONE fork per directory instead of two greps per stale file, which
# is the cost above. Read through `while read` (not `$(...)` word-splitting) so
# a path with spaces survives, and via process substitution so `note` writes to
# the real `problems` and not to a subshell's copy.
#
# Reports are named by their PATH, not their basename: with more than one
# progress dir in play, `impl_x.md` alone wouldn't say which one to open.
#
# Which shape gets checked is now gated on `$navori_subagent_type` (R10): the
# `implementer` only ever produces `.json` under R2, the `scribe` only `.md`
# under R5, and everyone else (or a payload the field never reached) falls back
# to checking whichever of the two exists — the identity-blind behavior this
# hook always had.
# An empty `dirs` is no longer an early exit: the compaction lane above does
# not depend on any handoff directory existing. Guarded, not iterated blindly,
# because expanding an empty array under `set -u` fails on bash < 4.4.
for dir in ${dirs[@]+"${dirs[@]}"}; do
  case "$navori_subagent_type" in
    implementer)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_json "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.json' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
    scribe)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_md "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
    *)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_json "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.json' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      while IFS= read -r f; do
        [ -n "$f" ] || continue
        navori_check_impl_md "$f"
      done < <(find "$dir" -maxdepth 1 -name 'impl_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
      ;;
  esac
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    if is_blank "$f"; then
      note "$f vacío"
    elif ! grep -qE 'APPROVED|CHANGES_REQUESTED' "$f" 2>/dev/null; then
      note "$f sin veredicto (APPROVED/CHANGES_REQUESTED)"
    fi
  done < <(find "$dir" -maxdepth 1 -name 'review_*.md' -mmin -"$HANDOFF_WINDOW_MIN" 2>/dev/null)
done

# `clean` vs `dirty` is the whole value of recording this hook: it is the only
# evidence that the handoff check RAN and found nothing, as opposed to never
# having run at all.
#
# One firing, one JSON document: the handoff warning and the compaction advice
# (R44) are emitted separately by exactly one path each, never both. A repeat or
# clean handoff still lets the compaction advice through; a NEW handoff warning
# carries the advice appended to its own message. `navori_emit` returns 0 only
# when the document was written, so neither the handoff stamp nor the
# once-per-session compaction mark records an undelivered warning.
navori_mode="${1:-}"
navori_emit() {
  local m="$1" out=""
  if command -v node >/dev/null 2>&1; then
    out=$(MSG="$m" node -e 'const m=process.env.MSG;process.stdout.write(JSON.stringify(process.argv[1]==="codex"?{systemMessage:m}:{systemMessage:m,hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:m}}))' "$navori_mode" 2>/dev/null) || out=""
  fi
  if [ -z "$out" ] && command -v jq >/dev/null 2>&1; then
    if [ "$navori_mode" = "codex" ]; then
      out=$(jq -n --arg m "$m" '{systemMessage:$m}' 2>/dev/null) || out=""
    else
      out=$(jq -n --arg m "$m" '{systemMessage:$m,hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$m}}' 2>/dev/null) || out=""
    fi
  fi
  [ -n "$out" ] && printf '%s\n' "$out"
}
# Emits the compaction advice alone and marks the session as advised.
navori_emit_advice() {
  local advice="$navori_partial_msg"
  if [ -n "$navori_compact_msg" ]; then
    advice="${advice}${advice:+ }${navori_compact_msg}"
  fi
  [ -n "$advice" ] || return 0
  if navori_emit "$advice"; then
    if [ -n "$navori_compact_msg" ]; then
      printf '1\n' >"$navori_compact_mark" 2>/dev/null || true
      navori_audit_verdict="compact-advice"
      navori_audit_reason="$navori_compact_total"
    elif [ -n "$navori_partial_msg" ]; then
      navori_audit_verdict="partial"
      navori_audit_reason="$navori_subagent_type"
    fi
  fi
  return 0
}

if [ -z "$problems" ]; then
  # Emptying the stamp is what keeps a RECURRENCE audible: the same problem
  # coming back after being fixed is news, and a stamp left behind would
  # swallow it. Truncated rather than deleted — one redirection, no process,
  # and no delete inside a hook that runs in the user's repo.
  : >"$navori_handoff_stamp" 2>/dev/null || true
  navori_audit_verdict="clean"
  navori_emit_advice
  exit 0
fi

# Same problem set as the previous firing of this session → the message was
# already delivered. The run is still RECORDED (verdict `repeat`), because "the
# check ran and found the same thing" is evidence the audit needs; what is
# skipped is only the injection.
#
# Read WITHOUT testing the path first, and that is deliberate: a failed
# redirection already answers "no stamp yet", and this script must keep having
# no existence test in it. `hook-claims-vs-scripts.test.ts` reads that absence
# as proof that the hook cannot notice a handoff that never landed — a `-f`
# here, on an unrelated file, would silently license every asset that claims it
# does.
#
# stderr is silenced AROUND THE GROUP, not on the `read`. Redirections are
# applied left to right, so `read … <"$stamp" 2>/dev/null` opens the input
# first: when the stamp does not exist yet the shell's "no such file" is
# written before anything has redirected stderr, which printed one line of noise
# on the first firing of every session under both bash and zsh.
navori_handoff_prev=""
{ IFS= read -r navori_handoff_prev <"$navori_handoff_stamp"; } 2>/dev/null ||
  navori_handoff_prev=""
navori_handoff_sig="${problems}|${navori_fingerprint}"
if [ "$navori_handoff_prev" = "$navori_handoff_sig" ]; then
  navori_audit_verdict="repeat"
  navori_audit_reason="$problems"
  navori_emit_advice
  exit 0
fi
msg="navori: handoff(s) de subagente incompletos — ${problems}. Revisa que el reporte quedó bien escrito antes de consolidarlo."
if [ -n "$navori_partial_msg" ]; then
  msg="${msg} ${navori_partial_msg}"
fi
if [ -n "$navori_compact_msg" ]; then
  msg="${msg} ${navori_compact_msg}"
fi

# BOTH channels, and they are not redundant: `additionalContext` is the one that
# reaches the orchestrator — the only reader that can act on this — while
# `systemMessage` is what puts it in front of the human. The text is imperative
# because it asks for an action; before #774 it went out on the user channel
# alone, so it asked the model for something the model never heard.
if navori_emit "$msg"; then
  printf '%s\n' "$navori_handoff_sig" >"$navori_handoff_stamp" 2>/dev/null || true
  if [ -n "$navori_compact_msg" ]; then
    printf '1\n' >"$navori_compact_mark" 2>/dev/null || true
  fi
fi
navori_audit_verdict="dirty"
navori_audit_reason="$problems"
exit 0
