#!/usr/bin/env bash
#
# PreToolUse(Bash|Monitor) guard — the mechanical half of the "no backgrounding
# inside a subagent" rule (`implementer.md:43`, `reviewer.md:79`,
# `verify-before-done.md`'s subagent row): a subagent must run its chained
# steps one by one in the foreground, or report `Status: BLOCKED` — never
# background a gate it will not be re-woken to read. Blocks with `exit 2`, the
# same channel `guard-destructive`/`implementer-no-markdown` use, evaluated
# BEFORE permission rules.
#
# WHY A HOOK AND NOT JUST THE CONTRACT. The prose already states the rule in
# three places and it is not holding — a subagent has been observed stopping
# "with background work of its own still running", the exact failure the rule
# exists to prevent (#1003). This is the mechanical backstop.
#
# WHO IT APPLIES TO. `agent_id` — read straight from the payload, present only
# when the hook fires inside a subagent call
# (https://code.claude.com/docs/en/hooks) — gates this, NOT `agent_type`: the
# rule is role-agnostic (implementer, reviewer, auditor, scribe, scout...),
# unlike `implementer-no-markdown.sh` which is scoped to one role. Absent →
# the main thread, never blocked: backgrounding there IS the documented,
# legitimate path for a gate that outlives the Bash timeout
# (`verify-before-done.md`'s main-session row) — a hook that blocked it too
# would contradict the very rule it enforces.
#
# `Monitor` — blocked UNCONDITIONALLY inside a subagent, no field to inspect:
# the call itself is the violation. Its hookability as a `PreToolUse` tool
# name is NOT confirmed by the official hooks doc (no fixed tool list is
# published there); this branch is defense in depth, inert rather than wrong
# if the tool name never reaches a hook in practice.
#
# OUT OF SCOPE ON PURPOSE. Bare shell `&` inside a Bash `command` is NOT
# detected here — same posture `guard-destructive.sh` and
# `implementer-no-markdown.sh` already take for text-based command matching:
# `&&`, `2>&1`, `&>` and `&` inside a quoted string are real false positives a
# regex over unsegmented command text cannot fully separate, and the payoff
# does not justify the segmentation machinery `guard-destructive.sh` needed to
# solve the analogous problem. That vector stays enforced by prose only.
#
# KNOWN, ACCEPTED LIMITATION — the fail-open gotcha. `payload_field`'s sed
# fallback (`_partials/extract-cmd.sh`) only matches a QUOTED JSON STRING
# value; `tool_input.run_in_background` is a JSON BOOLEAN (unquoted `true`),
# so when neither `jq` nor `node` is on the host, the sed fallback returns
# empty and this hook reads that as "not backgrounded" — it FAILS OPEN. Same
# fail-open philosophy this repo already documents explicitly
# (`implementer-no-markdown.sh`, `guard-destructive.sh`'s own header): an
# accepted, precedented tradeoff, not an oversight.
#
# CODEX. This asset still renders to `.codex/hooks/` (generic asset copy,
# `placeHook`), but it is NOT wired into Codex's `config.toml`
# `[[hooks.PreToolUse]]`, same as `implementer-no-markdown.sh`
# (`specs/0030-scribe-owns-markdown/design.md`): Codex's hook payload has no
# confirmed `agent_id`/`agent_type` equivalent to gate on, so wiring it there
# would either fire for every agent including the main thread, or never
# resolve who is calling. The rule reaches Codex as prose only.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# Command/field extraction (payload → $cmd, $payload). Shared body, single
# source of truth.
# navori:include extract-cmd

navori_audit_name="subagent-no-background"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127, and a
# recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-repo
# navori:include audit-log
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. This fires on EVERY Bash/Monitor call from EVERY agent (and
# the main thread); only a subagent is ever in scope. Fork-free PRESENCE test
# before anything that spawns a process — the main thread carries no
# `agent_id` key at all, so a plain substring test already proves absence
# without a fork.
case "$payload" in
  *'"agent_id"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_id (hilo principal)"
    exit 0
    ;;
esac

navori_tool=$(payload_field tool_name)

block() {
  echo "[navori] BLOCKED by subagent-no-background: $1" >&2
  echo "[navori] a subagent does not background its own work (verify-before-done: run chained steps one by one in the foreground, or report Status: BLOCKED)." >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

case "$navori_tool" in
  Monitor)
    block "Monitor dentro de un subagente"
    ;;
  Bash) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac

navori_bg=$(payload_field tool_input.run_in_background)
if [ "$navori_bg" = "true" ]; then
  block "Bash run_in_background dentro de un subagente"
fi

navori_audit_verdict="allow"
navori_audit_reason="no backgrounded"
exit 0
