#!/usr/bin/env bash
# navori — worktree reclaim (SessionEnd) — #527
#
# Agent worktrees accumulate a FULL CHECKOUT each and nobody reclaims them: a
# cleanup in this repo found 27 of them, ~2.6 GB, three carrying unpushed
# branches. Until now the only path was manual — `commit-pr-pilot` ends its
# report with a `worktree:` line, the orchestrator reads it and asks the user —
# so a session that got cut short, an agent that died mid-cycle, or an
# orchestrator that simply never reached that line left the checkout forever.
# Cleanup that depends on an agent REMEMBERING is the failure mode the rest of
# the harness keeps closing.
#
# WHY SessionEnd and not SubagentStop: when a subagent stops, its PR usually
# does not exist yet, so nothing could prove the work survived. At session end
# the answer is knowable. It also batches: one sweep instead of one check per
# agent.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# THE BAR FOR DELETING. A worktree holding uncommitted or unpushed work is the
# ONLY copy of it, so this removes one only when all three hold:
#   1. `git status --porcelain` is empty — nothing uncommitted, untracked
#      included.
#   2. The branch has an upstream and nothing ahead of it — nothing unpushed.
#   3. Its PR is MERGED, according to `gh`.
#
# On (3): this repo squash-merges, so the branch SHA is never an ancestor of the
# base and `git merge-base --is-ancestor` answers "not merged" for branches that
# shipped days ago. A hook trusting that would never delete anything (benign);
# one that inverted it would delete live work (not). `gh pr list --state merged`
# is the only cheap source of truth, so no `gh` means no deletions — the
# conservative direction on purpose.
#
# FAIL-OPEN ABSOLUTE: exit 0 on anything unexpected. This is cleanup, and
# cleanup must never be the reason a session reports a failure.

set +e

payload=$(cat 2>/dev/null)

navori_audit_name="worktree-reclaim"
navori_audit_phase="SessionEnd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# navori:include audit-log
navori_audit_begin

# The verdict is a VARIABLE resolved in a trap, not a call per branch. These
# hooks have several early exits each (no git, no worktrees, nothing to inject),
# and wiring a call into every one is how the set drifts the next time somebody
# adds an exit. Defaulting to `skip` makes a new early exit semantically correct
# for free: it means "ran, decided it had nothing to do", which is exactly what
# an unhandled early return is.
navori_audit_verdict="skip"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT


cwd=""
if [ -n "$payload" ] && command -v jq >/dev/null 2>&1; then
  cwd=$(printf '%s' "$payload" | jq -r '.cwd // ""' 2>/dev/null)
fi
[ -n "$cwd" ] || cwd=${CLAUDE_PROJECT_DIR:-$PWD}
cd "$cwd" 2>/dev/null || exit 0
# PHYSICAL path, symlinks resolved. `git worktree list` always prints the real
# path, while the payload's `cwd` carries whatever the caller had — and on macOS
# that is routinely the symlinked form (`/var/...` for `/private/var/...`,
# `/tmp/...` for `/private/tmp/...`). Comparing the two forms never matches, so
# the sweep below would find nothing and exit 0: inoperative, and silent about
# it. Any repo living under a symlinked path hits this, not just temp dirs.
cwd=$(pwd -P 2>/dev/null) || exit 0

command -v git >/dev/null 2>&1 || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0
# The main checkout is where the sweep belongs: a worktree cannot remove itself.
[ "$(git rev-parse --git-dir 2>/dev/null)" = "$(git rev-parse --git-common-dir 2>/dev/null)" ] || exit 0

wt_root="$cwd/.claude/worktrees"
[ -d "$wt_root" ] || exit 0

removed=""
kept=""

# `git worktree list --porcelain` emits blank-line-separated records; only the
# ones under `.claude/worktrees/` are ours to touch. A worktree the user made
# themselves is not agent scratch and is never considered.
while IFS= read -r line; do
  case "$line" in
    "worktree "*) wt=${line#worktree } ;;
    *) continue ;;
  esac
  case "$wt" in
    "$wt_root"/*) ;;
    *) continue ;;
  esac
  [ -d "$wt" ] || continue

  branch=$(git -C "$wt" rev-parse --abbrev-ref HEAD 2>/dev/null)
  [ -n "$branch" ] && [ "$branch" != "HEAD" ] || { kept="${kept}
  ${wt} — detached HEAD, cannot tell what it holds"; continue; }

  # (1) uncommitted work, untracked files included.
  if [ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — uncommitted changes on '${branch}'"
    continue
  fi

  # (2) unpushed commits — or no upstream at all, which means the branch exists
  # nowhere else.
  if ! git -C "$wt" rev-parse --abbrev-ref "@{u}" >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — '${branch}' has no upstream (never pushed)"
    continue
  fi
  if [ -n "$(git -C "$wt" rev-list "@{u}..HEAD" 2>/dev/null)" ]; then
    kept="${kept}
  ${wt} — '${branch}' has commits not pushed"
    continue
  fi

  # (3) the PR merged. No gh, no answer, no deletion.
  if ! command -v gh >/dev/null 2>&1; then
    kept="${kept}
  ${wt} — gh not available, cannot confirm '${branch}' merged"
    continue
  fi
  merged=$(gh pr list --head "$branch" --state merged --limit 1 --json number \
    --jq '.[0].number // ""' 2>/dev/null)
  if [ -z "$merged" ]; then
    kept="${kept}
  ${wt} — no merged PR found for '${branch}'"
    continue
  fi

  # `git worktree remove`, never `rm -rf`: the latter leaves the entry in git's
  # index and the next `git worktree list` still reports a checkout that is gone.
  if git worktree remove "$wt" >/dev/null 2>&1; then
    removed="${removed}
  ${wt}  (${branch}, PR #${merged})"
  else
    kept="${kept}
  ${wt} — 'git worktree remove' refused it"
  fi
done <<EOF
$(git worktree list --porcelain 2>/dev/null)
EOF

[ -n "$removed" ] && git worktree prune >/dev/null 2>&1

# SessionEnd has no one to talk to, so this goes to the transcript, never to a
# blocking prompt. Silence when there was nothing to sweep.
if [ -n "$removed" ]; then
  printf 'navori: reclaimed agent worktrees (clean, pushed, PR merged):%s\n' "$removed"
fi
if [ -n "$kept" ]; then
  printf 'navori: agent worktrees KEPT — each holds work that exists nowhere else:%s\n' "$kept"
fi

# The verdict says what the sweep DID, which is what an audit needs to answer
# "where did the disk go": `noop` is the common case (no worktrees to sweep) and
# must stay distinguishable from a run that reclaimed or refused one.
if [ -n "$removed" ] || [ -n "$kept" ]; then
  navori_audit_verdict="clean"
  navori_audit_reason="reclamados:${removed:+ si} conservados:${kept:+ si}"
else
  navori_audit_verdict="noop"
fi
exit 0
